libstdc++: Numeric Arrays
Numeric Arrays
Numerics
Macros
#define _DEFINE_BINARY_OPERATOR(_Op, _Name)
#define _DEFINE_VALARRAY_AUGMENTED_ASSIGNMENT(_Op, _Name)
#define _DEFINE_VALARRAY_EXPR_AUGMENTED_ASSIGNMENT(_Op, _Name)
#define _DEFINE_VALARRAY_OPERATOR(_Op, _Name)
#define _DEFINE_VALARRAY_OPERATOR(_Op, _Name)
#define _DEFINE_VALARRAY_OPERATOR(_Op, _Name)
#define _DEFINE_VALARRAY_OPERATOR(_Op, _Name)
#define _DEFINE_VALARRAY_UNARY_OPERATOR(_Op, _Name)
Functions
std::gslice::gslice ()
std::gslice::gslice (const gslice &)
std::gslice::gslice (size_t __o, const valarray< size_t > &__l, const valarray< size_t > &__s)
std::gslice_array< _Tp >::gslice_array (const gslice_array &)
std::indirect_array< _Tp >::indirect_array (const indirect_array &)
std::mask_array< _Tp >::mask_array (const mask_array &)
std::slice::slice ()
std::slice::slice (size_t __o, size_t __d, size_t __s)
std::slice_array< _Tp >::slice_array (const slice_array &)
std::valarray< _Tp >::valarray () noexcept
template<class _Dom >
std::valarray< _Tp >::valarray (const _Expr< _Dom, _Tp > &__e)
std::valarray< _Tp >::valarray (const _Tp &, size_t)
template<typename _Tp >
std::valarray< _Tp >::valarray (const _Tp *__restrict__ __p, size_t __n)
std::valarray< _Tp >::valarray (const gslice_array< _Tp > &)
std::valarray< _Tp >::valarray (const indirect_array< _Tp > &)
std::valarray< _Tp >::valarray (const mask_array< _Tp > &)
std::valarray< _Tp >::valarray (const slice_array< _Tp > &)
std::valarray< _Tp >::valarray (const valarray &)
std::valarray< _Tp >::valarray (initializer_list< _Tp >)
std::valarray< _Tp >::valarray (size_t)
std::valarray< _Tp >::valarray (valarray &&) noexcept
std::gslice::~gslice ()
_Expr< _ValFunClos< _ValArray, _Tp >, _Tp > std::valarray< _Tp >::apply (_Tp __func(_Tp)) const
_Expr< _RefFunClos< _ValArray, _Tp >, _Tp > std::valarray< _Tp >::apply (_Tp __func(const _Tp &)) const
template<class _Tp >
const _Tp * std::begin (const valarray< _Tp > &__va) noexcept
template<class _Tp >
_Tp * std::begin (valarray< _Tp > &__va) noexcept
valarray< _Tp > std::valarray< _Tp >::cshift (int __n) const
template<class _Tp >
const _Tp * std::end (const valarray< _Tp > &__va) noexcept
template<class _Tp >
_Tp * std::end (valarray< _Tp > &__va) noexcept
_Tp std::valarray< _Tp >::max () const
_Tp std::valarray< _Tp >::min () const
_UnaryOp< __logical_not >::_Rt std::valarray< _Tp >::operator! () const
template<typename _Tp >
_Expr< _BinClos< __not_equal_to, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __not_equal_to, _Tp >::result_type > std::operator!= (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __not_equal_to, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __not_equal_to, _Tp >::result_type > std::operator!= (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __not_equal_to, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __not_equal_to, _Tp >::result_type > std::operator!= (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp >
_Expr< _BinClos< __modulus, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __modulus, _Tp >::result_type > std::operator% (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __modulus, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __modulus, _Tp >::result_type > std::operator% (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __modulus, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __modulus, _Tp >::result_type > std::operator% (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
valarray< _Tp > & std::valarray< _Tp >::operator%= (const _Expr< _Dom, _Tp > &)
template<class _Dom >
void std::gslice_array< _Tp >::operator%= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::indirect_array< _Tp >::operator%= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::mask_array< _Tp >::operator%= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::slice_array< _Tp >::operator%= (const _Expr< _Dom, _Tp > &) const
valarray< _Tp > & std::valarray< _Tp >::operator%= (const _Tp &)
valarray< _Tp > & std::valarray< _Tp >::operator%= (const valarray< _Tp > &)
void std::gslice_array< _Tp >::operator%= (const valarray< _Tp > &) const
void std::indirect_array< _Tp >::operator%= (const valarray< _Tp > &) const
void std::mask_array< _Tp >::operator%= (const valarray< _Tp > &) const
void std::slice_array< _Tp >::operator%= (const valarray< _Tp > &) const
template<typename _Tp >
_Expr< _BinClos< __bitwise_and, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __bitwise_and, _Tp >::result_type > std::operator& (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __bitwise_and, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __bitwise_and, _Tp >::result_type > std::operator& (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __bitwise_and, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __bitwise_and, _Tp >::result_type > std::operator& (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp >
_Expr< _BinClos< __logical_and, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __logical_and, _Tp >::result_type > std::operator&& (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __logical_and, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __logical_and, _Tp >::result_type > std::operator&& (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __logical_and, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __logical_and, _Tp >::result_type > std::operator&& (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
valarray< _Tp > & std::valarray< _Tp >::operator&= (const _Expr< _Dom, _Tp > &)
template<class _Dom >
void std::gslice_array< _Tp >::operator&= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::indirect_array< _Tp >::operator&= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::mask_array< _Tp >::operator&= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::slice_array< _Tp >::operator&= (const _Expr< _Dom, _Tp > &) const
valarray< _Tp > & std::valarray< _Tp >::operator&= (const _Tp &)
valarray< _Tp > & std::valarray< _Tp >::operator&= (const valarray< _Tp > &)
void std::gslice_array< _Tp >::operator&= (const valarray< _Tp > &) const
void std::indirect_array< _Tp >::operator&= (const valarray< _Tp > &) const
void std::mask_array< _Tp >::operator&= (const valarray< _Tp > &) const
void std::slice_array< _Tp >::operator&= (const valarray< _Tp > &) const
template<typename _Tp >
_Expr< _BinClos< __multiplies, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __multiplies, _Tp >::result_type > std::operator* (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __multiplies, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __multiplies, _Tp >::result_type > std::operator* (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __multiplies, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __multiplies, _Tp >::result_type > std::operator* (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
valarray< _Tp > & std::valarray< _Tp >::operator*= (const _Expr< _Dom, _Tp > &)
template<class _Dom >
void std::gslice_array< _Tp >::operator*= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::indirect_array< _Tp >::operator*= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::mask_array< _Tp >::operator*= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::slice_array< _Tp >::operator*= (const _Expr< _Dom, _Tp > &) const
valarray< _Tp > & std::valarray< _Tp >::operator*= (const _Tp &)
valarray< _Tp > & std::valarray< _Tp >::operator*= (const valarray< _Tp > &)
void std::gslice_array< _Tp >::operator*= (const valarray< _Tp > &) const
void std::indirect_array< _Tp >::operator*= (const valarray< _Tp > &) const
void std::mask_array< _Tp >::operator*= (const valarray< _Tp > &) const
void std::slice_array< _Tp >::operator*= (const valarray< _Tp > &) const
_UnaryOp< __unary_plus >::_Rt std::valarray< _Tp >::operator+ () const
template<typename _Tp >
_Expr< _BinClos< __plus, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __plus, _Tp >::result_type > std::operator+ (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __plus, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __plus, _Tp >::result_type > std::operator+ (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __plus, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __plus, _Tp >::result_type > std::operator+ (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
valarray< _Tp > & std::valarray< _Tp >::operator+= (const _Expr< _Dom, _Tp > &)
template<class _Dom >
void std::gslice_array< _Tp >::operator+= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::indirect_array< _Tp >::operator+= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::mask_array< _Tp >::operator+= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::slice_array< _Tp >::operator+= (const _Expr< _Dom, _Tp > &) const
valarray< _Tp > & std::valarray< _Tp >::operator+= (const _Tp &)
valarray< _Tp > & std::valarray< _Tp >::operator+= (const valarray< _Tp > &)
void std::gslice_array< _Tp >::operator+= (const valarray< _Tp > &) const
void std::indirect_array< _Tp >::operator+= (const valarray< _Tp > &) const
void std::mask_array< _Tp >::operator+= (const valarray< _Tp > &) const
void std::slice_array< _Tp >::operator+= (const valarray< _Tp > &) const
_UnaryOp< __negate >::_Rt std::valarray< _Tp >::operator- () const
template<typename _Tp >
_Expr< _BinClos< __minus, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __minus, _Tp >::result_type > std::operator- (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __minus, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __minus, _Tp >::result_type > std::operator- (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __minus, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __minus, _Tp >::result_type > std::operator- (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
valarray< _Tp > & std::valarray< _Tp >::operator-= (const _Expr< _Dom, _Tp > &)
template<class _Dom >
void std::gslice_array< _Tp >::operator-= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::indirect_array< _Tp >::operator-= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::mask_array< _Tp >::operator-= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::slice_array< _Tp >::operator-= (const _Expr< _Dom, _Tp > &) const
valarray< _Tp > & std::valarray< _Tp >::operator-= (const _Tp &)
valarray< _Tp > & std::valarray< _Tp >::operator-= (const valarray< _Tp > &)
void std::gslice_array< _Tp >::operator-= (const valarray< _Tp > &) const
void std::indirect_array< _Tp >::operator-= (const valarray< _Tp > &) const
void std::mask_array< _Tp >::operator-= (const valarray< _Tp > &) const
void std::slice_array< _Tp >::operator-= (const valarray< _Tp > &) const
template<typename _Tp >
_Expr< _BinClos< __divides, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __divides, _Tp >::result_type > std::operator/ (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __divides, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __divides, _Tp >::result_type > std::operator/ (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __divides, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __divides, _Tp >::result_type > std::operator/ (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
valarray< _Tp > & std::valarray< _Tp >::operator/= (const _Expr< _Dom, _Tp > &)
template<class _Dom >
void std::gslice_array< _Tp >::operator/= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::indirect_array< _Tp >::operator/= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::mask_array< _Tp >::operator/= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::slice_array< _Tp >::operator/= (const _Expr< _Dom, _Tp > &) const
valarray< _Tp > & std::valarray< _Tp >::operator/= (const _Tp &)
valarray< _Tp > & std::valarray< _Tp >::operator/= (const valarray< _Tp > &)
void std::gslice_array< _Tp >::operator/= (const valarray< _Tp > &) const
void std::indirect_array< _Tp >::operator/= (const valarray< _Tp > &) const
void std::mask_array< _Tp >::operator/= (const valarray< _Tp > &) const
void std::slice_array< _Tp >::operator/= (const valarray< _Tp > &) const
template<typename _Tp >
_Expr< _BinClos< __less, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __less, _Tp >::result_type > std::operator< (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __less, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __less, _Tp >::result_type > std::operator< (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __less, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __less, _Tp >::result_type > std::operator< (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp >
_Expr< _BinClos< __shift_left, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __shift_left, _Tp >::result_type > std::operator<< (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __shift_left, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __shift_left, _Tp >::result_type > std::operator<< (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __shift_left, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __shift_left, _Tp >::result_type > std::operator<< (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
valarray< _Tp > & std::valarray< _Tp >::operator<<= (const _Expr< _Dom, _Tp > &)
template<class _Dom >
void std::gslice_array< _Tp >::operator<<= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::indirect_array< _Tp >::operator<<= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::mask_array< _Tp >::operator<<= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::slice_array< _Tp >::operator<<= (const _Expr< _Dom, _Tp > &) const
valarray< _Tp > & std::valarray< _Tp >::operator<<= (const _Tp &)
valarray< _Tp > & std::valarray< _Tp >::operator<<= (const valarray< _Tp > &)
void std::gslice_array< _Tp >::operator<<= (const valarray< _Tp > &) const
void std::indirect_array< _Tp >::operator<<= (const valarray< _Tp > &) const
void std::mask_array< _Tp >::operator<<= (const valarray< _Tp > &) const
void std::slice_array< _Tp >::operator<<= (const valarray< _Tp > &) const
template<typename _Tp >
_Expr< _BinClos< __less_equal, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __less_equal, _Tp >::result_type > std::operator<= (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __less_equal, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __less_equal, _Tp >::result_type > std::operator<= (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __less_equal, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __less_equal, _Tp >::result_type > std::operator<= (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
valarray< _Tp > & std::valarray< _Tp >::operator= (const _Expr< _Dom, _Tp > &)
template<class _Dom >
void std::gslice_array< _Tp >::operator= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::indirect_array< _Tp >::operator= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::slice_array< _Tp >::operator= (const _Expr< _Dom, _Tp > &) const
template<class _Ex >
void std::mask_array< _Tp >::operator= (const _Expr< _Ex, _Tp > &__e) const
void std::gslice_array< _Tp >::operator= (const _Tp &) const
void std::indirect_array< _Tp >::operator= (const _Tp &) const
void std::mask_array< _Tp >::operator= (const _Tp &) const
void std::slice_array< _Tp >::operator= (const _Tp &) const
valarray< _Tp > & std::valarray< _Tp >::operator= (const _Tp &__t)
gslice & std::gslice::operator= (const gslice &)
gslice_array & std::gslice_array< _Tp >::operator= (const gslice_array &)
valarray< _Tp > & std::valarray< _Tp >::operator= (const gslice_array< _Tp > &__ga)
indirect_array & std::indirect_array< _Tp >::operator= (const indirect_array &)
valarray< _Tp > & std::valarray< _Tp >::operator= (const indirect_array< _Tp > &__ia)
mask_array & std::mask_array< _Tp >::operator= (const mask_array &)
valarray< _Tp > & std::valarray< _Tp >::operator= (const mask_array< _Tp > &__ma)
slice_array & std::slice_array< _Tp >::operator= (const slice_array &)
valarray< _Tp > & std::valarray< _Tp >::operator= (const slice_array< _Tp > &__sa)
void std::gslice_array< _Tp >::operator= (const valarray< _Tp > &) const
void std::indirect_array< _Tp >::operator= (const valarray< _Tp > &) const
void std::mask_array< _Tp >::operator= (const valarray< _Tp > &) const
void std::slice_array< _Tp >::operator= (const valarray< _Tp > &) const
valarray< _Tp > & std::valarray< _Tp >::operator= (const valarray< _Tp > &__v)
valarray & std::valarray< _Tp >::operator= (initializer_list< _Tp > __l)
valarray< _Tp > & std::valarray< _Tp >::operator= (valarray< _Tp > &&__v) noexcept
template<typename _Tp >
_Expr< _BinClos< __equal_to, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __equal_to, _Tp >::result_type > std::operator== (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __equal_to, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __equal_to, _Tp >::result_type > std::operator== (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __equal_to, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __equal_to, _Tp >::result_type > std::operator== (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp >
_Expr< _BinClos< __greater, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __greater, _Tp >::result_type > std::operator> (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __greater, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __greater, _Tp >::result_type > std::operator> (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __greater, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __greater, _Tp >::result_type > std::operator> (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp >
_Expr< _BinClos< __greater_equal, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __greater_equal, _Tp >::result_type > std::operator>= (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __greater_equal, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __greater_equal, _Tp >::result_type > std::operator>= (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __greater_equal, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __greater_equal, _Tp >::result_type > std::operator>= (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<typename _Tp >
_Expr< _BinClos< __shift_right, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __shift_right, _Tp >::result_type > std::operator>> (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __shift_right, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __shift_right, _Tp >::result_type > std::operator>> (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __shift_right, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __shift_right, _Tp >::result_type > std::operator>> (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
valarray< _Tp > & std::valarray< _Tp >::operator>>= (const _Expr< _Dom, _Tp > &)
template<class _Dom >
void std::gslice_array< _Tp >::operator>>= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::indirect_array< _Tp >::operator>>= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::mask_array< _Tp >::operator>>= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::slice_array< _Tp >::operator>>= (const _Expr< _Dom, _Tp > &) const
valarray< _Tp > & std::valarray< _Tp >::operator>>= (const _Tp &)
valarray< _Tp > & std::valarray< _Tp >::operator>>= (const valarray< _Tp > &)
void std::gslice_array< _Tp >::operator>>= (const valarray< _Tp > &) const
void std::indirect_array< _Tp >::operator>>= (const valarray< _Tp > &) const
void std::mask_array< _Tp >::operator>>= (const valarray< _Tp > &) const
void std::slice_array< _Tp >::operator>>= (const valarray< _Tp > &) const
gslice_array< _Tp > std::valarray< _Tp >::operator[] (const gslice &__s)
_Expr< _GClos< _ValArray, _Tp >, _Tp > std::valarray< _Tp >::operator[] (const gslice &__s) const
mask_array< _Tp > std::valarray< _Tp >::operator[] (const valarray< bool > &__m)
valarray< _Tp > std::valarray< _Tp >::operator[] (const valarray< bool > &__m) const
indirect_array< _Tp > std::valarray< _Tp >::operator[] (const valarray< size_t > &__i)
_Expr< _IClos< _ValArray, _Tp >, _Tp > std::valarray< _Tp >::operator[] (const valarray< size_t > &__i) const
_Tp & std::valarray< _Tp >::operator[] (size_t __i) noexcept
const _Tp & std::valarray< _Tp >::operator[] (size_t) const noexcept
slice_array< _Tp > std::valarray< _Tp >::operator[] (slice __s)
_Expr< _SClos< _ValArray, _Tp >, _Tp > std::valarray< _Tp >::operator[] (slice __s) const
template<typename _Tp >
_Expr< _BinClos< __bitwise_xor, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __bitwise_xor, _Tp >::result_type > std::operator^ (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __bitwise_xor, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __bitwise_xor, _Tp >::result_type > std::operator^ (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __bitwise_xor, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __bitwise_xor, _Tp >::result_type > std::operator^ (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
valarray< _Tp > & std::valarray< _Tp >::operator^= (const _Expr< _Dom, _Tp > &)
template<class _Dom >
void std::gslice_array< _Tp >::operator^= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::indirect_array< _Tp >::operator^= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::mask_array< _Tp >::operator^= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::slice_array< _Tp >::operator^= (const _Expr< _Dom, _Tp > &) const
valarray< _Tp > & std::valarray< _Tp >::operator^= (const _Tp &)
valarray< _Tp > & std::valarray< _Tp >::operator^= (const valarray< _Tp > &)
void std::gslice_array< _Tp >::operator^= (const valarray< _Tp > &) const
void std::indirect_array< _Tp >::operator^= (const valarray< _Tp > &) const
void std::mask_array< _Tp >::operator^= (const valarray< _Tp > &) const
void std::slice_array< _Tp >::operator^= (const valarray< _Tp > &) const
template<typename _Tp >
_Expr< _BinClos< __bitwise_or, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __bitwise_or, _Tp >::result_type > std::operator| (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __bitwise_or, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __bitwise_or, _Tp >::result_type > std::operator| (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __bitwise_or, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __bitwise_or, _Tp >::result_type > std::operator| (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
valarray< _Tp > & std::valarray< _Tp >::operator|= (const _Expr< _Dom, _Tp > &)
template<class _Dom >
void std::gslice_array< _Tp >::operator|= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::indirect_array< _Tp >::operator|= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::mask_array< _Tp >::operator|= (const _Expr< _Dom, _Tp > &) const
template<class _Dom >
void std::slice_array< _Tp >::operator|= (const _Expr< _Dom, _Tp > &) const
valarray< _Tp > & std::valarray< _Tp >::operator|= (const _Tp &)
valarray< _Tp > & std::valarray< _Tp >::operator|= (const valarray< _Tp > &)
void std::gslice_array< _Tp >::operator|= (const valarray< _Tp > &) const
void std::indirect_array< _Tp >::operator|= (const valarray< _Tp > &) const
void std::mask_array< _Tp >::operator|= (const valarray< _Tp > &) const
void std::slice_array< _Tp >::operator|= (const valarray< _Tp > &) const
template<typename _Tp >
_Expr< _BinClos< __logical_or, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __logical_or, _Tp >::result_type > std::operator|| (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __logical_or, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __logical_or, _Tp >::result_type > std::operator|| (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __logical_or, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __logical_or, _Tp >::result_type > std::operator|| (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
_UnaryOp< __bitwise_not >::_Rt std::valarray< _Tp >::operator~ () const
void std::valarray< _Tp >::resize (size_t __size, _Tp __c=_Tp())
valarray< _Tp > std::valarray< _Tp >::shift (int __n) const
valarray< size_t > std::gslice::size () const
size_t std::slice::size () const
size_t std::valarray< _Tp >::size () const
size_t std::gslice::start () const
size_t std::slice::start () const
valarray< size_t > std::gslice::stride () const
size_t std::slice::stride () const
_Tp std::valarray< _Tp >::sum () const
void std::valarray< _Tp >::swap (valarray< _Tp > &__v) noexcept
template<typename _Tp , size_t _Nm>
std::valarray (const _Tp(&)[_Nm], size_t) -> valarray< _Tp >
Detailed Description
Classes and functions for representing and manipulating arrays of elements.
Function Documentation
gslice() [1/3]
std::gslice::gslice () inline
Construct an empty slice.
Definition at line 149 of file gslice.h.
gslice() [2/3]
std::gslice::gslice (const gslice & __g) inline
Copy constructor.
Definition at line 158 of file gslice.h.
gslice() [3/3]
std::gslice::gslice (size_t __o, const valarray< size_t > & __l, const valarray< size_t > & __s) inline
Construct a slice.
Constructs a slice with as many dimensions as the length of the l and s arrays.
Parameters
__o Offset in array of first element.
__l Array of dimension lengths.
__s Array of dimension strides between array elements.
Definition at line 153 of file gslice.h.
gslice_array()
template<typename _Tp > std::gslice_array< _Tp >::gslice_array (const gslice_array< _Tp > & __a) inline
Copy constructor. Both slices refer to the same underlying array.
Definition at line 148 of file gslice_array.h.
indirect_array()
template<typename _Tp > std::indirect_array< _Tp >::indirect_array (const indirect_array< _Tp > & __a) inline
Copy constructor. Both slices refer to the same underlying array.
Definition at line 143 of file indirect_array.h.
mask_array()
template<typename _Tp > std::mask_array< _Tp >::mask_array (const mask_array< _Tp > & __a) inline
Copy constructor. Both slices refer to the same underlying array.
Definition at line 144 of file mask_array.h.
slice() [1/2]
std::slice::slice () inline
Construct an empty slice.
Definition at line 95 of file slice_array.h.
slice() [2/2]
std::slice::slice (size_t __o, size_t __d, size_t __s) inline
Construct a slice.
Parameters
__o Offset in array of first element.
__d Number of elements in slice.
__s Stride between array elements.
Definition at line 99 of file slice_array.h.
slice_array()
template<typename _Tp > std::slice_array< _Tp >::slice_array (const slice_array< _Tp > & __a) inline
Copy constructor. Both slices refer to the same underlying array.
Definition at line 217 of file slice_array.h.
valarray() [1/10]
template<typename _Tp > std::valarray< _Tp >::valarray inline noexcept
Construct an empty array.
Definition at line 621 of file valarray.
valarray() [2/10]
template<typename _Tp > std::valarray< _Tp >::valarray (const _Tp & __t, size_t __n) inline
Construct an array with n elements initialized to t.
Definition at line 631 of file valarray.
valarray() [3/10]
template<typename _Tp > std::valarray< _Tp >::valarray (const gslice_array< _Tp > & __ga) inline
Construct an array with the same size and values in ga.
Definition at line 673 of file valarray.
valarray() [4/10]
template<typename _Tp > std::valarray< _Tp >::valarray (const indirect_array< _Tp > & __ia) inline
Construct an array with the same size and values in ia.
Definition at line 693 of file valarray.
valarray() [5/10]
template<typename _Tp > std::valarray< _Tp >::valarray (const mask_array< _Tp > & __ma) inline
Construct an array with the same size and values in ma.
Definition at line 684 of file valarray.
valarray() [6/10]
template<typename _Tp > std::valarray< _Tp >::valarray (const slice_array< _Tp > & __sa) inline
Construct an array with the same size and values in sa.
Definition at line 664 of file valarray.
valarray() [7/10]
template<typename _Tp > std::valarray< _Tp >::valarray (const valarray< _Tp > & __v) inline
Copy constructor.
Definition at line 646 of file valarray.
valarray() [8/10]
template<typename _Tp > std::valarray< _Tp >::valarray (initializer_list< _Tp > __l) inline
Construct an array with an initializer_list of values.
Definition at line 703 of file valarray.
valarray() [9/10]
template<typename _Tp > std::valarray< _Tp >::valarray (size_t __n) inline explicit
Construct an array with n elements.
Definition at line 625 of file valarray.
valarray() [10/10]
template<typename _Tp > std::valarray< _Tp >::valarray (valarray< _Tp > && __v) inline noexcept
Move constructor.
Definition at line 654 of file valarray.
~gslice()
std::gslice::~gslice () inline
Destructor.
Definition at line 163 of file gslice.h.
apply() [1/2]
template<class _Tp > _Expr< _ValFunClos< _ValArray, _Tp >, _Tp > std::valarray< _Tp >::apply (_Tp __func_Tp) const inline
Apply a function to the array.
Returns a new valarray with elements assigned to the result of applying __func to the corresponding element of this array. The new array has the same size as this one.
Parameters
__func Function of Tp returning Tp to apply.
Returns
New valarray with transformed elements.
Definition at line 1065 of file valarray.
apply() [2/2]
template<class _Tp > _Expr< _RefFunClos< _ValArray, _Tp >, _Tp > std::valarray< _Tp >::apply (_Tp __funcconst _Tp &) const inline
Apply a function to the array.
Returns a new valarray with elements assigned to the result of applying __func to the corresponding element of this array. The new array has the same size as this one.
Parameters
__func Function of const Tp& returning Tp to apply.
Returns
New valarray with transformed elements.
Definition at line 1073 of file valarray.
begin() [1/2]
template<class _Tp > const _Tp * std::begin (const valarray< _Tp > & __va) inline noexcept
Return an iterator pointing to the first element of the const valarray.
Parameters
__va valarray.
Definition at line 1226 of file valarray.
begin() [2/2]
template<class _Tp > _Tp * std::begin (valarray< _Tp > & __va) inline noexcept
Return an iterator pointing to the first element of the valarray.
Parameters
__va valarray.
Definition at line 1215 of file valarray.
Referenced by std::cbegin(), std::vector< _Tp, _Alloc >::insert(), std::list< _Tp, _Alloc >::merge(), std::list< _Tp, _Alloc >::remove(), std::list< _Tp, _Alloc >::remove_if(), and std::list< _Tp, _Alloc >::unique().
cshift()
template<class _Tp > valarray< _Tp > std::valarray< _Tp >::cshift (int __n) const inline
Return a rotated array.
A new valarray is constructed as a copy of this array with elements in shifted positions. For an element with index i, the new position is (i - n) % size(). The new valarray has the same size as the current one. Elements that are shifted beyond the array bounds are shifted into the other end of the array. No elements are lost.
Positive arguments shift toward index 0, wrapping around the top. Negative arguments shift towards the top, wrapping around to 0.
Parameters
__n Number of element positions to rotate.
Returns
New valarray with elements in shifted positions.
Definition at line 991 of file valarray.
end() [1/2]
template<class _Tp > const _Tp * std::end (const valarray< _Tp > & __va) inline noexcept
Return an iterator pointing to one past the last element of the const valarray.
Parameters
__va valarray.
Definition at line 1253 of file valarray.
end() [2/2]
template<class _Tp > _Tp * std::end (valarray< _Tp > & __va) inline noexcept
Return an iterator pointing to one past the last element of the valarray.
Parameters
__va valarray.
Definition at line 1237 of file valarray.
Referenced by std::cend(), std::vector< _Tp, _Alloc >::insert(), std::list< _Tp, _Alloc >::merge(), std::vector< double >::operator=(), std::list< _Tp, _Alloc >::remove(), std::list< _Tp, _Alloc >::remove_if(), std::list< _Tp, _Alloc >::resize(), and std::list< _Tp, _Alloc >::unique().
max()
template<typename _Tp > _Tp std::valarray< _Tp >::max inline
Return the maximum element using operator<().
Definition at line 1057 of file valarray.
min()
template<typename _Tp > _Tp std::valarray< _Tp >::min inline
Return the minimum element using operator<().
Definition at line 1049 of file valarray.
operator!()
template<typename _Tp > valarray< _Tp >::template _UnaryOp< __logical_not >::_Rt std::valarray< _Tp >::operator! inline
Return a new valarray by applying unary ! to each element.
Definition at line 1092 of file valarray.
operator%=() [1/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator%= (const _Tp & __t) inline
Set each element e of array to e % t.
Definition at line 1119 of file valarray.
operator%=() [2/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator%= (const valarray< _Tp > & __v) inline
Modulo elements of array by corresponding elements of v.
Definition at line 1119 of file valarray.
operator%=() [3/6]
template<typename _Tp > void std::gslice_array< _Tp >::operator%= (const valarray< _Tp > & __v) const inline
Modulo slice elements by corresponding elements of v.
Definition at line 207 of file gslice_array.h.
operator%=() [4/6]
template<typename _Tp > void std::indirect_array< _Tp >::operator%= (const valarray< _Tp > & __v) const inline
Modulo slice elements by corresponding elements of v.
Definition at line 196 of file indirect_array.h.
operator%=() [5/6]
template<typename _Tp > void std::mask_array< _Tp >::operator%= (const valarray< _Tp > & __v) const inline
Modulo slice elements by corresponding elements of v.
Definition at line 197 of file mask_array.h.
operator%=() [6/6]
template<typename _Tp > void std::slice_array< _Tp >::operator%= (const valarray< _Tp > & __v) const inline
Modulo slice elements by corresponding elements of v.
Definition at line 268 of file slice_array.h.
operator&=() [1/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator&= (const _Tp & __t) inline
Set each element e of array to e & t.
Definition at line 1121 of file valarray.
operator&=() [2/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator&= (const valarray< _Tp > & __v) inline
Logical and corresponding elements of v with elements of array.
Definition at line 1121 of file valarray.
operator&=() [3/6]
template<typename _Tp > void std::gslice_array< _Tp >::operator&= (const valarray< _Tp > & __v) const inline
Logical and slice elements with corresponding elements of v.
Definition at line 211 of file gslice_array.h.
operator&=() [4/6]
template<typename _Tp > void std::indirect_array< _Tp >::operator&= (const valarray< _Tp > & __v) const inline
Logical and slice elements with corresponding elements of v.
Definition at line 200 of file indirect_array.h.
operator&=() [5/6]
template<typename _Tp > void std::mask_array< _Tp >::operator&= (const valarray< _Tp > & __v) const inline
Logical and slice elements with corresponding elements of v.
Definition at line 201 of file mask_array.h.
operator&=() [6/6]
template<typename _Tp > void std::slice_array< _Tp >::operator&= (const valarray< _Tp > & __v) const inline
Logical and slice elements with corresponding elements of v.
Definition at line 272 of file slice_array.h.
operator*=() [1/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator*= (const _Tp & __t) inline
Multiply each element of array by t.
Definition at line 1117 of file valarray.
operator*=() [2/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator*= (const valarray< _Tp > & __v) inline
Multiply elements of array by corresponding elements of v.
Definition at line 1117 of file valarray.
operator*=() [3/6]
template<typename _Tp > void std::gslice_array< _Tp >::operator*= (const valarray< _Tp > & __v) const inline
Multiply slice elements by corresponding elements of v.
Definition at line 205 of file gslice_array.h.
operator*=() [4/6]
template<typename _Tp > void std::indirect_array< _Tp >::operator*= (const valarray< _Tp > & __v) const inline
Multiply slice elements by corresponding elements of v.
Definition at line 194 of file indirect_array.h.
operator*=() [5/6]
template<typename _Tp > void std::mask_array< _Tp >::operator*= (const valarray< _Tp > & __v) const inline
Multiply slice elements by corresponding elements of v.
Definition at line 195 of file mask_array.h.
operator*=() [6/6]
template<typename _Tp > void std::slice_array< _Tp >::operator*= (const valarray< _Tp > & __v) const inline
Multiply slice elements by corresponding elements of v.
Definition at line 266 of file slice_array.h.
operator+()
template<typename _Tp > valarray< _Tp >::template _UnaryOp< __unary_plus >::_Rt std::valarray< _Tp >::operator+ inline
Return a new valarray by applying unary + to each element.
Definition at line 1089 of file valarray.
operator+=() [1/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator+= (const _Tp & __t) inline
Add t to each element of array.
Definition at line 1115 of file valarray.
operator+=() [2/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator+= (const valarray< _Tp > & __v) inline
Add corresponding elements of v to elements of array.
Definition at line 1115 of file valarray.
operator+=() [3/6]
template<typename _Tp > void std::gslice_array< _Tp >::operator+= (const valarray< _Tp > & __v) const inline
Add corresponding elements of v to slice elements.
Definition at line 208 of file gslice_array.h.
operator+=() [4/6]
template<typename _Tp > void std::indirect_array< _Tp >::operator+= (const valarray< _Tp > & __v) const inline
Add corresponding elements of v to slice elements.
Definition at line 197 of file indirect_array.h.
operator+=() [5/6]
template<typename _Tp > void std::mask_array< _Tp >::operator+= (const valarray< _Tp > & __v) const inline
Add corresponding elements of v to slice elements.
Definition at line 198 of file mask_array.h.
operator+=() [6/6]
template<typename _Tp > void std::slice_array< _Tp >::operator+= (const valarray< _Tp > & __v) const inline
Add corresponding elements of v to slice elements.
Definition at line 269 of file slice_array.h.
operator-()
template<typename _Tp > valarray< _Tp >::template _UnaryOp< __negate >::_Rt std::valarray< _Tp >::operator- inline
Return a new valarray by applying unary - to each element.
Definition at line 1090 of file valarray.
operator-=() [1/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator-= (const _Tp & __t) inline
Subtract t to each element of array.
Definition at line 1116 of file valarray.
operator-=() [2/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator-= (const valarray< _Tp > & __v) inline
Subtract corresponding elements of v from elements of array.
Definition at line 1116 of file valarray.
operator-=() [3/6]
template<typename _Tp > void std::gslice_array< _Tp >::operator-= (const valarray< _Tp > & __v) const inline
Subtract corresponding elements of v from slice elements.
Definition at line 209 of file gslice_array.h.
operator-=() [4/6]
template<typename _Tp > void std::indirect_array< _Tp >::operator-= (const valarray< _Tp > & __v) const inline
Subtract corresponding elements of v from slice elements.
Definition at line 198 of file indirect_array.h.
operator-=() [5/6]
template<typename _Tp > void std::mask_array< _Tp >::operator-= (const valarray< _Tp > & __v) const inline
Subtract corresponding elements of v from slice elements.
Definition at line 199 of file mask_array.h.
operator-=() [6/6]
template<typename _Tp > void std::slice_array< _Tp >::operator-= (const valarray< _Tp > & __v) const inline
Subtract corresponding elements of v from slice elements.
Definition at line 270 of file slice_array.h.
operator/=() [1/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator/= (const _Tp & __t) inline
Divide each element of array by t.
Definition at line 1118 of file valarray.
operator/=() [2/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator/= (const valarray< _Tp > & __v) inline
Divide elements of array by corresponding elements of v.
Definition at line 1118 of file valarray.
operator/=() [3/6]
template<typename _Tp > void std::gslice_array< _Tp >::operator/= (const valarray< _Tp > & __v) const inline
Divide slice elements by corresponding elements of v.
Definition at line 206 of file gslice_array.h.
operator/=() [4/6]
template<typename _Tp > void std::indirect_array< _Tp >::operator/= (const valarray< _Tp > & __v) const inline
Divide slice elements by corresponding elements of v.
Definition at line 195 of file indirect_array.h.
operator/=() [5/6]
template<typename _Tp > void std::mask_array< _Tp >::operator/= (const valarray< _Tp > & __v) const inline
Divide slice elements by corresponding elements of v.
Definition at line 196 of file mask_array.h.
operator/=() [6/6]
template<typename _Tp > void std::slice_array< _Tp >::operator/= (const valarray< _Tp > & __v) const inline
Divide slice elements by corresponding elements of v.
Definition at line 267 of file slice_array.h.
operator<<=() [1/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator<<= (const _Tp & __t) inline
Left shift each element e of array by t bits.
Definition at line 1122 of file valarray.
operator<<=() [2/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator<<= (const valarray< _Tp > & __v) inline
Left shift elements of array by corresponding elements of v.
Definition at line 1122 of file valarray.
operator<<=() [3/6]
template<typename _Tp > void std::gslice_array< _Tp >::operator<<= (const valarray< _Tp > & __v) const inline
Left shift slice elements by corresponding elements of v.
Definition at line 213 of file gslice_array.h.
operator<<=() [4/6]
template<typename _Tp > void std::indirect_array< _Tp >::operator<<= (const valarray< _Tp > & __v) const inline
Left shift slice elements by corresponding elements of v.
Definition at line 202 of file indirect_array.h.
operator<<=() [5/6]
template<typename _Tp > void std::mask_array< _Tp >::operator<<= (const valarray< _Tp > & __v) const inline
Left shift slice elements by corresponding elements of v.
Definition at line 203 of file mask_array.h.
operator<<=() [6/6]
template<typename _Tp > void std::slice_array< _Tp >::operator<<= (const valarray< _Tp > & __v) const inline
Left shift slice elements by corresponding elements of v.
Definition at line 274 of file slice_array.h.
operator=() [1/20]
template<typename _Tp > void std::gslice_array< _Tp >::operator= (const _Tp & __t) const inline
Assign all slice elements to t.
Definition at line 163 of file gslice_array.h.
operator=() [2/20]
template<typename _Tp > void std::indirect_array< _Tp >::operator= (const _Tp & __t) const inline
Assign all slice elements to t.
Definition at line 163 of file indirect_array.h.
operator=() [3/20]
template<typename _Tp > void std::mask_array< _Tp >::operator= (const _Tp & __t) const inline
Assign all slice elements to t.
Definition at line 163 of file mask_array.h.
operator=() [4/20]
template<typename _Tp > void std::slice_array< _Tp >::operator= (const _Tp & __t) const inline
Assign all slice elements to t.
Definition at line 234 of file slice_array.h.
operator=() [5/20]
template<typename _Tp > valarray< _Tp > & std::valarray< _Tp >::operator= (const _Tp & __t) inline
Assign elements to a value.
Assign all elements of array to t.
Parameters
__t Value for elements.
Definition at line 788 of file valarray.
operator=() [6/20]
gslice & std::gslice::operator= (const gslice & __g) inline
Assignment operator.
Definition at line 170 of file gslice.h.
operator=() [7/20]
template<typename _Tp > gslice_array< _Tp > & std::gslice_array< _Tp >::operator= (const gslice_array< _Tp > & __a) inline
Assignment operator. Assigns slice elements to corresponding elements of a.
Definition at line 153 of file gslice_array.h.
operator=() [8/20]
template<typename _Tp > valarray< _Tp > & std::valarray< _Tp >::operator= (const gslice_array< _Tp > & __ga) inline
Assign elements to an array subset.
Assign elements of array to values in ga. Results are undefined if ga does not have the same size as this array.
Parameters
__ga Array slice to get values from.
Definition at line 806 of file valarray.
operator=() [9/20]
template<typename _Tp > indirect_array< _Tp > & std::indirect_array< _Tp >::operator= (const indirect_array< _Tp > & __a) inline
Assignment operator. Assigns elements to corresponding elements of a.
Definition at line 154 of file indirect_array.h.
operator=() [10/20]
template<typename _Tp > valarray< _Tp > & std::valarray< _Tp >::operator= (const indirect_array< _Tp > & __ia) inline
Assign elements to an array subset.
Assign elements of array to values in ia. Results are undefined if ia does not have the same size as this array.
Parameters
__ia Array slice to get values from.
Definition at line 826 of file valarray.
operator=() [11/20]
template<typename _Tp > mask_array< _Tp > & std::mask_array< _Tp >::operator= (const mask_array< _Tp > & __a) inline
Assignment operator. Assigns elements to corresponding elements of a.
Definition at line 154 of file mask_array.h.
operator=() [12/20]
template<typename _Tp > valarray< _Tp > & std::valarray< _Tp >::operator= (const mask_array< _Tp > & __ma) inline
Assign elements to an array subset.
Assign elements of array to values in ma. Results are undefined if ma does not have the same size as this array.
Parameters
__ma Array slice to get values from.
Definition at line 816 of file valarray.
operator=() [13/20]
template<typename _Tp > slice_array< _Tp > & std::slice_array< _Tp >::operator= (const slice_array< _Tp > & __a) inline
Assignment operator. Assigns slice elements to corresponding elements of a.
Definition at line 225 of file slice_array.h.
operator=() [14/20]
template<typename _Tp > valarray< _Tp > & std::valarray< _Tp >::operator= (const slice_array< _Tp > & __sa) inline
Assign elements to an array subset.
Assign elements of array to values in sa. Results are undefined if sa does not have the same size as this array.
Parameters
__sa Array slice to get values from.
Definition at line 796 of file valarray.
operator=() [15/20]
template<typename _Tp > void std::gslice_array< _Tp >::operator= (const valarray< _Tp > & __v) const inline
Assign slice elements to corresponding elements of v.
Definition at line 171 of file gslice_array.h.
References std::valarray< _Tp >::size().
operator=() [16/20]
template<typename _Tp > void std::indirect_array< _Tp >::operator= (const valarray< _Tp > & __v) const inline
Assign slice elements to corresponding elements of v.
Definition at line 168 of file indirect_array.h.
operator=() [17/20]
template<typename _Tp > void std::slice_array< _Tp >::operator= (const valarray< _Tp > & __v) const inline
Assign slice elements to corresponding elements of v.
Definition at line 239 of file slice_array.h.
operator=() [18/20]
template<typename _Tp > valarray< _Tp > & std::valarray< _Tp >::operator= (const valarray< _Tp > & __v) inline
Assign elements to an array.
Assign elements of array to values in v.
Parameters
__v Valarray to get values from.
Definition at line 724 of file valarray.
operator=() [19/20]
template<typename _Tp > valarray< _Tp > & std::valarray< _Tp >::operator= (initializer_list< _Tp > __l) inline
Assign elements to an initializer_list.
Assign elements of array to values in __l. Results are undefined if __l does not have the same size as this array.
Parameters
__l initializer_list to get values from.
Definition at line 764 of file valarray.
operator=() [20/20]
template<typename _Tp > valarray< _Tp > & std::valarray< _Tp >::operator= (valarray< _Tp > && __v) inline noexcept
Move assign elements to an array.
Move assign elements of array to values in v.
Parameters
__v Valarray to get values from.
Definition at line 748 of file valarray.
operator>>=() [1/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator>>= (const _Tp & __t) inline
Right shift each element e of array by t bits.
Definition at line 1124 of file valarray.
operator>>=() [2/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator>>= (const valarray< _Tp > & __v) inline
Right shift elements of array by corresponding elements of v.
Definition at line 1124 of file valarray.
operator>>=() [3/6]
template<typename _Tp > void std::gslice_array< _Tp >::operator>>= (const valarray< _Tp > & __v) const inline
Right shift slice elements by corresponding elements of v.
Definition at line 214 of file gslice_array.h.
operator>>=() [4/6]
template<typename _Tp > void std::indirect_array< _Tp >::operator>>= (const valarray< _Tp > & __v) const inline
Right shift slice elements by corresponding elements of v.
Definition at line 203 of file indirect_array.h.
operator>>=() [5/6]
template<typename _Tp > void std::mask_array< _Tp >::operator>>= (const valarray< _Tp > & __v) const inline
Right shift slice elements by corresponding elements of v.
Definition at line 204 of file mask_array.h.
operator>>=() [6/6]
template<typename _Tp > void std::slice_array< _Tp >::operator>>= (const valarray< _Tp > & __v) const inline
Right shift slice elements by corresponding elements of v.
Definition at line 275 of file slice_array.h.
operator[]() [1/9]
template<typename _Tp > gslice_array< _Tp > std::valarray< _Tp >::operator[] (const gslice & __s) inline
Return a reference to an array subset.
Returns a new valarray containing the elements of the array indicated by the gslice argument. The new valarray has the same size as the input gslice.
See also
gslice.
Parameters
__s The source gslice.
Returns
New valarray containing elements in __s.
Definition at line 880 of file valarray.
operator[]() [2/9]
template<typename _Tp > _Expr< _GClos< _ValArray, _Tp >, _Tp > std::valarray< _Tp >::operator[] (const gslice & __s) const inline
Return an array subset.
Returns a slice_array referencing the elements of the array indicated by the slice argument.
See also
gslice.
Parameters
__s The source slice.
Returns
Slice_array referencing elements indicated by __s.
Definition at line 871 of file valarray.
operator[]() [3/9]
template<typename _Tp > mask_array< _Tp > std::valarray< _Tp >::operator[] (const valarray< bool > & __m) inline
Return a reference to an array subset.
Returns a new mask_array referencing the elements of the array indicated by the argument. The input is a valarray of bool which represents a bitmask indicating which elements are part of the subset. Elements of the array are part of the subset if the corresponding element of the argument is true.
Parameters
__m The valarray bitmask.
Returns
New valarray containing elements indicated by __m.
Definition at line 900 of file valarray.
operator[]() [4/9]
template<typename _Tp > valarray< _Tp > std::valarray< _Tp >::operator[] (const valarray< bool > & __m) const inline
Return an array subset.
Returns a new valarray containing the elements of the array indicated by the argument. The input is a valarray of bool which represents a bitmask indicating which elements should be copied into the new valarray. Each element of the array is added to the return valarray if the corresponding element of the argument is true.
Parameters
__m The valarray bitmask.
Returns
New valarray containing elements indicated by __m.
Definition at line 888 of file valarray.
operator[]() [5/9]
template<typename _Tp > indirect_array< _Tp > std::valarray< _Tp >::operator[] (const valarray< size_t > & __i) inline
Return a reference to an array subset.
Returns an indirect_array referencing the elements of the array indicated by the argument. The elements in the argument are interpreted as the indices of elements of this valarray to include in the subset. The returned indirect_array refers to these elements.
Parameters
__i The valarray element index list.
Returns
Indirect_array referencing elements in __i.
Definition at line 919 of file valarray.
operator[]() [6/9]
template<typename _Tp > _Expr< _IClos< _ValArray, _Tp >, _Tp > std::valarray< _Tp >::operator[] (const valarray< size_t > & __i) const inline
Return an array subset.
Returns a new valarray containing the elements of the array indicated by the argument. The elements in the argument are interpreted as the indices of elements of this valarray to copy to the return valarray.
Parameters
__i The valarray element index list.
Returns
New valarray containing elements in __s.
Definition at line 911 of file valarray.
operator[]() [7/9]
template<typename _Tp > _Tp & std::valarray< _Tp >::operator[] (size_t __i) inline noexcept
Return a reference to the i'th array element.
Parameters
__i Index of element to return.
Returns
Reference to the i'th element.
Definition at line 592 of file valarray.
operator[]() [8/9]
template<typename _Tp > slice_array< _Tp > std::valarray< _Tp >::operator[] (slice __s) inline
Return a reference to an array subset.
Returns a new valarray containing the elements of the array indicated by the slice argument. The new valarray has the same size as the input slice.
See also
slice.
Parameters
__s The source slice.
Returns
New valarray containing elements in __s.
Definition at line 866 of file valarray.
operator[]() [9/9]
template<typename _Tp > _Expr< _SClos< _ValArray, _Tp >, _Tp > std::valarray< _Tp >::operator[] (slice __s) const inline
Return an array subset.
Returns a new valarray containing the elements of the array indicated by the slice argument. The new valarray has the same size as the input slice.
See also
slice.
Parameters
__s The source slice.
Returns
New valarray containing elements in __s.
Definition at line 858 of file valarray.
operator^=() [1/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator^= (const _Tp & __t) inline
Set each element e of array to e ^ t.
Definition at line 1120 of file valarray.
operator^=() [2/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator^= (const valarray< _Tp > & __v) inline
Logical xor corresponding elements of v with elements of array.
Definition at line 1120 of file valarray.
operator^=() [3/6]
template<typename _Tp > void std::gslice_array< _Tp >::operator^= (const valarray< _Tp > & __v) const inline
Logical xor slice elements with corresponding elements of v.
Definition at line 210 of file gslice_array.h.
operator^=() [4/6]
template<typename _Tp > void std::indirect_array< _Tp >::operator^= (const valarray< _Tp > & __v) const inline
Logical xor slice elements with corresponding elements of v.
Definition at line 199 of file indirect_array.h.
operator^=() [5/6]
template<typename _Tp > void std::mask_array< _Tp >::operator^= (const valarray< _Tp > & __v) const inline
Logical xor slice elements with corresponding elements of v.
Definition at line 200 of file mask_array.h.
operator^=() [6/6]
template<typename _Tp > void std::slice_array< _Tp >::operator^= (const valarray< _Tp > & __v) const inline
Logical xor slice elements with corresponding elements of v.
Definition at line 271 of file slice_array.h.
operator|=() [1/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator|= (const _Tp & __t) inline
Set each element e of array to e | t.
Definition at line 1122 of file valarray.
operator|=() [2/6]
template<class _Tp > valarray< _Tp > & std::valarray< _Tp >::operator|= (const valarray< _Tp > & __v) inline
Logical or corresponding elements of v with elements of array.
Definition at line 1122 of file valarray.
operator|=() [3/6]
template<typename _Tp > void std::gslice_array< _Tp >::operator|= (const valarray< _Tp > & __v) const inline
Logical or slice elements with corresponding elements of v.
Definition at line 212 of file gslice_array.h.
operator|=() [4/6]
template<typename _Tp > void std::indirect_array< _Tp >::operator|= (const valarray< _Tp > & __v) const inline
Logical or slice elements with corresponding elements of v.
Definition at line 201 of file indirect_array.h.
operator|=() [5/6]
template<typename _Tp > void std::mask_array< _Tp >::operator|= (const valarray< _Tp > & __v) const inline
Logical or slice elements with corresponding elements of v.
Definition at line 202 of file mask_array.h.
operator|=() [6/6]
template<typename _Tp > void std::slice_array< _Tp >::operator|= (const valarray< _Tp > & __v) const inline
Logical or slice elements with corresponding elements of v.
Definition at line 273 of file slice_array.h.
operator~()
template<typename _Tp > valarray< _Tp >::template _UnaryOp< __bitwise_not >::_Rt std::valarray< _Tp >::operator~ inline
Return a new valarray by applying unary ~ to each element.
Definition at line 1091 of file valarray.
resize()
template<class _Tp > void std::valarray< _Tp >::resize (size_t __size, _Tp __c = _Tp()) inline
Resize array.
Resize this array to size and set all elements to c. All references and iterators are invalidated.
Parameters
__size New array size.
__c New value for all elements.
Definition at line 1032 of file valarray.
shift()
template<class _Tp > valarray< _Tp > std::valarray< _Tp >::shift (int __n) const inline
Return a shifted array.
A new valarray is constructed as a copy of this array with elements in shifted positions. For an element with index i, the new position is i - n. The new valarray has the same size as the current one. New elements without a value are set to 0. Elements whose new position is outside the bounds of the array are discarded.
Positive arguments shift toward index 0, discarding elements [0, n). Negative arguments discard elements from the top of the array.
Parameters
__n Number of element positions to shift.
Returns
New valarray with elements in shifted positions.
Definition at line 950 of file valarray.
size() [1/3]
valarray< size_t > std::gslice::size () const inline
Return array of sizes of slice dimensions.
Definition at line 139 of file gslice.h.
size() [2/3]
size_t std::slice::size () const inline
Return size of slice.
Definition at line 107 of file slice_array.h.
size() [3/3]
template<class _Tp > size_t std::valarray< _Tp >::size inline
Return the number of elements in array.
Definition at line 937 of file valarray.
Referenced by std::gslice_array< _Tp >::operator=().
start() [1/2]
size_t std::gslice::start () const inline
Return array offset of first slice element.
Definition at line 135 of file gslice.h.
start() [2/2]
size_t std::slice::start () const inline
Return array offset of first slice element.
Definition at line 103 of file slice_array.h.
stride() [1/2]
valarray< size_t > std::gslice::stride () const inline
Return array of array strides for each dimension.
Definition at line 143 of file gslice.h.
stride() [2/2]
size_t std::slice::stride () const inline
Return array stride of slice.
Definition at line 111 of file slice_array.h.
sum()
template<class _Tp > _Tp std::valarray< _Tp >::sum inline
Return the sum of all elements in the array.
Accumulates the sum of all elements into a Tp using +=. The order of adding the elements is unspecified.
Definition at line 942 of file valarray.
swap()
template<class _Tp > void std::valarray< _Tp >::swap (valarray< _Tp > & __v) inline noexcept
Swap.
Definition at line 928 of file valarray.