libstdc++: std Namespace Reference
std Namespace Reference
Namespaces
__debug
__detail
__parallel
chrono
decimal
experimental
filesystem
literals
numbers
placeholders
regex_constants
rel_ops
this_thread
tr1
tr2
Classes
struct __atomic_base
struct __atomic_base< _PTp * >
struct __atomic_flag_base
class __basic_future
class __codecvt_abstract_base
class __ctype_abstract_base
struct __future_base
struct __is_location_invariant
struct __is_nullptr_t
class __new_allocator
struct __numeric_limits_base
struct _Base_bitset
struct _Base_bitset< 0 >
struct _Base_bitset< 1 >
class _Bind
class _Bind_result
class _Deque_base
struct _Deque_iterator
class _Function_base
struct _Fwd_list_base
struct _Fwd_list_const_iterator
struct _Fwd_list_iterator
struct _Fwd_list_node
struct _Fwd_list_node_base
class _List_base
struct _List_const_iterator
struct _List_iterator
struct _List_node
class _Node_handle
class _Node_handle< _Value, _Value, _NodeAlloc >
class _Node_handle_common
struct _Node_insert_return
class _Not_fn
struct _Optional_base
struct _Placeholder
struct _Sp_ebo_helper< _Nm, _Tp, false >
struct _Sp_ebo_helper< _Nm, _Tp, true >
class _Temporary_buffer
struct _Tuple_impl
struct _Tuple_impl< _Idx, _Head, _Tail... >
struct _Vector_base
struct add_const
struct add_cv
struct add_lvalue_reference
struct add_pointer
struct add_rvalue_reference
struct add_volatile
struct adopt_lock_t
struct aligned_storage
struct aligned_union
struct alignment_of
class allocator
class allocator< void >
struct allocator_traits
struct allocator_traits< allocator< _Tp > >
struct allocator_traits< allocator< void > >
struct allocator_traits< pmr::polymorphic_allocator< _Tp > >
class any
struct array
class atomic
struct atomic< _Tp * >
struct atomic< bool >
struct atomic< char >
struct atomic< char16_t >
struct atomic< char32_t >
struct atomic< int >
struct atomic< long >
struct atomic< long long >
struct atomic< short >
struct atomic< signed char >
struct atomic< unsigned char >
struct atomic< unsigned int >
struct atomic< unsigned long >
struct atomic< unsigned long long >
struct atomic< unsigned short >
struct atomic< wchar_t >
struct atomic_flag
struct atomic_ref
class auto_ptr
struct auto_ptr_ref
class back_insert_iterator
class bad_alloc
class bad_any_cast
class bad_cast
class bad_exception
class bad_function_call
class bad_optional_access
class bad_typeid
class bad_weak_ptr
class basic_filebuf
class basic_fstream
class basic_ifstream
class basic_ios
class basic_iostream
class basic_istream
class basic_istringstream
class basic_ofstream
class basic_ostream
class basic_ostringstream
class basic_regex
class basic_streambuf
class basic_string
class basic_string_view
class basic_stringbuf
class basic_stringstream
class bernoulli_distribution
struct bidirectional_iterator_tag
struct binary_function
class binary_negate
class binder1st
class binder2nd
class binomial_distribution
class bitset
class cauchy_distribution
struct char_traits
struct char_traits< __gnu_cxx::character< _Value, _Int, _St > >
struct char_traits< char >
struct char_traits< wchar_t >
class chi_squared_distribution
class codecvt
class codecvt< _InternT, _ExternT, encoding_state >
class codecvt< char, char, mbstate_t >
class codecvt< char16_t, char, mbstate_t >
class codecvt< char32_t, char, mbstate_t >
class codecvt< wchar_t, char, mbstate_t >
class codecvt_base
class codecvt_byname
class collate
class collate_byname
struct common_type
struct common_type< chrono::duration< _Rep, _Period > >
struct common_type< chrono::duration< _Rep, _Period >, chrono::duration< _Rep, _Period > >
struct common_type< chrono::duration< _Rep1, _Period1 >, chrono::duration< _Rep2, _Period2 > >
struct common_type< chrono::time_point< _Clock, _Duration > >
struct common_type< chrono::time_point< _Clock, _Duration >, chrono::time_point< _Clock, _Duration > >
struct common_type< chrono::time_point< _Clock, _Duration1 >, chrono::time_point< _Clock, _Duration2 > >
struct compare_three_way_result
class complex
class complex< double >
class complex< float >
class complex< long double >
class condition_variable
class condition_variable_any
struct conditional
class const_mem_fun1_ref_t
class const_mem_fun1_t
class const_mem_fun_ref_t
class const_mem_fun_t
struct contiguous_iterator_tag
class counted_iterator
class ctype
class ctype< char >
class ctype< wchar_t >
struct ctype_base
class ctype_byname
class ctype_byname< char >
class decay
struct default_delete
struct default_delete< _Tp[]>
struct defer_lock_t
class deque
struct destroying_delete_t
class discard_block_engine
class discrete_distribution
struct divides
struct divides< void >
class domain_error
struct enable_if
class enable_shared_from_this
struct equal_to
struct equal_to< void >
class error_category
class error_code
class error_condition
class exception
class exponential_distribution
struct extent
class extreme_value_distribution
class fisher_f_distribution
struct forward_iterator_tag
class forward_list
class fpos
struct from_chars_result
class front_insert_iterator
class function< _Res(_ArgTypes...)>
class future
class future< _Res & >
class future< void >
class future_error
class gamma_distribution
class geometric_distribution
struct greater
struct greater< void >
struct greater_equal
struct greater_equal< void >
class gslice
class gslice_array
struct has_unique_object_representations
struct has_virtual_destructor
struct hash
struct hash< __debug::bitset< _Nb > >
struct hash< __debug::vector< bool, _Alloc > >
struct hash< __gnu_cxx::__u16vstring >
struct hash< __gnu_cxx::__u32vstring >
struct hash< __gnu_cxx::__vstring >
struct hash< __gnu_cxx::__wvstring >
struct hash< __gnu_cxx::throw_value_limit >
struct hash< __gnu_cxx::throw_value_random >
struct hash< __gnu_debug::basic_string< _CharT > >
struct hash< __shared_ptr< _Tp, _Lp > >
struct hash< _Tp * >
struct hash< bool >
struct hash< char >
struct hash< char16_t >
struct hash< char32_t >
struct hash< double >
struct hash< error_code >
struct hash< error_condition >
struct hash< experimental::optional< _Tp > >
struct hash< experimental::shared_ptr< _Tp > >
struct hash< float >
struct hash< int >
struct hash< long >
struct hash< long double >
struct hash< long long >
struct hash< shared_ptr< _Tp > >
struct hash< short >
struct hash< signed char >
struct hash< string >
struct hash< thread::id >
struct hash< type_index >
struct hash< u16string >
struct hash< u32string >
struct hash< unique_ptr< _Tp, _Dp > >
struct hash< unsigned char >
struct hash< unsigned int >
struct hash< unsigned long >
struct hash< unsigned long long >
struct hash< unsigned short >
struct hash< wchar_t >
struct hash< wstring >
struct hash<::bitset< _Nb > >
struct hash<::vector< bool, _Alloc > >
struct identity
class independent_bits_engine
class indirect_array
class initializer_list
struct input_iterator_tag
class insert_iterator
struct integer_sequence
struct integral_constant
class invalid_argument
struct invoke_result
class ios_base
struct is_abstract
struct is_aggregate
struct is_arithmetic
struct is_array
struct is_assignable
struct is_base_of
struct is_bind_expression
struct is_bind_expression< _Bind< _Signature > >
struct is_bind_expression< _Bind_result< _Result, _Signature > >
struct is_bind_expression< const _Bind< _Signature > >
struct is_bind_expression< const _Bind_result< _Result, _Signature > >
struct is_bind_expression< const volatile _Bind< _Signature > >
struct is_bind_expression< const volatile _Bind_result< _Result, _Signature > >
struct is_bind_expression< volatile _Bind< _Signature > >
struct is_bind_expression< volatile _Bind_result< _Result, _Signature > >
struct is_bounded_array
struct is_class
struct is_compound
struct is_const
struct is_constructible
struct is_convertible
struct is_copy_assignable
struct is_copy_constructible
struct is_default_constructible
struct is_destructible
struct is_empty
struct is_enum
struct is_error_code_enum
struct is_error_code_enum< future_errc >
struct is_error_condition_enum
struct is_final
struct is_floating_point
struct is_function
struct is_fundamental
struct is_integral
struct is_invocable
struct is_invocable_r
struct is_layout_compatible
struct is_literal_type
struct is_lvalue_reference
struct is_member_function_pointer
struct is_member_object_pointer
struct is_member_pointer
struct is_move_assignable
struct is_move_constructible
struct is_nothrow_assignable
struct is_nothrow_constructible
struct is_nothrow_convertible
struct is_nothrow_copy_assignable
struct is_nothrow_copy_constructible
struct is_nothrow_default_constructible
struct is_nothrow_destructible
struct is_nothrow_invocable
struct is_nothrow_invocable_r
struct is_nothrow_move_assignable
struct is_nothrow_move_constructible
struct is_nothrow_swappable
struct is_nothrow_swappable_with
struct is_null_pointer
struct is_object
struct is_placeholder
struct is_placeholder< _Placeholder< _Num > >
struct is_pod
struct is_pointer
struct is_pointer_interconvertible_base_of
struct is_polymorphic
struct is_reference
struct is_rvalue_reference
struct is_same
struct is_scalar
struct is_signed
struct is_standard_layout
struct is_swappable
struct is_swappable_with
struct is_trivial
struct is_trivially_assignable
struct is_trivially_constructible
struct is_trivially_copy_assignable
struct is_trivially_copy_constructible
struct is_trivially_copyable
struct is_trivially_default_constructible
struct is_trivially_destructible
struct is_trivially_move_assignable
struct is_trivially_move_constructible
struct is_unbounded_array
struct is_union
struct is_unsigned
struct is_void
struct is_volatile
class istream_iterator
class istreambuf_iterator
struct iterator
struct iterator_traits
struct iterator_traits< _Tp * >
class jthread
class length_error
struct less
struct less< void >
struct less_equal
struct less_equal< void >
class linear_congruential_engine
class list
class locale
class lock_guard
class logic_error
struct logical_and
struct logical_and< void >
struct logical_not
struct logical_not< void >
struct logical_or
struct logical_or< void >
class lognormal_distribution
struct make_signed
struct make_unsigned
class map
class mask_array
class match_results
class mem_fun1_ref_t
class mem_fun1_t
class mem_fun_ref_t
class mem_fun_t
class mersenne_twister_engine
class messages
struct messages_base
class messages_byname
struct minus
struct minus< void >
struct modulus
struct modulus< void >
class money_base
class money_get
class money_put
class moneypunct
class moneypunct_byname
class move_iterator
class move_only_function< _Res(_ArgTypes...) _GLIBCXX_MOF_CV noexcept(_Noex)>
class multimap
struct multiplies
struct multiplies< void >
class multiset
class mutex
struct negate
struct negate< void >
class negative_binomial_distribution
class nested_exception
class normal_distribution
struct nostopstate_t
struct not_equal_to
struct not_equal_to< void >
struct nullopt_t
class num_get
class num_put
struct numeric_limits
struct numeric_limits< bool >
struct numeric_limits< char >
struct numeric_limits< char16_t >
struct numeric_limits< char32_t >
struct numeric_limits< double >
struct numeric_limits< float >
struct numeric_limits< int >
struct numeric_limits< long >
struct numeric_limits< long double >
struct numeric_limits< long long >
struct numeric_limits< short >
struct numeric_limits< signed char >
struct numeric_limits< unsigned char >
struct numeric_limits< unsigned int >
struct numeric_limits< unsigned long >
struct numeric_limits< unsigned long long >
struct numeric_limits< unsigned short >
struct numeric_limits< wchar_t >
class numpunct
class numpunct_byname
struct once_flag
class optional
class ostream_iterator
class ostreambuf_iterator
class out_of_range
struct output_iterator_tag
class overflow_error
struct owner_less
struct owner_less< shared_ptr< _Tp > >
struct owner_less< void >
struct owner_less< weak_ptr< _Tp > >
class packaged_task< _Res(_ArgTypes...)>
struct pair
class piecewise_constant_distribution
struct piecewise_construct_t
class piecewise_linear_distribution
struct plus
class pointer_to_binary_function
class pointer_to_unary_function
struct pointer_traits
struct pointer_traits< _Tp * >
class poisson_distribution
class priority_queue
struct projected
class promise
class promise< _Res & >
class promise< void >
class queue
struct random_access_iterator_tag
class random_device
class range_error
struct rank
struct ratio
struct ratio_equal
struct ratio_greater
struct ratio_greater_equal
struct ratio_less
struct ratio_less_equal
struct ratio_not_equal
class raw_storage_iterator
class recursive_mutex
class recursive_timed_mutex
class reference_wrapper
class regex_error
class regex_iterator
class regex_token_iterator
class regex_traits
struct remove_all_extents
struct remove_const
struct remove_cv
struct remove_extent
struct remove_pointer
struct remove_reference
struct remove_volatile
struct result_of
class reverse_iterator
class runtime_error
class scoped_allocator_adaptor
class scoped_lock
class seed_seq
class set
class shared_future
class shared_future< _Res & >
class shared_future< void >
class shared_lock
class shared_mutex
class shared_ptr
class shared_timed_mutex
class shuffle_order_engine
class slice
class slice_array
struct source_location
class stack
class stop_callback
class stop_source
class stop_token
class student_t_distribution
class sub_match
class subtract_with_carry_engine
class system_error
class thread
class time_base
class time_get
class time_get_byname
class time_put
class time_put_byname
class timed_mutex
struct to_chars_result
struct try_to_lock_t
class tuple
class tuple< _T1, _T2 >
struct tuple_element
struct tuple_element< 0, pair< _Tp1, _Tp2 > >
struct tuple_element< 1, pair< _Tp1, _Tp2 > >
struct tuple_element< __i, tuple< _Types... > >
struct tuple_element< _Ind, array< _Tp, _Nm > >
struct tuple_size
struct tuple_size< array< _Tp, _Nm > >
struct tuple_size< pair< _Tp1, _Tp2 > >
struct tuple_size< tuple< _Elements... > >
struct type_index
class type_info
struct unary_function
class unary_negate
class underflow_error
struct underlying_type
class uniform_int_distribution
class uniform_real_distribution
class unique_lock
class unique_ptr
class unique_ptr< _Tp[], _Dp >
class unordered_map
class unordered_multimap
class unordered_multiset
class unordered_set
struct unwrap_ref_decay
struct unwrap_reference
struct uses_allocator
struct uses_allocator< tuple< _Types... >, _Alloc >
class valarray
class vector
class vector< bool, _Alloc >
class wbuffer_convert
class weak_ptr
class weibull_distribution
class wstring_convert
Typedefs
template<typename _Tp >
using __allocator_base = __new_allocator< _Tp >
template<typename _Tp , typename _Up >
using __assigns_from_optional = __or_< is_assignable< _Tp &, const optional< _Up > & >, is_assignable< _Tp &, optional< _Up > & >, is_assignable< _Tp &, const optional< _Up > && >, is_assignable< _Tp &, optional< _Up > && > >
template<typename _Fn , typename... _Args>
using __async_result_of = typename __invoke_result< typename decay< _Fn >::type, typename decay< _Args >::type... >::type
template<typename _Tp >
using __atomic_diff_t = typename atomic< _Tp >::difference_type
typedef unsigned char __atomic_flag_data_type
template<typename _Tp >
using __atomic_val_t = __type_identity_t< _Tp >
template<typename _RAIter , typename _Hash , typename _Pred , typename _Val = typename iterator_traits<_RAIter>::value_type, typename _Diff = typename iterator_traits<_RAIter>::difference_type>
using __boyer_moore_base_t = __conditional_t< __is_byte_like< _Val, _Pred >::value, __boyer_moore_array_base< _Diff, 256, _Pred >, __boyer_moore_map_base< _Val, _Diff, _Hash, _Pred > >
template<typename _IntegerType >
using __byte_op_t = typename __byte_operand< _IntegerType >::__type
typedef FILE __c_file
typedef __locale_t __c_locale
typedef __gthread_mutex_t __c_lock
template<bool _Cond, typename _If , typename _Else >
using __conditional_t = typename __conditional< _Cond >::template type< _If, _Else >
template<typename _Tp , typename _Up >
using __converts_from_optional = __or_< is_constructible< _Tp, const optional< _Up > & >, is_constructible< _Tp, optional< _Up > & >, is_constructible< _Tp, const optional< _Up > && >, is_constructible< _Tp, optional< _Up > && >, is_convertible< const optional< _Up > &, _Tp >, is_convertible< optional< _Up > &, _Tp >, is_convertible< const optional< _Up > &&, _Tp >, is_convertible< optional< _Up > &&, _Tp > >
typedef basic_string< char > __cow_string
template<typename _Tp >
using __empty_not_final = __conditional_t< __is_final(_Tp), false_type, __is_empty_non_tuple< _Tp > >
template<typename _Tp , typename _Up = typename remove_cv<_Tp>::type, typename = typename enable_if<is_same<_Tp, _Up>::value>::type, size_t = tuple_size<_Tp>::value>
using __enable_if_has_tuple_size = _Tp
template<typename _Func , typename _SfinaeType >
using __has_is_transparent_t = typename __has_is_transparent< _Func, _SfinaeType >::type
template<typename _ToElementType , typename _FromElementType >
using __is_array_convertible = is_convertible< _FromElementType(*)[], _ToElementType(*)[]>
template<typename _Tp >
using __is_in_place_type = bool_constant< __is_in_place_type_v< _Tp > >
template<typename _Tp , typename _Up >
using __is_nothrow_assignable_impl = __bool_constant< __is_nothrow_assignable(_Tp, _Up)>
template<typename _Tp , typename _Tp2 = typename decay<_Tp>::type>
using __is_socketlike = __or_< is_integral< _Tp2 >, is_enum< _Tp2 > >
template<typename _InputIterator >
using __iter_key_t = remove_const_t< typename iterator_traits< _InputIterator >::value_type::first_type >
template<typename _InputIterator >
using __iter_to_alloc_t = pair< add_const_t< __iter_key_t< _InputIterator > >, __iter_val_t< _InputIterator > >
template<typename _InputIterator >
using __iter_val_t = typename iterator_traits< _InputIterator >::value_type::second_type
template<typename _Iter >
using __iterator_category_t = typename iterator_traits< _Iter >::iterator_category
template<typename _Tp , typename _Up >
using __optional_eq_t = __optional_relop_t< decltype(std::declval< const _Tp & >()==std::declval< const _Up & >()) >
template<typename _Tp , typename _Up >
using __optional_ge_t = __optional_relop_t< decltype(std::declval< const _Tp & >() >=std::declval< const _Up & >()) >
template<typename _Tp , typename _Up >
using __optional_gt_t = __optional_relop_t< decltype(std::declval< const _Tp & >() > std::declval< const _Up & >()) >
template<typename _Tp , typename _Up >
using __optional_le_t = __optional_relop_t< decltype(std::declval< const _Tp & >()<=std::declval< const _Up & >()) >
template<typename _Tp , typename _Up >
using __optional_lt_t = __optional_relop_t< decltype(std::declval< const _Tp & >()< std::declval< const _Up & >()) >
template<typename _Tp , typename _Up >
using __optional_ne_t = __optional_relop_t< decltype(std::declval< const _Tp & >() !=std::declval< const _Up & >()) >
template<typename _Tp >
using __optional_relop_t = enable_if_t< is_convertible< _Tp, bool >::value, bool >
template<typename _Ptr , typename _Tp >
using __ptr_rebind = typename pointer_traits< _Ptr >::template rebind< _Tp >
template<typename _Ptr >
using __ptr_traits_elem_t = typename __get_first_arg< _Ptr >::type
using __rvalue_stream_extraction_t = _Is &&
using __rvalue_stream_insertion_t = _Os &&
using __semaphore_impl = __atomic_semaphore
typedef basic_string< char > __sso_string
template<size_t __i, typename _Tp >
using __tuple_element_t = typename tuple_element< __i, _Tp >::type
template<typename _Key , typename _Tp , typename _Hash = hash<_Key>, typename _Pred = std::equal_to<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >, typename _Tr = __umap_traits<__cache_default<_Key, _Hash>::value>>
using __umap_hashtable = _Hashtable< _Key, std::pair< const _Key, _Tp >, _Alloc, __detail::_Select1st, _Pred, _Hash, __detail::_Mod_range_hashing, __detail::_Default_ranged_hash, __detail::_Prime_rehash_policy, _Tr >
template<bool _Cache>
using __umap_traits = __detail::_Hashtable_traits< _Cache, false, true >
template<typename _Key , typename _Tp , typename _Hash = hash<_Key>, typename _Pred = std::equal_to<_Key>, typename _Alloc = std::allocator<std::pair<const _Key, _Tp> >, typename _Tr = __ummap_traits<__cache_default<_Key, _Hash>::value>>
using __ummap_hashtable = _Hashtable< _Key, std::pair< const _Key, _Tp >, _Alloc, __detail::_Select1st, _Pred, _Hash, __detail::_Mod_range_hashing, __detail::_Default_ranged_hash, __detail::_Prime_rehash_policy, _Tr >
template<bool _Cache>
using __ummap_traits = __detail::_Hashtable_traits< _Cache, false, false >
template<typename _Value , typename _Hash = hash<_Value>, typename _Pred = std::equal_to<_Value>, typename _Alloc = std::allocator<_Value>, typename _Tr = __umset_traits<__cache_default<_Value, _Hash>::value>>
using __umset_hashtable = _Hashtable< _Value, _Value, _Alloc, __detail::_Identity, _Pred, _Hash, __detail::_Mod_range_hashing, __detail::_Default_ranged_hash, __detail::_Prime_rehash_policy, _Tr >
template<bool _Cache>
using __umset_traits = __detail::_Hashtable_traits< _Cache, true, false >
template<typename _Value , typename _Hash = hash<_Value>, typename _Pred = std::equal_to<_Value>, typename _Alloc = std::allocator<_Value>, typename _Tr = __uset_traits<__cache_default<_Value, _Hash>::value>>
using __uset_hashtable = _Hashtable< _Value, _Value, _Alloc, __detail::_Identity, _Pred, _Hash, __detail::_Mod_range_hashing, __detail::_Default_ranged_hash, __detail::_Prime_rehash_policy, _Tr >
template<bool _Cache>
using __uset_traits = __detail::_Hashtable_traits< _Cache, true, true >
template<typename _Fn , typename... _Args>
using _Bind_front_t = _Bind_front< decay_t< _Fn >, decay_t< _Args >... >
typedef unsigned long _Bit_type
template<typename _Path , typename _Result = _Path, typename _Path2 = decltype(std::declval<_Path&>().make_preferred().filename())>
using _If_fs_path = enable_if_t< is_same_v< _Path, _Path2 >, _Result >
template<typename _Alloc >
using _RequireAllocator = typename enable_if< __is_allocator< _Alloc >::value, _Alloc >::type
template<typename _InIter >
using _RequireInputIter = __enable_if_t< is_convertible< __iterator_category_t< _InIter >, input_iterator_tag >::value >
template<typename _Alloc >
using _RequireNotAllocator = typename enable_if<!__is_allocator< _Alloc >::value, _Alloc >::type
template<typename _Tp >
using add_const_t = typename add_const< _Tp >::type
template<typename _Tp >
using add_cv_t = typename add_cv< _Tp >::type
template<typename _Tp >
using add_lvalue_reference_t = typename add_lvalue_reference< _Tp >::type
template<typename _Tp >
using add_pointer_t = typename add_pointer< _Tp >::type
template<typename _Tp >
using add_rvalue_reference_t = typename add_rvalue_reference< _Tp >::type
template<typename _Tp >
using add_volatile_t = typename add_volatile< _Tp >::type
template<size_t _Len, size_t _Align = __alignof__(typename __aligned_storage_msa<_Len>::__type)>
using aligned_storage_t = typename aligned_storage< _Len, _Align >::type
template<size_t _Len, typename... _Types>
using aligned_union_t = typename aligned_union< _Len, _Types... >::type
typedef atomic< bool > atomic_bool
typedef atomic< char > atomic_char
typedef atomic< char16_t > atomic_char16_t
typedef atomic< char32_t > atomic_char32_t
typedef atomic< int > atomic_int
typedef atomic< int16_t > atomic_int16_t
typedef atomic< int32_t > atomic_int32_t
typedef atomic< int64_t > atomic_int64_t
typedef atomic< int8_t > atomic_int8_t
typedef atomic< int_fast16_t > atomic_int_fast16_t
typedef atomic< int_fast32_t > atomic_int_fast32_t
typedef atomic< int_fast64_t > atomic_int_fast64_t
typedef atomic< int_fast8_t > atomic_int_fast8_t
typedef atomic< int_least16_t > atomic_int_least16_t
typedef atomic< int_least32_t > atomic_int_least32_t
typedef atomic< int_least64_t > atomic_int_least64_t
typedef atomic< int_least8_t > atomic_int_least8_t
typedef atomic< intmax_t > atomic_intmax_t
typedef atomic< intptr_t > atomic_intptr_t
typedef atomic< long long > atomic_llong
typedef atomic< long > atomic_long
typedef atomic< ptrdiff_t > atomic_ptrdiff_t
typedef atomic< signed char > atomic_schar
typedef atomic< short > atomic_short
typedef atomic< size_t > atomic_size_t
typedef atomic< unsigned char > atomic_uchar
typedef atomic< unsigned int > atomic_uint
typedef atomic< uint16_t > atomic_uint16_t
typedef atomic< uint32_t > atomic_uint32_t
typedef atomic< uint64_t > atomic_uint64_t
typedef atomic< uint8_t > atomic_uint8_t
typedef atomic< uint_fast16_t > atomic_uint_fast16_t
typedef atomic< uint_fast32_t > atomic_uint_fast32_t
typedef atomic< uint_fast64_t > atomic_uint_fast64_t
typedef atomic< uint_fast8_t > atomic_uint_fast8_t
typedef atomic< uint_least16_t > atomic_uint_least16_t
typedef atomic< uint_least32_t > atomic_uint_least32_t
typedef atomic< uint_least64_t > atomic_uint_least64_t
typedef atomic< uint_least8_t > atomic_uint_least8_t
typedef atomic< uintmax_t > atomic_uintmax_t
typedef atomic< uintptr_t > atomic_uintptr_t
typedef atomic< unsigned long long > atomic_ullong
typedef atomic< unsigned long > atomic_ulong
typedef atomic< unsigned short > atomic_ushort
typedef atomic< wchar_t > atomic_wchar_t
typedef ratio< 1, 1000000000000000000 > atto
using binary_semaphore = std::counting_semaphore< 1 >
template<bool __v>
using bool_constant = integral_constant< bool, __v >
typedef ratio< 1, 100 > centi
typedef match_results< const char * > cmatch
template<typename... _Ts>
using common_comparison_category_t = typename common_comparison_category< _Ts... >::type
template<typename... _Tp>
using common_reference_t = typename common_reference< _Tp... >::type
template<typename... _Tp>
using common_type_t = typename common_type< _Tp... >::type
template<typename _Tp , typename _Up = _Tp>
using compare_three_way_result_t = typename __detail::__cmp3way_res_impl< _Tp, _Up >::type
template<bool _Cond, typename _Iftrue , typename _Iffalse >
using conditional_t = typename conditional< _Cond, _Iftrue, _Iffalse >::type
typedef regex_iterator< const char * > cregex_iterator
typedef regex_token_iterator< const char * > cregex_token_iterator
typedef sub_match< const char * > csub_match
typedef ratio< 10, 1 > deca
template<typename _Tp >
using decay_t = typename decay< _Tp >::type
typedef ratio< 1, 10 > deci
typedef minstd_rand0 default_random_engine
template<bool _Cond, typename _Tp = void>
using enable_if_t = typename enable_if< _Cond, _Tp >::type
typedef ratio< 1000000000000000000, 1 > exa
using false_type = integral_constant< bool, false >
typedef ratio< 1, 1000000000000000 > femto
typedef basic_filebuf< char > filebuf
typedef basic_fstream< char > fstream
typedef ratio< 1000000000, 1 > giga
typedef ratio< 100, 1 > hecto
typedef basic_ifstream< char > ifstream
template<size_t... _Idx>
using index_sequence = integer_sequence< size_t, _Idx... >
template<typename... _Types>
using index_sequence_for = make_index_sequence< sizeof...(_Types)>
using indirect_result_t = invoke_result_t< _Fn, iter_reference_t< _Is >... >
template<typename _Fn , typename... _Args>
using invoke_result_t = typename invoke_result< _Fn, _Args... >::type
typedef basic_ios< char > ios
typedef basic_iostream< char > iostream
typedef basic_istream< char > istream
typedef basic_istringstream< char > istringstream
template<indirectly_readable _Tp>
using iter_common_reference_t = common_reference_t< iter_reference_t< _Tp >, iter_value_t< _Tp > & >
template<typename _Tp >
using iter_difference_t = __detail::__iter_diff_t< remove_cvref_t< _Tp > >
template<__detail::__dereferenceable _Tp>
using iter_reference_t = decltype(*std::declval< _Tp & >())
template<__detail::__dereferenceable _Tp>
using iter_rvalue_reference_t = ranges::__cust_imove::_IMove::__type< _Tp & >
template<typename _Tp >
using iter_value_t = __detail::__iter_value_t< remove_cvref_t< _Tp > >
typedef ratio< 1000, 1 > kilo
typedef shuffle_order_engine< minstd_rand0, 256 > knuth_b
template<size_t _Num>
using make_index_sequence = make_integer_sequence< size_t, _Num >
template<typename _Tp , _Tp _Num>
using make_integer_sequence = __make_integer_seq< integer_sequence, _Tp, _Num >
template<typename _Tp >
using make_signed_t = typename make_signed< _Tp >::type
template<typename _Tp >
using make_unsigned_t = typename make_unsigned< _Tp >::type
typedef ratio< 1000000, 1 > mega
typedef ratio< 1, 1000000 > micro
typedef ratio< 1, 1000 > milli
typedef linear_congruential_engine< uint_fast32_t, 48271UL, 0UL, 2147483647UL > minstd_rand
typedef linear_congruential_engine< uint_fast32_t, 16807UL, 0UL, 2147483647UL > minstd_rand0
typedef mersenne_twister_engine< uint_fast32_t, 32, 624, 397, 31, 0x9908b0dfUL, 11, 0xffffffffUL, 7, 0x9d2c5680UL, 15, 0xefc60000UL, 18, 1812433253UL > mt19937
typedef mersenne_twister_engine< uint_fast64_t, 64, 312, 156, 31, 0xb5026f5aa96619e9ULL, 29, 0x5555555555555555ULL, 17, 0x71d67fffeda60000ULL, 37, 0xfff7eee000000000ULL, 43, 6364136223846793005ULL > mt19937_64
typedef ratio< 1, 1000000000 > nano
typedef void(* new_handler) ()
typedef basic_ofstream< char > ofstream
typedef basic_ostream< char > ostream
typedef basic_ostringstream< char > ostringstream
typedef ratio< 1000000000000000, 1 > peta
typedef ratio< 1, 1000000000000 > pico
typedef __PTRDIFF_TYPE__ ptrdiff_t
typedef discard_block_engine< ranlux24_base, 223, 23 > ranlux24
typedef subtract_with_carry_engine< uint_fast32_t, 24, 10, 24 > ranlux24_base
typedef discard_block_engine< ranlux48_base, 389, 11 > ranlux48
typedef subtract_with_carry_engine< uint_fast64_t, 48, 5, 12 > ranlux48_base
template<typename _R1 , typename _R2 >
using ratio_add = typename __ratio_add< _R1, _R2 >::type
template<typename _R1 , typename _R2 >
using ratio_divide = typename __ratio_divide< _R1, _R2 >::type
template<typename _R1 , typename _R2 >
using ratio_multiply = typename __ratio_multiply< _R1, _R2 >::type
template<typename _R1 , typename _R2 >
using ratio_subtract = typename __ratio_subtract< _R1, _R2 >::type
typedef basic_regex< char > regex
template<typename _Tp >
using remove_all_extents_t = typename remove_all_extents< _Tp >::type
template<typename _Tp >
using remove_const_t = typename remove_const< _Tp >::type
template<typename _Tp >
using remove_cv_t = typename remove_cv< _Tp >::type
template<typename _Tp >
using remove_extent_t = typename remove_extent< _Tp >::type
template<typename _Tp >
using remove_pointer_t = typename remove_pointer< _Tp >::type
template<typename _Tp >
using remove_reference_t = typename remove_reference< _Tp >::type
template<typename _Tp >
using remove_volatile_t = typename remove_volatile< _Tp >::type
template<typename _Tp >
using result_of_t = typename result_of< _Tp >::type
typedef __SIZE_TYPE__ size_t
typedef match_results< string::const_iterator > smatch
typedef regex_iterator< string::const_iterator > sregex_iterator
typedef regex_token_iterator< string::const_iterator > sregex_token_iterator
typedef sub_match< string::const_iterator > ssub_match
typedef basic_streambuf< char > streambuf
typedef long long streamoff
typedef fpos< mbstate_t > streampos
typedef ptrdiff_t streamsize
typedef basic_string< char > string
using string_view = basic_string_view< char >
typedef basic_stringbuf< char > stringbuf
typedef basic_stringstream< char > stringstream
typedef ratio< 1000000000000, 1 > tera
typedef void(* terminate_handler) ()
using true_type = integral_constant< bool, true >
template<size_t __i, typename _Tp >
using tuple_element_t = typename tuple_element< __i, _Tp >::type
typedef fpos< mbstate_t > u16streampos
typedef basic_string< char16_t > u16string
using u16string_view = basic_string_view< char16_t >
typedef fpos< mbstate_t > u32streampos
typedef basic_string< char32_t > u32string
using u32string_view = basic_string_view< char32_t >
template<typename _Tp >
using underlying_type_t = typename underlying_type< _Tp >::type
typedef void(* unexpected_handler) ()
template<size_t _Np, typename _Variant >
using variant_alternative_t = typename variant_alternative< _Np, _Variant >::type
template<typename... >
using void_t = void
typedef match_results< const wchar_t * > wcmatch
typedef regex_iterator< const wchar_t * > wcregex_iterator
typedef regex_token_iterator< const wchar_t * > wcregex_token_iterator
typedef sub_match< const wchar_t * > wcsub_match
typedef basic_filebuf< wchar_t > wfilebuf
typedef basic_fstream< wchar_t > wfstream
typedef basic_ifstream< wchar_t > wifstream
typedef basic_ios< wchar_t > wios
typedef basic_iostream< wchar_t > wiostream
typedef basic_istream< wchar_t > wistream
typedef basic_istringstream< wchar_t > wistringstream
typedef basic_ofstream< wchar_t > wofstream
typedef basic_ostream< wchar_t > wostream
typedef basic_ostringstream< wchar_t > wostringstream
typedef basic_regex< wchar_t > wregex
typedef match_results< wstring::const_iterator > wsmatch
typedef regex_iterator< wstring::const_iterator > wsregex_iterator
typedef regex_token_iterator< wstring::const_iterator > wsregex_token_iterator
typedef sub_match< wstring::const_iterator > wssub_match
typedef basic_streambuf< wchar_t > wstreambuf
typedef fpos< mbstate_t > wstreampos
typedef basic_string< wchar_t > wstring
using wstring_view = basic_string_view< wchar_t >
typedef basic_stringbuf< wchar_t > wstringbuf
typedef basic_stringstream< wchar_t > wstringstream
template<typename _Tp >
using remove_cvref_t = typename remove_cvref< _Tp >::type
template<typename _Tp >
using type_identity_t = typename type_identity< _Tp >::type
template<typename _Tp >
using unwrap_reference_t = typename unwrap_reference< _Tp >::type
template<typename _Tp >
using unwrap_ref_decay_t = typename unwrap_ref_decay< _Tp >::type
Enumerations
enum { _S_threshold }
enum { _S_chunk_size }
enum { _S_word_bit }
enum class __barrier_phase_t : unsigned char
enum __memory_order_modifier { __memory_order_mask , __memory_order_modifier_mask , __memory_order_hle_acquire , __memory_order_hle_release }
enum _Ios_Fmtflags {
_S_boolalpha , _S_dec , _S_fixed , _S_hex ,
_S_internal , _S_left , _S_oct , _S_right ,
_S_scientific , _S_showbase , _S_showpoint , _S_showpos ,
_S_skipws , _S_unitbuf , _S_uppercase , _S_adjustfield ,
_S_basefield , _S_floatfield , _S_ios_fmtflags_end , _S_ios_fmtflags_max ,
_S_ios_fmtflags_min
}
enum _Ios_Iostate {
_S_goodbit , _S_badbit , _S_eofbit , _S_failbit ,
_S_ios_iostate_end , _S_ios_iostate_max , _S_ios_iostate_min
}
enum _Ios_Openmode {
_S_app , _S_ate , _S_bin , _S_in ,
_S_out , _S_trunc , _S_noreplace , _S_ios_openmode_end ,
_S_ios_openmode_max , _S_ios_openmode_min
}
enum _Ios_Seekdir { _S_beg , _S_cur , _S_end , _S_ios_seekdir_end }
enum _Manager_operation { __get_type_info , __get_functor_ptr , __clone_functor , __destroy_functor }
enum _Rb_tree_color { _S_red , _S_black }
enum class align_val_t : size_t
enum class byte : unsigned char
enum class chars_format { scientific , fixed , hex , general }
enum codecvt_mode { consume_header , generate_header , little_endian }
enum class cv_status { no_timeout , timeout }
enum class endian { little , big , native }
enum class errc {
address_family_not_supported , address_in_use , address_not_available , already_connected ,
argument_list_too_long , argument_out_of_domain , bad_address , bad_file_descriptor ,
broken_pipe , connection_aborted , connection_already_in_progress , connection_refused ,
connection_reset , cross_device_link , destination_address_required , device_or_resource_busy ,
directory_not_empty , executable_format_error , file_exists , file_too_large ,
filename_too_long , function_not_supported , host_unreachable , illegal_byte_sequence ,
inappropriate_io_control_operation , interrupted , invalid_argument , invalid_seek ,
io_error , is_a_directory , message_size , network_down ,
network_reset , network_unreachable , no_buffer_space , no_child_process ,
no_lock_available , no_message , no_protocol_option , no_space_on_device ,
no_such_device_or_address , no_such_device , no_such_file_or_directory , no_such_process ,
not_a_directory , not_a_socket , not_connected , not_enough_memory ,
operation_in_progress , operation_not_permitted , operation_not_supported , operation_would_block ,
permission_denied , protocol_not_supported , read_only_file_system , resource_deadlock_would_occur ,
resource_unavailable_try_again , result_out_of_range , timed_out , too_many_files_open_in_system ,
too_many_files_open , too_many_links , too_many_symbolic_link_levels , wrong_protocol_type
}
enum float_denorm_style { denorm_indeterminate , denorm_absent , denorm_present }
enum float_round_style {
round_indeterminate , round_toward_zero , round_to_nearest , round_toward_infinity ,
round_toward_neg_infinity
}
enum class future_errc { future_already_retrieved , promise_already_satisfied , no_state , broken_promise }
enum class future_status { ready , timeout , deferred }
enum class io_errc { stream }
enum class launch { async , deferred }
enum class memory_order : int {
relaxed , consume , acquire , release ,
acq_rel , seq_cst
}
enum class pointer_safety { relaxed , preferred , strict }
Functions
template<typename _CharT >
_CharT * __add_grouping (_CharT *__s, _CharT __sep, const char *__gbeg, size_t __gsize, const _CharT *__first, const _CharT *__last)
template<typename _Tp >
constexpr _Tp * __addressof (_Tp &__r) noexcept
template<typename _ForwardIterator , typename _BinaryPredicate >
constexpr _ForwardIterator __adjacent_find (_ForwardIterator __first, _ForwardIterator __last, _BinaryPredicate __binary_pred)
template<typename _RandomAccessIterator , typename _Distance , typename _Tp , typename _Compare >
constexpr void __adjust_heap (_RandomAccessIterator __first, _Distance __holeIndex, _Distance __len, _Tp __value, _Compare __comp)
template<typename _BidirectionalIterator , typename _Distance >
constexpr void __advance (_BidirectionalIterator &__i, _Distance __n, bidirectional_iterator_tag)
template<typename _InputIterator , typename _Distance >
constexpr void __advance (_InputIterator &__i, _Distance __n, input_iterator_tag)
template<typename _OutputIterator , typename _Distance >
void __advance (_OutputIterator &, _Distance, output_iterator_tag)=delete
template<typename _RandomAccessIterator , typename _Distance >
constexpr void __advance (_RandomAccessIterator &__i, _Distance __n, random_access_iterator_tag)
template<typename _Alloc >
constexpr void __alloc_on_copy (_Alloc &__one, const _Alloc &__two)
template<typename _Alloc >
constexpr _Alloc __alloc_on_copy (const _Alloc &__a)
template<typename _Alloc >
constexpr void __alloc_on_move (_Alloc &__one, _Alloc &__two)
template<typename _Alloc >
constexpr void __alloc_on_swap (_Alloc &__one, _Alloc &__two)
template<typename _Tp , _Lock_policy _Lp = __default_lock_policy, typename _Alloc , typename... _Args>
__shared_ptr< _Tp, _Lp > __allocate_shared (const _Alloc &__a, _Args &&... __args)
template<typename _Fn , typename _Tuple , size_t... _Idx>
constexpr decltype(auto) __apply_impl (_Fn &&__f, _Tuple &&__t, index_sequence< _Idx... >)
template<typename _Tp >
void __atomic_notify_address (const _Tp *__addr, bool __all) noexcept
void __atomic_notify_address_bare (const __detail::__platform_wait_t *__addr, bool __all) noexcept
template<typename _Tp , typename _Pred >
void __atomic_wait_address (const _Tp *__addr, _Pred __pred) noexcept
template<typename _Pred >
void __atomic_wait_address_bare (const __detail::__platform_wait_t *__addr, _Pred __pred) noexcept
template<typename _Tp , typename _Pred , typename _Rep , typename _Period >
bool __atomic_wait_address_for (const _Tp *__addr, _Pred __pred, const chrono::duration< _Rep, _Period > &__rtime) noexcept
template<typename _Pred , typename _Rep , typename _Period >
bool __atomic_wait_address_for_bare (const __detail::__platform_wait_t *__addr, _Pred __pred, const chrono::duration< _Rep, _Period > &__rtime) noexcept
template<typename _Tp , typename _ValFn , typename _Rep , typename _Period >
bool __atomic_wait_address_for_v (const _Tp *__addr, _Tp &&__old, _ValFn &&__vfn, const chrono::duration< _Rep, _Period > &__rtime) noexcept
template<typename _Tp , typename _Pred , typename _Clock , typename _Dur >
bool __atomic_wait_address_until (const _Tp *__addr, _Pred __pred, const chrono::time_point< _Clock, _Dur > &__atime) noexcept
template<typename _Pred , typename _Clock , typename _Dur >
bool __atomic_wait_address_until_bare (const __detail::__platform_wait_t *__addr, _Pred __pred, const chrono::time_point< _Clock, _Dur > &__atime) noexcept
template<typename _Tp , typename _ValFn , typename _Clock , typename _Dur >
bool __atomic_wait_address_until_v (const _Tp *__addr, _Tp &&__old, _ValFn &&__vfn, const chrono::time_point< _Clock, _Dur > &__atime) noexcept
template<typename _Tp , typename _ValFn >
void __atomic_wait_address_v (const _Tp *__addr, _Tp __old, _ValFn __vfn) noexcept
template<typename _Facet >
const _Facet & __check_facet (const _Facet *__f)
template<typename _RandomAccessIterator , typename _Distance , typename _Compare >
constexpr void __chunk_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Distance __chunk_size, _Compare __comp)
constexpr memory_order __cmpexch_failure_order (memory_order __m) noexcept
constexpr memory_order __cmpexch_failure_order2 (memory_order __m) noexcept
template<typename _Tp >
_Tp __complex_abs (const complex< _Tp > &__z)
template<typename _Tp >
std::complex< _Tp > __complex_acos (const std::complex< _Tp > &__z)
template<typename _Tp >
std::complex< _Tp > __complex_acosh (const std::complex< _Tp > &__z)
template<typename _Tp >
_Tp __complex_arg (const complex< _Tp > &__z)
template<typename _Tp >
std::complex< _Tp > __complex_asin (const std::complex< _Tp > &__z)
template<typename _Tp >
std::complex< _Tp > __complex_asinh (const std::complex< _Tp > &__z)
template<typename _Tp >
std::complex< _Tp > __complex_atan (const std::complex< _Tp > &__z)
template<typename _Tp >
std::complex< _Tp > __complex_atanh (const std::complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > __complex_cos (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > __complex_cosh (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > __complex_exp (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > __complex_log (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > __complex_pow (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
complex< _Tp > __complex_pow_unsigned (complex< _Tp > __x, unsigned __n)
template<typename _Tp >
std::complex< _Tp > __complex_proj (const std::complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > __complex_sin (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > __complex_sinh (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > __complex_sqrt (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > __complex_tan (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > __complex_tanh (const complex< _Tp > &__z)
int __convert_from_v (const __c_locale &__cloc, char *__out, const int __size, const char *__fmt,...)
template<typename _Tp >
void __convert_to_v (const char *, _Tp &, ios_base::iostate &, const __c_locale &) throw ()
template<>
void __convert_to_v (const char *, double &, ios_base::iostate &, const __c_locale &) throw ()
template<>
void __convert_to_v (const char *, float &, ios_base::iostate &, const __c_locale &) throw ()
template<>
void __convert_to_v (const char *, long double &, ios_base::iostate &, const __c_locale &) throw ()
template<bool _IsMove, typename _II , typename _OI >
constexpr _OI __copy_move_a (_II __first, _II __last, _OI __result)
template<bool _IsMove, typename _II , typename _Ite , typename _Seq , typename _Cat >
__gnu_debug::_Safe_iterator< _Ite, _Seq, _Cat > __copy_move_a (_II, _II, const ::__gnu_debug::_Safe_iterator< _Ite, _Seq, _Cat > &)
template<bool _IsMove, typename _IIte , typename _ISeq , typename _ICat , typename _OIte , typename _OSeq , typename _OCat >
::__gnu_debug::_Safe_iterator< _OIte, _OSeq, _OCat > __copy_move_a (const ::__gnu_debug::_Safe_iterator< _IIte, _ISeq, _ICat > &, const ::__gnu_debug::_Safe_iterator< _IIte, _ISeq, _ICat > &, const ::__gnu_debug::_Safe_iterator< _OIte, _OSeq, _OCat > &)
template<bool _IsMove, typename _Ite , typename _Seq , typename _Cat , typename _OI >
_OI __copy_move_a (const ::__gnu_debug::_Safe_iterator< _Ite, _Seq, _Cat > &, const ::__gnu_debug::_Safe_iterator< _Ite, _Seq, _Cat > &, _OI)
template<bool _IsMove, typename _ITp , typename _IRef , typename _IPtr , typename _OTp >
::_Deque_iterator< _OTp, _OTp &, _OTp * > __copy_move_a1 (::_Deque_iterator< _ITp, _IRef, _IPtr > __first, ::_Deque_iterator< _ITp, _IRef, _IPtr > __last, ::_Deque_iterator< _OTp, _OTp &, _OTp * > __result)
template<bool _IsMove, typename _Tp , typename _Ref , typename _Ptr , typename _OI >
_OI __copy_move_a1 (::_Deque_iterator< _Tp, _Ref, _Ptr > __first, ::_Deque_iterator< _Tp, _Ref, _Ptr > __last, _OI __result)
template<bool _IsMove, typename _II , typename _Tp >
__gnu_cxx::__enable_if< __is_random_access_iter< _II >::__value, ::_Deque_iterator< _Tp, _Tp &, _Tp * > >::__type __copy_move_a1 (_II __first, _II __last, ::_Deque_iterator< _Tp, _Tp &, _Tp * > __result)
template<bool _IsMove, typename _II , typename _OI >
constexpr _OI __copy_move_a1 (_II __first, _II __last, _OI __result)
template<bool _IsMove, typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, ostreambuf_iterator< _CharT, char_traits< _CharT > > >::__type __copy_move_a2 (_CharT *, _CharT *, ostreambuf_iterator< _CharT, char_traits< _CharT > >)
template<bool _IsMove, typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, ostreambuf_iterator< _CharT > >::__type __copy_move_a2 (_CharT *__first, _CharT *__last, ostreambuf_iterator< _CharT > __result)
template<bool _IsMove, typename _II , typename _OI >
constexpr _OI __copy_move_a2 (_II __first, _II __last, _OI __result)
template<bool _IsMove, typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, ostreambuf_iterator< _CharT, char_traits< _CharT > > >::__type __copy_move_a2 (const _CharT *, const _CharT *, ostreambuf_iterator< _CharT, char_traits< _CharT > >)
template<bool _IsMove, typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, ostreambuf_iterator< _CharT > >::__type __copy_move_a2 (const _CharT *__first, const _CharT *__last, ostreambuf_iterator< _CharT > __result)
template<bool _IsMove, typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, _CharT * >::__type __copy_move_a2 (istreambuf_iterator< _CharT > __first, istreambuf_iterator< _CharT > __last, _CharT *__result)
template<bool _IsMove, typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, ::_Deque_iterator< _CharT, _CharT &, _CharT * > >::__type __copy_move_a2 (istreambuf_iterator< _CharT, char_traits< _CharT > > __first, istreambuf_iterator< _CharT, char_traits< _CharT > > __last, ::_Deque_iterator< _CharT, _CharT &, _CharT * > __result)
template<bool _IsMove, typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, _CharT * >::__type __copy_move_a2 (istreambuf_iterator< _CharT, char_traits< _CharT > >, istreambuf_iterator< _CharT, char_traits< _CharT > >, _CharT *)
template<bool _IsMove, typename _II , typename _OI >
constexpr _OI __copy_move_backward_a (_II __first, _II __last, _OI __result)
template<bool _IsMove, typename _II , typename _Ite , typename _Seq , typename _Cat >
__gnu_debug::_Safe_iterator< _Ite, _Seq, _Cat > __copy_move_backward_a (_II, _II, const ::__gnu_debug::_Safe_iterator< _Ite, _Seq, _Cat > &)
template<bool _IsMove, typename _IIte , typename _ISeq , typename _ICat , typename _OIte , typename _OSeq , typename _OCat >
::__gnu_debug::_Safe_iterator< _OIte, _OSeq, _OCat > __copy_move_backward_a (const ::__gnu_debug::_Safe_iterator< _IIte, _ISeq, _ICat > &, const ::__gnu_debug::_Safe_iterator< _IIte, _ISeq, _ICat > &, const ::__gnu_debug::_Safe_iterator< _OIte, _OSeq, _OCat > &)
template<bool _IsMove, typename _Ite , typename _Seq , typename _Cat , typename _OI >
_OI __copy_move_backward_a (const ::__gnu_debug::_Safe_iterator< _Ite, _Seq, _Cat > &, const ::__gnu_debug::_Safe_iterator< _Ite, _Seq, _Cat > &, _OI)
template<bool _IsMove, typename _ITp , typename _IRef , typename _IPtr , typename _OTp >
::_Deque_iterator< _OTp, _OTp &, _OTp * > __copy_move_backward_a1 (::_Deque_iterator< _ITp, _IRef, _IPtr > __first, ::_Deque_iterator< _ITp, _IRef, _IPtr > __last, ::_Deque_iterator< _OTp, _OTp &, _OTp * > __result)
template<bool _IsMove, typename _Tp , typename _Ref , typename _Ptr , typename _OI >
_OI __copy_move_backward_a1 (::_Deque_iterator< _Tp, _Ref, _Ptr > __first, ::_Deque_iterator< _Tp, _Ref, _Ptr > __last, _OI __result)
template<bool _IsMove, typename _BI1 , typename _BI2 >
constexpr _BI2 __copy_move_backward_a1 (_BI1 __first, _BI1 __last, _BI2 __result)
template<bool _IsMove, typename _II , typename _Tp >
__gnu_cxx::__enable_if< __is_random_access_iter< _II >::__value, ::_Deque_iterator< _Tp, _Tp &, _Tp * > >::__type __copy_move_backward_a1 (_II __first, _II __last, ::_Deque_iterator< _Tp, _Tp &, _Tp * > __result)
template<bool _IsMove, typename _BI1 , typename _BI2 >
constexpr _BI2 __copy_move_backward_a2 (_BI1 __first, _BI1 __last, _BI2 __result)
template<bool _IsMove, typename _Tp , typename _Ref , typename _Ptr , typename _OI >
_OI __copy_move_backward_dit (::_Deque_iterator< _Tp, _Ref, _Ptr > __first, ::_Deque_iterator< _Tp, _Ref, _Ptr > __last, _OI __result)
template<bool _IsMove, typename _Tp , typename _Ref , typename _Ptr , typename _OI >
_OI __copy_move_dit (::_Deque_iterator< _Tp, _Ref, _Ptr > __first, ::_Deque_iterator< _Tp, _Ref, _Ptr > __last, _OI __result)
template<typename _InputIterator , typename _Size , typename _OutputIterator >
constexpr _OutputIterator __copy_n (_InputIterator __first, _Size __n, _OutputIterator __result, input_iterator_tag)
template<typename _RandomAccessIterator , typename _Size , typename _OutputIterator >
constexpr _OutputIterator __copy_n (_RandomAccessIterator __first, _Size __n, _OutputIterator __result, random_access_iterator_tag)
template<typename _InputIterator , typename _Size , typename _OutputIterator >
constexpr _OutputIterator __copy_n_a (_InputIterator __first, _Size __n, _OutputIterator __result, bool)
template<typename _CharT , typename _Size >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, _CharT * >::__type __copy_n_a (istreambuf_iterator< _CharT > __it, _Size __n, _CharT *__result, bool __strict)
template<typename _CharT , typename _Size >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, ::_Deque_iterator< _CharT, _CharT &, _CharT * > >::__type __copy_n_a (istreambuf_iterator< _CharT, char_traits< _CharT > > __it, _Size __size, ::_Deque_iterator< _CharT, _CharT &, _CharT * > __result, bool __strict)
template<typename _CharT , typename _Size >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, _CharT * >::__type __copy_n_a (istreambuf_iterator< _CharT, char_traits< _CharT > >, _Size, _CharT *, bool)
template<typename _CharT , typename _Traits >
streamsize __copy_streambufs (basic_streambuf< _CharT, _Traits > *__sbin, basic_streambuf< _CharT, _Traits > *__sbout)
template<typename _CharT , typename _Traits >
streamsize __copy_streambufs_eof (basic_streambuf< _CharT, _Traits > *, basic_streambuf< _CharT, _Traits > *, bool &)
template<>
streamsize __copy_streambufs_eof (basic_streambuf< char > *__sbin, basic_streambuf< char > *__sbout, bool &__ineof)
template<>
streamsize __copy_streambufs_eof (basic_streambuf< wchar_t > *__sbin, basic_streambuf< wchar_t > *__sbout, bool &__ineof)
template<typename _InputIterator , typename _Predicate >
constexpr iterator_traits< _InputIterator >::difference_type __count_if (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _Signature , typename _Fn , typename _Alloc = std::allocator<int>>
static shared_ptr< __future_base::_Task_state_base< _Signature > > __create_task_state (_Fn &&__fn, const _Alloc &__a=_Alloc())
constexpr size_t __deque_buf_size (size_t __size)
template<typename _InputIterator >
constexpr iterator_traits< _InputIterator >::difference_type __distance (_InputIterator __first, _InputIterator __last, input_iterator_tag)
template<typename _OutputIterator >
void __distance (_OutputIterator, _OutputIterator, output_iterator_tag)=delete
template<typename _RandomAccessIterator >
constexpr iterator_traits< _RandomAccessIterator >::difference_type __distance (_RandomAccessIterator __first, _RandomAccessIterator __last, random_access_iterator_tag)
template<typename _OutStr , typename _InChar , typename _Codecvt , typename _State , typename _Fn >
bool __do_str_codecvt (const _InChar *__first, const _InChar *__last, _OutStr &__outstr, const _Codecvt &__cvt, _State &__state, size_t &__count, _Fn __fn)
template<typename _Result_type , typename _Visitor , typename... _Variants>
constexpr decltype(auto) __do_visit (_Visitor &&__visitor, _Variants &&... __variants)
template<typename _II1 , typename _II2 >
constexpr bool __equal4 (_II1 __first1, _II1 __last1, _II2 __first2, _II2 __last2)
template<typename _II1 , typename _II2 , typename _BinaryPredicate >
constexpr bool __equal4 (_II1 __first1, _II1 __last1, _II2 __first2, _II2 __last2, _BinaryPredicate __binary_pred)
template<typename _II1 , typename _II2 >
constexpr bool __equal_aux (_II1 __first1, _II1 __last1, _II2 __first2)
template<typename _II1 , typename _II2 , typename _Seq2 , typename _Cat2 >
bool __equal_aux (_II1, _II1, const ::__gnu_debug::_Safe_iterator< _II2, _Seq2, _Cat2 > &)
template<typename _II1 , typename _Seq1 , typename _Cat1 , typename _II2 >
bool __equal_aux (const ::__gnu_debug::_Safe_iterator< _II1, _Seq1, _Cat1 > &, const ::__gnu_debug::_Safe_iterator< _II1, _Seq1, _Cat1 > &, _II2)
template<typename _II1 , typename _Seq1 , typename _Cat1 , typename _II2 , typename _Seq2 , typename _Cat2 >
bool __equal_aux (const ::__gnu_debug::_Safe_iterator< _II1, _Seq1, _Cat1 > &, const ::__gnu_debug::_Safe_iterator< _II1, _Seq1, _Cat1 > &, const ::__gnu_debug::_Safe_iterator< _II2, _Seq2, _Cat2 > &)
template<typename _Tp , typename _Ref , typename _Ptr , typename _II >
__gnu_cxx::__enable_if< __is_random_access_iter< _II >::__value, bool >::__type __equal_aux1 (::_Deque_iterator< _Tp, _Ref, _Ptr > __first1, ::_Deque_iterator< _Tp, _Ref, _Ptr > __last1, _II __first2)
template<typename _Tp1 , typename _Ref1 , typename _Ptr1 , typename _Tp2 , typename _Ref2 , typename _Ptr2 >
bool __equal_aux1 (::_Deque_iterator< _Tp1, _Ref1, _Ptr1 > __first1, ::_Deque_iterator< _Tp1, _Ref1, _Ptr1 > __last1, ::_Deque_iterator< _Tp2, _Ref2, _Ptr2 > __first2)
template<typename _II , typename _Tp , typename _Ref , typename _Ptr >
__gnu_cxx::__enable_if< __is_random_access_iter< _II >::__value, bool >::__type __equal_aux1 (_II __first1, _II __last1, ::_Deque_iterator< _Tp, _Ref, _Ptr > __first2)
template<typename _II1 , typename _II2 >
constexpr bool __equal_aux1 (_II1 __first1, _II1 __last1, _II2 __first2)
template<typename _Tp , typename _Ref , typename _Ptr , typename _II >
bool __equal_dit (const ::_Deque_iterator< _Tp, _Ref, _Ptr > &__first1, const ::_Deque_iterator< _Tp, _Ref, _Ptr > &__last1, _II __first2)
template<typename _ForwardIterator , typename _Tp , typename _CompareItTp , typename _CompareTpIt >
constexpr pair< _ForwardIterator, _ForwardIterator > __equal_range (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _CompareItTp __comp_it_val, _CompareTpIt __comp_val_it)
template<typename _Tp , typename _Up = _Tp>
constexpr _Tp __exchange (_Tp &__obj, _Up &&__new_val)
template<typename _FIte , typename _Tp >
constexpr void __fill_a (_FIte __first, _FIte __last, const _Tp &__value)
template<typename _Ite , typename _Seq , typename _Cat , typename _Tp >
void __fill_a (const ::__gnu_debug::_Safe_iterator< _Ite, _Seq, _Cat > &, const ::__gnu_debug::_Safe_iterator< _Ite, _Seq, _Cat > &, const _Tp &)
template<typename _Ite , typename _Cont , typename _Tp >
constexpr void __fill_a1 (::__gnu_cxx::__normal_iterator< _Ite, _Cont > __first, ::__gnu_cxx::__normal_iterator< _Ite, _Cont > __last, const _Tp &__value)
constexpr void __fill_a1 (::_Bit_iterator, ::_Bit_iterator, const bool &)
template<typename _ForwardIterator , typename _Tp >
constexpr __gnu_cxx::__enable_if<!__is_scalar< _Tp >::__value, void >::__type __fill_a1 (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value)
template<typename _ForwardIterator , typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_scalar< _Tp >::__value, void >::__type __fill_a1 (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value)
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_byte< _Tp >::__value, void >::__type __fill_a1 (_Tp *__first, _Tp *__last, const _Tp &__c)
template<typename _Tp , typename _VTp >
void __fill_a1 (const ::_Deque_iterator< _Tp, _Tp &, _Tp * > &__first, const ::_Deque_iterator< _Tp, _Tp &, _Tp * > &__last, const _VTp &__value)
constexpr void __fill_bvector (_Bit_type *__v, unsigned int __first, unsigned int __last, bool __x) noexcept
constexpr void __fill_bvector_n (_Bit_type *, size_t, bool) noexcept
template<typename _OutputIterator , typename _Size , typename _Tp >
constexpr _OutputIterator __fill_n_a (_OutputIterator __first, _Size __n, const _Tp &__value, std::input_iterator_tag)
template<typename _OutputIterator , typename _Size , typename _Tp >
constexpr _OutputIterator __fill_n_a (_OutputIterator __first, _Size __n, const _Tp &__value, std::output_iterator_tag)
template<typename _OutputIterator , typename _Size , typename _Tp >
constexpr _OutputIterator __fill_n_a (_OutputIterator __first, _Size __n, const _Tp &__value, std::random_access_iterator_tag)
template<typename _Ite , typename _Seq , typename _Cat , typename _Size , typename _Tp >
::__gnu_debug::_Safe_iterator< _Ite, _Seq, _Cat > __fill_n_a (const ::__gnu_debug::_Safe_iterator< _Ite, _Seq, _Cat > &__first, _Size __n, const _Tp &__value, std::input_iterator_tag)
template<typename _OutputIterator , typename _Size , typename _Tp >
constexpr __gnu_cxx::__enable_if<!__is_scalar< _Tp >::__value, _OutputIterator >::__type __fill_n_a1 (_OutputIterator __first, _Size __n, const _Tp &__value)
template<typename _OutputIterator , typename _Size , typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_scalar< _Tp >::__value, _OutputIterator >::__type __fill_n_a1 (_OutputIterator __first, _Size __n, const _Tp &__value)
template<typename _RandomAccessIterator , typename _Compare >
constexpr void __final_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 , typename _BinaryPredicate >
constexpr _BidirectionalIterator1 __find_end (_BidirectionalIterator1 __first1, _BidirectionalIterator1 __last1, _BidirectionalIterator2 __first2, _BidirectionalIterator2 __last2, bidirectional_iterator_tag, bidirectional_iterator_tag, _BinaryPredicate __comp)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate >
constexpr _ForwardIterator1 __find_end (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2, forward_iterator_tag, forward_iterator_tag, _BinaryPredicate __comp)
template<typename _InputIterator , typename _Predicate >
constexpr _InputIterator __find_if (_InputIterator __first, _InputIterator __last, _Predicate __pred, input_iterator_tag)
template<typename _Iterator , typename _Predicate >
constexpr _Iterator __find_if (_Iterator __first, _Iterator __last, _Predicate __pred)
template<typename _RandomAccessIterator , typename _Predicate >
constexpr _RandomAccessIterator __find_if (_RandomAccessIterator __first, _RandomAccessIterator __last, _Predicate __pred, random_access_iterator_tag)
template<typename _InputIterator , typename _Predicate >
constexpr _InputIterator __find_if_not (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _InputIterator , typename _Predicate , typename _Distance >
constexpr _InputIterator __find_if_not_n (_InputIterator __first, _Distance &__len, _Predicate __pred)
template<typename _Tp , typename... _Types>
constexpr size_t __find_uniq_type_in_pack ()
template<typename _EuclideanRingElement >
constexpr _EuclideanRingElement __gcd (_EuclideanRingElement __m, _EuclideanRingElement __n)
template<typename _IntType , typename _UniformRandomBitGenerator >
pair< _IntType, _IntType > __gen_two_uniform_ints (_IntType __b0, _IntType __b1, _UniformRandomBitGenerator &&__g)
template<size_t __i, typename _Head , typename... _Tail>
constexpr _Head & __get_helper (_Tuple_impl< __i, _Head, _Tail... > &__t) noexcept
template<size_t __i, typename _Head , typename... _Tail>
constexpr const _Head & __get_helper (const _Tuple_impl< __i, _Head, _Tail... > &__t) noexcept
template<size_t __i, typename... _Types>
__enable_if_t<(__i >=sizeof...(_Types))> __get_helper (const tuple< _Types... > &)=delete
template<typename _RandomAccessIterator , typename _Compare >
constexpr void __heap_select (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last, _Compare __comp)
template<typename _Tp >
_Tp __hypot3 (_Tp __x, _Tp __y, _Tp __z)
template<typename _Tp >
size_t __iconv_adaptor (size_t(*__func)(iconv_t, _Tp, size_t *, char **, size_t *), iconv_t __cd, char **__inbuf, size_t *__inbytes, char **__outbuf, size_t *__outbytes)
template<typename _InputIterator1 , typename _InputIterator2 , typename _Compare >
constexpr bool __includes (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _Compare __comp)
template<typename _BidirectionalIterator , typename _Compare >
void __inplace_merge (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Compare >
void __inplace_stable_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Compare >
constexpr void __insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _CharT , typename _ValueT >
int __int_to_char (_CharT *__bufend, _ValueT __v, const _CharT *__lit, ios_base::fmtflags __flags, bool __dec)
template<typename _RandomAccessIterator , typename _Size , typename _Compare >
constexpr void __introselect (_RandomAccessIterator __first, _RandomAccessIterator __nth, _RandomAccessIterator __last, _Size __depth_limit, _Compare __comp)
template<typename _RandomAccessIterator , typename _Size , typename _Compare >
constexpr void __introsort_loop (_RandomAccessIterator __first, _RandomAccessIterator __last, _Size __depth_limit, _Compare __comp)
template<typename _Tp , typename _Up = typename __inv_unwrap<_Tp>::type>
constexpr _Up && __invfwd (typename remove_reference< _Tp >::type &__t) noexcept
template<typename _Callable , typename... _Args>
constexpr __invoke_result< _Callable, _Args... >::type __invoke (_Callable &&__fn, _Args &&... __args) noexcept(__is_nothrow_invocable< _Callable, _Args... >::value)
template<typename _Res , typename _MemFun , typename _Tp , typename... _Args>
constexpr _Res __invoke_impl (__invoke_memfun_deref, _MemFun &&__f, _Tp &&__t, _Args &&... __args)
template<typename _Res , typename _MemFun , typename _Tp , typename... _Args>
constexpr _Res __invoke_impl (__invoke_memfun_ref, _MemFun &&__f, _Tp &&__t, _Args &&... __args)
template<typename _Res , typename _MemPtr , typename _Tp >
constexpr _Res __invoke_impl (__invoke_memobj_deref, _MemPtr &&__f, _Tp &&__t)
template<typename _Res , typename _MemPtr , typename _Tp >
constexpr _Res __invoke_impl (__invoke_memobj_ref, _MemPtr &&__f, _Tp &&__t)
template<typename _Res , typename _Fn , typename... _Args>
constexpr _Res __invoke_impl (__invoke_other, _Fn &&__f, _Args &&... __args)
template<typename _Res , typename _Callable , typename... _Args>
constexpr enable_if_t< is_invocable_r_v< _Res, _Callable, _Args... >, _Res > __invoke_r (_Callable &&__fn, _Args &&... __args) noexcept(is_nothrow_invocable_r_v< _Res, _Callable, _Args... >)
constexpr bool __is_constant_evaluated () noexcept
template<typename _RandomAccessIterator , typename _Compare , typename _Distance >
constexpr bool __is_heap (_RandomAccessIterator __first, _Compare __comp, _Distance __n)
template<typename _RandomAccessIterator , typename _Distance >
constexpr bool __is_heap (_RandomAccessIterator __first, _Distance __n)
template<typename _RandomAccessIterator >
constexpr bool __is_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
constexpr bool __is_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Distance , typename _Compare >
constexpr _Distance __is_heap_until (_RandomAccessIterator __first, _Distance __n, _Compare &__comp)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate >
constexpr bool __is_permutation (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _BinaryPredicate __pred)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate >
constexpr bool __is_permutation (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2, _BinaryPredicate __pred)
template<typename _ForwardIterator , typename _Compare >
constexpr _ForwardIterator __is_sorted_until (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
constexpr bool __is_valid_cmpexch_failure_order (memory_order __m) noexcept
template<typename _CharT , typename _Traits >
void __istream_extract (basic_istream< _CharT, _Traits > &, _CharT *, streamsize)
void __istream_extract (istream &, char *, streamsize)
template<typename _Iter >
constexpr iterator_traits< _Iter >::iterator_category __iterator_category (const _Iter &)
template<typename _Fp >
constexpr _Fp __lerp (_Fp __a, _Fp __b, _Fp __t) noexcept
template<typename _Tp1 , typename _Ref , typename _Ptr , typename _Tp2 >
int __lex_cmp_dit (::_Deque_iterator< _Tp1, _Ref, _Ptr > __first1, ::_Deque_iterator< _Tp1, _Ref, _Ptr > __last1, const _Tp2 *__first2, const _Tp2 *__last2)
template<typename _II1 , typename _II2 >
constexpr bool __lexicographical_compare_aux (_II1 __first1, _II1 __last1, _II2 __first2, _II2 __last2)
template<typename _II1 , typename _Ite2 , typename _Seq2 , typename _Cat2 >
bool __lexicographical_compare_aux (_II1 __first1, _II1 __last1, const ::__gnu_debug::_Safe_iterator< _Ite2, _Seq2, _Cat2 > &__first2, const ::__gnu_debug::_Safe_iterator< _Ite2, _Seq2, _Cat2 > &__last2)
template<typename _II1 , typename _Iter2 , typename _Seq2 , typename _Cat2 >
bool __lexicographical_compare_aux (_II1, _II1, const ::__gnu_debug::_Safe_iterator< _Iter2, _Seq2, _Cat2 > &, const ::__gnu_debug::_Safe_iterator< _Iter2, _Seq2, _Cat2 > &)
template<typename _Ite1 , typename _Seq1 , typename _Cat1 , typename _II2 >
bool __lexicographical_compare_aux (const ::__gnu_debug::_Safe_iterator< _Ite1, _Seq1, _Cat1 > &__first1, const ::__gnu_debug::_Safe_iterator< _Ite1, _Seq1, _Cat1 > &__last1, _II2 __first2, _II2 __last2)
template<typename _Ite1 , typename _Seq1 , typename _Cat1 , typename _Ite2 , typename _Seq2 , typename _Cat2 >
bool __lexicographical_compare_aux (const ::__gnu_debug::_Safe_iterator< _Ite1, _Seq1, _Cat1 > &__first1, const ::__gnu_debug::_Safe_iterator< _Ite1, _Seq1, _Cat1 > &__last1, const ::__gnu_debug::_Safe_iterator< _Ite2, _Seq2, _Cat2 > &__first2, const ::__gnu_debug::_Safe_iterator< _Ite2, _Seq2, _Cat2 > &__last2)
template<typename _Iter1 , typename _Seq1 , typename _Cat1 , typename _II2 >
bool __lexicographical_compare_aux (const ::__gnu_debug::_Safe_iterator< _Iter1, _Seq1, _Cat1 > &, const ::__gnu_debug::_Safe_iterator< _Iter1, _Seq1, _Cat1 > &, _II2, _II2)
template<typename _Iter1 , typename _Seq1 , typename _Cat1 , typename _Iter2 , typename _Seq2 , typename _Cat2 >
bool __lexicographical_compare_aux (const ::__gnu_debug::_Safe_iterator< _Iter1, _Seq1, _Cat1 > &, const ::__gnu_debug::_Safe_iterator< _Iter1, _Seq1, _Cat1 > &, const ::__gnu_debug::_Safe_iterator< _Iter2, _Seq2, _Cat2 > &, const ::__gnu_debug::_Safe_iterator< _Iter2, _Seq2, _Cat2 > &)
template<typename _Tp1 , typename _Ref1 , typename _Ptr1 , typename _Tp2 , typename _Ref2 , typename _Ptr2 >
bool __lexicographical_compare_aux1 (::_Deque_iterator< _Tp1, _Ref1, _Ptr1 > __first1, ::_Deque_iterator< _Tp1, _Ref1, _Ptr1 > __last1, ::_Deque_iterator< _Tp2, _Ref2, _Ptr2 > __first2, ::_Deque_iterator< _Tp2, _Ref2, _Ptr2 > __last2)
template<typename _Tp1 , typename _Ref1 , typename _Ptr1 , typename _Tp2 >
bool __lexicographical_compare_aux1 (::_Deque_iterator< _Tp1, _Ref1, _Ptr1 > __first1, ::_Deque_iterator< _Tp1, _Ref1, _Ptr1 > __last1, _Tp2 *__first2, _Tp2 *__last2)
template<typename _II1 , typename _II2 >
constexpr bool __lexicographical_compare_aux1 (_II1 __first1, _II1 __last1, _II2 __first2, _II2 __last2)
template<typename _Tp1 , typename _Tp2 , typename _Ref2 , typename _Ptr2 >
bool __lexicographical_compare_aux1 (_Tp1 *__first1, _Tp1 *__last1, ::_Deque_iterator< _Tp2, _Ref2, _Ptr2 > __first2, ::_Deque_iterator< _Tp2, _Ref2, _Ptr2 > __last2)
template<typename _II1 , typename _II2 , typename _Compare >
constexpr bool __lexicographical_compare_impl (_II1 __first1, _II1 __last1, _II2 __first2, _II2 __last2, _Compare __comp)
constexpr int __lg (int __n)
constexpr long __lg (long __n)
constexpr long long __lg (long long __n)
constexpr unsigned __lg (unsigned __n)
constexpr unsigned long __lg (unsigned long __n)
constexpr unsigned long long __lg (unsigned long long __n)
template<typename _ForwardIterator , typename _Tp , typename _Compare >
constexpr _ForwardIterator __lower_bound (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _Compare __comp)
template<typename _Tp , typename _Tuple , size_t... _Idx>
constexpr _Tp __make_from_tuple_impl (_Tuple &&__t, index_sequence< _Idx... >)
template<typename _RandomAccessIterator , typename _Compare >
constexpr void __make_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare &__comp)
template<typename _Iterator , typename _ReturnType = __conditional_t<__move_if_noexcept_cond <typename iterator_traits<_Iterator>::value_type>::value, _Iterator, move_iterator<_Iterator>>>
constexpr _ReturnType __make_move_if_noexcept_iterator (_Iterator __i)
template<typename _Tp , typename _ReturnType = __conditional_t<__move_if_noexcept_cond<_Tp>::value, const _Tp*, move_iterator<_Tp*>>>
constexpr _ReturnType __make_move_if_noexcept_iterator (_Tp *__i)
template<typename _Iterator >
constexpr reverse_iterator< _Iterator > __make_reverse_iterator (_Iterator __i)
template<typename _Tp , _Lock_policy _Lp = __default_lock_policy, typename... _Args>
__shared_ptr< _Tp, _Lp > __make_shared (_Args &&... __args)
template<typename _ForwardIterator , typename _Compare >
constexpr _ForwardIterator __max_element (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _Tp , typename _Up >
constexpr int __memcmp (const _Tp *__first1, const _Up *__first2, size_t __num)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
constexpr _OutputIterator __merge (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _BidirectionalIterator , typename _Distance , typename _Pointer , typename _Compare >
void __merge_adaptive (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Distance __len1, _Distance __len2, _Pointer __buffer, _Distance __buffer_size, _Compare __comp)
template<typename _RandomAccessIterator1 , typename _RandomAccessIterator2 , typename _Distance , typename _Compare >
void __merge_sort_loop (_RandomAccessIterator1 __first, _RandomAccessIterator1 __last, _RandomAccessIterator2 __result, _Distance __step_size, _Compare __comp)
template<typename _RandomAccessIterator , typename _Pointer , typename _Compare >
void __merge_sort_with_buffer (_RandomAccessIterator __first, _RandomAccessIterator __last, _Pointer __buffer, _Compare __comp)
template<typename _BidirectionalIterator , typename _Distance , typename _Compare >
void __merge_without_buffer (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Distance __len1, _Distance __len2, _Compare __comp)
template<typename _ForwardIterator , typename _Compare >
constexpr _ForwardIterator __min_element (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _ForwardIterator , typename _Compare >
constexpr pair< _ForwardIterator, _ForwardIterator > __minmax_element (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _InputIterator1 , typename _InputIterator2 , typename _BinaryPredicate >
constexpr pair< _InputIterator1, _InputIterator2 > __mismatch (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _BinaryPredicate __binary_pred)
template<typename _InputIterator1 , typename _InputIterator2 , typename _BinaryPredicate >
constexpr pair< _InputIterator1, _InputIterator2 > __mismatch (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _BinaryPredicate __binary_pred)
template<typename _Iterator >
constexpr _Iterator __miter_base (_Iterator __it)
template<typename _Iterator >
constexpr auto __miter_base (move_iterator< _Iterator > __it) -> decltype(__miter_base(__it.base()))
template<typename _Iterator >
constexpr auto __miter_base (reverse_iterator< _Iterator > __it) -> decltype(__make_reverse_iterator(__miter_base(__it.base())))
template<typename _Iterator , typename _Compare >
constexpr void __move_median_to_first (_Iterator __result, _Iterator __a, _Iterator __b, _Iterator __c, _Compare __comp)
template<typename _InputIterator , typename _OutputIterator , typename _Compare >
_OutputIterator __move_merge (_InputIterator __first1, _InputIterator __last1, _InputIterator __first2, _InputIterator __last2, _OutputIterator __result, _Compare __comp)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
void __move_merge_adaptive (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 , typename _BidirectionalIterator3 , typename _Compare >
void __move_merge_adaptive_backward (_BidirectionalIterator1 __first1, _BidirectionalIterator1 __last1, _BidirectionalIterator2 __first2, _BidirectionalIterator2 __last2, _BidirectionalIterator3 __result, _Compare __comp)
template<typename _BidirectionalIterator , typename _Compare >
constexpr bool __next_permutation (_BidirectionalIterator __first, _BidirectionalIterator __last, _Compare __comp)
template<typename _Iterator , typename _Container >
constexpr _Iterator __niter_base (__gnu_cxx::__normal_iterator< _Iterator, _Container > __it) noexcept(/*conditional */)
template<typename _Iterator >
constexpr _Iterator __niter_base (_Iterator __it) noexcept(/*conditional */)
template<typename _Ite , typename _Seq >
_Ite __niter_base (const ::__gnu_debug::_Safe_iterator< _Ite, _Seq, std::random_access_iterator_tag > &)
template<typename _Iterator >
constexpr auto __niter_base (move_iterator< _Iterator > __it) -> decltype(make_move_iterator(__niter_base(__it.base())))
template<typename _Iterator >
constexpr auto __niter_base (reverse_iterator< _Iterator > __it) -> decltype(__make_reverse_iterator(__niter_base(__it.base())))
template<typename _From , typename _To >
constexpr _From __niter_wrap (_From __from, _To __res)
template<typename _Iterator >
constexpr _Iterator __niter_wrap (const _Iterator &, _Iterator __res)
void __once_proxy (void)
template<typename _CharT , typename _Traits >
void __ostream_fill (basic_ostream< _CharT, _Traits > &__out, streamsize __n)
template<typename _CharT , typename _Traits >
basic_ostream< _CharT, _Traits > & __ostream_insert (basic_ostream< _CharT, _Traits > &__out, const _CharT *__s, streamsize __n)
template<typename _CharT , typename _Traits >
void __ostream_write (basic_ostream< _CharT, _Traits > &__out, const _CharT *__s, streamsize __n)
template<typename _RandomAccessIterator , typename _Compare >
constexpr void __partial_sort (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last, _Compare __comp)
template<typename _InputIterator , typename _RandomAccessIterator , typename _Compare >
constexpr _RandomAccessIterator __partial_sort_copy (_InputIterator __first, _InputIterator __last, _RandomAccessIterator __result_first, _RandomAccessIterator __result_last, _Compare __comp)
template<typename _BidirectionalIterator , typename _Predicate >
constexpr _BidirectionalIterator __partition (_BidirectionalIterator __first, _BidirectionalIterator __last, _Predicate __pred, bidirectional_iterator_tag)
template<typename _ForwardIterator , typename _Predicate >
constexpr _ForwardIterator __partition (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, forward_iterator_tag)
template<typename _RandomAccessIterator , typename _Compare >
constexpr void __pop_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _RandomAccessIterator __result, _Compare &__comp)
template<typename _BidirectionalIterator , typename _Compare >
constexpr bool __prev_permutation (_BidirectionalIterator __first, _BidirectionalIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Distance , typename _Tp , typename _Compare >
constexpr void __push_heap (_RandomAccessIterator __first, _Distance __holeIndex, _Distance __topIndex, _Tp __value, _Compare &__comp)
template<typename _InputIterator , typename _OutputIterator , typename _Predicate >
constexpr _OutputIterator __remove_copy_if (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _Predicate __pred)
template<typename _ForwardIterator , typename _Predicate >
constexpr _ForwardIterator __remove_if (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred)
template<typename _InputIterator , typename _OutputIterator , typename _Predicate , typename _Tp >
constexpr _OutputIterator __replace_copy_if (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _Predicate __pred, const _Tp &__new_value)
template<typename _BidirectionalIterator >
constexpr void __reverse (_BidirectionalIterator __first, _BidirectionalIterator __last, bidirectional_iterator_tag)
template<typename _RandomAccessIterator >
constexpr void __reverse (_RandomAccessIterator __first, _RandomAccessIterator __last, random_access_iterator_tag)
template<typename _BidirectionalIterator >
constexpr _BidirectionalIterator __rotate (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, bidirectional_iterator_tag)
template<typename _ForwardIterator >
constexpr _ForwardIterator __rotate (_ForwardIterator __first, _ForwardIterator __middle, _ForwardIterator __last, forward_iterator_tag)
template<typename _RandomAccessIterator >
constexpr _RandomAccessIterator __rotate (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last, random_access_iterator_tag)
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 , typename _Distance >
_BidirectionalIterator1 __rotate_adaptive (_BidirectionalIterator1 __first, _BidirectionalIterator1 __middle, _BidirectionalIterator1 __last, _Distance __len1, _Distance __len2, _BidirectionalIterator2 __buffer, _Distance __buffer_size)
template<typename _ForwardIterator , typename _OutputIterator , typename _Cat , typename _Size , typename _UniformRandomBitGenerator >
_OutputIterator __sample (_ForwardIterator __first, _ForwardIterator __last, forward_iterator_tag, _OutputIterator __out, _Cat, _Size __n, _UniformRandomBitGenerator &&__g)
template<typename _InputIterator , typename _RandomAccessIterator , typename _Size , typename _UniformRandomBitGenerator >
_RandomAccessIterator __sample (_InputIterator __first, _InputIterator __last, input_iterator_tag, _RandomAccessIterator __out, random_access_iterator_tag, _Size __n, _UniformRandomBitGenerator &&__g)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate >
constexpr _ForwardIterator1 __search (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2, _BinaryPredicate __predicate)
template<typename _ForwardIterator , typename _Integer , typename _UnaryPredicate >
constexpr _ForwardIterator __search_n (_ForwardIterator __first, _ForwardIterator __last, _Integer __count, _UnaryPredicate __unary_pred)
template<typename _ForwardIterator , typename _Integer , typename _UnaryPredicate >
constexpr _ForwardIterator __search_n_aux (_ForwardIterator __first, _ForwardIterator __last, _Integer __count, _UnaryPredicate __unary_pred, std::forward_iterator_tag)
template<typename _RandomAccessIter , typename _Integer , typename _UnaryPredicate >
constexpr _RandomAccessIter __search_n_aux (_RandomAccessIter __first, _RandomAccessIter __last, _Integer __count, _UnaryPredicate __unary_pred, std::random_access_iterator_tag)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
constexpr _OutputIterator __set_difference (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
constexpr _OutputIterator __set_intersection (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
constexpr _OutputIterator __set_symmetric_difference (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
constexpr _OutputIterator __set_union (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
constexpr long long __size_to_integer (double __n)
constexpr long long __size_to_integer (float __n)
constexpr int __size_to_integer (int __n)
constexpr long __size_to_integer (long __n)
constexpr long long __size_to_integer (long double __n)
constexpr long long __size_to_integer (long long __n)
constexpr unsigned __size_to_integer (unsigned __n)
constexpr unsigned long __size_to_integer (unsigned long __n)
constexpr unsigned long long __size_to_integer (unsigned long long __n)
template<typename _RandomAccessIterator , typename _Compare >
constexpr void __sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Compare >
constexpr void __sort_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare &__comp)
template<typename _ForwardIterator , typename _Predicate >
_ForwardIterator __stable_partition (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred)
template<typename _ForwardIterator , typename _Pointer , typename _Predicate , typename _Distance >
_ForwardIterator __stable_partition_adaptive (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, _Distance __len, _Pointer __buffer, _Distance __buffer_size)
template<typename _RandomAccessIterator , typename _Compare >
void __stable_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Pointer , typename _Distance , typename _Compare >
void __stable_sort_adaptive (_RandomAccessIterator __first, _RandomAccessIterator __last, _Pointer __buffer, _Distance __buffer_size, _Compare __comp)
template<typename _CharT , typename _Traits , typename _Alloc , typename _State >
bool __str_codecvt_in (const char *__first, const char *__last, basic_string< _CharT, _Traits, _Alloc > &__outstr, const codecvt< _CharT, char, _State > &__cvt)
template<typename _CharT , typename _Traits , typename _Alloc , typename _State >
bool __str_codecvt_in (const char *__first, const char *__last, basic_string< _CharT, _Traits, _Alloc > &__outstr, const codecvt< _CharT, char, _State > &__cvt, _State &__state, size_t &__count)
template<typename _CharT , typename _Traits , typename _Alloc , typename _State >
bool __str_codecvt_in_all (const char *__first, const char *__last, basic_string< _CharT, _Traits, _Alloc > &__outstr, const codecvt< _CharT, char, _State > &__cvt)
template<typename _CharT , typename _Traits , typename _Alloc , typename _State >
bool __str_codecvt_out (const _CharT *__first, const _CharT *__last, basic_string< char, _Traits, _Alloc > &__outstr, const codecvt< _CharT, char, _State > &__cvt)
template<typename _CharT , typename _Traits , typename _Alloc , typename _State >
bool __str_codecvt_out (const _CharT *__first, const _CharT *__last, basic_string< char, _Traits, _Alloc > &__outstr, const codecvt< _CharT, char, _State > &__cvt, _State &__state, size_t &__count)
template<typename _CharT , typename _Traits , typename _Alloc , typename _State >
bool __str_codecvt_out_all (const _CharT *__first, const _CharT *__last, basic_string< char, _Traits, _Alloc > &__outstr, const codecvt< _CharT, char, _State > &__cvt)
constexpr size_t __sv_check (size_t __size, size_t __pos, const char *__s)
constexpr size_t __sv_limit (size_t __size, size_t __pos, size_t __off) noexcept
void __terminate () noexcept
void __throw_bad_alloc (void)
void __throw_bad_any_cast ()
void __throw_bad_array_new_length (void)
void __throw_bad_cast (void)
void __throw_bad_exception (void)
void __throw_bad_function_call ()
void __throw_bad_optional_access ()
void __throw_bad_typeid (void)
void __throw_bad_variant_access (bool __valueless)
void __throw_bad_variant_access (const char *__what)
void __throw_bad_weak_ptr ()
void __throw_domain_error (const char *)
void __throw_future_error (int)
void __throw_invalid_argument (const char *)
void __throw_ios_failure (const char *)
void __throw_ios_failure (const char *, int)
void __throw_length_error (const char *)
void __throw_logic_error (const char *)
void __throw_out_of_range (const char *)
void __throw_out_of_range_fmt (const char *,...)
void __throw_overflow_error (const char *)
void __throw_range_error (const char *)
void __throw_runtime_error (const char *)
void __throw_system_error (int)
void __throw_underflow_error (const char *)
template<typename _Tp >
constexpr _Tp * __to_address (_Tp *__ptr) noexcept
template<typename _Ptr >
constexpr auto __to_address (const _Ptr &__ptr) noexcept -> decltype(std::pointer_traits< _Ptr >::to_address(__ptr))
template<typename _Ptr , typename... _None>
constexpr auto __to_address (const _Ptr &__ptr, _None...) noexcept
template<bool _Move = false, typename _Tp , size_t... _Idx>
constexpr array< remove_cv_t< _Tp >, sizeof...(_Idx)> __to_array (_Tp(&__a)[sizeof...(_Idx)], index_sequence< _Idx... >)
template<typename _Tp >
__detail::__integer_to_chars_result_type< _Tp > __to_chars_i (char *__first, char *__last, _Tp __value, int __base=10)
template<typename _RandomAccessIterator , typename _Compare >
constexpr void __unguarded_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Compare >
constexpr void __unguarded_linear_insert (_RandomAccessIterator __last, _Compare __comp)
template<typename _RandomAccessIterator , typename _Compare >
constexpr _RandomAccessIterator __unguarded_partition (_RandomAccessIterator __first, _RandomAccessIterator __last, _RandomAccessIterator __pivot, _Compare __comp)
template<typename _RandomAccessIterator , typename _Compare >
constexpr _RandomAccessIterator __unguarded_partition_pivot (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _Pointer , typename _ForwardIterator >
void __uninitialized_construct_buf (_Pointer __first, _Pointer __last, _ForwardIterator __seed)
template<typename _ForwardIterator , typename _BinaryPredicate >
constexpr _ForwardIterator __unique (_ForwardIterator __first, _ForwardIterator __last, _BinaryPredicate __binary_pred)
template<typename _ForwardIterator , typename _OutputIterator , typename _BinaryPredicate >
constexpr _OutputIterator __unique_copy (_ForwardIterator __first, _ForwardIterator __last, _OutputIterator __result, _BinaryPredicate __binary_pred, forward_iterator_tag, output_iterator_tag)
template<typename _InputIterator , typename _ForwardIterator , typename _BinaryPredicate >
constexpr _ForwardIterator __unique_copy (_InputIterator __first, _InputIterator __last, _ForwardIterator __result, _BinaryPredicate __binary_pred, input_iterator_tag, forward_iterator_tag)
template<typename _InputIterator , typename _OutputIterator , typename _BinaryPredicate >
constexpr _OutputIterator __unique_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryPredicate __binary_pred, input_iterator_tag, output_iterator_tag)
template<typename _ForwardIterator , typename _Tp , typename _Compare >
constexpr _ForwardIterator __upper_bound (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _Compare __comp)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __a, _Array< bool > __m, size_t __n, _Array< _Tp > __b, _Array< bool > __k)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __a, size_t __n, size_t __s1, _Array< _Tp > __b, size_t __s2)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __e, _Array< size_t > __f, size_t __n, _Array< _Tp > __a, _Array< size_t > __i)
template<typename _Tp >
void __valarray_copy (_Array< _Tp > __src, size_t __n, _Array< size_t > __i, _Array< _Tp > __dst, _Array< size_t > __j)
template<typename _Tp , class _Dom >
void __valarray_copy (const _Expr< _Dom, _Tp > &__e, size_t __n, _Array< _Tp > __a)
template<typename _Tp , class _Dom >
void __valarray_copy (const _Expr< _Dom, _Tp > &__e, size_t __n, _Array< _Tp > __a, _Array< bool > __m)
template<typename _Tp , class _Dom >
void __valarray_copy (const _Expr< _Dom, _Tp > &__e, size_t __n, _Array< _Tp > __a, _Array< size_t > __i)
template<typename _Tp , class _Dom >
void __valarray_copy (const _Expr< _Dom, _Tp > &__e, size_t __n, _Array< _Tp > __a, size_t __s)
template<typename _Tp >
void __valarray_copy (const _Tp *__restrict__ __a, _Tp *__restrict__ __b, size_t __n, size_t __s)
template<typename _Tp >
void __valarray_copy (const _Tp *__restrict__ __a, const size_t *__restrict__ __i, _Tp *__restrict__ __b, size_t __n)
template<typename _Tp >
void __valarray_copy (const _Tp *__restrict__ __a, size_t __n, _Tp *__restrict__ __b)
template<typename _Tp >
void __valarray_copy (const _Tp *__restrict__ __a, size_t __n, _Tp *__restrict__ __b, const size_t *__restrict__ __i)
template<typename _Tp >
void __valarray_copy (const _Tp *__restrict__ __a, size_t __n, size_t __s, _Tp *__restrict__ __b)
template<typename _Tp >
void __valarray_copy (const _Tp *__restrict__ __src, size_t __n, const size_t *__restrict__ __i, _Tp *__restrict__ __dst, const size_t *__restrict__ __j)
template<typename _Tp >
void __valarray_copy (const _Tp *__restrict__ __src, size_t __n, size_t __s1, _Tp *__restrict__ __dst, size_t __s2)
template<typename _Tp >
void __valarray_copy_construct (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void __valarray_copy_construct (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp >
void __valarray_copy_construct (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp , class _Dom >
void __valarray_copy_construct (const _Expr< _Dom, _Tp > &__e, size_t __n, _Array< _Tp > __a)
template<typename _Tp >
void __valarray_copy_construct (const _Tp *__b, const _Tp *__e, _Tp *__restrict__ __o)
template<typename _Tp >
void __valarray_copy_construct (const _Tp *__restrict__ __a, const size_t *__restrict__ __i, _Tp *__restrict__ __o, size_t __n)
template<typename _Tp >
void __valarray_copy_construct (const _Tp *__restrict__ __a, size_t __n, size_t __s, _Tp *__restrict__ __o)
template<typename _Tp >
void __valarray_default_construct (_Tp *__b, _Tp *__e)
template<typename _Tp >
void __valarray_destroy_elements (_Tp *__b, _Tp *__e)
template<typename _Tp >
void __valarray_fill (_Array< _Tp > __a, _Array< size_t > __i, size_t __n, const _Tp &__t)
template<typename _Tp >
void __valarray_fill (_Array< _Tp > __a, size_t __n, _Array< bool > __m, const _Tp &__t)
template<typename _Tp >
void __valarray_fill (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void __valarray_fill (_Array< _Tp > __a, size_t __n, size_t __s, const _Tp &__t)
template<typename _Tp >
void __valarray_fill (_Tp *__restrict__ __a, const size_t *__restrict__ __i, size_t __n, const _Tp &__t)
template<typename _Tp >
void __valarray_fill (_Tp *__restrict__ __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void __valarray_fill (_Tp *__restrict__ __a, size_t __n, size_t __s, const _Tp &__t)
template<typename _Tp >
void __valarray_fill_construct (_Tp *__b, _Tp *__e, const _Tp __t)
template<typename _Tp >
_Tp * __valarray_get_storage (size_t)
template<typename _Ta >
_Ta::value_type __valarray_max (const _Ta &__a)
template<typename _Ta >
_Ta::value_type __valarray_min (const _Ta &__a)
void __valarray_release_memory (void *__p)
template<typename _Tp >
_Tp __valarray_sum (const _Tp *__f, const _Tp *__l)
template<template< typename > class _Trait, typename _Tp , typename _Up = _Tp>
constexpr _Up __value_or (_Up __def=_Up()) noexcept
template<typename... _Types, typename _Tp >
constexpr decltype(auto) __variant_cast (_Tp &&__rhs)
bool __verify_grouping (const char *__grouping, size_t __grouping_size, const string &__grouping_tmp) throw ()
template<typename _CharT , typename _OutIter >
_OutIter __write (_OutIter __s, const _CharT *__ws, int __len)
template<typename _CharT >
ostreambuf_iterator< _CharT > __write (ostreambuf_iterator< _CharT > __s, const _CharT *__ws, int __len)
template<typename _Tp >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_and (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_or (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp , class _Dom >
void _Array_augmented___bitwise_xor (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___divides (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp >
void _Array_augmented___divides (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___divides (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___divides (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___divides (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___divides (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___divides (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___divides (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void _Array_augmented___divides (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp >
void _Array_augmented___divides (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___divides (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp , class _Dom >
void _Array_augmented___divides (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___minus (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp >
void _Array_augmented___minus (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___minus (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___minus (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___minus (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___minus (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___minus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___minus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void _Array_augmented___minus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp >
void _Array_augmented___minus (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___minus (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp , class _Dom >
void _Array_augmented___minus (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___modulus (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp >
void _Array_augmented___modulus (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___modulus (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___modulus (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___modulus (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___modulus (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___modulus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___modulus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void _Array_augmented___modulus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp >
void _Array_augmented___modulus (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___modulus (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp , class _Dom >
void _Array_augmented___modulus (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___multiplies (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp >
void _Array_augmented___multiplies (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___multiplies (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___multiplies (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___multiplies (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___multiplies (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp >
void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp , class _Dom >
void _Array_augmented___multiplies (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___plus (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp >
void _Array_augmented___plus (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___plus (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___plus (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___plus (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___plus (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___plus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___plus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void _Array_augmented___plus (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp >
void _Array_augmented___plus (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___plus (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp , class _Dom >
void _Array_augmented___plus (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___shift_left (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp >
void _Array_augmented___shift_left (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___shift_left (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___shift_left (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___shift_left (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___shift_left (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp >
void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp , class _Dom >
void _Array_augmented___shift_left (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___shift_right (_Array< _Tp > __a, _Array< _Tp > __b, size_t __n, size_t __s)
template<typename _Tp >
void _Array_augmented___shift_right (_Array< _Tp > __a, _Array< bool > __m, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___shift_right (_Array< _Tp > __a, _Array< bool > __m, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___shift_right (_Array< _Tp > __a, _Array< size_t > __i, _Array< _Tp > __b, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___shift_right (_Array< _Tp > __a, _Array< size_t > __i, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , class _Dom >
void _Array_augmented___shift_right (_Array< _Tp > __a, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp >
void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b)
template<typename _Tp >
void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< bool > __m)
template<typename _Tp >
void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __n, _Array< _Tp > __b, _Array< size_t > __i)
template<typename _Tp >
void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __n, const _Tp &__t)
template<typename _Tp >
void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __n, size_t __s, _Array< _Tp > __b)
template<typename _Tp , class _Dom >
void _Array_augmented___shift_right (_Array< _Tp > __a, size_t __s, const _Expr< _Dom, _Tp > &__e, size_t __n)
template<typename _Tp , typename... _Args>
constexpr void _Construct (_Tp *__p, _Args &&... __args)
template<typename _T1 >
void _Construct_novalue (_T1 *__p)
template<typename _ForwardIterator >
constexpr void _Destroy (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Allocator >
constexpr void _Destroy (_ForwardIterator __first, _ForwardIterator __last, _Allocator &__alloc)
template<typename _ForwardIterator , typename _Tp >
constexpr void _Destroy (_ForwardIterator __first, _ForwardIterator __last, allocator< _Tp > &)
template<typename _Tp >
constexpr void _Destroy (_Tp *__pointer)
template<typename _ForwardIterator , typename _Size >
constexpr _ForwardIterator _Destroy_n (_ForwardIterator __first, _Size __count)
size_t _Fnv_hash_bytes (const void *__ptr, size_t __len, size_t __seed)
size_t _Hash_bytes (const void *__ptr, size_t __len, size_t __seed)
unsigned int _Rb_tree_black_count (const _Rb_tree_node_base *__node, const _Rb_tree_node_base *__root) throw ()
_Rb_tree_node_base * _Rb_tree_decrement (_Rb_tree_node_base *__x) throw ()
const _Rb_tree_node_base * _Rb_tree_decrement (const _Rb_tree_node_base *__x) throw ()
_Rb_tree_node_base * _Rb_tree_increment (_Rb_tree_node_base *__x) throw ()
const _Rb_tree_node_base * _Rb_tree_increment (const _Rb_tree_node_base *__x) throw ()
void _Rb_tree_insert_and_rebalance (const bool __insert_left, _Rb_tree_node_base *__x, _Rb_tree_node_base *__p, _Rb_tree_node_base &__header) throw ()
_Rb_tree_node_base * _Rb_tree_rebalance_for_erase (_Rb_tree_node_base *const __z, _Rb_tree_node_base &__header) throw ()
template<class _Dom >
_Expr< _UnClos< struct std::_Abs, _Expr, _Dom >, typename _Dom::value_type > abs (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
_Tp abs (const complex< _Tp > &)
template<typename _Tp >
_Expr< _UnClos< struct std::_Abs, _ValArray, _Tp >, _Tp > abs (const valarray< _Tp > &__v)
constexpr double abs (double __x)
constexpr float abs (float __x)
long abs (long __i)
constexpr long double abs (long double __x)
long long abs (long long __x)
template<typename _InputIterator , typename _Tp >
constexpr _Tp accumulate (_InputIterator __first, _InputIterator __last, _Tp __init)
template<typename _InputIterator , typename _Tp , typename _BinaryOperation >
constexpr _Tp accumulate (_InputIterator __first, _InputIterator __last, _Tp __init, _BinaryOperation __binary_op)
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type acos (_Tp __x)
template<class _Dom >
_Expr< _UnClos< struct std::_Acos, _Expr, _Dom >, typename _Dom::value_type > acos (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
std::complex< _Tp > acos (const std::complex< _Tp > &__z)
template<typename _Tp >
_Expr< _UnClos< struct std::_Acos, _ValArray, _Tp >, _Tp > acos (const valarray< _Tp > &__v)
constexpr float acos (float __x)
constexpr long double acos (long double __x)
template<typename _Tp >
std::complex< _Tp > acosh (const std::complex< _Tp > &__z)
template<typename _Tp >
constexpr _Tp * addressof (_Tp &__r) noexcept
template<typename _Tp >
const _Tp * addressof (const _Tp &&)=delete
template<typename _InputIterator , typename _OutputIterator >
constexpr _OutputIterator adjacent_difference (_InputIterator __first, _InputIterator __last, _OutputIterator __result)
template<typename _InputIterator , typename _OutputIterator , typename _BinaryOperation >
constexpr _OutputIterator adjacent_difference (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryOperation __binary_op)
template<typename _FIter >
constexpr _FIter adjacent_find (_FIter, _FIter)
template<typename _FIter , typename _BinaryPredicate >
constexpr _FIter adjacent_find (_FIter, _FIter, _BinaryPredicate)
template<typename _ForwardIterator >
constexpr _ForwardIterator adjacent_find (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _BinaryPredicate >
constexpr _ForwardIterator adjacent_find (_ForwardIterator __first, _ForwardIterator __last, _BinaryPredicate __binary_pred)
template<typename _InputIterator , typename _Distance >
constexpr void advance (_InputIterator &__i, _Distance __n)
template<typename _CharT , typename _Distance >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, void >::__type advance (istreambuf_iterator< _CharT > &__i, _Distance __n)
void * align (size_t __align, size_t __size, void *&__ptr, size_t &__space) noexcept
template<typename _IIter , typename _Predicate >
constexpr bool all_of (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate >
constexpr bool all_of (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _ValueType >
_ValueType any_cast (const any &__any)
template<typename _IIter , typename _Predicate >
constexpr bool any_of (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate >
constexpr bool any_of (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _Fn , typename _Tuple >
constexpr decltype(auto) apply (_Fn &&__f, _Tuple &&__t) noexcept(__unpack_std_tuple< is_nothrow_invocable, _Fn, _Tuple >)
template<typename _Tp >
__gnu_cxx::__promote< _Tp >::__type arg (_Tp __x)
template<typename _Tp >
_Tp arg (const complex< _Tp > &)
template<typename _Tp , typename... _Up>
array (_Tp, _Up...) -> array< enable_if_t<(is_same_v< _Tp, _Up > &&...), _Tp >, 1+sizeof...(_Up)>
template<typename _Type , size_t _Extent>
span< const byte, _Extent==dynamic_extent ? dynamic_extent :_Extent *sizeof(_Type)> as_bytes (span< _Type, _Extent > __sp) noexcept
template<typename _Tp >
constexpr add_const_t< _Tp > & as_const (_Tp &__t) noexcept
template<typename _Tp >
void as_const (const _Tp &&)=delete
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type asin (_Tp __x)
template<class _Dom >
_Expr< _UnClos< struct std::_Asin, _Expr, _Dom >, typename _Dom::value_type > asin (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
std::complex< _Tp > asin (const std::complex< _Tp > &__z)
template<typename _Tp >
_Expr< _UnClos< struct std::_Asin, _ValArray, _Tp >, _Tp > asin (const valarray< _Tp > &__v)
constexpr float asin (float __x)
constexpr long double asin (long double __x)
template<typename _Tp >
std::complex< _Tp > asinh (const std::complex< _Tp > &__z)
template<typename _Tp >
__gnu_cxx::__promote< _Tp >::__type assoc_laguerre (unsigned int __n, unsigned int __m, _Tp __x)
float assoc_laguerref (unsigned int __n, unsigned int __m, float __x)
long double assoc_laguerrel (unsigned int __n, unsigned int __m, long double __x)
template<typename _Tp >
__gnu_cxx::__promote< _Tp >::__type assoc_legendre (unsigned int __l, unsigned int __m, _Tp __x)
float assoc_legendref (unsigned int __l, unsigned int __m, float __x)
long double assoc_legendrel (unsigned int __l, unsigned int __m, long double __x)
template<size_t _Align, class _Tp >
constexpr _Tp * assume_aligned (_Tp *__ptr) noexcept
template<typename _Fn , typename... _Args>
future< __async_result_of< _Fn, _Args... > > async (_Fn &&__fn, _Args &&... __args)
template<typename _Fn , typename... _Args>
future< __async_result_of< _Fn, _Args... > > async (launch __policy, _Fn &&__fn, _Args &&... __args)
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type atan (_Tp __x)
template<class _Dom >
_Expr< _UnClos< struct std::_Atan, _Expr, _Dom >, typename _Dom::value_type > atan (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
std::complex< _Tp > atan (const std::complex< _Tp > &__z)
template<typename _Tp >
_Expr< _UnClos< struct std::_Atan, _ValArray, _Tp >, _Tp > atan (const valarray< _Tp > &__v)
constexpr float atan (float __x)
constexpr long double atan (long double __x)
template<typename _Tp , typename _Up >
constexpr __gnu_cxx::__promote_2< _Tp, _Up >::__type atan2 (_Tp __y, _Up __x)
template<class _Dom >
_Expr< _BinClos< struct std::_Atan2, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename _Dom::value_type > atan2 (const _Expr< _Dom, typename _Dom::value_type > &__e, const typename _Dom::value_type &__t)
template<class _Dom >
_Expr< _BinClos< struct std::_Atan2, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename _Dom::value_type > atan2 (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::_Atan2, _Expr, _Expr, _Dom1, _Dom2 >, typename _Dom1::value_type > atan2 (const _Expr< _Dom1, typename _Dom1::value_type > &__e1, const _Expr< _Dom2, typename _Dom2::value_type > &__e2)
template<class _Dom >
_Expr< _BinClos< struct std::_Atan2, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename _Dom::value_type > atan2 (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
_Expr< _BinClos< struct std::_Atan2, _Constant, _ValArray, _Tp, _Tp >, _Tp > atan2 (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< struct std::_Atan2, _ValArray, _Constant, _Tp, _Tp >, _Tp > atan2 (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< struct std::_Atan2, _ValArray, _ValArray, _Tp, _Tp >, _Tp > atan2 (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::_Atan2, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename _Dom::value_type > atan2 (const valarray< typename _Dom::valarray > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
constexpr float atan2 (float __y, float __x)
constexpr long double atan2 (long double __y, long double __x)
template<typename _Tp >
std::complex< _Tp > atanh (const std::complex< _Tp > &__z)
template<typename _ITp >
bool atomic_compare_exchange_strong (atomic< _ITp > *__a, __atomic_val_t< _ITp > *__i1, __atomic_val_t< _ITp > __i2) noexcept
template<typename _ITp >
bool atomic_compare_exchange_strong (volatile atomic< _ITp > *__a, __atomic_val_t< _ITp > *__i1, __atomic_val_t< _ITp > __i2) noexcept
template<typename _ITp >
bool atomic_compare_exchange_strong_explicit (atomic< _ITp > *__a, __atomic_val_t< _ITp > *__i1, __atomic_val_t< _ITp > __i2, memory_order __m1, memory_order __m2) noexcept
template<typename _ITp >
bool atomic_compare_exchange_strong_explicit (volatile atomic< _ITp > *__a, __atomic_val_t< _ITp > *__i1, __atomic_val_t< _ITp > __i2, memory_order __m1, memory_order __m2) noexcept
template<typename _ITp >
bool atomic_compare_exchange_weak (atomic< _ITp > *__a, __atomic_val_t< _ITp > *__i1, __atomic_val_t< _ITp > __i2) noexcept
template<typename _ITp >
bool atomic_compare_exchange_weak (volatile atomic< _ITp > *__a, __atomic_val_t< _ITp > *__i1, __atomic_val_t< _ITp > __i2) noexcept
template<typename _ITp >
bool atomic_compare_exchange_weak_explicit (atomic< _ITp > *__a, __atomic_val_t< _ITp > *__i1, __atomic_val_t< _ITp > __i2, memory_order __m1, memory_order __m2) noexcept
template<typename _ITp >
bool atomic_compare_exchange_weak_explicit (volatile atomic< _ITp > *__a, __atomic_val_t< _ITp > *__i1, __atomic_val_t< _ITp > __i2, memory_order __m1, memory_order __m2) noexcept
template<typename _ITp >
_ITp atomic_exchange (atomic< _ITp > *__a, __atomic_val_t< _ITp > __i) noexcept
template<typename _ITp >
_ITp atomic_exchange (volatile atomic< _ITp > *__a, __atomic_val_t< _ITp > __i) noexcept
template<typename _ITp >
_ITp atomic_exchange_explicit (atomic< _ITp > *__a, __atomic_val_t< _ITp > __i, memory_order __m) noexcept
template<typename _ITp >
_ITp atomic_exchange_explicit (volatile atomic< _ITp > *__a, __atomic_val_t< _ITp > __i, memory_order __m) noexcept
template<typename _ITp >
_ITp atomic_fetch_add (atomic< _ITp > *__a, __atomic_diff_t< _ITp > __i) noexcept
template<typename _ITp >
_ITp atomic_fetch_add (volatile atomic< _ITp > *__a, __atomic_diff_t< _ITp > __i) noexcept
template<typename _ITp >
_ITp atomic_fetch_add_explicit (atomic< _ITp > *__a, __atomic_diff_t< _ITp > __i, memory_order __m) noexcept
template<typename _ITp >
_ITp atomic_fetch_add_explicit (volatile atomic< _ITp > *__a, __atomic_diff_t< _ITp > __i, memory_order __m) noexcept
template<typename _ITp >
_ITp atomic_fetch_and (__atomic_base< _ITp > *__a, __atomic_val_t< _ITp > __i) noexcept
template<typename _ITp >
_ITp atomic_fetch_and (volatile __atomic_base< _ITp > *__a, __atomic_val_t< _ITp > __i) noexcept
template<typename _ITp >
_ITp atomic_fetch_and_explicit (__atomic_base< _ITp > *__a, __atomic_val_t< _ITp > __i, memory_order __m) noexcept
template<typename _ITp >
_ITp atomic_fetch_and_explicit (volatile __atomic_base< _ITp > *__a, __atomic_val_t< _ITp > __i, memory_order __m) noexcept
template<typename _ITp >
_ITp atomic_fetch_or (__atomic_base< _ITp > *__a, __atomic_val_t< _ITp > __i) noexcept
template<typename _ITp >
_ITp atomic_fetch_or (volatile __atomic_base< _ITp > *__a, __atomic_val_t< _ITp > __i) noexcept
template<typename _ITp >
_ITp atomic_fetch_or_explicit (__atomic_base< _ITp > *__a, __atomic_val_t< _ITp > __i, memory_order __m) noexcept
template<typename _ITp >
_ITp atomic_fetch_or_explicit (volatile __atomic_base< _ITp > *__a, __atomic_val_t< _ITp > __i, memory_order __m) noexcept
template<typename _ITp >
_ITp atomic_fetch_sub (atomic< _ITp > *__a, __atomic_diff_t< _ITp > __i) noexcept
template<typename _ITp >
_ITp atomic_fetch_sub (volatile atomic< _ITp > *__a, __atomic_diff_t< _ITp > __i) noexcept
template<typename _ITp >
_ITp atomic_fetch_sub_explicit (atomic< _ITp > *__a, __atomic_diff_t< _ITp > __i, memory_order __m) noexcept
template<typename _ITp >
_ITp atomic_fetch_sub_explicit (volatile atomic< _ITp > *__a, __atomic_diff_t< _ITp > __i, memory_order __m) noexcept
template<typename _ITp >
_ITp atomic_fetch_xor (__atomic_base< _ITp > *__a, __atomic_val_t< _ITp > __i) noexcept
template<typename _ITp >
_ITp atomic_fetch_xor (volatile __atomic_base< _ITp > *__a, __atomic_val_t< _ITp > __i) noexcept
template<typename _ITp >
_ITp atomic_fetch_xor_explicit (__atomic_base< _ITp > *__a, __atomic_val_t< _ITp > __i, memory_order __m) noexcept
template<typename _ITp >
_ITp atomic_fetch_xor_explicit (volatile __atomic_base< _ITp > *__a, __atomic_val_t< _ITp > __i, memory_order __m) noexcept
void atomic_flag_clear (atomic_flag *__a) noexcept
void atomic_flag_clear (volatile atomic_flag *__a) noexcept
void atomic_flag_clear_explicit (atomic_flag *__a, memory_order __m) noexcept
void atomic_flag_clear_explicit (volatile atomic_flag *__a, memory_order __m) noexcept
bool atomic_flag_test_and_set (atomic_flag *__a) noexcept
bool atomic_flag_test_and_set (volatile atomic_flag *__a) noexcept
bool atomic_flag_test_and_set_explicit (atomic_flag *__a, memory_order __m) noexcept
bool atomic_flag_test_and_set_explicit (volatile atomic_flag *__a, memory_order __m) noexcept
template<typename _ITp >
void atomic_init (atomic< _ITp > *__a, __atomic_val_t< _ITp > __i) noexcept
template<typename _ITp >
void atomic_init (volatile atomic< _ITp > *__a, __atomic_val_t< _ITp > __i) noexcept
template<typename _ITp >
bool atomic_is_lock_free (const atomic< _ITp > *__a) noexcept
template<typename _ITp >
bool atomic_is_lock_free (const volatile atomic< _ITp > *__a) noexcept
template<typename _ITp >
_ITp atomic_load (const atomic< _ITp > *__a) noexcept
template<typename _ITp >
_ITp atomic_load (const volatile atomic< _ITp > *__a) noexcept
template<typename _ITp >
_ITp atomic_load_explicit (const atomic< _ITp > *__a, memory_order __m) noexcept
template<typename _ITp >
_ITp atomic_load_explicit (const volatile atomic< _ITp > *__a, memory_order __m) noexcept
template<typename _Tp >
void atomic_notify_all (atomic< _Tp > *__a) noexcept
template<typename _Tp >
void atomic_notify_one (atomic< _Tp > *__a) noexcept
void atomic_signal_fence (memory_order __m) noexcept
template<typename _ITp >
void atomic_store (atomic< _ITp > *__a, __atomic_val_t< _ITp > __i) noexcept
template<typename _ITp >
void atomic_store (volatile atomic< _ITp > *__a, __atomic_val_t< _ITp > __i) noexcept
template<typename _ITp >
void atomic_store_explicit (atomic< _ITp > *__a, __atomic_val_t< _ITp > __i, memory_order __m) noexcept
template<typename _ITp >
void atomic_store_explicit (volatile atomic< _ITp > *__a, __atomic_val_t< _ITp > __i, memory_order __m) noexcept
void atomic_thread_fence (memory_order __m) noexcept
template<typename _Tp >
void atomic_wait (const atomic< _Tp > *__a, typename std::atomic< _Tp >::value_type __old) noexcept
template<typename _Tp >
void atomic_wait_explicit (const atomic< _Tp > *__a, typename std::atomic< _Tp >::value_type __old, std::memory_order __m) noexcept
template<typename _Container >
constexpr back_insert_iterator< _Container > back_inserter (_Container &__x)
template<typename _ForwardIterator >
basic_regex (_ForwardIterator, _ForwardIterator, regex_constants::syntax_option_type={}) -> basic_regex< typename iterator_traits< _ForwardIterator >::value_type >
template<typename _InputIterator , typename _CharT = typename iterator_traits<_InputIterator>::value_type, typename _Allocator = allocator<_CharT>, typename = _RequireInputIter<_InputIterator>, typename = _RequireAllocator<_Allocator>>
basic_string (_InputIterator, _InputIterator, _Allocator=_Allocator()) -> basic_string< _CharT, char_traits< _CharT >, _Allocator >
template<typename _CharT , typename _Traits , typename _Allocator = allocator<_CharT>, typename = _RequireAllocator<_Allocator>>
basic_string (basic_string_view< _CharT, _Traits >, const _Allocator &=_Allocator()) -> basic_string< _CharT, _Traits, _Allocator >
template<typename _CharT , typename _Traits , typename _Allocator = allocator<_CharT>, typename = _RequireAllocator<_Allocator>>
basic_string (basic_string_view< _CharT, _Traits >, typename basic_string< _CharT, _Traits, _Allocator >::size_type, typename basic_string< _CharT, _Traits, _Allocator >::size_type, const _Allocator &=_Allocator()) -> basic_string< _CharT, _Traits, _Allocator >
template<contiguous_iterator _It, sized_sentinel_for< _It > _End>
basic_string_view (_It, _End) -> basic_string_view< iter_value_t< _It >>
template<typename _Container >
constexpr auto begin (_Container &__cont) -> decltype(__cont.begin())
template<typename _Tp , size_t _Nm>
constexpr _Tp * begin (_Tp(&__arr)[_Nm]) noexcept
template<typename _Container >
constexpr auto begin (const _Container &__cont) -> decltype(__cont.begin())
template<class _Tp >
const _Tp * begin (const valarray< _Tp > &__va) noexcept
template<class _Tp >
_Tp * begin (valarray< _Tp > &__va) noexcept
template<typename _Tpa , typename _Tpb >
__gnu_cxx::__promote_2< _Tpa, _Tpb >::__type beta (_Tpa __a, _Tpb __b)
float betaf (float __a, float __b)
long double betal (long double __a, long double __b)
template<typename _FIter , typename _Tp >
constexpr bool binary_search (_FIter, _FIter, const _Tp &)
template<typename _FIter , typename _Tp , typename _Compare >
constexpr bool binary_search (_FIter, _FIter, const _Tp &, _Compare)
template<typename _ForwardIterator , typename _Tp >
constexpr bool binary_search (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val)
template<typename _ForwardIterator , typename _Tp , typename _Compare >
constexpr bool binary_search (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _Compare __comp)
template<typename _Func , typename... _BoundArgs>
constexpr _Bind_helper< __is_socketlike< _Func >::value, _Func, _BoundArgs... >::type bind (_Func &&__f, _BoundArgs &&... __args)
template<typename _Result , typename _Func , typename... _BoundArgs>
constexpr _Bindres_helper< _Result, _Func, _BoundArgs... >::type bind (_Func &&__f, _BoundArgs &&... __args)
template<typename _Operation , typename _Tp >
binder1st< _Operation > bind1st (const _Operation &__fn, const _Tp &__x)
template<typename _Operation , typename _Tp >
binder2nd< _Operation > bind2nd (const _Operation &__fn, const _Tp &__x)
template<typename _Fn , typename... _Args>
constexpr _Bind_front_t< _Fn, _Args... > bind_front (_Fn &&__fn, _Args &&... __args) noexcept(is_nothrow_constructible_v< _Bind_front_t< _Fn, _Args... >, int, _Fn, _Args... >)
template<typename _To , typename _From >
constexpr _To bit_cast (const _From &__from) noexcept requires(sizeof(_To)
template<typename _Tp >
constexpr _If_is_unsigned_integer< _Tp > bit_ceil (_Tp __x) noexcept
template<typename _Tp >
constexpr _If_is_unsigned_integer< _Tp > bit_floor (_Tp __x) noexcept
template<typename _Tp >
constexpr _If_is_unsigned_integer< _Tp > bit_width (_Tp __x) noexcept
ios_base & boolalpha (ios_base &__base)
template<typename _Callable , typename... _Args>
void call_once (once_flag &__once, _Callable &&__f, _Args &&... __args)
template<typename _Container >
constexpr auto cbegin (const _Container &__cont) noexcept(noexcept(std::begin(__cont))) -> decltype(std::begin(__cont))
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type ceil (_Tp __x)
constexpr float ceil (float __x)
constexpr long double ceil (long double __x)
template<typename _Container >
constexpr auto cend (const _Container &__cont) noexcept(noexcept(std::end(__cont))) -> decltype(std::end(__cont))
template<typename _Tp >
constexpr const _Tp & clamp (const _Tp &__val, const _Tp &__lo, const _Tp &__hi)
template<typename _Tp , typename _Compare >
constexpr const _Tp & clamp (const _Tp &__val, const _Tp &__lo, const _Tp &__hi, _Compare __comp)
template<typename _Tp , typename _Up >
constexpr bool cmp_equal (_Tp __t, _Up __u) noexcept
template<typename _Tp , typename _Up >
constexpr bool cmp_greater (_Tp __t, _Up __u) noexcept
template<typename _Tp , typename _Up >
constexpr bool cmp_greater_equal (_Tp __t, _Up __u) noexcept
template<typename _Tp , typename _Up >
constexpr bool cmp_less (_Tp __t, _Up __u) noexcept
template<typename _Tp , typename _Up >
constexpr bool cmp_less_equal (_Tp __t, _Up __u) noexcept
template<typename _Tp , typename _Up >
constexpr bool cmp_not_equal (_Tp __t, _Up __u) noexcept
template<typename _Tp >
__gnu_cxx::__promote< _Tp >::__type comp_ellint_1 (_Tp __k)
float comp_ellint_1f (float __k)
long double comp_ellint_1l (long double __k)
template<typename _Tp >
__gnu_cxx::__promote< _Tp >::__type comp_ellint_2 (_Tp __k)
float comp_ellint_2f (float __k)
long double comp_ellint_2l (long double __k)
template<typename _Tp , typename _Tpn >
__gnu_cxx::__promote_2< _Tp, _Tpn >::__type comp_ellint_3 (_Tp __k, _Tpn __nu)
float comp_ellint_3f (float __k, float __nu)
long double comp_ellint_3l (long double __k, long double __nu)
template<typename _Tp >
constexpr std::complex< typename __gnu_cxx::__promote< _Tp >::__type > conj (_Tp __x)
template<typename _Tp >
constexpr complex< _Tp > conj (const complex< _Tp > &)
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp>
__shared_ptr< _Tp, _Lp > const_pointer_cast (const __shared_ptr< _Tp1, _Lp > &__r) noexcept
template<typename _Tp , typename... _Args>
constexpr auto construct_at (_Tp *__location, _Args &&... __args) noexcept(noexcept(::new((void *) 0) _Tp(std::declval< _Args >()...))) -> decltype(::new((void *) 0) _Tp(std::declval< _Args >()...))
template<typename _II , typename _OI >
constexpr _OI copy (_II __first, _II __last, _OI __result)
template<typename _IIter , typename _OIter >
constexpr _OIter copy (_IIter, _IIter, _OIter)
template<typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, ostreambuf_iterator< _CharT > >::__type copy (istreambuf_iterator< _CharT > __first, istreambuf_iterator< _CharT > __last, ostreambuf_iterator< _CharT > __result)
template<typename _BI1 , typename _BI2 >
constexpr _BI2 copy_backward (_BI1 __first, _BI1 __last, _BI2 __result)
template<typename _BIter1 , typename _BIter2 >
constexpr _BIter2 copy_backward (_BIter1, _BIter1, _BIter2)
template<typename _IIter , typename _OIter , typename _Predicate >
constexpr _OIter copy_if (_IIter, _IIter, _OIter, _Predicate)
template<typename _InputIterator , typename _OutputIterator , typename _Predicate >
constexpr _OutputIterator copy_if (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _Predicate __pred)
template<typename _IIter , typename _Size , typename _OIter >
constexpr _OIter copy_n (_IIter, _Size, _OIter)
template<typename _InputIterator , typename _Size , typename _OutputIterator >
constexpr _OutputIterator copy_n (_InputIterator __first, _Size __n, _OutputIterator __result)
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type cos (_Tp __x)
template<class _Dom >
_Expr< _UnClos< struct std::_Cos, _Expr, _Dom >, typename _Dom::value_type > cos (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
complex< _Tp > cos (const complex< _Tp > &)
template<typename _Tp >
_Expr< _UnClos< struct std::_Cos, _ValArray, _Tp >, _Tp > cos (const valarray< _Tp > &__v)
constexpr float cos (float __x)
constexpr long double cos (long double __x)
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type cosh (_Tp __x)
template<class _Dom >
_Expr< _UnClos< struct std::_Cosh, _Expr, _Dom >, typename _Dom::value_type > cosh (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
complex< _Tp > cosh (const complex< _Tp > &)
template<typename _Tp >
_Expr< _UnClos< struct std::_Cosh, _ValArray, _Tp >, _Tp > cosh (const valarray< _Tp > &__v)
constexpr float cosh (float __x)
constexpr long double cosh (long double __x)
template<typename _IIter , typename _Tp >
constexpr iterator_traits< _IIter >::difference_type count (_IIter, _IIter, const _Tp &)
template<typename _InputIterator , typename _Tp >
constexpr iterator_traits< _InputIterator >::difference_type count (_InputIterator __first, _InputIterator __last, const _Tp &__value)
template<typename _IIter , typename _Predicate >
constexpr iterator_traits< _IIter >::difference_type count_if (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate >
constexpr iterator_traits< _InputIterator >::difference_type count_if (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _Tp >
constexpr _If_is_unsigned_integer< _Tp, int > countl_one (_Tp __x) noexcept
constexpr _To int countl_zero (_Tp __x) noexcept
template<typename _Tp >
constexpr _If_is_unsigned_integer< _Tp, int > countr_one (_Tp __x) noexcept
template<typename _Tp >
constexpr _If_is_unsigned_integer< _Tp, int > countr_zero (_Tp __x) noexcept
template<typename _Container >
constexpr auto crbegin (const _Container &__cont) -> decltype(std::rbegin(__cont))
template<typename _Container >
constexpr auto crend (const _Container &__cont) -> decltype(std::rend(__cont))
exception_ptr current_exception () noexcept
template<typename _Tpnu , typename _Tp >
__gnu_cxx::__promote_2< _Tpnu, _Tp >::__type cyl_bessel_i (_Tpnu __nu, _Tp __x)
float cyl_bessel_if (float __nu, float __x)
long double cyl_bessel_il (long double __nu, long double __x)
template<typename _Tpnu , typename _Tp >
__gnu_cxx::__promote_2< _Tpnu, _Tp >::__type cyl_bessel_j (_Tpnu __nu, _Tp __x)
float cyl_bessel_jf (float __nu, float __x)
long double cyl_bessel_jl (long double __nu, long double __x)
template<typename _Tpnu , typename _Tp >
__gnu_cxx::__promote_2< _Tpnu, _Tp >::__type cyl_bessel_k (_Tpnu __nu, _Tp __x)
float cyl_bessel_kf (float __nu, float __x)
long double cyl_bessel_kl (long double __nu, long double __x)
template<typename _Tpnu , typename _Tp >
__gnu_cxx::__promote_2< _Tpnu, _Tp >::__type cyl_neumann (_Tpnu __nu, _Tp __x)
float cyl_neumannf (float __nu, float __x)
long double cyl_neumannl (long double __nu, long double __x)
template<typename _Container >
constexpr auto data (_Container &__cont) noexcept(noexcept(__cont.data())) -> decltype(__cont.data())
template<typename _Tp , size_t _Nm>
constexpr _Tp * data (_Tp(&__array)[_Nm]) noexcept
template<typename _Container >
constexpr auto data (const _Container &__cont) noexcept(noexcept(__cont.data())) -> decltype(__cont.data())
template<typename _Tp >
constexpr const _Tp * data (initializer_list< _Tp > __il) noexcept
ios_base & dec (ios_base &__base)
void declare_no_pointers (char *, size_t)
void declare_reachable (void *)
template<typename _Tp >
auto declval () noexcept -> decltype(__declval< _Tp >(0))
ios_base & defaultfloat (ios_base &__base)
template<typename _InputIterator , typename _ValT = typename iterator_traits<_InputIterator>::value_type, typename _Allocator = allocator<_ValT>, typename = _RequireInputIter<_InputIterator>, typename = _RequireAllocator<_Allocator>>
deque (_InputIterator, _InputIterator, _Allocator=_Allocator()) -> deque< _ValT, _Allocator >
template<typename _ForwardIterator >
constexpr void destroy (_ForwardIterator __first, _ForwardIterator __last)
template<typename _Tp >
constexpr void destroy_at (_Tp *__location)
template<typename _ForwardIterator , typename _Size >
constexpr _ForwardIterator destroy_n (_ForwardIterator __first, _Size __count)
template<typename _InputIterator >
constexpr iterator_traits< _InputIterator >::difference_type distance (_InputIterator __first, _InputIterator __last)
ldiv_t div (long __i, long __j)
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp>
__shared_ptr< _Tp, _Lp > dynamic_pointer_cast (const __shared_ptr< _Tp1, _Lp > &__r) noexcept
template<typename _Tp , typename _Tpp >
__gnu_cxx::__promote_2< _Tp, _Tpp >::__type ellint_1 (_Tp __k, _Tpp __phi)
float ellint_1f (float __k, float __phi)
long double ellint_1l (long double __k, long double __phi)
template<typename _Tp , typename _Tpp >
__gnu_cxx::__promote_2< _Tp, _Tpp >::__type ellint_2 (_Tp __k, _Tpp __phi)
float ellint_2f (float __k, float __phi)
long double ellint_2l (long double __k, long double __phi)
template<typename _Tp , typename _Tpn , typename _Tpp >
__gnu_cxx::__promote_3< _Tp, _Tpn, _Tpp >::__type ellint_3 (_Tp __k, _Tpn __nu, _Tpp __phi)
float ellint_3f (float __k, float __nu, float __phi)
long double ellint_3l (long double __k, long double __nu, long double __phi)
template<typename _Container >
constexpr auto empty (const _Container &__cont) noexcept(noexcept(__cont.empty())) -> decltype(__cont.empty())
template<typename _Tp , size_t _Nm>
constexpr bool empty (const _Tp(&)[_Nm]) noexcept
template<typename _Tp >
constexpr bool empty (initializer_list< _Tp > __il) noexcept
template<typename _Container >
constexpr auto end (_Container &__cont) -> decltype(__cont.end())
template<typename _Tp , size_t _Nm>
constexpr _Tp * end (_Tp(&__arr)[_Nm]) noexcept
template<typename _Container >
constexpr auto end (const _Container &__cont) -> decltype(__cont.end())
template<class _Tp >
const _Tp * end (const valarray< _Tp > &__va) noexcept
template<class _Tp >
_Tp * end (valarray< _Tp > &__va) noexcept
template<typename _CharT , typename _Traits >
basic_ostream< _CharT, _Traits > & endl (basic_ostream< _CharT, _Traits > &__os)
template<typename _CharT , typename _Traits >
basic_ostream< _CharT, _Traits > & ends (basic_ostream< _CharT, _Traits > &__os)
template<typename _II1 , typename _II2 >
constexpr bool equal (_II1 __first1, _II1 __last1, _II2 __first2)
template<typename _II1 , typename _II2 >
constexpr bool equal (_II1 __first1, _II1 __last1, _II2 __first2, _II2 __last2)
template<typename _IIter1 , typename _IIter2 , typename _BinaryPredicate >
constexpr bool equal (_IIter1 __first1, _IIter1 __last1, _IIter2 __first2, _BinaryPredicate __binary_pred)
template<typename _IIter1 , typename _IIter2 , typename _BinaryPredicate >
constexpr bool equal (_IIter1 __first1, _IIter1 __last1, _IIter2 __first2, _IIter2 __last2, _BinaryPredicate __binary_pred)
template<typename _IIter1 , typename _IIter2 >
constexpr bool equal (_IIter1, _IIter1, _IIter2)
template<typename _FIter , typename _Tp >
constexpr pair< _FIter, _FIter > equal_range (_FIter, _FIter, const _Tp &)
template<typename _FIter , typename _Tp , typename _Compare >
constexpr pair< _FIter, _FIter > equal_range (_FIter, _FIter, const _Tp &, _Compare)
template<typename _ForwardIterator , typename _Tp >
constexpr pair< _ForwardIterator, _ForwardIterator > equal_range (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val)
template<typename _ForwardIterator , typename _Tp , typename _Compare >
constexpr pair< _ForwardIterator, _ForwardIterator > equal_range (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _Compare __comp)
template<typename _CharT , typename _Traits , typename _Alloc , typename _Up >
constexpr basic_string< _CharT, _Traits, _Alloc >::size_type erase (basic_string< _CharT, _Traits, _Alloc > &__cont, const _Up &__value)
template<typename _Tp , typename _Alloc , typename _Up >
deque< _Tp, _Alloc >::size_type erase (deque< _Tp, _Alloc > &__cont, const _Up &__value)
template<typename _Tp , typename _Alloc , typename _Up >
forward_list< _Tp, _Alloc >::size_type erase (forward_list< _Tp, _Alloc > &__cont, const _Up &__value)
template<typename _Tp , typename _Alloc , typename _Up >
list< _Tp, _Alloc >::size_type erase (list< _Tp, _Alloc > &__cont, const _Up &__value)
template<typename _Tp , typename _Alloc , typename _Up >
constexpr vector< _Tp, _Alloc >::size_type erase (vector< _Tp, _Alloc > &__cont, const _Up &__value)
template<typename _CharT , typename _Traits , typename _Alloc , typename _Predicate >
constexpr basic_string< _CharT, _Traits, _Alloc >::size_type erase_if (basic_string< _CharT, _Traits, _Alloc > &__cont, _Predicate __pred)
template<typename _Tp , typename _Alloc , typename _Predicate >
deque< _Tp, _Alloc >::size_type erase_if (deque< _Tp, _Alloc > &__cont, _Predicate __pred)
template<typename _Tp , typename _Alloc , typename _Predicate >
forward_list< _Tp, _Alloc >::size_type erase_if (forward_list< _Tp, _Alloc > &__cont, _Predicate __pred)
template<typename _Tp , typename _Alloc , typename _Predicate >
list< _Tp, _Alloc >::size_type erase_if (list< _Tp, _Alloc > &__cont, _Predicate __pred)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc , typename _Predicate >
map< _Key, _Tp, _Compare, _Alloc >::size_type erase_if (map< _Key, _Tp, _Compare, _Alloc > &__cont, _Predicate __pred)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc , typename _Predicate >
multimap< _Key, _Tp, _Compare, _Alloc >::size_type erase_if (multimap< _Key, _Tp, _Compare, _Alloc > &__cont, _Predicate __pred)
template<typename _Key , typename _Compare , typename _Alloc , typename _Predicate >
multiset< _Key, _Compare, _Alloc >::size_type erase_if (multiset< _Key, _Compare, _Alloc > &__cont, _Predicate __pred)
template<typename _Key , typename _Compare , typename _Alloc , typename _Predicate >
set< _Key, _Compare, _Alloc >::size_type erase_if (set< _Key, _Compare, _Alloc > &__cont, _Predicate __pred)
template<typename _Key , typename _Tp , typename _Hash , typename _CPred , typename _Alloc , typename _Predicate >
unordered_map< _Key, _Tp, _Hash, _CPred, _Alloc >::size_type erase_if (unordered_map< _Key, _Tp, _Hash, _CPred, _Alloc > &__cont, _Predicate __pred)
template<typename _Key , typename _Tp , typename _Hash , typename _CPred , typename _Alloc , typename _Predicate >
unordered_multimap< _Key, _Tp, _Hash, _CPred, _Alloc >::size_type erase_if (unordered_multimap< _Key, _Tp, _Hash, _CPred, _Alloc > &__cont, _Predicate __pred)
template<typename _Key , typename _Hash , typename _CPred , typename _Alloc , typename _Predicate >
unordered_multiset< _Key, _Hash, _CPred, _Alloc >::size_type erase_if (unordered_multiset< _Key, _Hash, _CPred, _Alloc > &__cont, _Predicate __pred)
template<typename _Key , typename _Hash , typename _CPred , typename _Alloc , typename _Predicate >
unordered_set< _Key, _Hash, _CPred, _Alloc >::size_type erase_if (unordered_set< _Key, _Hash, _CPred, _Alloc > &__cont, _Predicate __pred)
template<typename _Tp , typename _Alloc , typename _Predicate >
constexpr vector< _Tp, _Alloc >::size_type erase_if (vector< _Tp, _Alloc > &__cont, _Predicate __pred)
template<typename _Tp , typename _Up = _Tp>
constexpr _Tp exchange (_Tp &__obj, _Up &&__new_val) noexcept(__and_< is_nothrow_move_constructible< _Tp >, is_nothrow_assignable< _Tp &, _Up >>::value)
template<typename _InputIterator , typename _OutputIterator , typename _Tp >
constexpr _OutputIterator exclusive_scan (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _Tp __init)
template<typename _InputIterator , typename _OutputIterator , typename _Tp , typename _BinaryOperation >
constexpr _OutputIterator exclusive_scan (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _Tp __init, _BinaryOperation __binary_op)
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type exp (_Tp __x)
template<class _Dom >
_Expr< _UnClos< struct std::_Exp, _Expr, _Dom >, typename _Dom::value_type > exp (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
complex< _Tp > exp (const complex< _Tp > &)
template<typename _Tp >
_Expr< _UnClos< struct std::_Exp, _ValArray, _Tp >, _Tp > exp (const valarray< _Tp > &__v)
constexpr float exp (float __x)
constexpr long double exp (long double __x)
template<typename _Tp >
__gnu_cxx::__promote< _Tp >::__type expint (_Tp __x)
float expintf (float __x)
long double expintl (long double __x)
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type fabs (_Tp __x)
template<typename _Tp >
_Tp fabs (const std::complex< _Tp > &__z)
constexpr float fabs (float __x)
constexpr long double fabs (long double __x)
template<typename _FIter , typename _Tp >
constexpr void fill (_FIter, _FIter, const _Tp &)
template<typename _ForwardIterator , typename _Tp >
constexpr void fill (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value)
template<typename _OI , typename _Size , typename _Tp >
constexpr _OI fill_n (_OI __first, _Size __n, const _Tp &__value)
template<typename _OIter , typename _Size , typename _Tp >
constexpr _OIter fill_n (_OIter, _Size, const _Tp &)
template<typename _IIter , typename _Tp >
constexpr _IIter find (_IIter, _IIter, const _Tp &)
template<typename _InputIterator , typename _Tp >
constexpr _InputIterator find (_InputIterator __first, _InputIterator __last, const _Tp &__val)
template<typename _CharT >
__gnu_cxx::__enable_if< __is_char< _CharT >::__value, istreambuf_iterator< _CharT > >::__type find (istreambuf_iterator< _CharT > __first, istreambuf_iterator< _CharT > __last, const _CharT &__val)
template<typename _FIter1 , typename _FIter2 >
constexpr _FIter1 find_end (_FIter1, _FIter1, _FIter2, _FIter2)
template<typename _FIter1 , typename _FIter2 , typename _BinaryPredicate >
constexpr _FIter1 find_end (_FIter1, _FIter1, _FIter2, _FIter2, _BinaryPredicate)
template<typename _ForwardIterator1 , typename _ForwardIterator2 >
constexpr _ForwardIterator1 find_end (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate >
constexpr _ForwardIterator1 find_end (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2, _BinaryPredicate __comp)
template<typename _FIter1 , typename _FIter2 >
constexpr _FIter1 find_first_of (_FIter1, _FIter1, _FIter2, _FIter2)
template<typename _FIter1 , typename _FIter2 , typename _BinaryPredicate >
constexpr _FIter1 find_first_of (_FIter1, _FIter1, _FIter2, _FIter2, _BinaryPredicate)
template<typename _InputIterator , typename _ForwardIterator >
constexpr _InputIterator find_first_of (_InputIterator __first1, _InputIterator __last1, _ForwardIterator __first2, _ForwardIterator __last2)
template<typename _InputIterator , typename _ForwardIterator , typename _BinaryPredicate >
constexpr _InputIterator find_first_of (_InputIterator __first1, _InputIterator __last1, _ForwardIterator __first2, _ForwardIterator __last2, _BinaryPredicate __comp)
template<typename _IIter , typename _Predicate >
constexpr _IIter find_if (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate >
constexpr _InputIterator find_if (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _IIter , typename _Predicate >
constexpr _IIter find_if_not (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate >
constexpr _InputIterator find_if_not (_InputIterator __first, _InputIterator __last, _Predicate __pred)
ios_base & fixed (ios_base &__base)
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type floor (_Tp __x)
constexpr float floor (float __x)
constexpr long double floor (long double __x)
template<typename _CharT , typename _Traits >
basic_ostream< _CharT, _Traits > & flush (basic_ostream< _CharT, _Traits > &__os)
template<typename _Tp , typename _Up >
constexpr __gnu_cxx::__promote_2< _Tp, _Up >::__type fmod (_Tp __x, _Up __y)
constexpr float fmod (float __x, float __y)
constexpr long double fmod (long double __x, long double __y)
template<typename _IIter , typename _Funct >
constexpr _Funct for_each (_IIter, _IIter, _Funct)
template<typename _InputIterator , typename _Function >
constexpr _Function for_each (_InputIterator __first, _InputIterator __last, _Function __f)
template<typename _InputIterator , typename _Size , typename _Function >
constexpr _InputIterator for_each_n (_InputIterator __first, _Size __n, _Function __f)
template<typename _Tp >
constexpr _Tp && forward (typename std::remove_reference< _Tp >::type &&__t) noexcept
template<typename _Tp >
constexpr _Tp && forward (typename std::remove_reference< _Tp >::type &__t) noexcept
template<typename... _Elements>
constexpr tuple< _Elements &&... > forward_as_tuple (_Elements &&... __args) noexcept
template<typename _InputIterator , typename _ValT = typename iterator_traits<_InputIterator>::value_type, typename _Allocator = allocator<_ValT>, typename = _RequireInputIter<_InputIterator>, typename = _RequireAllocator<_Allocator>>
forward_list (_InputIterator, _InputIterator, _Allocator=_Allocator()) -> forward_list< _ValT, _Allocator >
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type frexp (_Tp __x, int *__exp)
float frexp (float __x, int *__exp)
long double frexp (long double __x, int *__exp)
template<typename _Tp >
__detail::__integer_from_chars_result_type< _Tp > from_chars (const char *__first, const char *__last, _Tp &__value, int __base=10)
template<typename _Container >
constexpr front_insert_iterator< _Container > front_inserter (_Container &__x)
template<typename _Functor , typename _Signature = typename __function_guide_helper<decltype(&_Functor::operator())>::type>
function (_Functor) -> function< _Signature >
template<typename _Res , typename... _ArgTypes>
function (_Res(*)(_ArgTypes...)) -> function< _Res(_ArgTypes...)>
const error_category & future_category () noexcept
template<typename _Mn , typename _Nn >
constexpr common_type_t< _Mn, _Nn > gcd (_Mn __m, _Nn __n) noexcept
template<typename _FIter , typename _Generator >
constexpr void generate (_FIter, _FIter, _Generator)
template<typename _ForwardIterator , typename _Generator >
constexpr void generate (_ForwardIterator __first, _ForwardIterator __last, _Generator __gen)
template<typename _RealType , size_t __bits, typename _UniformRandomNumberGenerator >
_RealType generate_canonical (_UniformRandomNumberGenerator &__g)
template<typename _OIter , typename _Size , typename _Generator >
constexpr _OIter generate_n (_OIter, _Size, _Generator)
template<typename _OutputIterator , typename _Size , typename _Generator >
constexpr _OutputIterator generate_n (_OutputIterator __first, _Size __n, _Generator __gen)
const error_category & generic_category () noexcept
template<std::size_t _Int, typename _Tp , std::size_t _Nm>
constexpr _Tp && get (array< _Tp, _Nm > &&__arr) noexcept
template<std::size_t _Int, typename _Tp , std::size_t _Nm>
constexpr _Tp & get (array< _Tp, _Nm > &__arr) noexcept
template<std::size_t _Int, typename _Tp , std::size_t _Nm>
constexpr const _Tp && get (const array< _Tp, _Nm > &&__arr) noexcept
template<std::size_t _Int, typename _Tp , std::size_t _Nm>
constexpr const _Tp & get (const array< _Tp, _Nm > &__arr) noexcept
template<size_t __i, typename... _Elements>
constexpr const __tuple_element_t< __i, tuple< _Elements... > > && get (const tuple< _Elements... > &&__t) noexcept
template<size_t __i, typename... _Elements>
constexpr const __tuple_element_t< __i, tuple< _Elements... > > & get (const tuple< _Elements... > &__t) noexcept
template<typename _Tp , typename... _Types>
constexpr const _Tp && get (const tuple< _Types... > &&__t) noexcept
template<typename _Tp , typename... _Types>
constexpr const _Tp & get (const tuple< _Types... > &__t) noexcept
template<size_t _Np, typename... _Types>
constexpr variant_alternative_t< _Np, variant< _Types... > > const && get (const variant< _Types... > &&)
template<typename _Tp , typename... _Types>
constexpr const _Tp && get (const variant< _Types... > &&__v)
template<size_t _Np, typename... _Types>
constexpr const variant_alternative_t< _Np, variant< _Types... > > && get (const variant< _Types... > &&__v)
template<size_t _Np, typename... _Types>
constexpr variant_alternative_t< _Np, variant< _Types... > > const & get (const variant< _Types... > &)
template<typename _Tp , typename... _Types>
constexpr const _Tp & get (const variant< _Types... > &__v)
template<size_t _Np, typename... _Types>
constexpr const variant_alternative_t< _Np, variant< _Types... > > & get (const variant< _Types... > &__v)
template<size_t __i, typename... _Elements>
constexpr __tuple_element_t< __i, tuple< _Elements... > > && get (tuple< _Elements... > &&__t) noexcept
template<size_t __i, typename... _Elements>
constexpr __tuple_element_t< __i, tuple< _Elements... > > & get (tuple< _Elements... > &__t) noexcept
template<typename _Tp , typename... _Types>
constexpr _Tp && get (tuple< _Types... > &&__t) noexcept
template<typename _Tp , typename... _Types>
constexpr _Tp & get (tuple< _Types... > &__t) noexcept
template<size_t _Np, typename... _Types>
constexpr variant_alternative_t< _Np, variant< _Types... > > && get (variant< _Types... > &&)
template<typename _Tp , typename... _Types>
constexpr _Tp && get (variant< _Types... > &&__v)
template<size_t _Np, typename... _Types>
constexpr variant_alternative_t< _Np, variant< _Types... > > & get (variant< _Types... > &)
template<typename _Tp , typename... _Types>
constexpr _Tp & get (variant< _Types... > &__v)
Catalogs & get_catalogs ()
template<typename _Del , typename _Tp , _Lock_policy _Lp>
_Del * get_deleter (const __shared_ptr< _Tp, _Lp > &__p) noexcept
template<size_t _Np, typename... _Types>
constexpr add_pointer_t< const variant_alternative_t< _Np, variant< _Types... > > > get_if (const variant< _Types... > *__ptr) noexcept
template<typename _Tp , typename... _Types>
constexpr add_pointer_t< const _Tp > get_if (const variant< _Types... > *__ptr) noexcept
template<size_t _Np, typename... _Types>
constexpr add_pointer_t< variant_alternative_t< _Np, variant< _Types... > > > get_if (variant< _Types... > *__ptr) noexcept
template<typename _Tp , typename... _Types>
constexpr add_pointer_t< _Tp > get_if (variant< _Types... > *__ptr) noexcept
template<typename _MoneyT >
_Get_money< _MoneyT > get_money (_MoneyT &__mon, bool __intl=false)
new_handler get_new_handler () noexcept
pointer_safety get_pointer_safety () noexcept
template<typename _Tp >
pair< _Tp *, ptrdiff_t > get_temporary_buffer (ptrdiff_t __len) noexcept
terminate_handler get_terminate () noexcept
template<typename _CharT >
_Get_time< _CharT > get_time (std::tm *__tmb, const _CharT *__fmt)
unexpected_handler get_unexpected () noexcept
template<typename _CharT , typename _Traits , typename _Alloc >
basic_istream< _CharT, _Traits > & getline (basic_istream< _CharT, _Traits > &&__is, basic_string< _CharT, _Traits, _Alloc > &__str)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_istream< _CharT, _Traits > & getline (basic_istream< _CharT, _Traits > &&__is, basic_string< _CharT, _Traits, _Alloc > &__str, _CharT __delim)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
basic_istream< _CharT, _Traits > & getline (basic_istream< _CharT, _Traits > &__is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > &__str)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
basic_istream< _CharT, _Traits > & getline (basic_istream< _CharT, _Traits > &__is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > &__str, _CharT __delim)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_istream< _CharT, _Traits > & getline (basic_istream< _CharT, _Traits > &__is, basic_string< _CharT, _Traits, _Alloc > &__str)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_istream< _CharT, _Traits > & getline (basic_istream< _CharT, _Traits > &__is, basic_string< _CharT, _Traits, _Alloc > &__str, _CharT __delim)
template<>
basic_istream< char > & getline (basic_istream< char > &__in, basic_string< char > &__str, char __delim)
template<>
basic_istream< wchar_t > & getline (basic_istream< wchar_t > &__in, basic_string< wchar_t > &__str, wchar_t __delim)
template<typename _Facet >
bool has_facet (const locale &__loc) throw ()
template<typename _Tp >
constexpr _If_is_unsigned_integer< _Tp, bool > has_single_bit (_Tp __x) noexcept
template<typename _Tp >
__gnu_cxx::__promote< _Tp >::__type hermite (unsigned int __n, _Tp __x)
float hermitef (unsigned int __n, float __x)
long double hermitel (unsigned int __n, long double __x)
ios_base & hex (ios_base &__base)
ios_base & hexfloat (ios_base &__base)
template<typename _Tp , typename... _Types>
constexpr bool holds_alternative (const variant< _Types... > &__v) noexcept
template<typename _Tp , typename _Up , typename _Vp >
__gnu_cxx::__promoted_t< _Tp, _Up, _Vp > hypot (_Tp __x, _Up __y, _Vp __z)
double hypot (double __x, double __y, double __z)
float hypot (float __x, float __y, float __z)
long double hypot (long double __x, long double __y, long double __z)
template<typename _Tp >
constexpr __gnu_cxx::__promote< _Tp >::__type imag (_Tp)
template<typename _Tp >
constexpr _Tp imag (const complex< _Tp > &__z)
template<typename _Up , typename _Tp >
constexpr bool in_range (_Tp __t) noexcept
template<typename _IIter1 , typename _IIter2 >
constexpr bool includes (_IIter1, _IIter1, _IIter2, _IIter2)
template<typename _IIter1 , typename _IIter2 , typename _Compare >
constexpr bool includes (_IIter1, _IIter1, _IIter2, _IIter2, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 >
constexpr bool includes (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2)
template<typename _InputIterator1 , typename _InputIterator2 , typename _Compare >
constexpr bool includes (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _Compare __comp)
template<typename _InputIterator , typename _OutputIterator >
constexpr _OutputIterator inclusive_scan (_InputIterator __first, _InputIterator __last, _OutputIterator __result)
template<typename _InputIterator , typename _OutputIterator , typename _BinaryOperation >
constexpr _OutputIterator inclusive_scan (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryOperation __binary_op)
template<typename _InputIterator , typename _OutputIterator , typename _BinaryOperation , typename _Tp >
constexpr _OutputIterator inclusive_scan (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryOperation __binary_op, _Tp __init)
template<typename _InputIterator1 , typename _InputIterator2 , typename _Tp >
constexpr _Tp inner_product (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _Tp __init)
template<typename _InputIterator1 , typename _InputIterator2 , typename _Tp , typename _BinaryOperation1 , typename _BinaryOperation2 >
constexpr _Tp inner_product (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _Tp __init, _BinaryOperation1 __binary_op1, _BinaryOperation2 __binary_op2)
template<typename _BidirectionalIterator >
void inplace_merge (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last)
template<typename _BidirectionalIterator , typename _Compare >
void inplace_merge (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Compare __comp)
template<typename _BIter >
void inplace_merge (_BIter, _BIter, _BIter)
template<typename _BIter , typename _Compare >
void inplace_merge (_BIter, _BIter, _BIter, _Compare)
template<typename _Container >
constexpr insert_iterator< _Container > inserter (_Container &__x, std::__detail::__range_iter_t< _Container > __i)
ios_base & internal (ios_base &__base)
template<typename _Callable , typename... _Args>
constexpr invoke_result_t< _Callable, _Args... > invoke (_Callable &&__fn, _Args &&... __args) noexcept(is_nothrow_invocable_v< _Callable, _Args... >)
const error_category & iostream_category () noexcept
template<typename _ForwardIterator , typename _Tp >
constexpr void iota (_ForwardIterator __first, _ForwardIterator __last, _Tp __value)
constexpr bool is_constant_evaluated () noexcept
template<typename _S1 , typename _S2 , typename _M1 , typename _M2 >
constexpr bool is_corresponding_member (_M1 _S1::*__m1, _M2 _S2::*__m2) noexcept
constexpr bool is_eq (partial_ordering __cmp) noexcept
constexpr bool is_gt (partial_ordering __cmp) noexcept
constexpr bool is_gteq (partial_ordering __cmp) noexcept
template<typename _RAIter >
constexpr bool is_heap (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
constexpr bool is_heap (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator >
constexpr bool is_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
constexpr bool is_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RAIter >
constexpr _RAIter is_heap_until (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
constexpr _RAIter is_heap_until (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator >
constexpr _RandomAccessIterator is_heap_until (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
constexpr _RandomAccessIterator is_heap_until (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
constexpr bool is_lt (partial_ordering __cmp) noexcept
constexpr bool is_lteq (partial_ordering __cmp) noexcept
constexpr bool is_neq (partial_ordering __cmp) noexcept
template<typename _IIter , typename _Predicate >
constexpr bool is_partitioned (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate >
constexpr bool is_partitioned (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _FIter1 , typename _FIter2 >
constexpr bool is_permutation (_FIter1, _FIter1, _FIter2)
template<typename _FIter1 , typename _FIter2 , typename _BinaryPredicate >
constexpr bool is_permutation (_FIter1, _FIter1, _FIter2, _BinaryPredicate)
template<typename _ForwardIterator1 , typename _ForwardIterator2 >
constexpr bool is_permutation (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate >
constexpr bool is_permutation (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _BinaryPredicate __pred)
template<typename _ForwardIterator1 , typename _ForwardIterator2 >
constexpr bool is_permutation (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate >
constexpr bool is_permutation (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2, _BinaryPredicate __pred)
template<typename _Tp , typename _Mem >
constexpr bool is_pointer_interconvertible_with_class (_Mem _Tp::*__mp) noexcept
template<typename _FIter >
constexpr bool is_sorted (_FIter, _FIter)
template<typename _FIter , typename _Compare >
constexpr bool is_sorted (_FIter, _FIter, _Compare)
template<typename _ForwardIterator >
constexpr bool is_sorted (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Compare >
constexpr bool is_sorted (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _FIter >
constexpr _FIter is_sorted_until (_FIter, _FIter)
template<typename _FIter , typename _Compare >
constexpr _FIter is_sorted_until (_FIter, _FIter, _Compare)
template<typename _ForwardIterator >
constexpr _ForwardIterator is_sorted_until (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Compare >
constexpr _ForwardIterator is_sorted_until (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _CharT >
bool isalnum (_CharT __c, const locale &__loc)
template<typename _CharT >
bool isalpha (_CharT __c, const locale &__loc)
template<typename _CharT >
bool isblank (_CharT __c, const locale &__loc)
template<typename _CharT >
bool iscntrl (_CharT __c, const locale &__loc)
template<typename _CharT >
bool isdigit (_CharT __c, const locale &__loc)
template<typename _CharT >
bool isgraph (_CharT __c, const locale &__loc)
template<typename _CharT >
bool islower (_CharT __c, const locale &__loc)
template<typename _CharT >
bool isprint (_CharT __c, const locale &__loc)
template<typename _CharT >
bool ispunct (_CharT __c, const locale &__loc)
template<typename _CharT >
bool isspace (_CharT __c, const locale &__loc)
template<typename _CharT >
bool isupper (_CharT __c, const locale &__loc)
template<typename _CharT >
bool isxdigit (_CharT __c, const locale &__loc)
template<typename _FIter1 , typename _FIter2 >
constexpr void iter_swap (_FIter1, _FIter2)
template<typename _ForwardIterator1 , typename _ForwardIterator2 >
constexpr void iter_swap (_ForwardIterator1 __a, _ForwardIterator2 __b)
template<typename _Tp >
_Tp kill_dependency (_Tp __y) noexcept
template<typename _Tp >
__gnu_cxx::__promote< _Tp >::__type laguerre (unsigned int __n, _Tp __x)
float laguerref (unsigned int __n, float __x)
long double laguerrel (unsigned int __n, long double __x)
template<typename _Ret , typename... _Args>
void launder (_Ret(*)(_Args...))=delete
template<typename _Ret , typename... _Args>
void launder (_Ret(*)(_Args......))=delete
template<typename _Tp >
constexpr _Tp * launder (_Tp *__p) noexcept
void launder (const void *)=delete
void launder (const volatile void *)=delete
void launder (void *)=delete
void launder (volatile void *)=delete
template<typename _Mn , typename _Nn >
constexpr common_type_t< _Mn, _Nn > lcm (_Mn __m, _Nn __n) noexcept
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type ldexp (_Tp __x, int __exp)
constexpr float ldexp (float __x, int __exp)
constexpr long double ldexp (long double __x, int __exp)
ios_base & left (ios_base &__base)
template<typename _Tp >
__gnu_cxx::__promote< _Tp >::__type legendre (unsigned int __l, _Tp __x)
float legendref (unsigned int __l, float __x)
long double legendrel (unsigned int __l, long double __x)
template<typename _Tp , typename _Up , typename _Vp >
constexpr __gnu_cxx::__promoted_t< _Tp, _Up, _Vp > lerp (_Tp __x, _Up __y, _Vp __z) noexcept
constexpr double lerp (double __a, double __b, double __t) noexcept
constexpr float lerp (float __a, float __b, float __t) noexcept
constexpr long double lerp (long double __a, long double __b, long double __t) noexcept
template<typename _II1 , typename _II2 >
constexpr bool lexicographical_compare (_II1 __first1, _II1 __last1, _II2 __first2, _II2 __last2)
template<typename _II1 , typename _II2 , typename _Compare >
constexpr bool lexicographical_compare (_II1 __first1, _II1 __last1, _II2 __first2, _II2 __last2, _Compare __comp)
template<typename _IIter1 , typename _IIter2 >
constexpr bool lexicographical_compare (_IIter1, _IIter1, _IIter2, _IIter2)
template<typename _IIter1 , typename _IIter2 , typename _Compare >
constexpr bool lexicographical_compare (_IIter1, _IIter1, _IIter2, _IIter2, _Compare)
template<typename _InputIterator , typename _ValT = typename iterator_traits<_InputIterator>::value_type, typename _Allocator = allocator<_ValT>, typename = _RequireInputIter<_InputIterator>, typename = _RequireAllocator<_Allocator>>
list (_InputIterator, _InputIterator, _Allocator=_Allocator()) -> list< _ValT, _Allocator >
template<typename _L1 , typename _L2 , typename... _L3>
void lock (_L1 &__l1, _L2 &__l2, _L3 &... __l3)
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type log (_Tp __x)
template<class _Dom >
_Expr< _UnClos< struct std::_Log, _Expr, _Dom >, typename _Dom::value_type > log (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
complex< _Tp > log (const complex< _Tp > &)
template<typename _Tp >
_Expr< _UnClos< struct std::_Log, _ValArray, _Tp >, _Tp > log (const valarray< _Tp > &__v)
constexpr float log (float __x)
constexpr long double log (long double __x)
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type log10 (_Tp __x)
template<class _Dom >
_Expr< _UnClos< struct std::_Log10, _Expr, _Dom >, typename _Dom::value_type > log10 (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
complex< _Tp > log10 (const complex< _Tp > &)
template<typename _Tp >
_Expr< _UnClos< struct std::_Log10, _ValArray, _Tp >, _Tp > log10 (const valarray< _Tp > &__v)
constexpr float log10 (float __x)
constexpr long double log10 (long double __x)
template<typename _FIter , typename _Tp >
constexpr _FIter lower_bound (_FIter, _FIter, const _Tp &)
template<typename _FIter , typename _Tp , typename _Compare >
constexpr _FIter lower_bound (_FIter, _FIter, const _Tp &, _Compare)
template<typename _ForwardIterator , typename _Tp >
constexpr _ForwardIterator lower_bound (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val)
template<typename _ForwardIterator , typename _Tp , typename _Compare >
constexpr _ForwardIterator lower_bound (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _Compare __comp)
template<typename _Tp , typename... _Args>
enable_if_t< is_constructible_v< any, in_place_type_t< _Tp >, _Args... >, any > make_any (_Args &&... __args)
template<typename _Tp , typename _Up , typename... _Args>
enable_if_t< is_constructible_v< any, in_place_type_t< _Tp >, initializer_list< _Up > &, _Args... >, any > make_any (initializer_list< _Up > __il, _Args &&... __args)
error_code make_error_code (future_errc __errc) noexcept
error_code make_error_code (io_errc __e) noexcept
error_condition make_error_condition (future_errc __errc) noexcept
error_condition make_error_condition (io_errc __e) noexcept
template<typename _Ex >
exception_ptr make_exception_ptr (_Ex __ex) noexcept
template<typename _Tp , typename _Tuple >
constexpr _Tp make_from_tuple (_Tuple &&__t) noexcept(__unpack_std_tuple< is_nothrow_constructible, _Tp, _Tuple >)
template<typename _RAIter >
constexpr void make_heap (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
constexpr void make_heap (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator >
constexpr void make_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
constexpr void make_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _Iterator >
constexpr move_iterator< _Iterator > make_move_iterator (_Iterator __i)
template<typename _Tp , typename _Alloc , typename... _Args>
constexpr _Tp make_obj_using_allocator (const _Alloc &__a, _Args &&... __args)
template<typename _Tp , typename... _Args>
constexpr enable_if_t< is_constructible_v< _Tp, _Args... >, optional< _Tp > > make_optional (_Args &&... __args) noexcept(is_nothrow_constructible_v< _Tp, _Args... >)
template<typename _Tp >
constexpr enable_if_t< is_constructible_v< decay_t< _Tp >, _Tp >, optional< decay_t< _Tp > > > make_optional (_Tp &&__t) noexcept(is_nothrow_constructible_v< optional< decay_t< _Tp >>, _Tp >)
template<typename _Tp , typename _Up , typename... _Args>
constexpr enable_if_t< is_constructible_v< _Tp, initializer_list< _Up > &, _Args... >, optional< _Tp > > make_optional (initializer_list< _Up > __il, _Args &&... __args) noexcept(is_nothrow_constructible_v< _Tp, initializer_list< _Up > &, _Args... >)
template<typename _Iterator >
constexpr reverse_iterator< _Iterator > make_reverse_iterator (_Iterator __i)
template<typename... _Elements>
constexpr tuple< typename __decay_and_strip< _Elements >::__type... > make_tuple (_Elements &&... __args)
template<typename _InputIterator , typename _Allocator , typename = _RequireInputIter<_InputIterator>, typename = _RequireAllocator<_Allocator>>
map (_InputIterator, _InputIterator, _Allocator) -> map< __iter_key_t< _InputIterator >, __iter_val_t< _InputIterator >, less< __iter_key_t< _InputIterator >>, _Allocator >
template<typename _InputIterator , typename _Compare = less<__iter_key_t<_InputIterator>>, typename _Allocator = allocator<__iter_to_alloc_t<_InputIterator>>, typename = _RequireInputIter<_InputIterator>, typename = _RequireNotAllocator<_Compare>, typename = _RequireAllocator<_Allocator>>
map (_InputIterator, _InputIterator, _Compare=_Compare(), _Allocator=_Allocator()) -> map< __iter_key_t< _InputIterator >, __iter_val_t< _InputIterator >, _Compare, _Allocator >
template<typename _Key , typename _Tp , typename _Allocator , typename = _RequireAllocator<_Allocator>>
map (initializer_list< pair< _Key, _Tp >>, _Allocator) -> map< _Key, _Tp, less< _Key >, _Allocator >
template<typename _Key , typename _Tp , typename _Compare = less<_Key>, typename _Allocator = allocator<pair<const _Key, _Tp>>, typename = _RequireNotAllocator<_Compare>, typename = _RequireAllocator<_Allocator>>
map (initializer_list< pair< _Key, _Tp >>, _Compare=_Compare(), _Allocator=_Allocator()) -> map< _Key, _Tp, _Compare, _Allocator >
template<typename _Tp >
constexpr const _Tp & max (const _Tp &__a, const _Tp &__b)
template<typename _Tp , typename _Compare >
constexpr const _Tp & max (const _Tp &__a, const _Tp &__b, _Compare __comp)
template<typename _Tp >
constexpr _Tp max (initializer_list< _Tp >)
template<typename _Tp , typename _Compare >
constexpr _Tp max (initializer_list< _Tp >, _Compare)
template<typename _FIter >
constexpr _FIter max_element (_FIter, _FIter)
template<typename _FIter , typename _Compare >
constexpr _FIter max_element (_FIter, _FIter, _Compare)
template<typename _ForwardIterator >
constexpr _ForwardIterator max_element (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Compare >
constexpr _ForwardIterator max_element (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _Tp , typename _Class >
constexpr _Mem_fn< _Tp _Class::* > mem_fn (_Tp _Class::*__pm) noexcept
template<typename _Ret , typename _Tp >
const_mem_fun_t< _Ret, _Tp > mem_fun (_Ret(_Tp::*__f)() const)
template<typename _Ret , typename _Tp >
mem_fun_t< _Ret, _Tp > mem_fun (_Ret(_Tp::*__f)())
template<typename _Ret , typename _Tp , typename _Arg >
const_mem_fun1_t< _Ret, _Tp, _Arg > mem_fun (_Ret(_Tp::*__f)(_Arg) const)
template<typename _Ret , typename _Tp , typename _Arg >
mem_fun1_t< _Ret, _Tp, _Arg > mem_fun (_Ret(_Tp::*__f)(_Arg))
template<typename _Ret , typename _Tp >
const_mem_fun_ref_t< _Ret, _Tp > mem_fun_ref (_Ret(_Tp::*__f)() const)
template<typename _Ret , typename _Tp >
mem_fun_ref_t< _Ret, _Tp > mem_fun_ref (_Ret(_Tp::*__f)())
template<typename _Ret , typename _Tp , typename _Arg >
const_mem_fun1_ref_t< _Ret, _Tp, _Arg > mem_fun_ref (_Ret(_Tp::*__f)(_Arg) const)
template<typename _Ret , typename _Tp , typename _Arg >
mem_fun1_ref_t< _Ret, _Tp, _Arg > mem_fun_ref (_Ret(_Tp::*__f)(_Arg))
void * memchr (void *__s, int __c, size_t __n)
template<typename _IIter1 , typename _IIter2 , typename _OIter >
constexpr _OIter merge (_IIter1, _IIter1, _IIter2, _IIter2, _OIter)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _Compare >
constexpr _OIter merge (_IIter1, _IIter1, _IIter2, _IIter2, _OIter, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator >
constexpr _OutputIterator merge (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
constexpr _OutputIterator merge (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _Tp >
constexpr enable_if_t< is_object_v< _Tp >, _Tp * > midpoint (_Tp *__a, _Tp *__b) noexcept
template<typename _Tp >
constexpr enable_if_t< __and_v< is_arithmetic< _Tp >, is_same< remove_cv_t< _Tp >, _Tp >, __not_< is_same< _Tp, bool > > >, _Tp > midpoint (_Tp __a, _Tp __b) noexcept
template<typename _Tp >
constexpr const _Tp & min (const _Tp &__a, const _Tp &__b)
template<typename _Tp , typename _Compare >
constexpr const _Tp & min (const _Tp &__a, const _Tp &__b, _Compare __comp)
template<typename _Tp >
constexpr _Tp min (initializer_list< _Tp >)
template<typename _Tp , typename _Compare >
constexpr _Tp min (initializer_list< _Tp >, _Compare)
template<typename _FIter >
constexpr _FIter min_element (_FIter, _FIter)
template<typename _FIter , typename _Compare >
constexpr _FIter min_element (_FIter, _FIter, _Compare)
template<typename _ForwardIterator >
constexpr _ForwardIterator min_element (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Compare >
constexpr _ForwardIterator min_element (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _Tp >
constexpr pair< const _Tp &, const _Tp & > minmax (const _Tp &__a, const _Tp &__b)
template<typename _Tp , typename _Compare >
constexpr pair< const _Tp &, const _Tp & > minmax (const _Tp &__a, const _Tp &__b, _Compare __comp)
template<typename _Tp >
constexpr pair< _Tp, _Tp > minmax (initializer_list< _Tp >)
template<typename _Tp , typename _Compare >
constexpr pair< _Tp, _Tp > minmax (initializer_list< _Tp >, _Compare)
template<typename _FIter >
constexpr pair< _FIter, _FIter > minmax_element (_FIter, _FIter)
template<typename _FIter , typename _Compare >
constexpr pair< _FIter, _FIter > minmax_element (_FIter, _FIter, _Compare)
template<typename _ForwardIterator >
constexpr pair< _ForwardIterator, _ForwardIterator > minmax_element (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Compare >
constexpr pair< _ForwardIterator, _ForwardIterator > minmax_element (_ForwardIterator __first, _ForwardIterator __last, _Compare __comp)
template<typename _IIter1 , typename _IIter2 >
constexpr pair< _IIter1, _IIter2 > mismatch (_IIter1, _IIter1, _IIter2)
template<typename _IIter1 , typename _IIter2 , typename _BinaryPredicate >
constexpr pair< _IIter1, _IIter2 > mismatch (_IIter1, _IIter1, _IIter2, _BinaryPredicate)
template<typename _InputIterator1 , typename _InputIterator2 >
constexpr pair< _InputIterator1, _InputIterator2 > mismatch (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2)
template<typename _InputIterator1 , typename _InputIterator2 , typename _BinaryPredicate >
constexpr pair< _InputIterator1, _InputIterator2 > mismatch (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _BinaryPredicate __binary_pred)
template<typename _InputIterator1 , typename _InputIterator2 >
constexpr pair< _InputIterator1, _InputIterator2 > mismatch (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2)
template<typename _InputIterator1 , typename _InputIterator2 , typename _BinaryPredicate >
constexpr pair< _InputIterator1, _InputIterator2 > mismatch (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _BinaryPredicate __binary_pred)
float modf (float __x, float *__iptr)
long double modf (long double __x, long double *__iptr)
template<typename _II , typename _OI >
constexpr _OI move (_II __first, _II __last, _OI __result)
template<typename _Tp >
constexpr std::remove_reference< _Tp >::type && move (_Tp &&__t) noexcept
template<typename _BI1 , typename _BI2 >
constexpr _BI2 move_backward (_BI1 __first, _BI1 __last, _BI2 __result)
template<typename _Tp >
constexpr __conditional_t< __move_if_noexcept_cond< _Tp >::value, const _Tp &, _Tp && > move_if_noexcept (_Tp &__x) noexcept
template<typename _InputIterator , typename _Allocator , typename = _RequireInputIter<_InputIterator>, typename = _RequireAllocator<_Allocator>>
multimap (_InputIterator, _InputIterator, _Allocator) -> multimap< __iter_key_t< _InputIterator >, __iter_val_t< _InputIterator >, less< __iter_key_t< _InputIterator >>, _Allocator >
template<typename _InputIterator , typename _Compare = less<__iter_key_t<_InputIterator>>, typename _Allocator = allocator<__iter_to_alloc_t<_InputIterator>>, typename = _RequireInputIter<_InputIterator>, typename = _RequireNotAllocator<_Compare>, typename = _RequireAllocator<_Allocator>>
multimap (_InputIterator, _InputIterator, _Compare=_Compare(), _Allocator=_Allocator()) -> multimap< __iter_key_t< _InputIterator >, __iter_val_t< _InputIterator >, _Compare, _Allocator >
template<typename _Key , typename _Tp , typename _Allocator , typename = _RequireAllocator<_Allocator>>
multimap (initializer_list< pair< _Key, _Tp >>, _Allocator) -> multimap< _Key, _Tp, less< _Key >, _Allocator >
template<typename _Key , typename _Tp , typename _Compare = less<_Key>, typename _Allocator = allocator<pair<const _Key, _Tp>>, typename = _RequireNotAllocator<_Compare>, typename = _RequireAllocator<_Allocator>>
multimap (initializer_list< pair< _Key, _Tp >>, _Compare=_Compare(), _Allocator=_Allocator()) -> multimap< _Key, _Tp, _Compare, _Allocator >
template<typename _InputIterator , typename _Allocator , typename = _RequireInputIter<_InputIterator>, typename = _RequireAllocator<_Allocator>>
multiset (_InputIterator, _InputIterator, _Allocator) -> multiset< typename iterator_traits< _InputIterator >::value_type, less< typename iterator_traits< _InputIterator >::value_type >, _Allocator >
template<typename _InputIterator , typename _Compare = less<typename iterator_traits<_InputIterator>::value_type>, typename _Allocator = allocator<typename iterator_traits<_InputIterator>::value_type>, typename = _RequireInputIter<_InputIterator>, typename = _RequireNotAllocator<_Compare>, typename = _RequireAllocator<_Allocator>>
multiset (_InputIterator, _InputIterator, _Compare=_Compare(), _Allocator=_Allocator()) -> multiset< typename iterator_traits< _InputIterator >::value_type, _Compare, _Allocator >
template<typename _Key , typename _Allocator , typename = _RequireAllocator<_Allocator>>
multiset (initializer_list< _Key >, _Allocator) -> multiset< _Key, less< _Key >, _Allocator >
template<typename _Key , typename _Compare = less<_Key>, typename _Allocator = allocator<_Key>, typename = _RequireNotAllocator<_Compare>, typename = _RequireAllocator<_Allocator>>
multiset (initializer_list< _Key >, _Compare=_Compare(), _Allocator=_Allocator()) -> multiset< _Key, _Compare, _Allocator >
template<typename _InputIterator >
constexpr _InputIterator next (_InputIterator __x, typename iterator_traits< _InputIterator >::difference_type __n=1)
template<typename _BidirectionalIterator >
constexpr bool next_permutation (_BidirectionalIterator __first, _BidirectionalIterator __last)
template<typename _BidirectionalIterator , typename _Compare >
constexpr bool next_permutation (_BidirectionalIterator __first, _BidirectionalIterator __last, _Compare __comp)
template<typename _BIter >
constexpr bool next_permutation (_BIter, _BIter)
template<typename _BIter , typename _Compare >
constexpr bool next_permutation (_BIter, _BIter, _Compare)
ios_base & noboolalpha (ios_base &__base)
template<typename _IIter , typename _Predicate >
constexpr bool none_of (_IIter, _IIter, _Predicate)
template<typename _InputIterator , typename _Predicate >
constexpr bool none_of (_InputIterator __first, _InputIterator __last, _Predicate __pred)
template<typename _Tp >
constexpr __gnu_cxx::__promote< _Tp >::__type norm (_Tp __x)
template<typename _Tp >
constexpr _Tp norm (const complex< _Tp > &)
ios_base & noshowbase (ios_base &__base)
ios_base & noshowpoint (ios_base &__base)
ios_base & noshowpos (ios_base &__base)
ios_base & noskipws (ios_base &__base)
template<typename _Predicate >
constexpr unary_negate< _Predicate > not1 (const _Predicate &__pred)
template<typename _Predicate >
constexpr binary_negate< _Predicate > not2 (const _Predicate &__pred)
template<typename _Fn >
constexpr auto not_fn (_Fn &&__fn) noexcept(std::is_nothrow_constructible< std::decay_t< _Fn >, _Fn && >::value)
void notify_all_at_thread_exit (condition_variable &, unique_lock< mutex >)
ios_base & nounitbuf (ios_base &__base)
ios_base & nouppercase (ios_base &__base)
template<typename _RAIter >
constexpr void nth_element (_RAIter, _RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
constexpr void nth_element (_RAIter, _RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator >
constexpr void nth_element (_RandomAccessIterator __first, _RandomAccessIterator __nth, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
constexpr void nth_element (_RandomAccessIterator __first, _RandomAccessIterator __nth, _RandomAccessIterator __last, _Compare __comp)
ios_base & oct (ios_base &__base)
template<typename _CharT , typename _Traits >
constexpr bool operator!= (__type_identity_t< basic_string_view< _CharT, _Traits >> __x, basic_string_view< _CharT, _Traits > __y) noexcept
template<typename _CharT , typename _Traits >
constexpr bool operator!= (basic_string_view< _CharT, _Traits > __x, __type_identity_t< basic_string_view< _CharT, _Traits >> __y) noexcept
template<typename _CharT , typename _Traits >
constexpr bool operator!= (basic_string_view< _CharT, _Traits > __x, basic_string_view< _CharT, _Traits > __y) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator!= (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _Tp1 , typename _Tp2 , _Lock_policy _Lp>
bool operator!= (const __shared_ptr< _Tp1, _Lp > &__a, const __shared_ptr< _Tp2, _Lp > &__b) noexcept
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator!= (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<class _Dom >
_Expr< _BinClos< struct std::__not_equal_to, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__not_equal_to, typename _Dom::value_type >::result_type > operator!= (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__not_equal_to, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__not_equal_to, typename _Dom::value_type >::result_type > operator!= (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__not_equal_to, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__not_equal_to, typename _Dom1::value_type >::result_type > operator!= (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<typename _Tp , typename _Up >
constexpr auto operator!= (const _Up &__lhs, const optional< _Tp > &__rhs) -> __optional_ne_t< _Up, _Tp >
template<typename _Tp , std::size_t _Nm>
constexpr bool operator!= (const array< _Tp, _Nm > &__one, const array< _Tp, _Nm > &__two)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator!= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator!= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs) noexcept
template<typename _Tp , typename _Alloc >
bool operator!= (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
bool operator!= (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _StateT >
bool operator!= (const fpos< _StateT > &__lhs, const fpos< _StateT > &__rhs)
template<typename _Tp , typename _Alloc >
bool operator!= (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator!= (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Bi_iter , class _Alloc >
bool operator!= (const match_results< _Bi_iter, _Alloc > &__m1, const match_results< _Bi_iter, _Alloc > &__m2)
template<typename _Iterator >
constexpr bool operator!= (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _IteratorL , typename _IteratorR >
constexpr bool operator!= (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator!= (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc >
bool operator!= (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Tp , typename _Up >
constexpr auto operator!= (const optional< _Tp > &__lhs, const _Up &__rhs) -> __optional_ne_t< _Tp, _Up >
template<typename _Tp , typename _Up >
constexpr auto operator!= (const optional< _Tp > &__lhs, const optional< _Up > &__rhs) -> __optional_ne_t< _Tp, _Up >
template<typename _Tp >
constexpr bool operator!= (const optional< _Tp > &__lhs, nullopt_t) noexcept
template<typename _Tp , typename _Seq >
bool operator!= (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
template<typename _IteratorL , typename _IteratorR >
constexpr bool operator!= (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y) requires requires
template<typename _Key , typename _Compare , typename _Alloc >
bool operator!= (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename _Tp , typename _Seq >
bool operator!= (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
bool operator!= (const std::bernoulli_distribution &__d1, const std::bernoulli_distribution &__d2)
template<typename _IntType >
bool operator!= (const std::binomial_distribution< _IntType > &__d1, const std::binomial_distribution< _IntType > &__d2)
template<typename _RealType >
bool operator!= (const std::cauchy_distribution< _RealType > &__d1, const std::cauchy_distribution< _RealType > &__d2)
template<typename _RealType >
bool operator!= (const std::chi_squared_distribution< _RealType > &__d1, const std::chi_squared_distribution< _RealType > &__d2)
template<typename _RandomNumberEngine , size_t __p, size_t __r>
bool operator!= (const std::discard_block_engine< _RandomNumberEngine, __p, __r > &__lhs, const std::discard_block_engine< _RandomNumberEngine, __p, __r > &__rhs)
template<typename _IntType >
bool operator!= (const std::discrete_distribution< _IntType > &__d1, const std::discrete_distribution< _IntType > &__d2)
template<typename _RealType >
bool operator!= (const std::exponential_distribution< _RealType > &__d1, const std::exponential_distribution< _RealType > &__d2)
template<typename _RealType >
bool operator!= (const std::extreme_value_distribution< _RealType > &__d1, const std::extreme_value_distribution< _RealType > &__d2)
template<typename _RealType >
bool operator!= (const std::fisher_f_distribution< _RealType > &__d1, const std::fisher_f_distribution< _RealType > &__d2)
template<typename _RealType >
bool operator!= (const std::gamma_distribution< _RealType > &__d1, const std::gamma_distribution< _RealType > &__d2)
template<typename _IntType >
bool operator!= (const std::geometric_distribution< _IntType > &__d1, const std::geometric_distribution< _IntType > &__d2)
template<typename _RandomNumberEngine , size_t __w, typename _UIntType >
bool operator!= (const std::independent_bits_engine< _RandomNumberEngine, __w, _UIntType > &__lhs, const std::independent_bits_engine< _RandomNumberEngine, __w, _UIntType > &__rhs)
template<typename _UIntType , _UIntType __a, _UIntType __c, _UIntType __m>
bool operator!= (const std::linear_congruential_engine< _UIntType, __a, __c, __m > &__lhs, const std::linear_congruential_engine< _UIntType, __a, __c, __m > &__rhs)
template<typename _RealType >
bool operator!= (const std::lognormal_distribution< _RealType > &__d1, const std::lognormal_distribution< _RealType > &__d2)
template<typename _UIntType , size_t __w, size_t __n, size_t __m, size_t __r, _UIntType __a, size_t __u, _UIntType __d, size_t __s, _UIntType __b, size_t __t, _UIntType __c, size_t __l, _UIntType __f>
bool operator!= (const std::mersenne_twister_engine< _UIntType, __w, __n, __m, __r, __a, __u, __d, __s, __b, __t, __c, __l, __f > &__lhs, const std::mersenne_twister_engine< _UIntType, __w, __n, __m, __r, __a, __u, __d, __s, __b, __t, __c, __l, __f > &__rhs)
template<typename _IntType >
bool operator!= (const std::negative_binomial_distribution< _IntType > &__d1, const std::negative_binomial_distribution< _IntType > &__d2)
template<typename _RealType >
bool operator!= (const std::normal_distribution< _RealType > &__d1, const std::normal_distribution< _RealType > &__d2)
template<typename _RealType >
bool operator!= (const std::piecewise_constant_distribution< _RealType > &__d1, const std::piecewise_constant_distribution< _RealType > &__d2)
template<typename _RealType >
bool operator!= (const std::piecewise_linear_distribution< _RealType > &__d1, const std::piecewise_linear_distribution< _RealType > &__d2)
template<typename _IntType >
bool operator!= (const std::poisson_distribution< _IntType > &__d1, const std::poisson_distribution< _IntType > &__d2)
template<typename _RandomNumberEngine , size_t __k>
bool operator!= (const std::shuffle_order_engine< _RandomNumberEngine, __k > &__lhs, const std::shuffle_order_engine< _RandomNumberEngine, __k > &__rhs)
template<typename _RealType >
bool operator!= (const std::student_t_distribution< _RealType > &__d1, const std::student_t_distribution< _RealType > &__d2)
template<typename _UIntType , size_t __w, size_t __s, size_t __r>
bool operator!= (const std::subtract_with_carry_engine< _UIntType, __w, __s, __r > &__lhs, const std::subtract_with_carry_engine< _UIntType, __w, __s, __r > &__rhs)
template<typename _IntType >
bool operator!= (const std::uniform_int_distribution< _IntType > &__d1, const std::uniform_int_distribution< _IntType > &__d2)
template<typename _IntType >
bool operator!= (const std::uniform_real_distribution< _IntType > &__d1, const std::uniform_real_distribution< _IntType > &__d2)
template<typename _RealType >
bool operator!= (const std::weibull_distribution< _RealType > &__d1, const std::weibull_distribution< _RealType > &__d2)
template<typename... _TElements, typename... _UElements>
constexpr bool operator!= (const tuple< _TElements... > &__t, const tuple< _UElements... > &__u)
template<class _Dom >
_Expr< _BinClos< struct std::__not_equal_to, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__not_equal_to, typename _Dom::value_type >::result_type > operator!= (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __not_equal_to, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __not_equal_to, _Tp >::result_type > operator!= (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp , typename _Dp , typename _Up , typename _Ep >
bool operator!= (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _Tp , typename _Dp >
bool operator!= (const unique_ptr< _Tp, _Dp > &__x, nullptr_t) noexcept
template<typename _Tp >
_Expr< _BinClos< __not_equal_to, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __not_equal_to, _Tp >::result_type > operator!= (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __not_equal_to, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __not_equal_to, _Tp >::result_type > operator!= (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__not_equal_to, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__not_equal_to, typename _Dom::value_type >::result_type > operator!= (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename... _Types>
constexpr bool operator!= (const variant< _Types... > &__lhs, const variant< _Types... > &__rhs)
template<typename _Tp , typename _Alloc >
bool operator!= (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
constexpr bool operator!= (monostate, monostate) noexcept
template<typename _Tp >
constexpr bool operator!= (nullopt_t, const optional< _Tp > &__rhs) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator!= (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _Tp , typename _Dp >
bool operator!= (nullptr_t, const unique_ptr< _Tp, _Dp > &__x) noexcept
bool operator!= (thread::id __x, thread::id __y) noexcept
template<class _Dom >
_Expr< _BinClos< struct std::__modulus, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__modulus, typename _Dom::value_type >::result_type > operator% (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__modulus, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__modulus, typename _Dom::value_type >::result_type > operator% (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__modulus, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__modulus, typename _Dom1::value_type >::result_type > operator% (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__modulus, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__modulus, typename _Dom::value_type >::result_type > operator% (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __modulus, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __modulus, _Tp >::result_type > operator% (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __modulus, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __modulus, _Tp >::result_type > operator% (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __modulus, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __modulus, _Tp >::result_type > operator% (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__modulus, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__modulus, typename _Dom::value_type >::result_type > operator% (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
constexpr _Ios_Fmtflags operator& (_Ios_Fmtflags __a, _Ios_Fmtflags __b)
constexpr _Ios_Iostate operator& (_Ios_Iostate __a, _Ios_Iostate __b)
constexpr _Ios_Openmode operator& (_Ios_Openmode __a, _Ios_Openmode __b)
constexpr byte operator& (byte __l, byte __r) noexcept
constexpr chars_format operator& (chars_format __lhs, chars_format __rhs) noexcept
template<class _Dom >
_Expr< _BinClos< struct std::__bitwise_and, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__bitwise_and, typename _Dom::value_type >::result_type > operator& (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__bitwise_and, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__bitwise_and, typename _Dom::value_type >::result_type > operator& (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__bitwise_and, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__bitwise_and, typename _Dom1::value_type >::result_type > operator& (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__bitwise_and, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__bitwise_and, typename _Dom::value_type >::result_type > operator& (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __bitwise_and, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __bitwise_and, _Tp >::result_type > operator& (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __bitwise_and, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __bitwise_and, _Tp >::result_type > operator& (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __bitwise_and, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __bitwise_and, _Tp >::result_type > operator& (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__bitwise_and, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__bitwise_and, typename _Dom::value_type >::result_type > operator& (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
constexpr launch operator& (launch __x, launch __y) noexcept
constexpr memory_order operator& (memory_order __m, __memory_order_modifier __mod)
template<class _Dom >
_Expr< _BinClos< struct std::__logical_and, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__logical_and, typename _Dom::value_type >::result_type > operator&& (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__logical_and, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__logical_and, typename _Dom::value_type >::result_type > operator&& (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__logical_and, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__logical_and, typename _Dom1::value_type >::result_type > operator&& (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__logical_and, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__logical_and, typename _Dom::value_type >::result_type > operator&& (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __logical_and, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __logical_and, _Tp >::result_type > operator&& (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __logical_and, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __logical_and, _Tp >::result_type > operator&& (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __logical_and, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __logical_and, _Tp >::result_type > operator&& (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__logical_and, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__logical_and, typename _Dom::value_type >::result_type > operator&& (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
const _Ios_Fmtflags & operator&= (_Ios_Fmtflags &__a, _Ios_Fmtflags __b)
const _Ios_Iostate & operator&= (_Ios_Iostate &__a, _Ios_Iostate __b)
const _Ios_Openmode & operator&= (_Ios_Openmode &__a, _Ios_Openmode __b)
constexpr byte & operator&= (byte &__l, byte __r) noexcept
constexpr chars_format & operator&= (chars_format &__lhs, chars_format __rhs) noexcept
launch & operator&= (launch &__x, launch __y) noexcept
template<class _Dom >
_Expr< _BinClos< struct std::__multiplies, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__multiplies, typename _Dom::value_type >::result_type > operator* (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__multiplies, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__multiplies, typename _Dom::value_type >::result_type > operator* (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__multiplies, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__multiplies, typename _Dom1::value_type >::result_type > operator* (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__multiplies, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__multiplies, typename _Dom::value_type >::result_type > operator* (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __multiplies, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __multiplies, _Tp >::result_type > operator* (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __multiplies, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __multiplies, _Tp >::result_type > operator* (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __multiplies, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __multiplies, _Tp >::result_type > operator* (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__multiplies, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__multiplies, typename _Dom::value_type >::result_type > operator* (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _CharT , typename _Traits , typename _Alloc >
constexpr basic_string< _CharT, _Traits, _Alloc > operator+ (_CharT __lhs, basic_string< _CharT, _Traits, _Alloc > &&__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
constexpr basic_string< _CharT, _Traits, _Alloc > operator+ (_CharT __lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
constexpr basic_string< _CharT, _Traits, _Alloc > operator+ (basic_string< _CharT, _Traits, _Alloc > &&__lhs, _CharT __rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
constexpr basic_string< _CharT, _Traits, _Alloc > operator+ (basic_string< _CharT, _Traits, _Alloc > &&__lhs, basic_string< _CharT, _Traits, _Alloc > &&__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
constexpr basic_string< _CharT, _Traits, _Alloc > operator+ (basic_string< _CharT, _Traits, _Alloc > &&__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
constexpr basic_string< _CharT, _Traits, _Alloc > operator+ (basic_string< _CharT, _Traits, _Alloc > &&__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
constexpr basic_string< _CharT, _Traits, _Alloc > operator+ (const _CharT *__lhs, basic_string< _CharT, _Traits, _Alloc > &&__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
constexpr basic_string< _CharT, _Traits, _Alloc > operator+ (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<class _Dom >
_Expr< _BinClos< struct std::__plus, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__plus, typename _Dom::value_type >::result_type > operator+ (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__plus, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__plus, typename _Dom::value_type >::result_type > operator+ (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__plus, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__plus, typename _Dom1::value_type >::result_type > operator+ (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<typename _CharT , typename _Traits , typename _Alloc >
constexpr basic_string< _CharT, _Traits, _Alloc > operator+ (const basic_string< _CharT, _Traits, _Alloc > &__lhs, _CharT __rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
constexpr basic_string< _CharT, _Traits, _Alloc > operator+ (const basic_string< _CharT, _Traits, _Alloc > &__lhs, basic_string< _CharT, _Traits, _Alloc > &&__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
constexpr basic_string< _CharT, _Traits, _Alloc > operator+ (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
constexpr basic_string< _CharT, _Traits, _Alloc > operator+ (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<typename _Tp >
constexpr complex< _Tp > operator+ (const complex< _Tp > &__x)
template<class _Dom >
_Expr< _BinClos< struct std::__plus, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__plus, typename _Dom::value_type >::result_type > operator+ (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __plus, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __plus, _Tp >::result_type > operator+ (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __plus, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __plus, _Tp >::result_type > operator+ (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __plus, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __plus, _Tp >::result_type > operator+ (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__plus, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__plus, typename _Dom::value_type >::result_type > operator+ (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Iterator >
constexpr move_iterator< _Iterator > operator+ (typename move_iterator< _Iterator >::difference_type __n, const move_iterator< _Iterator > &__x)
template<typename _Iterator >
constexpr reverse_iterator< _Iterator > operator+ (typename reverse_iterator< _Iterator >::difference_type __n, const reverse_iterator< _Iterator > &__x)
template<class _Dom >
_Expr< _BinClos< struct std::__minus, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__minus, typename _Dom::value_type >::result_type > operator- (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__minus, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__minus, typename _Dom::value_type >::result_type > operator- (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__minus, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__minus, typename _Dom1::value_type >::result_type > operator- (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<typename _Tp >
constexpr complex< _Tp > operator- (const complex< _Tp > &__x)
template<typename _IteratorL , typename _IteratorR >
constexpr auto operator- (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y) -> decltype(__x.base() - __y.base())
template<typename _IteratorL , typename _IteratorR >
constexpr auto operator- (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y) -> decltype(__y.base() - __x.base())
template<class _Dom >
_Expr< _BinClos< struct std::__minus, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__minus, typename _Dom::value_type >::result_type > operator- (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __minus, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __minus, _Tp >::result_type > operator- (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __minus, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __minus, _Tp >::result_type > operator- (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __minus, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __minus, _Tp >::result_type > operator- (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__minus, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__minus, typename _Dom::value_type >::result_type > operator- (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<class _Dom >
_Expr< _BinClos< struct std::__divides, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__divides, typename _Dom::value_type >::result_type > operator/ (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__divides, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__divides, typename _Dom::value_type >::result_type > operator/ (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__divides, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__divides, typename _Dom1::value_type >::result_type > operator/ (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__divides, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__divides, typename _Dom::value_type >::result_type > operator/ (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __divides, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __divides, _Tp >::result_type > operator/ (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __divides, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __divides, _Tp >::result_type > operator/ (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __divides, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __divides, _Tp >::result_type > operator/ (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__divides, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__divides, typename _Dom::value_type >::result_type > operator/ (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _CharT , typename _Traits >
constexpr bool operator< (__type_identity_t< basic_string_view< _CharT, _Traits >> __x, basic_string_view< _CharT, _Traits > __y) noexcept
template<typename _CharT , typename _Traits >
constexpr bool operator< (basic_string_view< _CharT, _Traits > __x, __type_identity_t< basic_string_view< _CharT, _Traits >> __y) noexcept
template<typename _CharT , typename _Traits >
constexpr bool operator< (basic_string_view< _CharT, _Traits > __x, basic_string_view< _CharT, _Traits > __y) noexcept
template<typename _Tp , typename _Up , _Lock_policy _Lp>
bool operator< (const __shared_ptr< _Tp, _Lp > &__a, const __shared_ptr< _Up, _Lp > &__b) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator< (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator< (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<class _Dom >
_Expr< _BinClos< struct std::__less, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__less, typename _Dom::value_type >::result_type > operator< (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__less, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__less, typename _Dom::value_type >::result_type > operator< (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__less, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__less, typename _Dom1::value_type >::result_type > operator< (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<typename _Tp , typename _Up >
constexpr auto operator< (const _Up &__lhs, const optional< _Tp > &__rhs) -> __optional_lt_t< _Up, _Tp >
template<typename _Tp , std::size_t _Nm>
constexpr bool operator< (const array< _Tp, _Nm > &__a, const array< _Tp, _Nm > &__b)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator< (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator< (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs) noexcept
template<typename _Tp , typename _Alloc >
bool operator< (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
bool operator< (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _Tp , typename _Alloc >
bool operator< (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator< (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Iterator >
constexpr bool operator< (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _IteratorL , typename _IteratorR >
constexpr bool operator< (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y) requires requires
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator< (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc >
bool operator< (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Tp >
constexpr bool operator< (const optional< _Tp > &, nullopt_t) noexcept
template<typename _Tp , typename _Up >
constexpr auto operator< (const optional< _Tp > &__lhs, const _Up &__rhs) -> __optional_lt_t< _Tp, _Up >
template<typename _Tp , typename _Up >
constexpr auto operator< (const optional< _Tp > &__lhs, const optional< _Up > &__rhs) -> __optional_lt_t< _Tp, _Up >
template<typename _Tp , typename _Seq >
bool operator< (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
template<typename _IteratorL , typename _IteratorR >
constexpr bool operator< (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y) requires requires
template<typename _Key , typename _Compare , typename _Alloc >
bool operator< (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename _Tp , typename _Seq >
bool operator< (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
template<typename... _TElements, typename... _UElements>
constexpr bool operator< (const tuple< _TElements... > &__t, const tuple< _UElements... > &__u)
template<class _Dom >
_Expr< _BinClos< struct std::__less, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__less, typename _Dom::value_type >::result_type > operator< (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __less, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __less, _Tp >::result_type > operator< (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp , typename _Dp , typename _Up , typename _Ep >
_GLIBCXX23_CONSTEXPR bool operator< (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _Tp , typename _Dp >
_GLIBCXX23_CONSTEXPR bool operator< (const unique_ptr< _Tp, _Dp > &__x, nullptr_t)
template<typename _Tp >
_Expr< _BinClos< __less, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __less, _Tp >::result_type > operator< (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __less, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __less, _Tp >::result_type > operator< (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__less, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__less, typename _Dom::value_type >::result_type > operator< (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename... _Types>
constexpr bool operator< (const variant< _Types... > &__lhs, const variant< _Types... > &__rhs)
template<typename _Tp , typename _Alloc >
bool operator< (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
constexpr bool operator< (monostate, monostate) noexcept
template<typename _Tp >
constexpr bool operator< (nullopt_t, const optional< _Tp > &__rhs) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator< (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _Tp , typename _Dp >
_GLIBCXX23_CONSTEXPR bool operator< (nullptr_t, const unique_ptr< _Tp, _Dp > &__x)
bool operator< (thread::id __x, thread::id __y) noexcept
template<typename _Ostream , typename _Tp >
__rvalue_stream_insertion_t< _Ostream, _Tp > operator<< (_Ostream &&__os, const _Tp &__x)
template<typename _CharT , typename _Traits , typename _MoneyT >
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, _Put_money< _MoneyT > __f)
template<typename _CharT , typename _Traits >
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, _Put_time< _CharT > __f)
template<typename _CharT , typename _Traits >
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, _Resetiosflags __f)
template<typename _CharT , typename _Traits >
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, _Setbase __f)
template<typename _CharT , typename _Traits >
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, _Setfill< _CharT > __f)
template<typename _CharT , typename _Traits >
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, _Setiosflags __f)
template<typename _CharT , typename _Traits >
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, _Setprecision __f)
template<typename _CharT , typename _Traits >
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, _Setw __f)
template<typename _CharT , typename _Traits >
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, basic_string_view< _CharT, _Traits > __str)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, const __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > &__str)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, const basic_string< _CharT, _Traits, _Alloc > &__str)
template<typename _Tp , typename _CharT , class _Traits >
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__os, const complex< _Tp > &__x)
template<class _CharT , class _Traits >
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__out, thread::id __id)
template<typename _IntegerType >
constexpr __byte_op_t< _IntegerType > operator<< (byte __b, _IntegerType __shift) noexcept
template<class _Dom >
_Expr< _BinClos< struct std::__shift_left, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__shift_left, typename _Dom::value_type >::result_type > operator<< (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__shift_left, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__shift_left, typename _Dom::value_type >::result_type > operator<< (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__shift_left, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__shift_left, typename _Dom1::value_type >::result_type > operator<< (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__shift_left, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__shift_left, typename _Dom::value_type >::result_type > operator<< (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __shift_left, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __shift_left, _Tp >::result_type > operator<< (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __shift_left, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __shift_left, _Tp >::result_type > operator<< (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __shift_left, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __shift_left, _Tp >::result_type > operator<< (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__shift_left, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__shift_left, typename _Dom::value_type >::result_type > operator<< (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _IntType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &, const std::uniform_int_distribution< _IntType > &)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &, const std::uniform_real_distribution< _RealType > &)
template<typename _IntType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const binomial_distribution< _IntType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const chi_squared_distribution< _RealType > &__x)
template<typename _RandomNumberEngine , size_t __p, size_t __r, typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const discard_block_engine< _RandomNumberEngine, __p, __r > &__x)
template<typename _IntType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const discrete_distribution< _IntType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const fisher_f_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const gamma_distribution< _RealType > &__x)
template<typename _UIntType , _UIntType __a, _UIntType __c, _UIntType __m, typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const linear_congruential_engine< _UIntType, __a, __c, __m > &__lcr)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const lognormal_distribution< _RealType > &__x)
template<typename _UIntType , size_t __w, size_t __n, size_t __m, size_t __r, _UIntType __a, size_t __u, _UIntType __d, size_t __s, _UIntType __b, size_t __t, _UIntType __c, size_t __l, _UIntType __f, typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const mersenne_twister_engine< _UIntType, __w, __n, __m, __r, __a, __u, __d, __s, __b, __t, __c, __l, __f > &__x)
template<typename _IntType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const negative_binomial_distribution< _IntType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const normal_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const piecewise_constant_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const piecewise_linear_distribution< _RealType > &__x)
template<typename _IntType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const poisson_distribution< _IntType > &__x)
template<typename _RandomNumberEngine , size_t __k, typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const shuffle_order_engine< _RandomNumberEngine, __k > &__x)
template<typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::bernoulli_distribution &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::cauchy_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::exponential_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::extreme_value_distribution< _RealType > &__x)
template<typename _IntType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::geometric_distribution< _IntType > &__x)
template<typename _RandomNumberEngine , size_t __w, typename _UIntType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::independent_bits_engine< _RandomNumberEngine, __w, _UIntType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::weibull_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const student_t_distribution< _RealType > &__x)
template<typename _UIntType , size_t __w, size_t __s, size_t __r, typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const subtract_with_carry_engine< _UIntType, __w, __s, __r > &__x)
template<typename _IntegerType >
constexpr __byte_op_t< _IntegerType > & operator<<= (byte &__b, _IntegerType __shift) noexcept
template<typename _CharT , typename _Traits >
constexpr bool operator<= (__type_identity_t< basic_string_view< _CharT, _Traits >> __x, basic_string_view< _CharT, _Traits > __y) noexcept
template<typename _CharT , typename _Traits >
constexpr bool operator<= (basic_string_view< _CharT, _Traits > __x, __type_identity_t< basic_string_view< _CharT, _Traits >> __y) noexcept
template<typename _CharT , typename _Traits >
constexpr bool operator<= (basic_string_view< _CharT, _Traits > __x, basic_string_view< _CharT, _Traits > __y) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator<= (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _Tp1 , typename _Tp2 , _Lock_policy _Lp>
bool operator<= (const __shared_ptr< _Tp1, _Lp > &__a, const __shared_ptr< _Tp2, _Lp > &__b) noexcept
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator<= (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<class _Dom >
_Expr< _BinClos< struct std::__less_equal, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__less_equal, typename _Dom::value_type >::result_type > operator<= (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__less_equal, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__less_equal, typename _Dom::value_type >::result_type > operator<= (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__less_equal, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__less_equal, typename _Dom1::value_type >::result_type > operator<= (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<typename _Tp , typename _Up >
constexpr auto operator<= (const _Up &__lhs, const optional< _Tp > &__rhs) -> __optional_le_t< _Up, _Tp >
template<typename _Tp , std::size_t _Nm>
constexpr bool operator<= (const array< _Tp, _Nm > &__one, const array< _Tp, _Nm > &__two)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator<= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator<= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs) noexcept
template<typename _Tp , typename _Alloc >
bool operator<= (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
bool operator<= (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _Tp , typename _Alloc >
bool operator<= (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator<= (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Iterator >
constexpr bool operator<= (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _IteratorL , typename _IteratorR >
constexpr bool operator<= (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y) requires requires
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator<= (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc >
bool operator<= (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Tp , typename _Up >
constexpr auto operator<= (const optional< _Tp > &__lhs, const _Up &__rhs) -> __optional_le_t< _Tp, _Up >
template<typename _Tp , typename _Up >
constexpr auto operator<= (const optional< _Tp > &__lhs, const optional< _Up > &__rhs) -> __optional_le_t< _Tp, _Up >
template<typename _Tp >
constexpr bool operator<= (const optional< _Tp > &__lhs, nullopt_t) noexcept
template<typename _Tp , typename _Seq >
bool operator<= (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
template<typename _IteratorL , typename _IteratorR >
constexpr bool operator<= (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y) requires requires
template<typename _Key , typename _Compare , typename _Alloc >
bool operator<= (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename _Tp , typename _Seq >
bool operator<= (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
template<typename... _TElements, typename... _UElements>
constexpr bool operator<= (const tuple< _TElements... > &__t, const tuple< _UElements... > &__u)
template<class _Dom >
_Expr< _BinClos< struct std::__less_equal, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__less_equal, typename _Dom::value_type >::result_type > operator<= (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __less_equal, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __less_equal, _Tp >::result_type > operator<= (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp , typename _Dp , typename _Up , typename _Ep >
_GLIBCXX23_CONSTEXPR bool operator<= (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _Tp , typename _Dp >
_GLIBCXX23_CONSTEXPR bool operator<= (const unique_ptr< _Tp, _Dp > &__x, nullptr_t)
template<typename _Tp >
_Expr< _BinClos< __less_equal, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __less_equal, _Tp >::result_type > operator<= (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __less_equal, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __less_equal, _Tp >::result_type > operator<= (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__less_equal, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__less_equal, typename _Dom::value_type >::result_type > operator<= (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename... _Types>
constexpr bool operator<= (const variant< _Types... > &__lhs, const variant< _Types... > &__rhs)
template<typename _Tp , typename _Alloc >
bool operator<= (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
constexpr bool operator<= (monostate, monostate) noexcept
template<typename _Tp >
constexpr bool operator<= (nullopt_t, const optional< _Tp > &) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator<= (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _Tp , typename _Dp >
_GLIBCXX23_CONSTEXPR bool operator<= (nullptr_t, const unique_ptr< _Tp, _Dp > &__x)
bool operator<= (thread::id __x, thread::id __y) noexcept
template<three_way_comparable _Iterator>
constexpr compare_three_way_result_t< _Iterator, _Iterator > operator<=> (const reverse_iterator< _Iterator > &__x, const reverse_iterator< _Iterator > &__y)
template<typename _IteratorL , three_way_comparable_with< _IteratorL > _IteratorR>
constexpr compare_three_way_result_t< _IteratorL, _IteratorR > operator<=> (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y)
template<typename _CharT , typename _Traits >
constexpr bool operator== (__type_identity_t< basic_string_view< _CharT, _Traits >> __x, basic_string_view< _CharT, _Traits > __y) noexcept
template<typename _CharT , typename _Traits >
constexpr bool operator== (basic_string_view< _CharT, _Traits > __x, __type_identity_t< basic_string_view< _CharT, _Traits >> __y) noexcept
template<typename _CharT , typename _Traits >
constexpr bool operator== (basic_string_view< _CharT, _Traits > __x, basic_string_view< _CharT, _Traits > __y) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator== (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _Tp1 , typename _Tp2 , _Lock_policy _Lp>
bool operator== (const __shared_ptr< _Tp1, _Lp > &__a, const __shared_ptr< _Tp2, _Lp > &__b) noexcept
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator== (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<class _Dom >
_Expr< _BinClos< struct std::__equal_to, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__equal_to, typename _Dom::value_type >::result_type > operator== (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__equal_to, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__equal_to, typename _Dom::value_type >::result_type > operator== (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__equal_to, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__equal_to, typename _Dom1::value_type >::result_type > operator== (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<typename _Tp , typename _Up >
constexpr auto operator== (const _Up &__lhs, const optional< _Tp > &__rhs) -> __optional_eq_t< _Up, _Tp >
template<typename _T1 , typename _T2 >
constexpr bool operator== (const allocator< _T1 > &, const allocator< _T2 > &) noexcept
template<typename _Tp , std::size_t _Nm>
constexpr bool operator== (const array< _Tp, _Nm > &__one, const array< _Tp, _Nm > &__two)
template<typename _CharT >
constexpr __gnu_cxx::__enable_if< __is_char< _CharT >::__value, bool >::__type operator== (const basic_string< _CharT > &__lhs, const basic_string< _CharT > &__rhs) noexcept
template<typename _CharT , typename _Traits , typename _Alloc >
constexpr bool operator== (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
constexpr bool operator== (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs) noexcept
template<typename _Tp , typename _Alloc >
bool operator== (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
bool operator== (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _StateT >
bool operator== (const fpos< _StateT > &__lhs, const fpos< _StateT > &__rhs)
template<typename _Res , typename... _Args>
bool operator== (const function< _Res(_Args...)> &__f, nullptr_t) noexcept
template<typename _CharT , typename _Traits >
bool operator== (const istreambuf_iterator< _CharT, _Traits > &__a, const istreambuf_iterator< _CharT, _Traits > &__b)
template<typename _Tp , typename _Alloc >
bool operator== (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator== (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Bi_iter , typename _Alloc >
bool operator== (const match_results< _Bi_iter, _Alloc > &__m1, const match_results< _Bi_iter, _Alloc > &__m2)
template<typename _Iterator >
constexpr bool operator== (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _IteratorL , typename _IteratorR >
constexpr bool operator== (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y) requires requires
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator== (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc >
bool operator== (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Tp , typename _Up >
constexpr auto operator== (const optional< _Tp > &__lhs, const _Up &__rhs) -> __optional_eq_t< _Tp, _Up >
template<typename _Tp , typename _Up >
constexpr auto operator== (const optional< _Tp > &__lhs, const optional< _Up > &__rhs) -> __optional_eq_t< _Tp, _Up >
template<typename _Tp >
constexpr bool operator== (const optional< _Tp > &__lhs, nullopt_t) noexcept
template<typename _Tp , typename _Seq >
bool operator== (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
template<typename _Iterator >
constexpr bool operator== (const reverse_iterator< _Iterator > &__x, const reverse_iterator< _Iterator > &__y) requires requires
template<typename _IteratorL , typename _IteratorR >
constexpr bool operator== (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y) requires requires
template<typename _Key , typename _Compare , typename _Alloc >
bool operator== (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename _Tp , typename _Seq >
bool operator== (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
template<typename _RealType >
bool operator== (const std::normal_distribution< _RealType > &__d1, const std::normal_distribution< _RealType > &__d2)
template<typename... _TElements, typename... _UElements>
constexpr bool operator== (const tuple< _TElements... > &__t, const tuple< _UElements... > &__u)
template<class _Dom >
_Expr< _BinClos< struct std::__equal_to, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__equal_to, typename _Dom::value_type >::result_type > operator== (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __equal_to, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __equal_to, _Tp >::result_type > operator== (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp , typename _Dp , typename _Up , typename _Ep >
_GLIBCXX23_CONSTEXPR bool operator== (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _Tp , typename _Dp >
_GLIBCXX23_CONSTEXPR bool operator== (const unique_ptr< _Tp, _Dp > &__x, nullptr_t) noexcept
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc >
bool operator== (const unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc > &__x, const unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc > &__y)
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc >
bool operator== (const unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc > &__x, const unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc > &__y)
template<class _Value , class _Hash , class _Pred , class _Alloc >
bool operator== (const unordered_multiset< _Value, _Hash, _Pred, _Alloc > &__x, const unordered_multiset< _Value, _Hash, _Pred, _Alloc > &__y)
template<class _Value , class _Hash , class _Pred , class _Alloc >
bool operator== (const unordered_set< _Value, _Hash, _Pred, _Alloc > &__x, const unordered_set< _Value, _Hash, _Pred, _Alloc > &__y)
template<typename _Tp >
_Expr< _BinClos< __equal_to, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __equal_to, _Tp >::result_type > operator== (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __equal_to, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __equal_to, _Tp >::result_type > operator== (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__equal_to, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__equal_to, typename _Dom::value_type >::result_type > operator== (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename... _Types>
constexpr bool operator== (const variant< _Types... > &__lhs, const variant< _Types... > &__rhs)
template<typename _Tp , typename _Alloc >
constexpr bool operator== (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
constexpr bool operator== (monostate, monostate) noexcept
template<typename _Tp >
constexpr bool operator== (nullopt_t, const optional< _Tp > &__rhs) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator== (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _Tp , typename _Dp >
bool operator== (nullptr_t, const unique_ptr< _Tp, _Dp > &__x) noexcept
bool operator== (thread::id __x, thread::id __y) noexcept
template<typename _CharT , typename _Traits >
constexpr bool operator> (__type_identity_t< basic_string_view< _CharT, _Traits >> __x, basic_string_view< _CharT, _Traits > __y) noexcept
template<typename _CharT , typename _Traits >
constexpr bool operator> (basic_string_view< _CharT, _Traits > __x, __type_identity_t< basic_string_view< _CharT, _Traits >> __y) noexcept
template<typename _CharT , typename _Traits >
constexpr bool operator> (basic_string_view< _CharT, _Traits > __x, basic_string_view< _CharT, _Traits > __y) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator> (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _Tp1 , typename _Tp2 , _Lock_policy _Lp>
bool operator> (const __shared_ptr< _Tp1, _Lp > &__a, const __shared_ptr< _Tp2, _Lp > &__b) noexcept
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator> (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<class _Dom >
_Expr< _BinClos< struct std::__greater, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__greater, typename _Dom::value_type >::result_type > operator> (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__greater, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__greater, typename _Dom::value_type >::result_type > operator> (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__greater, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__greater, typename _Dom1::value_type >::result_type > operator> (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<typename _Tp , typename _Up >
constexpr auto operator> (const _Up &__lhs, const optional< _Tp > &__rhs) -> __optional_gt_t< _Up, _Tp >
template<typename _Tp , std::size_t _Nm>
constexpr bool operator> (const array< _Tp, _Nm > &__one, const array< _Tp, _Nm > &__two)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator> (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator> (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs) noexcept
template<typename _Tp , typename _Alloc >
bool operator> (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
bool operator> (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _Tp , typename _Alloc >
bool operator> (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator> (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Iterator >
constexpr bool operator> (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _IteratorL , typename _IteratorR >
constexpr bool operator> (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y) requires requires
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator> (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc >
bool operator> (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Tp , typename _Up >
constexpr auto operator> (const optional< _Tp > &__lhs, const _Up &__rhs) -> __optional_gt_t< _Tp, _Up >
template<typename _Tp , typename _Up >
constexpr auto operator> (const optional< _Tp > &__lhs, const optional< _Up > &__rhs) -> __optional_gt_t< _Tp, _Up >
template<typename _Tp >
constexpr bool operator> (const optional< _Tp > &__lhs, nullopt_t) noexcept
template<typename _Tp , typename _Seq >
bool operator> (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
template<typename _IteratorL , typename _IteratorR >
constexpr bool operator> (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y) requires requires
template<typename _Key , typename _Compare , typename _Alloc >
bool operator> (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename _Tp , typename _Seq >
bool operator> (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
template<typename... _TElements, typename... _UElements>
constexpr bool operator> (const tuple< _TElements... > &__t, const tuple< _UElements... > &__u)
template<class _Dom >
_Expr< _BinClos< struct std::__greater, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__greater, typename _Dom::value_type >::result_type > operator> (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __greater, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __greater, _Tp >::result_type > operator> (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp , typename _Dp , typename _Up , typename _Ep >
_GLIBCXX23_CONSTEXPR bool operator> (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _Tp , typename _Dp >
_GLIBCXX23_CONSTEXPR bool operator> (const unique_ptr< _Tp, _Dp > &__x, nullptr_t)
template<typename _Tp >
_Expr< _BinClos< __greater, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __greater, _Tp >::result_type > operator> (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __greater, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __greater, _Tp >::result_type > operator> (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__greater, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__greater, typename _Dom::value_type >::result_type > operator> (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename... _Types>
constexpr bool operator> (const variant< _Types... > &__lhs, const variant< _Types... > &__rhs)
template<typename _Tp , typename _Alloc >
bool operator> (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
constexpr bool operator> (monostate, monostate) noexcept
template<typename _Tp >
constexpr bool operator> (nullopt_t, const optional< _Tp > &) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator> (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _Tp , typename _Dp >
_GLIBCXX23_CONSTEXPR bool operator> (nullptr_t, const unique_ptr< _Tp, _Dp > &__x)
bool operator> (thread::id __x, thread::id __y) noexcept
template<typename _CharT , typename _Traits >
constexpr bool operator>= (__type_identity_t< basic_string_view< _CharT, _Traits >> __x, basic_string_view< _CharT, _Traits > __y) noexcept
template<typename _CharT , typename _Traits >
constexpr bool operator>= (basic_string_view< _CharT, _Traits > __x, __type_identity_t< basic_string_view< _CharT, _Traits >> __y) noexcept
template<typename _CharT , typename _Traits >
constexpr bool operator>= (basic_string_view< _CharT, _Traits > __x, basic_string_view< _CharT, _Traits > __y) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator>= (const __shared_ptr< _Tp, _Lp > &__a, nullptr_t) noexcept
template<typename _Tp1 , typename _Tp2 , _Lock_policy _Lp>
bool operator>= (const __shared_ptr< _Tp1, _Lp > &__a, const __shared_ptr< _Tp2, _Lp > &__b) noexcept
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator>= (const _CharT *__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs)
template<class _Dom >
_Expr< _BinClos< struct std::__greater_equal, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__greater_equal, typename _Dom::value_type >::result_type > operator>= (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__greater_equal, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__greater_equal, typename _Dom::value_type >::result_type > operator>= (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__greater_equal, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__greater_equal, typename _Dom1::value_type >::result_type > operator>= (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<typename _Tp , typename _Up >
constexpr auto operator>= (const _Up &__lhs, const optional< _Tp > &__rhs) -> __optional_ge_t< _Up, _Tp >
template<typename _Tp , std::size_t _Nm>
constexpr bool operator>= (const array< _Tp, _Nm > &__one, const array< _Tp, _Nm > &__two)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator>= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc >
bool operator>= (const basic_string< _CharT, _Traits, _Alloc > &__lhs, const basic_string< _CharT, _Traits, _Alloc > &__rhs) noexcept
template<typename _Tp , typename _Alloc >
bool operator>= (const deque< _Tp, _Alloc > &__x, const deque< _Tp, _Alloc > &__y)
template<typename _Tp , typename _Alloc >
bool operator>= (const forward_list< _Tp, _Alloc > &__lx, const forward_list< _Tp, _Alloc > &__ly)
template<typename _Tp , typename _Alloc >
bool operator>= (const list< _Tp, _Alloc > &__x, const list< _Tp, _Alloc > &__y)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator>= (const map< _Key, _Tp, _Compare, _Alloc > &__x, const map< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Iterator >
constexpr bool operator>= (const move_iterator< _Iterator > &__x, const move_iterator< _Iterator > &__y)
template<typename _IteratorL , typename _IteratorR >
constexpr bool operator>= (const move_iterator< _IteratorL > &__x, const move_iterator< _IteratorR > &__y) requires requires
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
bool operator>= (const multimap< _Key, _Tp, _Compare, _Alloc > &__x, const multimap< _Key, _Tp, _Compare, _Alloc > &__y)
template<typename _Key , typename _Compare , typename _Alloc >
bool operator>= (const multiset< _Key, _Compare, _Alloc > &__x, const multiset< _Key, _Compare, _Alloc > &__y)
template<typename _Tp >
constexpr bool operator>= (const optional< _Tp > &, nullopt_t) noexcept
template<typename _Tp , typename _Up >
constexpr auto operator>= (const optional< _Tp > &__lhs, const _Up &__rhs) -> __optional_ge_t< _Tp, _Up >
template<typename _Tp , typename _Up >
constexpr auto operator>= (const optional< _Tp > &__lhs, const optional< _Up > &__rhs) -> __optional_ge_t< _Tp, _Up >
template<typename _Tp , typename _Seq >
bool operator>= (const queue< _Tp, _Seq > &__x, const queue< _Tp, _Seq > &__y)
template<typename _IteratorL , typename _IteratorR >
constexpr bool operator>= (const reverse_iterator< _IteratorL > &__x, const reverse_iterator< _IteratorR > &__y) requires requires
template<typename _Key , typename _Compare , typename _Alloc >
bool operator>= (const set< _Key, _Compare, _Alloc > &__x, const set< _Key, _Compare, _Alloc > &__y)
template<typename _Tp , typename _Seq >
bool operator>= (const stack< _Tp, _Seq > &__x, const stack< _Tp, _Seq > &__y)
template<typename... _TElements, typename... _UElements>
constexpr bool operator>= (const tuple< _TElements... > &__t, const tuple< _UElements... > &__u)
template<class _Dom >
_Expr< _BinClos< struct std::__greater_equal, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__greater_equal, typename _Dom::value_type >::result_type > operator>= (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __greater_equal, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __greater_equal, _Tp >::result_type > operator>= (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp , typename _Dp , typename _Up , typename _Ep >
_GLIBCXX23_CONSTEXPR bool operator>= (const unique_ptr< _Tp, _Dp > &__x, const unique_ptr< _Up, _Ep > &__y)
template<typename _Tp , typename _Dp >
_GLIBCXX23_CONSTEXPR bool operator>= (const unique_ptr< _Tp, _Dp > &__x, nullptr_t)
template<typename _Tp >
_Expr< _BinClos< __greater_equal, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __greater_equal, _Tp >::result_type > operator>= (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __greater_equal, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __greater_equal, _Tp >::result_type > operator>= (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__greater_equal, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__greater_equal, typename _Dom::value_type >::result_type > operator>= (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename... _Types>
constexpr bool operator>= (const variant< _Types... > &__lhs, const variant< _Types... > &__rhs)
template<typename _Tp , typename _Alloc >
bool operator>= (const vector< _Tp, _Alloc > &__x, const vector< _Tp, _Alloc > &__y)
constexpr bool operator>= (monostate, monostate) noexcept
template<typename _Tp >
constexpr bool operator>= (nullopt_t, const optional< _Tp > &__rhs) noexcept
template<typename _Tp , _Lock_policy _Lp>
bool operator>= (nullptr_t, const __shared_ptr< _Tp, _Lp > &__a) noexcept
template<typename _Tp , typename _Dp >
bool operator>= (nullptr_t, const unique_ptr< _Tp, _Dp > &__x)
bool operator>= (thread::id __x, thread::id __y) noexcept
template<typename _Istream , typename _Tp >
__rvalue_stream_extraction_t< _Istream, _Tp > operator>> (_Istream &&__is, _Tp &&__x)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > &__str)
template<typename _CharT , typename _Traits , typename _MoneyT >
basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, _Get_money< _MoneyT > __f)
template<typename _CharT , typename _Traits >
basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, _Get_time< _CharT > __f)
template<typename _CharT , typename _Traits >
basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, _Resetiosflags __f)
template<typename _CharT , typename _Traits >
basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, _Setbase __f)
template<typename _CharT , typename _Traits >
basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, _Setfill< _CharT > __f)
template<typename _CharT , typename _Traits >
basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, _Setiosflags __f)
template<typename _CharT , typename _Traits >
basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, _Setprecision __f)
template<typename _CharT , typename _Traits >
basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, _Setw __f)
template<typename _CharT , typename _Traits , typename _Alloc >
basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, basic_string< _CharT, _Traits, _Alloc > &__str)
template<typename _Tp , typename _CharT , class _Traits >
basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__is, complex< _Tp > &__x)
template<>
basic_istream< char > & operator>> (basic_istream< char > &__is, basic_string< char > &__str)
template<typename _IntegerType >
constexpr __byte_op_t< _IntegerType > operator>> (byte __b, _IntegerType __shift) noexcept
template<class _Dom >
_Expr< _BinClos< struct std::__shift_right, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__shift_right, typename _Dom::value_type >::result_type > operator>> (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__shift_right, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__shift_right, typename _Dom::value_type >::result_type > operator>> (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__shift_right, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__shift_right, typename _Dom1::value_type >::result_type > operator>> (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__shift_right, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__shift_right, typename _Dom::value_type >::result_type > operator>> (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __shift_right, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __shift_right, _Tp >::result_type > operator>> (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __shift_right, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __shift_right, _Tp >::result_type > operator>> (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __shift_right, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __shift_right, _Tp >::result_type > operator>> (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__shift_right, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__shift_right, typename _Dom::value_type >::result_type > operator>> (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _IntType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &, std::uniform_int_distribution< _IntType > &)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &, std::uniform_real_distribution< _RealType > &)
template<typename _IntType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, binomial_distribution< _IntType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, chi_squared_distribution< _RealType > &__x)
template<typename _RandomNumberEngine , size_t __p, size_t __r, typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, discard_block_engine< _RandomNumberEngine, __p, __r > &__x)
template<typename _IntType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, discrete_distribution< _IntType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, fisher_f_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, gamma_distribution< _RealType > &__x)
template<typename _UIntType , _UIntType __a, _UIntType __c, _UIntType __m, typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, linear_congruential_engine< _UIntType, __a, __c, __m > &__lcr)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, lognormal_distribution< _RealType > &__x)
template<typename _UIntType , size_t __w, size_t __n, size_t __m, size_t __r, _UIntType __a, size_t __u, _UIntType __d, size_t __s, _UIntType __b, size_t __t, _UIntType __c, size_t __l, _UIntType __f, typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, mersenne_twister_engine< _UIntType, __w, __n, __m, __r, __a, __u, __d, __s, __b, __t, __c, __l, __f > &__x)
template<typename _IntType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, negative_binomial_distribution< _IntType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, normal_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, piecewise_constant_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, piecewise_linear_distribution< _RealType > &__x)
template<typename _IntType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, poisson_distribution< _IntType > &__x)
template<typename _RandomNumberEngine , size_t __k, typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, shuffle_order_engine< _RandomNumberEngine, __k > &__x)
template<typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::bernoulli_distribution &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::cauchy_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::exponential_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::extreme_value_distribution< _RealType > &__x)
template<typename _IntType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::geometric_distribution< _IntType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::weibull_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, student_t_distribution< _RealType > &__x)
template<typename _UIntType , size_t __w, size_t __s, size_t __r, typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, subtract_with_carry_engine< _UIntType, __w, __s, __r > &__x)
template<typename _IntegerType >
constexpr __byte_op_t< _IntegerType > & operator>>= (byte &__b, _IntegerType __shift) noexcept
constexpr _Ios_Fmtflags operator^ (_Ios_Fmtflags __a, _Ios_Fmtflags __b)
constexpr _Ios_Iostate operator^ (_Ios_Iostate __a, _Ios_Iostate __b)
constexpr _Ios_Openmode operator^ (_Ios_Openmode __a, _Ios_Openmode __b)
constexpr byte operator^ (byte __l, byte __r) noexcept
constexpr chars_format operator^ (chars_format __lhs, chars_format __rhs) noexcept
template<class _Dom >
_Expr< _BinClos< struct std::__bitwise_xor, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__bitwise_xor, typename _Dom::value_type >::result_type > operator^ (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__bitwise_xor, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__bitwise_xor, typename _Dom::value_type >::result_type > operator^ (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__bitwise_xor, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__bitwise_xor, typename _Dom1::value_type >::result_type > operator^ (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__bitwise_xor, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__bitwise_xor, typename _Dom::value_type >::result_type > operator^ (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __bitwise_xor, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __bitwise_xor, _Tp >::result_type > operator^ (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __bitwise_xor, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __bitwise_xor, _Tp >::result_type > operator^ (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __bitwise_xor, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __bitwise_xor, _Tp >::result_type > operator^ (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__bitwise_xor, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__bitwise_xor, typename _Dom::value_type >::result_type > operator^ (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
constexpr launch operator^ (launch __x, launch __y) noexcept
const _Ios_Fmtflags & operator^= (_Ios_Fmtflags &__a, _Ios_Fmtflags __b)
const _Ios_Iostate & operator^= (_Ios_Iostate &__a, _Ios_Iostate __b)
const _Ios_Openmode & operator^= (_Ios_Openmode &__a, _Ios_Openmode __b)
constexpr byte & operator^= (byte &__l, byte __r) noexcept
constexpr chars_format & operator^= (chars_format &__lhs, chars_format __rhs) noexcept
launch & operator^= (launch &__x, launch __y) noexcept
constexpr _Ios_Fmtflags operator| (_Ios_Fmtflags __a, _Ios_Fmtflags __b)
constexpr _Ios_Iostate operator| (_Ios_Iostate __a, _Ios_Iostate __b)
constexpr _Ios_Openmode operator| (_Ios_Openmode __a, _Ios_Openmode __b)
constexpr byte operator| (byte __l, byte __r) noexcept
constexpr chars_format operator| (chars_format __lhs, chars_format __rhs) noexcept
template<class _Dom >
_Expr< _BinClos< struct std::__bitwise_or, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__bitwise_or, typename _Dom::value_type >::result_type > operator| (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__bitwise_or, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__bitwise_or, typename _Dom::value_type >::result_type > operator| (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__bitwise_or, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__bitwise_or, typename _Dom1::value_type >::result_type > operator| (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__bitwise_or, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__bitwise_or, typename _Dom::value_type >::result_type > operator| (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __bitwise_or, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __bitwise_or, _Tp >::result_type > operator| (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __bitwise_or, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __bitwise_or, _Tp >::result_type > operator| (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __bitwise_or, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __bitwise_or, _Tp >::result_type > operator| (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__bitwise_or, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__bitwise_or, typename _Dom::value_type >::result_type > operator| (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
constexpr launch operator| (launch __x, launch __y) noexcept
constexpr memory_order operator| (memory_order __m, __memory_order_modifier __mod)
const _Ios_Fmtflags & operator|= (_Ios_Fmtflags &__a, _Ios_Fmtflags __b)
const _Ios_Iostate & operator|= (_Ios_Iostate &__a, _Ios_Iostate __b)
const _Ios_Openmode & operator|= (_Ios_Openmode &__a, _Ios_Openmode __b)
constexpr byte & operator|= (byte &__l, byte __r) noexcept
constexpr chars_format & operator|= (chars_format &__lhs, chars_format __rhs) noexcept
launch & operator|= (launch &__x, launch __y) noexcept
template<class _Dom >
_Expr< _BinClos< struct std::__logical_or, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename __fun< struct std::__logical_or, typename _Dom::value_type >::result_type > operator|| (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom >
_Expr< _BinClos< struct std::__logical_or, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename __fun< struct std::__logical_or, typename _Dom::value_type >::result_type > operator|| (const _Expr< _Dom, typename _Dom::value_type > &__v, const typename _Dom::value_type &__t)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::__logical_or, _Expr, _Expr, _Dom1, _Dom2 >, typename __fun< struct std::__logical_or, typename _Dom1::value_type >::result_type > operator|| (const _Expr< _Dom1, typename _Dom1::value_type > &__v, const _Expr< _Dom2, typename _Dom2::value_type > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__logical_or, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__logical_or, typename _Dom::value_type >::result_type > operator|| (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__v)
template<typename _Tp >
_Expr< _BinClos< __logical_or, _Constant, _ValArray, _Tp, _Tp >, typename __fun< __logical_or, _Tp >::result_type > operator|| (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< __logical_or, _ValArray, _Constant, _Tp, _Tp >, typename __fun< __logical_or, _Tp >::result_type > operator|| (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< __logical_or, _ValArray, _ValArray, _Tp, _Tp >, typename __fun< __logical_or, _Tp >::result_type > operator|| (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::__logical_or, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename __fun< struct std::__logical_or, typename _Dom::value_type >::result_type > operator|| (const valarray< typename _Dom::value_type > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
constexpr _Ios_Fmtflags operator~ (_Ios_Fmtflags __a)
constexpr _Ios_Iostate operator~ (_Ios_Iostate __a)
constexpr _Ios_Openmode operator~ (_Ios_Openmode __a)
constexpr byte operator~ (byte __b) noexcept
constexpr chars_format operator~ (chars_format __fmt) noexcept
constexpr launch operator~ (launch __x) noexcept
template<typename _Tp >
optional (_Tp) -> optional< _Tp >
template<typename _Fun , typename _Signature = typename __function_guide_helper<decltype(&_Fun::operator())>::type>
packaged_task (_Fun) -> packaged_task< _Signature >
template<typename _Res , typename... _ArgTypes>
packaged_task (_Res(*)(_ArgTypes...)) -> packaged_task< _Res(_ArgTypes...)>
template<typename _RAIter >
constexpr void partial_sort (_RAIter, _RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
constexpr void partial_sort (_RAIter, _RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator >
constexpr void partial_sort (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
constexpr void partial_sort (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last, _Compare __comp)
template<typename _IIter , typename _RAIter >
constexpr _RAIter partial_sort_copy (_IIter, _IIter, _RAIter, _RAIter)
template<typename _IIter , typename _RAIter , typename _Compare >
constexpr _RAIter partial_sort_copy (_IIter, _IIter, _RAIter, _RAIter, _Compare)
template<typename _InputIterator , typename _RandomAccessIterator >
constexpr _RandomAccessIterator partial_sort_copy (_InputIterator __first, _InputIterator __last, _RandomAccessIterator __result_first, _RandomAccessIterator __result_last)
template<typename _InputIterator , typename _RandomAccessIterator , typename _Compare >
constexpr _RandomAccessIterator partial_sort_copy (_InputIterator __first, _InputIterator __last, _RandomAccessIterator __result_first, _RandomAccessIterator __result_last, _Compare __comp)
template<typename _InputIterator , typename _OutputIterator >
constexpr _OutputIterator partial_sum (_InputIterator __first, _InputIterator __last, _OutputIterator __result)
template<typename _InputIterator , typename _OutputIterator , typename _BinaryOperation >
constexpr _OutputIterator partial_sum (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryOperation __binary_op)
template<typename _BIter , typename _Predicate >
constexpr _BIter partition (_BIter, _BIter, _Predicate)
template<typename _ForwardIterator , typename _Predicate >
constexpr _ForwardIterator partition (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred)
template<typename _IIter , typename _OIter1 , typename _OIter2 , typename _Predicate >
constexpr pair< _OIter1, _OIter2 > partition_copy (_IIter, _IIter, _OIter1, _OIter2, _Predicate)
template<typename _InputIterator , typename _OutputIterator1 , typename _OutputIterator2 , typename _Predicate >
constexpr pair< _OutputIterator1, _OutputIterator2 > partition_copy (_InputIterator __first, _InputIterator __last, _OutputIterator1 __out_true, _OutputIterator2 __out_false, _Predicate __pred)
template<typename _FIter , typename _Predicate >
constexpr _FIter partition_point (_FIter, _FIter, _Predicate)
template<typename _ForwardIterator , typename _Predicate >
constexpr _ForwardIterator partition_point (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred)
template<typename _Tp >
complex< _Tp > polar (const _Tp &, const _Tp &=0)
template<typename _RAIter >
constexpr void pop_heap (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
constexpr void pop_heap (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator >
constexpr void pop_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
constexpr void pop_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _Tp >
constexpr _If_is_unsigned_integer< _Tp, int > popcount (_Tp __x) noexcept
template<typename _Tp , typename _Up >
constexpr __gnu_cxx::__promote_2< _Tp, _Up >::__type pow (_Tp __x, _Up __y)
template<class _Dom >
_Expr< _BinClos< struct std::_Pow, _Expr, _Constant, _Dom, typename _Dom::value_type >, typename _Dom::value_type > pow (const _Expr< _Dom, typename _Dom::value_type > &__e, const typename _Dom::value_type &__t)
template<class _Dom >
_Expr< _BinClos< struct std::_Pow, _Expr, _ValArray, _Dom, typename _Dom::value_type >, typename _Dom::value_type > pow (const _Expr< _Dom, typename _Dom::value_type > &__e, const valarray< typename _Dom::value_type > &__v)
template<class _Dom1 , class _Dom2 >
_Expr< _BinClos< struct std::_Pow, _Expr, _Expr, _Dom1, _Dom2 >, typename _Dom1::value_type > pow (const _Expr< _Dom1, typename _Dom1::value_type > &__e1, const _Expr< _Dom2, typename _Dom2::value_type > &__e2)
template<typename _Tp >
complex< _Tp > pow (const _Tp &, const complex< _Tp > &)
template<typename _Tp , typename _Up >
std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > pow (const _Tp &__x, const std::complex< _Up > &__y)
template<typename _Tp >
complex< _Tp > pow (const complex< _Tp > &, const _Tp &)
template<typename _Tp >
complex< _Tp > pow (const complex< _Tp > &, const complex< _Tp > &)
template<typename _Tp >
complex< _Tp > pow (const complex< _Tp > &, int)
template<typename _Tp , typename _Up >
std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > pow (const std::complex< _Tp > &__x, const _Up &__y)
template<typename _Tp , typename _Up >
std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > pow (const std::complex< _Tp > &__x, const std::complex< _Up > &__y)
template<class _Dom >
_Expr< _BinClos< struct std::_Pow, _Constant, _Expr, typename _Dom::value_type, _Dom >, typename _Dom::value_type > pow (const typename _Dom::value_type &__t, const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
_Expr< _BinClos< struct std::_Pow, _Constant, _ValArray, _Tp, _Tp >, _Tp > pow (const typename valarray< _Tp >::value_type &__t, const valarray< _Tp > &__v)
template<typename _Tp >
_Expr< _BinClos< struct std::_Pow, _ValArray, _Constant, _Tp, _Tp >, _Tp > pow (const valarray< _Tp > &__v, const typename valarray< _Tp >::value_type &__t)
template<typename _Tp >
_Expr< _BinClos< struct std::_Pow, _ValArray, _ValArray, _Tp, _Tp >, _Tp > pow (const valarray< _Tp > &__v, const valarray< _Tp > &__w)
template<class _Dom >
_Expr< _BinClos< struct std::_Pow, _ValArray, _Expr, typename _Dom::value_type, _Dom >, typename _Dom::value_type > pow (const valarray< typename _Dom::valarray > &__v, const _Expr< _Dom, typename _Dom::value_type > &__e)
constexpr float pow (float __x, float __y)
constexpr long double pow (long double __x, long double __y)
template<typename _BidirectionalIterator >
constexpr _BidirectionalIterator prev (_BidirectionalIterator __x, typename iterator_traits< _BidirectionalIterator >::difference_type __n=1)
template<typename _BidirectionalIterator >
constexpr bool prev_permutation (_BidirectionalIterator __first, _BidirectionalIterator __last)
template<typename _BidirectionalIterator , typename _Compare >
constexpr bool prev_permutation (_BidirectionalIterator __first, _BidirectionalIterator __last, _Compare __comp)
template<typename _BIter >
constexpr bool prev_permutation (_BIter, _BIter)
template<typename _BIter , typename _Compare >
constexpr bool prev_permutation (_BIter, _BIter, _Compare)
template<typename _Compare , typename _Container , typename = _RequireNotAllocator<_Compare>, typename = _RequireNotAllocator<_Container>>
priority_queue (_Compare, _Container) -> priority_queue< typename _Container::value_type, _Container, _Compare >
template<typename _Compare , typename _Container , typename _Allocator , typename = _RequireNotAllocator<_Compare>, typename = _RequireNotAllocator<_Container>>
priority_queue (_Compare, _Container, _Allocator) -> priority_queue< typename _Container::value_type, _Container, _Compare >
template<typename _InputIterator , typename _ValT = typename iterator_traits<_InputIterator>::value_type, typename _Compare = less<_ValT>, typename _Container = vector<_ValT>, typename = _RequireInputIter<_InputIterator>, typename = _RequireNotAllocator<_Compare>, typename = _RequireNotAllocator<_Container>>
priority_queue (_InputIterator, _InputIterator, _Compare=_Compare(), _Container=_Container()) -> priority_queue< _ValT, _Container, _Compare >
template<typename _Tp >
std::complex< typename __gnu_cxx::__promote< _Tp >::__type > proj (_Tp __x)
template<typename _Tp >
std::complex< _Tp > proj (const std::complex< _Tp > &)
template<typename _Arg , typename _Result >
pointer_to_unary_function< _Arg, _Result > ptr_fun (_Result(*__x)(_Arg))
template<typename _Arg1 , typename _Arg2 , typename _Result >
pointer_to_binary_function< _Arg1, _Arg2, _Result > ptr_fun (_Result(*__x)(_Arg1, _Arg2))
template<typename _RAIter >
constexpr void push_heap (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
constexpr void push_heap (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator >
constexpr void push_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
constexpr void push_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _MoneyT >
_Put_money< _MoneyT > put_money (const _MoneyT &__mon, bool __intl=false)
template<typename _CharT >
_Put_time< _CharT > put_time (const std::tm *__tmb, const _CharT *__fmt)
template<typename _Container , typename = _RequireNotAllocator<_Container>>
queue (_Container) -> queue< typename _Container::value_type, _Container >
template<typename _Container , typename _Allocator , typename = _RequireNotAllocator<_Container>>
queue (_Container, _Allocator) -> queue< typename _Container::value_type, _Container >
template<typename _CharT , typename _Traits , typename _Alloc >
auto quoted (basic_string< _CharT, _Traits, _Alloc > &__string, _CharT __delim=_CharT('"'), _CharT __escape = _CharT('\\'))
template<typename _CharT , typename _Traits >
auto quoted (basic_string_view< _CharT, _Traits > __sv, _CharT __delim=_CharT('"'), _CharT __escape = _CharT('\\'))
template<typename _CharT >
auto quoted (const _CharT *__string, _CharT __delim=_CharT('"'), _CharT __escape = _CharT('\\'))
template<typename _CharT , typename _Traits , typename _Alloc >
auto quoted (const basic_string< _CharT, _Traits, _Alloc > &__string, _CharT __delim=_CharT('"'), _CharT __escape = _CharT('\\'))
template<typename _RAIter >
void random_shuffle (_RAIter, _RAIter)
template<typename _RAIter , typename _Generator >
void random_shuffle (_RAIter, _RAIter, _Generator &&)
template<typename _RandomAccessIterator >
void random_shuffle (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _RandomNumberGenerator >
void random_shuffle (_RandomAccessIterator __first, _RandomAccessIterator __last, _RandomNumberGenerator &&__rand)
template<typename _Container >
constexpr auto rbegin (_Container &__cont) -> decltype(__cont.rbegin())
template<typename _Tp , size_t _Nm>
constexpr reverse_iterator< _Tp * > rbegin (_Tp(&__arr)[_Nm]) noexcept
template<typename _Container >
constexpr auto rbegin (const _Container &__cont) -> decltype(__cont.rbegin())
template<typename _Tp >
constexpr reverse_iterator< const _Tp * > rbegin (initializer_list< _Tp > __il) noexcept
template<typename _Tp >
constexpr __gnu_cxx::__promote< _Tp >::__type real (_Tp __x)
template<typename _Tp >
constexpr _Tp real (const complex< _Tp > &__z)
template<typename _InputIterator >
constexpr iterator_traits< _InputIterator >::value_type reduce (_InputIterator __first, _InputIterator __last)
template<typename _InputIterator , typename _Tp >
constexpr _Tp reduce (_InputIterator __first, _InputIterator __last, _Tp __init)
template<typename _InputIterator , typename _Tp , typename _BinaryOperation >
constexpr _Tp reduce (_InputIterator __first, _InputIterator __last, _Tp __init, _BinaryOperation __binary_op)
template<typename _Tp >
reference_wrapper (_Tp &) -> reference_wrapper< _Tp >
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp>
__shared_ptr< _Tp, _Lp > reinterpret_pointer_cast (const __shared_ptr< _Tp1, _Lp > &__r) noexcept
template<typename _FIter , typename _Tp >
constexpr _FIter remove (_FIter, _FIter, const _Tp &)
template<typename _ForwardIterator , typename _Tp >
constexpr _ForwardIterator remove (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__value)
template<typename _IIter , typename _OIter , typename _Tp >
constexpr _OIter remove_copy (_IIter, _IIter, _OIter, const _Tp &)
template<typename _InputIterator , typename _OutputIterator , typename _Tp >
constexpr _OutputIterator remove_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, const _Tp &__value)
template<typename _IIter , typename _OIter , typename _Predicate >
constexpr _OIter remove_copy_if (_IIter, _IIter, _OIter, _Predicate)
template<typename _InputIterator , typename _OutputIterator , typename _Predicate >
constexpr _OutputIterator remove_copy_if (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _Predicate __pred)
template<typename _FIter , typename _Predicate >
constexpr _FIter remove_if (_FIter, _FIter, _Predicate)
template<typename _ForwardIterator , typename _Predicate >
constexpr _ForwardIterator remove_if (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred)
template<typename _Container >
constexpr auto rend (_Container &__cont) -> decltype(__cont.rend())
template<typename _Tp , size_t _Nm>
constexpr reverse_iterator< _Tp * > rend (_Tp(&__arr)[_Nm]) noexcept
template<typename _Container >
constexpr auto rend (const _Container &__cont) -> decltype(__cont.rend())
template<typename _Tp >
constexpr reverse_iterator< const _Tp * > rend (initializer_list< _Tp > __il) noexcept
template<typename _FIter , typename _Tp >
constexpr void replace (_FIter, _FIter, const _Tp &, const _Tp &)
template<typename _ForwardIterator , typename _Tp >
constexpr void replace (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__old_value, const _Tp &__new_value)
template<typename _IIter , typename _OIter , typename _Tp >
constexpr _OIter replace_copy (_IIter, _IIter, _OIter, const _Tp &, const _Tp &)
template<typename _InputIterator , typename _OutputIterator , typename _Tp >
constexpr _OutputIterator replace_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, const _Tp &__old_value, const _Tp &__new_value)
template<typename _InputIterator , typename _OutputIterator , typename _Predicate , typename _Tp >
constexpr _OutputIterator replace_copy_if (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _Predicate __pred, const _Tp &__new_value)
template<typename _Iter , typename _OIter , typename _Predicate , typename _Tp >
constexpr _OIter replace_copy_if (_Iter, _Iter, _OIter, _Predicate, const _Tp &)
template<typename _FIter , typename _Predicate , typename _Tp >
constexpr void replace_if (_FIter, _FIter, _Predicate, const _Tp &)
template<typename _ForwardIterator , typename _Predicate , typename _Tp >
constexpr void replace_if (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, const _Tp &__new_value)
template<typename _Type , size_t _Extent>
requires (!is_const_v< _Type >) inline span< byte
template<typename _Tp >
requires (!requires { typename _Tp::difference_type;} &&requires(const _Tp &__a, const _Tp &__b) { { __a - __b } -> integral;}) struct incrementable_traits< _Tp >
template<input_or_output_iterator _It, sentinel_for< _It > _Sent>
requires (!same_as< _It, _Sent >) &&copyable< _It > class common_iterator
template<typename _Iterator1 , typename _Iterator2 >
requires (!sized_sentinel_for< _Iterator1, _Iterator2 >) inline const expr bool disable_sized_sentinel_for< reverse_iterator< _Iterator1 >
template<typename _Is , typename _Tp >
requires __derived_from_ios_base< _Is > && requires (_Is &__is, _Tp &&__t)
template<size_t _Np, typename _Tp0 , typename _Tp1 , typename _Tp2 , typename... _Rest>
requires (_Np >=3) struct _Nth_type< _Np
template<typename _Os , typename _Tp >
requires __derived_from_ios_base< _Os > && requires (_Os &__os, const _Tp &__t)
template<typename _Fn , typename... _Is>
requires (indirectly_readable< _Is > &&...) &&invocable< _Fn
_Resetiosflags resetiosflags (ios_base::fmtflags __mask)
void rethrow_exception (exception_ptr)
template<typename _Ex >
void rethrow_if_nested (const _Ex &__ex)
template<typename _Tp >
void return_temporary_buffer (_Tp *__p)
template<typename _BidirectionalIterator >
constexpr void reverse (_BidirectionalIterator __first, _BidirectionalIterator __last)
template<typename _BIter >
constexpr void reverse (_BIter, _BIter)
template<typename _BidirectionalIterator , typename _OutputIterator >
constexpr _OutputIterator reverse_copy (_BidirectionalIterator __first, _BidirectionalIterator __last, _OutputIterator __result)
template<typename _BIter , typename _OIter >
constexpr _OIter reverse_copy (_BIter, _BIter, _OIter)
template<typename _Tp >
__gnu_cxx::__promote< _Tp >::__type riemann_zeta (_Tp __s)
float riemann_zetaf (float __s)
long double riemann_zetal (long double __s)
ios_base & right (ios_base &__base)
template<typename _FIter >
constexpr _FIter rotate (_FIter, _FIter, _FIter)
template<typename _ForwardIterator >
constexpr _ForwardIterator rotate (_ForwardIterator __first, _ForwardIterator __middle, _ForwardIterator __last)
template<typename _FIter , typename _OIter >
constexpr _OIter rotate_copy (_FIter, _FIter, _FIter, _OIter)
template<typename _ForwardIterator , typename _OutputIterator >
constexpr _OutputIterator rotate_copy (_ForwardIterator __first, _ForwardIterator __middle, _ForwardIterator __last, _OutputIterator __result)
template<typename _PopulationIterator , typename _SampleIterator , typename _Distance , typename _UniformRandomBitGenerator >
_SampleIterator sample (_PopulationIterator __first, _PopulationIterator __last, _SampleIterator __out, _Distance __n, _UniformRandomBitGenerator &&__g)
ios_base & scientific (ios_base &__base)
template<typename _FIter1 , typename _FIter2 >
constexpr _FIter1 search (_FIter1, _FIter1, _FIter2, _FIter2)
template<typename _FIter1 , typename _FIter2 , typename _BinaryPredicate >
constexpr _FIter1 search (_FIter1, _FIter1, _FIter2, _FIter2, _BinaryPredicate)
template<typename _ForwardIterator , typename _Searcher >
constexpr _ForwardIterator search (_ForwardIterator __first, _ForwardIterator __last, const _Searcher &__searcher)
template<typename _ForwardIterator1 , typename _ForwardIterator2 >
constexpr _ForwardIterator1 search (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2)
template<typename _ForwardIterator1 , typename _ForwardIterator2 , typename _BinaryPredicate >
constexpr _ForwardIterator1 search (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2, _ForwardIterator2 __last2, _BinaryPredicate __predicate)
template<typename _FIter , typename _Size , typename _Tp >
constexpr _FIter search_n (_FIter, _FIter, _Size, const _Tp &)
template<typename _FIter , typename _Size , typename _Tp , typename _BinaryPredicate >
constexpr _FIter search_n (_FIter, _FIter, _Size, const _Tp &, _BinaryPredicate)
template<typename _ForwardIterator , typename _Integer , typename _Tp >
constexpr _ForwardIterator search_n (_ForwardIterator __first, _ForwardIterator __last, _Integer __count, const _Tp &__val)
template<typename _ForwardIterator , typename _Integer , typename _Tp , typename _BinaryPredicate >
constexpr _ForwardIterator search_n (_ForwardIterator __first, _ForwardIterator __last, _Integer __count, const _Tp &__val, _BinaryPredicate __binary_pred)
template<typename _InputIterator , typename _Allocator , typename = _RequireInputIter<_InputIterator>, typename = _RequireAllocator<_Allocator>>
set (_InputIterator, _InputIterator, _Allocator) -> set< typename iterator_traits< _InputIterator >::value_type, less< typename iterator_traits< _InputIterator >::value_type >, _Allocator >
template<typename _InputIterator , typename _Compare = less<typename iterator_traits<_InputIterator>::value_type>, typename _Allocator = allocator<typename iterator_traits<_InputIterator>::value_type>, typename = _RequireInputIter<_InputIterator>, typename = _RequireNotAllocator<_Compare>, typename = _RequireAllocator<_Allocator>>
set (_InputIterator, _InputIterator, _Compare=_Compare(), _Allocator=_Allocator()) -> set< typename iterator_traits< _InputIterator >::value_type, _Compare, _Allocator >
template<typename _Key , typename _Allocator , typename = _RequireAllocator<_Allocator>>
set (initializer_list< _Key >, _Allocator) -> set< _Key, less< _Key >, _Allocator >
template<typename _Key , typename _Compare = less<_Key>, typename _Allocator = allocator<_Key>, typename = _RequireNotAllocator<_Compare>, typename = _RequireAllocator<_Allocator>>
set (initializer_list< _Key >, _Compare=_Compare(), _Allocator=_Allocator()) -> set< _Key, _Compare, _Allocator >
template<typename _IIter1 , typename _IIter2 , typename _OIter >
constexpr _OIter set_difference (_IIter1, _IIter1, _IIter2, _IIter2, _OIter)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _Compare >
constexpr _OIter set_difference (_IIter1, _IIter1, _IIter2, _IIter2, _OIter, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator >
constexpr _OutputIterator set_difference (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
constexpr _OutputIterator set_difference (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
template<typename _IIter1 , typename _IIter2 , typename _OIter >
constexpr _OIter set_intersection (_IIter1, _IIter1, _IIter2, _IIter2, _OIter)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _Compare >
constexpr _OIter set_intersection (_IIter1, _IIter1, _IIter2, _IIter2, _OIter, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator >
constexpr _OutputIterator set_intersection (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
constexpr _OutputIterator set_intersection (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
new_handler set_new_handler (new_handler) throw ()
template<typename _IIter1 , typename _IIter2 , typename _OIter >
constexpr _OIter set_symmetric_difference (_IIter1, _IIter1, _IIter2, _IIter2, _OIter)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _Compare >
constexpr _OIter set_symmetric_difference (_IIter1, _IIter1, _IIter2, _IIter2, _OIter, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator >
constexpr _OutputIterator set_symmetric_difference (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
constexpr _OutputIterator set_symmetric_difference (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
terminate_handler set_terminate (terminate_handler) noexcept
unexpected_handler set_unexpected (unexpected_handler) noexcept
template<typename _IIter1 , typename _IIter2 , typename _OIter >
constexpr _OIter set_union (_IIter1, _IIter1, _IIter2, _IIter2, _OIter)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _Compare >
constexpr _OIter set_union (_IIter1, _IIter1, _IIter2, _IIter2, _OIter, _Compare)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator >
constexpr _OutputIterator set_union (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare >
constexpr _OutputIterator set_union (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
_Setbase setbase (int __base)
template<typename _CharT >
_Setfill< _CharT > setfill (_CharT __c)
_Setiosflags setiosflags (ios_base::fmtflags __mask)
_Setprecision setprecision (int __n)
_Setw setw (int __n)
template<typename _Tp , typename _Del >
shared_ptr (unique_ptr< _Tp, _Del >) -> shared_ptr< _Tp >
template<typename _Tp >
shared_ptr (weak_ptr< _Tp >) -> shared_ptr< _Tp >
template<typename _ForwardIterator >
constexpr _ForwardIterator shift_left (_ForwardIterator __first, _ForwardIterator __last, typename iterator_traits< _ForwardIterator >::difference_type __n)
template<typename _ForwardIterator >
constexpr _ForwardIterator shift_right (_ForwardIterator __first, _ForwardIterator __last, typename iterator_traits< _ForwardIterator >::difference_type __n)
ios_base & showbase (ios_base &__base)
ios_base & showpoint (ios_base &__base)
ios_base & showpos (ios_base &__base)
template<typename _RAIter , typename _UGenerator >
void shuffle (_RAIter, _RAIter, _UGenerator &&)
template<typename _RandomAccessIterator , typename _UniformRandomNumberGenerator >
void shuffle (_RandomAccessIterator __first, _RandomAccessIterator __last, _UniformRandomNumberGenerator &&__g)
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type sin (_Tp __x)
template<class _Dom >
_Expr< _UnClos< struct std::_Sin, _Expr, _Dom >, typename _Dom::value_type > sin (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
complex< _Tp > sin (const complex< _Tp > &)
template<typename _Tp >
_Expr< _UnClos< struct std::_Sin, _ValArray, _Tp >, _Tp > sin (const valarray< _Tp > &__v)
constexpr float sin (float __x)
constexpr long double sin (long double __x)
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type sinh (_Tp __x)
template<class _Dom >
_Expr< _UnClos< struct std::_Sinh, _Expr, _Dom >, typename _Dom::value_type > sinh (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
complex< _Tp > sinh (const complex< _Tp > &)
template<typename _Tp >
_Expr< _UnClos< struct std::_Sinh, _ValArray, _Tp >, _Tp > sinh (const valarray< _Tp > &__v)
constexpr float sinh (float __x)
constexpr long double sinh (long double __x)
template<typename _Container >
constexpr auto size (const _Container &__cont) noexcept(noexcept(__cont.size())) -> decltype(__cont.size())
template<typename _Tp , size_t _Nm>
constexpr size_t size (const _Tp(&)[_Nm]) noexcept
ios_base & skipws (ios_base &__base)
template<typename _RAIter >
constexpr void sort (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
constexpr void sort (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator >
constexpr void sort (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
constexpr void sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _RAIter >
constexpr void sort_heap (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
constexpr void sort_heap (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator >
constexpr void sort_heap (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
constexpr void sort_heap (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<contiguous_iterator _Iter, typename _End >
span (_Iter, _End) -> span< remove_reference_t< iter_reference_t< _Iter >>>
template<ranges::contiguous_range _Range>
span (_Range &&) -> span< remove_reference_t< ranges::range_reference_t< _Range & >>>
template<typename _Type , size_t _ArrayExtent>
span (_Type(&)[_ArrayExtent]) -> span< _Type, _ArrayExtent >
template<typename _Type , size_t _ArrayExtent>
span (array< _Type, _ArrayExtent > &) -> span< _Type, _ArrayExtent >
template<typename _Type , size_t _ArrayExtent>
span (const array< _Type, _ArrayExtent > &) -> span< const _Type, _ArrayExtent >
template<typename _Tp >
__gnu_cxx::__promote< _Tp >::__type sph_bessel (unsigned int __n, _Tp __x)
float sph_besself (unsigned int __n, float __x)
long double sph_bessell (unsigned int __n, long double __x)
template<typename _Tp >
__gnu_cxx::__promote< _Tp >::__type sph_legendre (unsigned int __l, unsigned int __m, _Tp __theta)
float sph_legendref (unsigned int __l, unsigned int __m, float __theta)
long double sph_legendrel (unsigned int __l, unsigned int __m, long double __theta)
template<typename _Tp >
__gnu_cxx::__promote< _Tp >::__type sph_neumann (unsigned int __n, _Tp __x)
float sph_neumannf (unsigned int __n, float __x)
long double sph_neumannl (unsigned int __n, long double __x)
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type sqrt (_Tp __x)
template<class _Dom >
_Expr< _UnClos< struct std::_Sqrt, _Expr, _Dom >, typename _Dom::value_type > sqrt (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
complex< _Tp > sqrt (const complex< _Tp > &)
template<typename _Tp >
_Expr< _UnClos< struct std::_Sqrt, _ValArray, _Tp >, _Tp > sqrt (const valarray< _Tp > &__v)
constexpr float sqrt (float __x)
constexpr long double sqrt (long double __x)
template<typename _Container >
constexpr auto ssize (const _Container &__cont) noexcept(noexcept(__cont.size())) -> common_type_t< ptrdiff_t, make_signed_t< decltype(__cont.size())>>
template<typename _Tp , ptrdiff_t _Num>
constexpr ptrdiff_t ssize (const _Tp(&)[_Num]) noexcept
template<typename _BIter , typename _Predicate >
_BIter stable_partition (_BIter, _BIter, _Predicate)
template<typename _ForwardIterator , typename _Predicate >
_ForwardIterator stable_partition (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred)
template<typename _RAIter >
void stable_sort (_RAIter, _RAIter)
template<typename _RAIter , typename _Compare >
void stable_sort (_RAIter, _RAIter, _Compare)
template<typename _RandomAccessIterator >
void stable_sort (_RandomAccessIterator __first, _RandomAccessIterator __last)
template<typename _RandomAccessIterator , typename _Compare >
void stable_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
template<typename _Container , typename = _RequireNotAllocator<_Container>>
stack (_Container) -> stack< typename _Container::value_type, _Container >
template<typename _Container , typename _Allocator , typename = _RequireNotAllocator<_Container>>
stack (_Container, _Allocator) -> stack< typename _Container::value_type, _Container >
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp>
__shared_ptr< _Tp, _Lp > static_pointer_cast (const __shared_ptr< _Tp1, _Lp > &__r) noexcept
template<typename _Callback >
stop_callback (stop_token, _Callback) -> stop_callback< _Callback >
char * strchr (char *__s, int __n)
char * strpbrk (char *__s1, const char *__s2)
char * strrchr (char *__s, int __n)
char * strstr (char *__s1, const char *__s2)
template<typename _Tp , _Lock_policy _Lp>
void swap (__shared_ptr< _Tp, _Lp > &__a, __shared_ptr< _Tp, _Lp > &__b) noexcept
template<typename _Tp , _Lock_policy _Lp>
void swap (__weak_ptr< _Tp, _Lp > &__a, __weak_ptr< _Tp, _Lp > &__b) noexcept
template<typename _Key , typename _Val , typename _KeyOfValue , typename _Compare , typename _Alloc >
void swap (_Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__x, _Rb_tree< _Key, _Val, _KeyOfValue, _Compare, _Alloc > &__y)
template<typename _Tp >
constexpr _Require< __not_< __is_tuple_like< _Tp > >, is_move_constructible< _Tp >, is_move_assignable< _Tp > > swap (_Tp &, _Tp &) noexcept(__and_< is_nothrow_move_constructible< _Tp >, is_nothrow_move_assignable< _Tp >>::value)
template<typename _Tp >
constexpr enable_if< __and_< __not_< __is_tuple_like< _Tp > >, is_move_constructible< _Tp >, is_move_assignable< _Tp > >::value >::type swap (_Tp &__a, _Tp &__b) noexcept(/*conditional */) is_nothrow_move_assignable< _Tp >>
template<typename _Tp , size_t _Nm>
constexpr enable_if< __is_swappable< _Tp >::value >::type swap (_Tp(&__a)[_Nm], _Tp(&__b)[_Nm]) noexcept(/*conditional */)
template<typename _Tp , size_t _Nm>
constexpr __enable_if_t< __is_swappable< _Tp >::value > swap (_Tp(&__a)[_Nm], _Tp(&__b)[_Nm]) noexcept(__is_nothrow_swappable< _Tp >::value)
void swap (any &__x, any &__y) noexcept
template<typename _Tp , std::size_t _Nm>
enable_if< !__array_traits< _Tp, _Nm >::_Is_swappable::value >::type swap (array< _Tp, _Nm > &, array< _Tp, _Nm > &)=delete
template<typename _Tp , std::size_t _Nm>
constexpr enable_if< __array_traits< _Tp, _Nm >::_Is_swappable::value >::type swap (array< _Tp, _Nm > &__one, array< _Tp, _Nm > &__two) noexcept(noexcept(__one.swap(__two)))
template<class _CharT , class _Traits >
void swap (basic_filebuf< _CharT, _Traits > &__x, basic_filebuf< _CharT, _Traits > &__y)
template<class _CharT , class _Traits >
void swap (basic_fstream< _CharT, _Traits > &__x, basic_fstream< _CharT, _Traits > &__y)
template<class _CharT , class _Traits >
void swap (basic_ifstream< _CharT, _Traits > &__x, basic_ifstream< _CharT, _Traits > &__y)
template<class _CharT , class _Traits , class _Allocator >
void swap (basic_istringstream< _CharT, _Traits, _Allocator > &__x, basic_istringstream< _CharT, _Traits, _Allocator > &__y)
template<class _CharT , class _Traits >
void swap (basic_ofstream< _CharT, _Traits > &__x, basic_ofstream< _CharT, _Traits > &__y)
template<class _CharT , class _Traits , class _Allocator >
void swap (basic_ostringstream< _CharT, _Traits, _Allocator > &__x, basic_ostringstream< _CharT, _Traits, _Allocator > &__y)
template<typename _CharT , typename _Traits , typename _Alloc >
constexpr void swap (basic_string< _CharT, _Traits, _Alloc > &__lhs, basic_string< _CharT, _Traits, _Alloc > &__rhs) noexcept(/*conditional */)
template<class _CharT , class _Traits , class _Allocator >
void swap (basic_stringbuf< _CharT, _Traits, _Allocator > &__x, basic_stringbuf< _CharT, _Traits, _Allocator > &__y) noexcept(noexcept(__x.swap(__y)))
template<class _CharT , class _Traits , class _Allocator >
void swap (basic_stringstream< _CharT, _Traits, _Allocator > &__x, basic_stringstream< _CharT, _Traits, _Allocator > &__y)
template<typename _Tp , typename _Alloc >
void swap (deque< _Tp, _Alloc > &__x, deque< _Tp, _Alloc > &__y) noexcept(/*conditional */)
template<typename _Tp , typename _Alloc >
void swap (forward_list< _Tp, _Alloc > &__lx, forward_list< _Tp, _Alloc > &__ly) noexcept(noexcept(__lx.swap(__ly)))
template<typename _Res , typename... _Args>
void swap (function< _Res(_Args...)> &__x, function< _Res(_Args...)> &__y) noexcept
template<typename _Tp , typename _Alloc >
void swap (list< _Tp, _Alloc > &__x, list< _Tp, _Alloc > &__y) noexcept(/*conditional */)
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
void swap (map< _Key, _Tp, _Compare, _Alloc > &__x, map< _Key, _Tp, _Compare, _Alloc > &__y) noexcept(/*conditional */)
template<typename _Bi_iter , typename _Alloc >
void swap (match_results< _Bi_iter, _Alloc > &__lhs, match_results< _Bi_iter, _Alloc > &__rhs) noexcept
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc >
void swap (multimap< _Key, _Tp, _Compare, _Alloc > &__x, multimap< _Key, _Tp, _Compare, _Alloc > &__y) noexcept(/*conditional */)
template<typename _Key , typename _Compare , typename _Alloc >
void swap (multiset< _Key, _Compare, _Alloc > &__x, multiset< _Key, _Compare, _Alloc > &__y) noexcept(/*conditional */)
template<typename _Tp >
enable_if_t<!(is_move_constructible_v< _Tp > &&is_swappable_v< _Tp >)> swap (optional< _Tp > &, optional< _Tp > &)=delete
template<typename _Tp >
constexpr enable_if_t< is_move_constructible_v< _Tp > &&is_swappable_v< _Tp > > swap (optional< _Tp > &__lhs, optional< _Tp > &__rhs) noexcept(noexcept(__lhs.swap(__rhs)))
template<typename _Res , typename... _ArgTypes>
void swap (packaged_task< _Res(_ArgTypes...)> &__x, packaged_task< _Res(_ArgTypes...)> &__y) noexcept
template<typename _Tp , typename _Sequence , typename _Compare >
enable_if< __and_< __is_swappable< _Sequence >, __is_swappable< _Compare > >::value >::type swap (priority_queue< _Tp, _Sequence, _Compare > &__x, priority_queue< _Tp, _Sequence, _Compare > &__y) noexcept(noexcept(__x.swap(__y)))
template<typename _Res >
void swap (promise< _Res > &__x, promise< _Res > &__y) noexcept
template<typename _Tp , typename _Seq >
enable_if< __is_swappable< _Seq >::value >::type swap (queue< _Tp, _Seq > &__x, queue< _Tp, _Seq > &__y) noexcept(noexcept(__x.swap(__y)))
template<typename _Key , typename _Compare , typename _Alloc >
void swap (set< _Key, _Compare, _Alloc > &__x, set< _Key, _Compare, _Alloc > &__y) noexcept(/*conditional */)
template<typename _Tp , typename _Seq >
enable_if< __is_swappable< _Seq >::value >::type swap (stack< _Tp, _Seq > &__x, stack< _Tp, _Seq > &__y) noexcept(noexcept(__x.swap(__y)))
void swap (thread &__x, thread &__y) noexcept
template<typename... _Elements>
constexpr enable_if<!__and_< __is_swappable< _Elements >... >::value >::type swap (tuple< _Elements... > &, tuple< _Elements... > &)=delete
template<typename... _Elements>
constexpr enable_if< __and_< __is_swappable< _Elements >... >::value >::type swap (tuple< _Elements... > &__x, tuple< _Elements... > &__y) noexcept(noexcept(__x.swap(__y)))
template<typename _Tp , typename _Dp >
enable_if<!__is_swappable< _Dp >::value >::type swap (unique_ptr< _Tp, _Dp > &, unique_ptr< _Tp, _Dp > &)=delete
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc >
void swap (unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc > &__x, unordered_map< _Key, _Tp, _Hash, _Pred, _Alloc > &__y) noexcept(noexcept(__x.swap(__y)))
template<class _Key , class _Tp , class _Hash , class _Pred , class _Alloc >
void swap (unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc > &__x, unordered_multimap< _Key, _Tp, _Hash, _Pred, _Alloc > &__y) noexcept(noexcept(__x.swap(__y)))
template<class _Value , class _Hash , class _Pred , class _Alloc >
void swap (unordered_multiset< _Value, _Hash, _Pred, _Alloc > &__x, unordered_multiset< _Value, _Hash, _Pred, _Alloc > &__y) noexcept(noexcept(__x.swap(__y)))
template<class _Value , class _Hash , class _Pred , class _Alloc >
void swap (unordered_set< _Value, _Hash, _Pred, _Alloc > &__x, unordered_set< _Value, _Hash, _Pred, _Alloc > &__y) noexcept(noexcept(__x.swap(__y)))
template<typename... _Types>
enable_if_t<!((is_move_constructible_v< _Types > &&...) &&(is_swappable_v< _Types > &&...))> swap (variant< _Types... > &, variant< _Types... > &)=delete
template<typename... _Types>
constexpr enable_if_t<(is_move_constructible_v< _Types > &&...) &&(is_swappable_v< _Types > &&...)> swap (variant< _Types... > &__lhs, variant< _Types... > &__rhs) noexcept(noexcept(__lhs.swap(__rhs)))
template<typename _Tp , typename _Alloc >
constexpr void swap (vector< _Tp, _Alloc > &__x, vector< _Tp, _Alloc > &__y) noexcept(/*conditional */)
template<typename _FIter1 , typename _FIter2 >
constexpr _FIter2 swap_ranges (_FIter1, _FIter1, _FIter2)
template<typename _ForwardIterator1 , typename _ForwardIterator2 >
constexpr _ForwardIterator2 swap_ranges (_ForwardIterator1 __first1, _ForwardIterator1 __last1, _ForwardIterator2 __first2)
const error_category & system_category () noexcept
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type tan (_Tp __x)
template<class _Dom >
_Expr< _UnClos< struct std::_Tan, _Expr, _Dom >, typename _Dom::value_type > tan (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
complex< _Tp > tan (const complex< _Tp > &)
template<typename _Tp >
_Expr< _UnClos< struct std::_Tan, _ValArray, _Tp >, _Tp > tan (const valarray< _Tp > &__v)
constexpr float tan (float __x)
constexpr long double tan (long double __x)
template<typename _Tp >
constexpr __gnu_cxx::__enable_if< __is_integer< _Tp >::__value, double >::__type tanh (_Tp __x)
template<class _Dom >
_Expr< _UnClos< struct std::_Tanh, _Expr, _Dom >, typename _Dom::value_type > tanh (const _Expr< _Dom, typename _Dom::value_type > &__e)
template<typename _Tp >
complex< _Tp > tanh (const complex< _Tp > &)
template<typename _Tp >
_Expr< _UnClos< struct std::_Tanh, _ValArray, _Tp >, _Tp > tanh (const valarray< _Tp > &__v)
constexpr float tanh (float __x)
constexpr long double tanh (long double __x)
void terminate () noexcept
template<typename _Tp >
void throw_with_nested (_Tp &&__t)
template<typename... _Elements>
constexpr tuple< _Elements &... > tie (_Elements &... __args) noexcept
template<typename _Tp >
constexpr _Tp * to_address (_Tp *__ptr) noexcept
template<typename _Ptr >
constexpr auto to_address (const _Ptr &__ptr) noexcept
template<typename _Tp , size_t _Nm>
constexpr array< remove_cv_t< _Tp >, _Nm > to_array (_Tp(&&__a)[_Nm]) noexcept(is_nothrow_move_constructible_v< _Tp >)
template<typename _Tp , size_t _Nm>
constexpr array< remove_cv_t< _Tp >, _Nm > to_array (_Tp(&__a)[_Nm]) noexcept(is_nothrow_constructible_v< _Tp, _Tp & >)
to_chars_result to_chars (char *, char *, bool, int=10)=delete
to_chars_result to_chars (char *__first, char *__last, char __value, int __base=10)
to_chars_result to_chars (char *__first, char *__last, signed char __value, int __base=10)
to_chars_result to_chars (char *__first, char *__last, signed int __value, int __base=10)
to_chars_result to_chars (char *__first, char *__last, signed long __value, int __base=10)
to_chars_result to_chars (char *__first, char *__last, signed long long __value, int __base=10)
to_chars_result to_chars (char *__first, char *__last, signed short __value, int __base=10)
to_chars_result to_chars (char *__first, char *__last, unsigned char __value, int __base=10)
to_chars_result to_chars (char *__first, char *__last, unsigned int __value, int __base=10)
to_chars_result to_chars (char *__first, char *__last, unsigned long __value, int __base=10)
to_chars_result to_chars (char *__first, char *__last, unsigned long long __value, int __base=10)
to_chars_result to_chars (char *__first, char *__last, unsigned short __value, int __base=10)
template<typename _IntegerType >
constexpr _IntegerType to_integer (__byte_op_t< _IntegerType > __b) noexcept
string to_string (int __val)
string to_string (long __val)
string to_string (long long __val)
string to_string (unsigned __val)
string to_string (unsigned long __val)
string to_string (unsigned long long __val)
template<typename _CharT >
_CharT tolower (_CharT __c, const locale &__loc)
template<typename _CharT >
_CharT toupper (_CharT __c, const locale &__loc)
template<typename _IIter , typename _OIter , typename _UnaryOperation >
constexpr _OIter transform (_IIter, _IIter, _OIter, _UnaryOperation)
template<typename _IIter1 , typename _IIter2 , typename _OIter , typename _BinaryOperation >
constexpr _OIter transform (_IIter1, _IIter1, _IIter2, _OIter, _BinaryOperation)
template<typename _InputIterator , typename _OutputIterator , typename _UnaryOperation >
constexpr _OutputIterator transform (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _UnaryOperation __unary_op)
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _BinaryOperation >
constexpr _OutputIterator transform (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _OutputIterator __result, _BinaryOperation __binary_op)
template<typename _InputIterator , typename _OutputIterator , typename _Tp , typename _BinaryOperation , typename _UnaryOperation >
constexpr _OutputIterator transform_exclusive_scan (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _Tp __init, _BinaryOperation __binary_op, _UnaryOperation __unary_op)
template<typename _InputIterator , typename _OutputIterator , typename _BinaryOperation , typename _UnaryOperation >
constexpr _OutputIterator transform_inclusive_scan (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryOperation __binary_op, _UnaryOperation __unary_op)
template<typename _InputIterator , typename _OutputIterator , typename _BinaryOperation , typename _UnaryOperation , typename _Tp >
constexpr _OutputIterator transform_inclusive_scan (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryOperation __binary_op, _UnaryOperation __unary_op, _Tp __init)
template<typename _InputIterator , typename _Tp , typename _BinaryOperation , typename _UnaryOperation >
constexpr _Tp transform_reduce (_InputIterator __first, _InputIterator __last, _Tp __init, _BinaryOperation __binary_op, _UnaryOperation __unary_op)
template<typename _InputIterator1 , typename _InputIterator2 , typename _Tp >
constexpr _Tp transform_reduce (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _Tp __init)
template<typename _InputIterator1 , typename _InputIterator2 , typename _Tp , typename _BinaryOperation1 , typename _BinaryOperation2 >
constexpr _Tp transform_reduce (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _Tp __init, _BinaryOperation1 __binary_op1, _BinaryOperation2 __binary_op2)
template<typename _L1 , typename _L2 , typename... _L3>
int try_lock (_L1 &__l1, _L2 &__l2, _L3 &... __l3)
template<typename... _UTypes>
tuple (_UTypes...) -> tuple< _UTypes... >
template<typename _Alloc , typename... _UTypes>
tuple (allocator_arg_t, _Alloc, _UTypes...) -> tuple< _UTypes... >
template<typename _Alloc , typename _T1 , typename _T2 >
tuple (allocator_arg_t, _Alloc, pair< _T1, _T2 >) -> tuple< _T1, _T2 >
template<typename _Alloc , typename... _UTypes>
tuple (allocator_arg_t, _Alloc, tuple< _UTypes... >) -> tuple< _UTypes... >
template<typename _T1 , typename _T2 >
tuple (pair< _T1, _T2 >) -> tuple< _T1, _T2 >
template<typename... _Tpls, typename = typename enable_if<__and_<__is_tuple_like<_Tpls>...>::value>::type>
constexpr auto tuple_cat (_Tpls &&... __tpls) -> typename __tuple_cat_result< _Tpls... >::__type
bool uncaught_exception () noexcept
int uncaught_exceptions () noexcept
void undeclare_no_pointers (char *, size_t)
template<typename _Tp >
_Tp * undeclare_reachable (_Tp *__p)
void unexpected ()
template<typename _Tp , typename _Alloc , typename... _Args>
constexpr _Tp * uninitialized_construct_using_allocator (_Tp *__p, const _Alloc &__a, _Args &&... __args)
template<typename _InputIterator , typename _ForwardIterator >
_ForwardIterator uninitialized_copy (_InputIterator __first, _InputIterator __last, _ForwardIterator __result)
template<typename _InputIterator , typename _Size , typename _ForwardIterator >
_ForwardIterator uninitialized_copy_n (_InputIterator __first, _Size __n, _ForwardIterator __result)
template<typename _ForwardIterator >
void uninitialized_default_construct (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Size >
_ForwardIterator uninitialized_default_construct_n (_ForwardIterator __first, _Size __count)
template<typename _ForwardIterator , typename _Tp >
void uninitialized_fill (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__x)
template<typename _ForwardIterator , typename _Size , typename _Tp >
_ForwardIterator uninitialized_fill_n (_ForwardIterator __first, _Size __n, const _Tp &__x)
template<typename _InputIterator , typename _ForwardIterator >
_ForwardIterator uninitialized_move (_InputIterator __first, _InputIterator __last, _ForwardIterator __result)
template<typename _InputIterator , typename _Size , typename _ForwardIterator >
pair< _InputIterator, _ForwardIterator > uninitialized_move_n (_InputIterator __first, _Size __count, _ForwardIterator __result)
template<typename _ForwardIterator >
void uninitialized_value_construct (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _Size >
_ForwardIterator uninitialized_value_construct_n (_ForwardIterator __first, _Size __count)
template<typename _FIter >
constexpr _FIter unique (_FIter, _FIter)
template<typename _FIter , typename _BinaryPredicate >
constexpr _FIter unique (_FIter, _FIter, _BinaryPredicate)
template<typename _ForwardIterator >
constexpr _ForwardIterator unique (_ForwardIterator __first, _ForwardIterator __last)
template<typename _ForwardIterator , typename _BinaryPredicate >
constexpr _ForwardIterator unique (_ForwardIterator __first, _ForwardIterator __last, _BinaryPredicate __binary_pred)
template<typename _IIter , typename _OIter >
constexpr _OIter unique_copy (_IIter, _IIter, _OIter)
template<typename _IIter , typename _OIter , typename _BinaryPredicate >
constexpr _OIter unique_copy (_IIter, _IIter, _OIter, _BinaryPredicate)
template<typename _InputIterator , typename _OutputIterator >
constexpr _OutputIterator unique_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result)
template<typename _InputIterator , typename _OutputIterator , typename _BinaryPredicate >
constexpr _OutputIterator unique_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryPredicate __binary_pred)
ios_base & unitbuf (ios_base &__base)
template<typename _InputIterator , typename _Allocator , typename = _RequireInputIter<_InputIterator>, typename = _RequireAllocator<_Allocator>>
unordered_map (_InputIterator, _InputIterator, _Allocator) -> unordered_map< __iter_key_t< _InputIterator >, __iter_val_t< _InputIterator >, hash< __iter_key_t< _InputIterator >>, equal_to< __iter_key_t< _InputIterator >>, _Allocator >
template<typename _InputIterator , typename _Allocator , typename = _RequireInputIter<_InputIterator>, typename = _RequireAllocator<_Allocator>>
unordered_map (_InputIterator, _InputIterator, typename unordered_map< int, int >::size_type, _Allocator) -> unordered_map< __iter_key_t< _InputIterator >, __iter_val_t< _InputIterator >, hash< __iter_key_t< _InputIterator >>, equal_to< __iter_key_t< _InputIterator >>, _Allocator >
template<typename _InputIterator , typename _Hash , typename _Allocator , typename = _RequireInputIter<_InputIterator>, typename = _RequireNotAllocatorOrIntegral<_Hash>, typename = _RequireAllocator<_Allocator>>
unordered_map (_InputIterator, _InputIterator, typename unordered_map< int, int >::size_type, _Hash, _Allocator) -> unordered_map< __iter_key_t< _InputIterator >, __iter_val_t< _InputIterator >, _Hash, equal_to< __iter_key_t< _InputIterator >>, _Allocator >
template<typename _InputIterator , typename _Hash = hash<__iter_key_t<_InputIterator>>, typename _Pred = equal_to<__iter_key_t<_InputIterator>>, typename _Allocator = allocator<__iter_to_alloc_t<_InputIterator>>, typename = _RequireInputIter<_InputIterator>, typename = _RequireNotAllocatorOrIntegral<_Hash>, typename = _RequireNotAllocator<_Pred>, typename = _RequireAllocator<_Allocator>>
unordered_map (_InputIterator, _InputIterator, typename unordered_map< int, int >::size_type={}, _Hash=_Hash(), _Pred=_Pred(), _Allocator=_Allocator()) -> unordered_map< __iter_key_t< _InputIterator >, __iter_val_t< _InputIterator >, _Hash, _Pred, _Allocator >
template<typename _Key , typename _Tp , typename _Allocator , typename = _RequireAllocator<_Allocator>>
unordered_map (initializer_list< pair< _Key, _Tp >>, _Allocator) -> unordered_map< _Key, _Tp, hash< _Key >, equal_to< _Key >, _Allocator >
template<typename _Key , typename _Tp , typename _Allocator , typename = _RequireAllocator<_Allocator>>
unordered_map (initializer_list< pair< _Key, _Tp >>, typename unordered_map< int, int >::size_type, _Allocator) -> unordered_map< _Key, _Tp, hash< _Key >, equal_to< _Key >, _Allocator >
template<typename _Key , typename _Tp , typename _Hash , typename _Allocator , typename = _RequireNotAllocatorOrIntegral<_Hash>, typename = _RequireAllocator<_Allocator>>
unordered_map (initializer_list< pair< _Key, _Tp >>, typename unordered_map< int, int >::size_type, _Hash, _Allocator) -> unordered_map< _Key, _Tp, _Hash, equal_to< _Key >, _Allocator >
template<typename _Key , typename _Tp , typename _Hash = hash<_Key>, typename _Pred = equal_to<_Key>, typename _Allocator = allocator<pair<const _Key, _Tp>>, typename = _RequireNotAllocatorOrIntegral<_Hash>, typename = _RequireNotAllocator<_Pred>, typename = _RequireAllocator<_Allocator>>
unordered_map (initializer_list< pair< _Key, _Tp >>, typename unordered_map< int, int >::size_type={}, _Hash=_Hash(), _Pred=_Pred(), _Allocator=_Allocator()) -> unordered_map< _Key, _Tp, _Hash, _Pred, _Allocator >
template<typename _InputIterator , typename _Allocator , typename = _RequireInputIter<_InputIterator>, typename = _RequireAllocator<_Allocator>>
unordered_multimap (_InputIterator, _InputIterator, _Allocator) -> unordered_multimap< __iter_key_t< _InputIterator >, __iter_val_t< _InputIterator >, hash< __iter_key_t< _InputIterator >>, equal_to< __iter_key_t< _InputIterator >>, _Allocator >
template<typename _InputIterator , typename _Allocator , typename = _RequireInputIter<_InputIterator>, typename = _RequireAllocator<_Allocator>>
unordered_multimap (_InputIterator, _InputIterator, unordered_multimap< int, int >::size_type, _Allocator) -> unordered_multimap< __iter_key_t< _InputIterator >, __iter_val_t< _InputIterator >, hash< __iter_key_t< _InputIterator >>, equal_to< __iter_key_t< _InputIterator >>, _Allocator >
template<typename _InputIterator , typename _Hash , typename _Allocator , typename = _RequireInputIter<_InputIterator>, typename = _RequireNotAllocatorOrIntegral<_Hash>, typename = _RequireAllocator<_Allocator>>
unordered_multimap (_InputIterator, _InputIterator, unordered_multimap< int, int >::size_type, _Hash, _Allocator) -> unordered_multimap< __iter_key_t< _InputIterator >, __iter_val_t< _InputIterator >, _Hash, equal_to< __iter_key_t< _InputIterator >>, _Allocator >
template<typename _InputIterator , typename _Hash = hash<__iter_key_t<_InputIterator>>, typename _Pred = equal_to<__iter_key_t<_InputIterator>>, typename _Allocator = allocator<__iter_to_alloc_t<_InputIterator>>, typename = _RequireInputIter<_InputIterator>, typename = _RequireNotAllocatorOrIntegral<_Hash>, typename = _RequireNotAllocator<_Pred>, typename = _RequireAllocator<_Allocator>>
unordered_multimap (_InputIterator, _InputIterator, unordered_multimap< int, int >::size_type={}, _Hash=_Hash(), _Pred=_Pred(), _Allocator=_Allocator()) -> unordered_multimap< __iter_key_t< _InputIterator >, __iter_val_t< _InputIterator >, _Hash, _Pred, _Allocator >
template<typename _Key , typename _Tp , typename _Allocator , typename = _RequireAllocator<_Allocator>>
unordered_multimap (initializer_list< pair< _Key, _Tp >>, _Allocator) -> unordered_multimap< _Key, _Tp, hash< _Key >, equal_to< _Key >, _Allocator >
template<typename _Key , typename _Tp , typename _Allocator , typename = _RequireAllocator<_Allocator>>
unordered_multimap (initializer_list< pair< _Key, _Tp >>, unordered_multimap< int, int >::size_type, _Allocator) -> unordered_multimap< _Key, _Tp, hash< _Key >, equal_to< _Key >, _Allocator >
template<typename _Key , typename _Tp , typename _Hash , typename _Allocator , typename = _RequireNotAllocatorOrIntegral<_Hash>, typename = _RequireAllocator<_Allocator>>
unordered_multimap (initializer_list< pair< _Key, _Tp >>, unordered_multimap< int, int >::size_type, _Hash, _Allocator) -> unordered_multimap< _Key, _Tp, _Hash, equal_to< _Key >, _Allocator >
template<typename _Key , typename _Tp , typename _Hash = hash<_Key>, typename _Pred = equal_to<_Key>, typename _Allocator = allocator<pair<const _Key, _Tp>>, typename = _RequireNotAllocatorOrIntegral<_Hash>, typename = _RequireNotAllocator<_Pred>, typename = _RequireAllocator<_Allocator>>
unordered_multimap (initializer_list< pair< _Key, _Tp >>, unordered_multimap< int, int >::size_type={}, _Hash=_Hash(), _Pred=_Pred(), _Allocator=_Allocator()) -> unordered_multimap< _Key, _Tp, _Hash, _Pred, _Allocator >
template<typename _InputIterator , typename _Allocator , typename = _RequireInputIter<_InputIterator>, typename = _RequireAllocator<_Allocator>>
unordered_multiset (_InputIterator, _InputIterator, unordered_multiset< int >::size_type, _Allocator) -> unordered_multiset< typename iterator_traits< _InputIterator >::value_type, hash< typename iterator_traits< _InputIterator >::value_type >, equal_to< typename iterator_traits< _InputIterator >::value_type >, _Allocator >
template<typename _InputIterator , typename _Hash , typename _Allocator , typename = _RequireInputIter<_InputIterator>, typename = _RequireNotAllocatorOrIntegral<_Hash>, typename = _RequireAllocator<_Allocator>>
unordered_multiset (_InputIterator, _InputIterator, unordered_multiset< int >::size_type, _Hash, _Allocator) -> unordered_multiset< typename iterator_traits< _InputIterator >::value_type, _Hash, equal_to< typename iterator_traits< _InputIterator >::value_type >, _Allocator >
template<typename _InputIterator , typename _Hash = hash<typename iterator_traits<_InputIterator>::value_type>, typename _Pred = equal_to<typename iterator_traits<_InputIterator>::value_type>, typename _Allocator = allocator<typename iterator_traits<_InputIterator>::value_type>, typename = _RequireInputIter<_InputIterator>, typename = _RequireNotAllocatorOrIntegral<_Hash>, typename = _RequireNotAllocator<_Pred>, typename = _RequireAllocator<_Allocator>>
unordered_multiset (_InputIterator, _InputIterator, unordered_multiset< int >::size_type={}, _Hash=_Hash(), _Pred=_Pred(), _Allocator=_Allocator()) -> unordered_multiset< typename iterator_traits< _InputIterator >::value_type, _Hash, _Pred, _Allocator >
template<typename _Tp , typename _Allocator , typename = _RequireAllocator<_Allocator>>
unordered_multiset (initializer_list< _Tp >, unordered_multiset< int >::size_type, _Allocator) -> unordered_multiset< _Tp, hash< _Tp >, equal_to< _Tp >, _Allocator >
template<typename _Tp , typename _Hash , typename _Allocator , typename = _RequireNotAllocatorOrIntegral<_Hash>, typename = _RequireAllocator<_Allocator>>
unordered_multiset (initializer_list< _Tp >, unordered_multiset< int >::size_type, _Hash, _Allocator) -> unordered_multiset< _Tp, _Hash, equal_to< _Tp >, _Allocator >
template<typename _Tp , typename _Hash = hash<_Tp>, typename _Pred = equal_to<_Tp>, typename _Allocator = allocator<_Tp>, typename = _RequireNotAllocatorOrIntegral<_Hash>, typename = _RequireNotAllocator<_Pred>, typename = _RequireAllocator<_Allocator>>
unordered_multiset (initializer_list< _Tp >, unordered_multiset< int >::size_type={}, _Hash=_Hash(), _Pred=_Pred(), _Allocator=_Allocator()) -> unordered_multiset< _Tp, _Hash, _Pred, _Allocator >
template<typename _InputIterator , typename _Allocator , typename = _RequireInputIter<_InputIterator>, typename = _RequireAllocator<_Allocator>>
unordered_set (_InputIterator, _InputIterator, unordered_set< int >::size_type, _Allocator) -> unordered_set< typename iterator_traits< _InputIterator >::value_type, hash< typename iterator_traits< _InputIterator >::value_type >, equal_to< typename iterator_traits< _InputIterator >::value_type >, _Allocator >
template<typename _InputIterator , typename _Hash , typename _Allocator , typename = _RequireInputIter<_InputIterator>, typename = _RequireNotAllocatorOrIntegral<_Hash>, typename = _RequireAllocator<_Allocator>>
unordered_set (_InputIterator, _InputIterator, unordered_set< int >::size_type, _Hash, _Allocator) -> unordered_set< typename iterator_traits< _InputIterator >::value_type, _Hash, equal_to< typename iterator_traits< _InputIterator >::value_type >, _Allocator >
template<typename _InputIterator , typename _Hash = hash<typename iterator_traits<_InputIterator>::value_type>, typename _Pred = equal_to<typename iterator_traits<_InputIterator>::value_type>, typename _Allocator = allocator<typename iterator_traits<_InputIterator>::value_type>, typename = _RequireInputIter<_InputIterator>, typename = _RequireNotAllocatorOrIntegral<_Hash>, typename = _RequireNotAllocator<_Pred>, typename = _RequireAllocator<_Allocator>>
unordered_set (_InputIterator, _InputIterator, unordered_set< int >::size_type={}, _Hash=_Hash(), _Pred=_Pred(), _Allocator=_Allocator()) -> unordered_set< typename iterator_traits< _InputIterator >::value_type, _Hash, _Pred, _Allocator >
template<typename _Tp , typename _Allocator , typename = _RequireAllocator<_Allocator>>
unordered_set (initializer_list< _Tp >, unordered_set< int >::size_type, _Allocator) -> unordered_set< _Tp, hash< _Tp >, equal_to< _Tp >, _Allocator >
template<typename _Tp , typename _Hash , typename _Allocator , typename = _RequireNotAllocatorOrIntegral<_Hash>, typename = _RequireAllocator<_Allocator>>
unordered_set (initializer_list< _Tp >, unordered_set< int >::size_type, _Hash, _Allocator) -> unordered_set< _Tp, _Hash, equal_to< _Tp >, _Allocator >
template<typename _Tp , typename _Hash = hash<_Tp>, typename _Pred = equal_to<_Tp>, typename _Allocator = allocator<_Tp>, typename = _RequireNotAllocatorOrIntegral<_Hash>, typename = _RequireNotAllocator<_Pred>, typename = _RequireAllocator<_Allocator>>
unordered_set (initializer_list< _Tp >, unordered_set< int >::size_type={}, _Hash=_Hash(), _Pred=_Pred(), _Allocator=_Allocator()) -> unordered_set< _Tp, _Hash, _Pred, _Allocator >
template<typename _FIter , typename _Tp >
constexpr _FIter upper_bound (_FIter, _FIter, const _Tp &)
template<typename _FIter , typename _Tp , typename _Compare >
constexpr _FIter upper_bound (_FIter, _FIter, const _Tp &, _Compare)
template<typename _ForwardIterator , typename _Tp >
constexpr _ForwardIterator upper_bound (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val)
template<typename _ForwardIterator , typename _Tp , typename _Compare >
constexpr _ForwardIterator upper_bound (_ForwardIterator __first, _ForwardIterator __last, const _Tp &__val, _Compare __comp)
ios_base & uppercase (ios_base &__base)
template<typename _Facet >
const _Facet & use_facet (const locale &__loc)
template<_Std_pair _Tp, typename _Alloc >
constexpr auto uses_allocator_construction_args (const _Alloc &) noexcept
template<_Std_pair _Tp, typename _Alloc , typename _Up , typename _Vp >
constexpr auto uses_allocator_construction_args (const _Alloc &, _Up &&, _Vp &&) noexcept
template<_Std_pair _Tp, typename _Alloc , typename _Up , typename _Vp >
constexpr auto uses_allocator_construction_args (const _Alloc &, const pair< _Up, _Vp > &) noexcept
template<_Std_pair _Tp, typename _Alloc , typename _Up , typename _Vp >
constexpr auto uses_allocator_construction_args (const _Alloc &, pair< _Up, _Vp > &&) noexcept
template<typename _Tp , typename _Alloc , typename... _Args>
constexpr auto uses_allocator_construction_args (const _Alloc &__a, _Args &&... __args) noexcept requires(! _Std_pair< _Tp >)
template<_Std_pair _Tp, typename _Alloc , typename _Tuple1 , typename _Tuple2 >
constexpr auto uses_allocator_construction_args (const _Alloc &__a, piecewise_construct_t, _Tuple1 &&__x, _Tuple2 &&__y) noexcept
template<typename _Tp , size_t _Nm>
valarray (const _Tp(&)[_Nm], size_t) -> valarray< _Tp >
template<typename _InputIterator , typename _ValT = typename iterator_traits<_InputIterator>::value_type, typename _Allocator = allocator<_ValT>, typename = _RequireInputIter<_InputIterator>, typename = _RequireAllocator<_Allocator>>
vector (_InputIterator, _InputIterator, _Allocator=_Allocator()) -> vector< _ValT, _Allocator >
template<typename _Visitor , typename... _Variants>
constexpr __detail::__variant::__visit_result_t< _Visitor, _Variants... > visit (_Visitor &&, _Variants &&...)
template<typename _Visitor , typename... _Variants>
constexpr __detail::__variant::__visit_result_t< _Visitor, _Variants... > visit (_Visitor &&__visitor, _Variants &&... __variants)
template<typename _Res , typename _Visitor , typename... _Variants>
constexpr _Res visit (_Visitor &&__visitor, _Variants &&... __variants)
wchar_t * wcschr (wchar_t *__p, wchar_t __c)
wchar_t * wcspbrk (wchar_t *__s1, const wchar_t *__s2)
wchar_t * wcsrchr (wchar_t *__p, wchar_t __c)
wchar_t * wcsstr (wchar_t *__s1, const wchar_t *__s2)
template<typename _Tp >
weak_ptr (shared_ptr< _Tp >) -> weak_ptr< _Tp >
wchar_t * wmemchr (wchar_t *__p, wchar_t __c, size_t __n)
template<typename _CharT , typename _Traits >
basic_istream< _CharT, _Traits > & ws (basic_istream< _CharT, _Traits > &__is)
template<typename _ValueType >
_ValueType any_cast (any &__any)
template<typename _ValueType >
_ValueType any_cast (any &&__any)
template<typename _ValueType >
const _ValueType * any_cast (const any *__any) noexcept
template<typename _ValueType >
_ValueType * any_cast (any *__any) noexcept
template<size_t _Nb>
bitset< _Nb > operator& (const bitset< _Nb > &__x, const bitset< _Nb > &__y) noexcept
template<size_t _Nb>
bitset< _Nb > operator| (const bitset< _Nb > &__x, const bitset< _Nb > &__y) noexcept
template<size_t _Nb>
bitset< _Nb > operator^ (const bitset< _Nb > &__x, const bitset< _Nb > &__y) noexcept
template<class _CharT , class _Traits , size_t _Nb>
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, bitset< _Nb > &__x)
template<class _CharT , class _Traits , size_t _Nb>
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const bitset< _Nb > &__x)
template<typename _Tp >
constexpr complex< _Tp > operator+ (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > operator+ (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp >
constexpr complex< _Tp > operator+ (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > operator- (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > operator- (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp >
constexpr complex< _Tp > operator- (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > operator* (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > operator* (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp >
constexpr complex< _Tp > operator* (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > operator/ (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > operator/ (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp >
constexpr complex< _Tp > operator/ (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr bool operator== (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr bool operator== (const complex< _Tp > &__x, const _Tp &__y)
template<typename _CharT , typename _Traits >
basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__in, _CharT &__c)
template<class _Traits >
basic_istream< char, _Traits > & operator>> (basic_istream< char, _Traits > &__in, unsigned char &__c)
template<class _Traits >
basic_istream< char, _Traits > & operator>> (basic_istream< char, _Traits > &__in, signed char &__c)
template<typename _CharT , typename _Traits , size_t _Num>
basic_istream< _CharT, _Traits > & operator>> (basic_istream< _CharT, _Traits > &__in, _CharT(&__s)[_Num])
template<class _Traits , size_t _Num>
basic_istream< char, _Traits > & operator>> (basic_istream< char, _Traits > &__in, unsigned char(&__s)[_Num])
template<class _Traits , size_t _Num>
basic_istream< char, _Traits > & operator>> (basic_istream< char, _Traits > &__in, signed char(&__s)[_Num])
template<typename _CharT , typename _Traits >
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__out, _CharT __c)
template<typename _CharT , typename _Traits >
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__out, char __c)
template<typename _Traits >
basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &__out, char __c)
template<typename _Traits >
basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &__out, signed char __c)
template<typename _Traits >
basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &__out, unsigned char __c)
template<typename _Traits >
basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &, wchar_t)=delete
template<typename _Traits >
basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &, char16_t)=delete
template<typename _Traits >
basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &, char32_t)=delete
template<typename _Traits >
basic_ostream< wchar_t, _Traits > & operator<< (basic_ostream< wchar_t, _Traits > &, char16_t)=delete
template<typename _Traits >
basic_ostream< wchar_t, _Traits > & operator<< (basic_ostream< wchar_t, _Traits > &, char32_t)=delete
template<typename _CharT , typename _Traits >
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__out, const _CharT *__s)
template<typename _CharT , typename _Traits >
basic_ostream< _CharT, _Traits > & operator<< (basic_ostream< _CharT, _Traits > &__out, const char *__s)
template<typename _Traits >
basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &__out, const char *__s)
template<typename _Traits >
basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &__out, const signed char *__s)
template<typename _Traits >
basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &__out, const unsigned char *__s)
template<typename _Traits >
basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &, const wchar_t *)=delete
template<typename _Traits >
basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &, const char16_t *)=delete
template<typename _Traits >
basic_ostream< char, _Traits > & operator<< (basic_ostream< char, _Traits > &, const char32_t *)=delete
template<typename _Traits >
basic_ostream< wchar_t, _Traits > & operator<< (basic_ostream< wchar_t, _Traits > &, const char16_t *)=delete
template<typename _Traits >
basic_ostream< wchar_t, _Traits > & operator<< (basic_ostream< wchar_t, _Traits > &, const char32_t *)=delete
Matching, Searching, and Replacing
template<typename _Bi_iter , typename _Alloc , typename _Ch_type , typename _Rx_traits >
bool regex_match (_Bi_iter __s, _Bi_iter __e, match_results< _Bi_iter, _Alloc > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Bi_iter , typename _Ch_type , typename _Rx_traits >
bool regex_match (_Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Ch_type , typename _Alloc , typename _Rx_traits >
bool regex_match (const _Ch_type *__s, match_results< const _Ch_type *, _Alloc > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_traits , typename _Ch_alloc , typename _Alloc , typename _Ch_type , typename _Rx_traits >
bool regex_match (const basic_string< _Ch_type, _Ch_traits, _Ch_alloc > &__s, match_results< typename basic_string< _Ch_type, _Ch_traits, _Ch_alloc >::const_iterator, _Alloc > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Ch_traits , typename _Ch_alloc , typename _Alloc , typename _Ch_type , typename _Rx_traits >
bool regex_match (const basic_string< _Ch_type, _Ch_traits, _Ch_alloc > &&, match_results< typename basic_string< _Ch_type, _Ch_traits, _Ch_alloc >::const_iterator, _Alloc > &, const basic_regex< _Ch_type, _Rx_traits > &, regex_constants::match_flag_type=regex_constants::match_default)=delete
template<typename _Ch_type , class _Rx_traits >
bool regex_match (const _Ch_type *__s, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_traits , typename _Str_allocator , typename _Ch_type , typename _Rx_traits >
bool regex_match (const basic_string< _Ch_type, _Ch_traits, _Str_allocator > &__s, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Bi_iter , typename _Alloc , typename _Ch_type , typename _Rx_traits >
bool regex_search (_Bi_iter __s, _Bi_iter __e, match_results< _Bi_iter, _Alloc > &__m, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Bi_iter , typename _Ch_type , typename _Rx_traits >
bool regex_search (_Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__re, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Ch_type , class _Alloc , class _Rx_traits >
bool regex_search (const _Ch_type *__s, match_results< const _Ch_type *, _Alloc > &__m, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_type , typename _Rx_traits >
bool regex_search (const _Ch_type *__s, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_traits , typename _String_allocator , typename _Ch_type , typename _Rx_traits >
bool regex_search (const basic_string< _Ch_type, _Ch_traits, _String_allocator > &__s, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Ch_traits , typename _Ch_alloc , typename _Alloc , typename _Ch_type , typename _Rx_traits >
bool regex_search (const basic_string< _Ch_type, _Ch_traits, _Ch_alloc > &__s, match_results< typename basic_string< _Ch_type, _Ch_traits, _Ch_alloc >::const_iterator, _Alloc > &__m, const basic_regex< _Ch_type, _Rx_traits > &__e, regex_constants::match_flag_type __f=regex_constants::match_default)
template<typename _Ch_traits , typename _Ch_alloc , typename _Alloc , typename _Ch_type , typename _Rx_traits >
bool regex_search (const basic_string< _Ch_type, _Ch_traits, _Ch_alloc > &&, match_results< typename basic_string< _Ch_type, _Ch_traits, _Ch_alloc >::const_iterator, _Alloc > &, const basic_regex< _Ch_type, _Rx_traits > &, regex_constants::match_flag_type=regex_constants::match_default)=delete
template<typename _Out_iter , typename _Bi_iter , typename _Rx_traits , typename _Ch_type >
_Out_iter __regex_replace (_Out_iter __out, _Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__e, const _Ch_type *__fmt, size_t __len, regex_constants::match_flag_type __flags)
template<typename _Out_iter , typename _Bi_iter , typename _Rx_traits , typename _Ch_type , typename _St , typename _Sa >
_Out_iter regex_replace (_Out_iter __out, _Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__e, const basic_string< _Ch_type, _St, _Sa > &__fmt, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Out_iter , typename _Bi_iter , typename _Rx_traits , typename _Ch_type >
_Out_iter regex_replace (_Out_iter __out, _Bi_iter __first, _Bi_iter __last, const basic_regex< _Ch_type, _Rx_traits > &__e, const _Ch_type *__fmt, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Rx_traits , typename _Ch_type , typename _St , typename _Sa , typename _Fst , typename _Fsa >
basic_string< _Ch_type, _St, _Sa > regex_replace (const basic_string< _Ch_type, _St, _Sa > &__s, const basic_regex< _Ch_type, _Rx_traits > &__e, const basic_string< _Ch_type, _Fst, _Fsa > &__fmt, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Rx_traits , typename _Ch_type , typename _St , typename _Sa >
basic_string< _Ch_type, _St, _Sa > regex_replace (const basic_string< _Ch_type, _St, _Sa > &__s, const basic_regex< _Ch_type, _Rx_traits > &__e, const _Ch_type *__fmt, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Rx_traits , typename _Ch_type , typename _St , typename _Sa >
basic_string< _Ch_type > regex_replace (const _Ch_type *__s, const basic_regex< _Ch_type, _Rx_traits > &__e, const basic_string< _Ch_type, _St, _Sa > &__fmt, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<typename _Rx_traits , typename _Ch_type >
basic_string< _Ch_type > regex_replace (const _Ch_type *__s, const basic_regex< _Ch_type, _Rx_traits > &__e, const _Ch_type *__fmt, regex_constants::match_flag_type __flags=regex_constants::match_default)
template<size_t _Int, class _Tp1 , class _Tp2 >
constexpr tuple_element< _Int, pair< _Tp1, _Tp2 > >::type & get (pair< _Tp1, _Tp2 > &__in) noexcept
template<size_t _Int, class _Tp1 , class _Tp2 >
constexpr tuple_element< _Int, pair< _Tp1, _Tp2 > >::type && get (pair< _Tp1, _Tp2 > &&__in) noexcept
template<size_t _Int, class _Tp1 , class _Tp2 >
constexpr const tuple_element< _Int, pair< _Tp1, _Tp2 > >::type & get (const pair< _Tp1, _Tp2 > &__in) noexcept
template<size_t _Int, class _Tp1 , class _Tp2 >
constexpr const tuple_element< _Int, pair< _Tp1, _Tp2 > >::type && get (const pair< _Tp1, _Tp2 > &&__in) noexcept
template<typename _Tp , typename _Up >
constexpr _Tp & get (pair< _Tp, _Up > &__p) noexcept
template<typename _Tp , typename _Up >
constexpr const _Tp & get (const pair< _Tp, _Up > &__p) noexcept
template<typename _Tp , typename _Up >
constexpr _Tp && get (pair< _Tp, _Up > &&__p) noexcept
template<typename _Tp , typename _Up >
constexpr const _Tp && get (const pair< _Tp, _Up > &&__p) noexcept
template<typename _Tp , typename _Up >
constexpr _Tp & get (pair< _Up, _Tp > &__p) noexcept
template<typename _Tp , typename _Up >
constexpr const _Tp & get (const pair< _Up, _Tp > &__p) noexcept
template<typename _Tp , typename _Up >
constexpr _Tp && get (pair< _Up, _Tp > &&__p) noexcept
template<typename _Tp , typename _Up >
constexpr const _Tp && get (const pair< _Up, _Tp > &&__p) noexcept
Variables
template<typename _Alloc >
concept __allocator_like
template<typename _Tp >
constexpr auto __denorm_min_v
template<typename _Tp >
concept __derived_from_ios_base
template<typename _Tp >
constexpr auto __digits10_v
template<typename _Tp >
constexpr auto __digits_v
template<typename _Tp >
constexpr auto __epsilon_v
template<typename _Tp >
constexpr auto __finite_max_v
template<typename _Tp >
constexpr auto __finite_min_v
template<template< typename > class _Trait, typename _Tp >
constexpr bool __has_iec559_behavior_v
template<typename _Tp >
constexpr bool __has_iec559_storage_format_v
template<typename _Tp >
constexpr auto __infinity_v
static ios_base::Init __ioinit
template<typename >
constexpr bool __is_in_place_type_v
template<typename _Tp >
constexpr bool __is_in_place_type_v< in_place_type_t< _Tp > >
template<typename _Tp >
constexpr bool __is_optional_v
template<typename _Tp >
constexpr bool __is_optional_v< optional< _Tp > >
template<typename _Tp >
constexpr bool __is_pair
template<typename _Tp , typename _Up >
constexpr bool __is_pair< const pair< _Tp, _Up > >
template<typename _Tp , typename _Up >
constexpr bool __is_pair< pair< _Tp, _Up > >
template<typename _Up >
static constexpr bool __is_shared_ptr
template<typename _Up >
static constexpr bool __is_shared_ptr< shared_ptr< _Up > >
template<typename _Tp >
constexpr auto __max_digits10_v
template<typename _Tp >
constexpr auto __max_exponent10_v
template<typename _Tp >
constexpr auto __max_exponent_v
template<typename _Tp >
constexpr auto __min_exponent10_v
template<typename _Tp >
constexpr auto __min_exponent_v
template<typename _Tp >
constexpr auto __norm_min_v
return __os
_Rest __pad0__
template<typename _Tp >
constexpr bool __platform_wait_uses_type
template<typename _Callable , typename... _Args>
constexpr bool __pmf_expects_stop_token
template<typename _Callable , typename _Obj , typename... _Args>
constexpr bool __pmf_expects_stop_token< _Callable, _Obj, _Args... >
template<typename _Tp >
constexpr auto __quiet_NaN_v
template<typename _Tp >
constexpr auto __radix_v
template<typename _Tp >
constexpr auto __reciprocal_overflow_threshold_v
template<typename _Tp >
constexpr auto __round_error_v
template<typename _Tp >
constexpr auto __signaling_NaN_v
template<template< typename... > class _Trait, typename _Tp , typename _Tuple >
constexpr bool __unpack_std_tuple
template<template< typename... > class _Trait, typename _Tp , typename... _Up>
constexpr bool __unpack_std_tuple< _Trait, _Tp, const tuple< _Up... > & >
template<template< typename... > class _Trait, typename _Tp , typename... _Up>
constexpr bool __unpack_std_tuple< _Trait, _Tp, const tuple< _Up... > >
template<template< typename... > class _Trait, typename _Tp , typename... _Up>
constexpr bool __unpack_std_tuple< _Trait, _Tp, tuple< _Up... > & >
template<template< typename... > class _Trait, typename _Tp , typename... _Up>
constexpr bool __unpack_std_tuple< _Trait, _Tp, tuple< _Up... > >
template<template< typename > class _Trait, typename _Tp >
constexpr bool __value_exists_v
_Rest _Rest
template<typename _Tp >
concept _Std_pair
_Tp0
_Tp1
_Tp2
constexpr adopt_lock_t adopt_lock
template<typename _Lhs , typename _Rhs >
concept assignable_from
template<typename _Iter >
concept bidirectional_iterator
template<typename _Tp , typename _Up >
concept common_reference_with
template<typename _Tp , typename _Up >
concept common_with
constexpr __cmp_cust::_Partial_fallback compare_partial_order_fallback
constexpr __cmp_cust::_Strong_fallback compare_strong_order_fallback
constexpr __cmp_cust::_Weak_fallback compare_weak_order_fallback
template<typename _Tp , typename... _Args>
concept constructible_from
template<typename _Iter >
concept contiguous_iterator
template<typename _From , typename _To >
concept convertible_to
template<typename _Tp >
concept copy_constructible
template<typename _Tp >
concept copyable
template<typename _Tp >
concept default_initializable
constexpr default_sentinel_t default_sentinel
constexpr defer_lock_t defer_lock
template<typename _Derived , typename _Base >
concept derived_from
constexpr destroying_delete_t destroying_delete
template<typename _Tp >
concept destructible
template<typename _Sent , typename _Iter >
constexpr bool disable_sized_sentinel_for
constexpr size_t dynamic_extent
template<typename _Tp >
concept equality_comparable
template<typename _Tp , typename _Up >
concept equality_comparable_with
template<typename _Rel , typename _Tp , typename _Up >
concept equivalence_relation
template<typename _Tp >
concept floating_point
template<typename _Iter >
concept forward_iterator
template<typename _Tp >
constexpr bool has_unique_object_representations_v
constexpr _Swallow_assign ignore
constexpr in_place_t in_place
template<size_t _Idx>
constexpr in_place_index_t< _Idx > in_place_index
template<typename _Tp >
constexpr in_place_type_t< _Tp > in_place_type
template<typename _Iter >
concept incrementable
template<typename _Fn , typename _I1 , typename _I2 >
concept indirect_binary_predicate
template<typename _Fn , typename _I1 , typename _I2 = _I1>
concept indirect_equivalence_relation
template<typename _Fn , typename _I1 , typename _I2 = _I1>
concept indirect_strict_weak_order
template<typename _Fn , typename _Iter >
concept indirect_unary_predicate
template<typename _I1 , typename _I2 , typename _Rel , typename _P1 = identity, typename _P2 = identity>
concept indirectly_comparable
template<typename _In , typename _Out >
concept indirectly_copyable
template<typename _In , typename _Out >
concept indirectly_copyable_storable
template<typename _In , typename _Out >
concept indirectly_movable
template<typename _In , typename _Out >
concept indirectly_movable_storable
template<typename _In >
concept indirectly_readable
template<typename _Fn , typename _Iter >
concept indirectly_regular_unary_invocable
template<typename _I1 , typename _I2 = _I1>
concept indirectly_swappable
template<typename _Fn , typename _Iter >
concept indirectly_unary_invocable
template<typename _Out , typename _Tp >
concept indirectly_writable
template<typename _Iter >
concept input_iterator
template<typename _Iter >
concept input_or_output_iterator
template<typename _Tp >
concept integral
template<typename _Fn , typename... _Args>
concept invocable
template<typename _Tp >
constexpr bool is_aggregate_v
template<typename _Tp >
constexpr bool is_bind_expression_v
template<typename _Tp >
constexpr bool is_bounded_array_v
template<typename _Tp >
constexpr bool is_error_code_enum_v
template<typename _Tp >
constexpr bool is_error_condition_enum_v
template<typename _Tp , typename _Up >
constexpr bool is_layout_compatible_v
template<typename _From , typename _To >
constexpr bool is_nothrow_convertible_v
template<typename _Tp >
constexpr bool is_nothrow_swappable_v
template<typename _Tp , typename _Up >
constexpr bool is_nothrow_swappable_with_v
template<typename _Tp >
constexpr int is_placeholder_v
template<typename _Base , typename _Derived >
constexpr bool is_pointer_interconvertible_base_of_v
template<typename _Tp >
constexpr bool is_swappable_v
template<typename _Tp , typename _Up >
constexpr bool is_swappable_with_v
template<typename _Tp >
constexpr bool is_unbounded_array_v
template<typename _Tp >
requires is_object_v< _Tp > struct iterator_traits< _Tp * >
error_code make_error_code (errc) noexcept
constexpr memory_order memory_order_acq_rel
constexpr memory_order memory_order_acquire
constexpr memory_order memory_order_consume
constexpr memory_order memory_order_relaxed
constexpr memory_order memory_order_release
constexpr memory_order memory_order_seq_cst
template<typename _I1 , typename _I2 , typename _Out , typename _Rel = ranges::less, typename _P1 = identity, typename _P2 = identity>
concept mergeable
template<typename _Tp >
concept movable
template<typename _Tp >
concept move_constructible
constexpr nostopstate_t nostopstate
const nothrow_t nothrow
constexpr nullopt_t nullopt
decltype(nullptr) typedef nullptr_t
template<typename _Iter , typename _Tp >
concept output_iterator
constexpr __cmp_cust::_Partial_order partial_order
template<typename _Iter >
concept permutable
constexpr piecewise_construct_t piecewise_construct
template<typename _Fn , typename... _Args>
concept predicate
template<typename _Iter >
concept random_access_iterator
template<typename _R1 , typename _R2 >
constexpr bool ratio_equal_v
template<typename _R1 , typename _R2 >
constexpr bool ratio_greater_equal_v
template<typename _R1 , typename _R2 >
constexpr bool ratio_greater_v
template<typename _R1 , typename _R2 >
constexpr bool ratio_less_equal_v
template<typename _R1 , typename _R2 >
constexpr bool ratio_less_v
template<typename _R1 , typename _R2 >
constexpr bool ratio_not_equal_v
template<typename _Tp >
concept regular
template<typename _Fn , typename... _Args>
concept regular_invocable
template<typename _Rel , typename _Tp , typename _Up >
concept relation
template<typename _Tp >
requires requires
reverse_iterator< _Iterator2 >
template<typename _Tp , typename _Up >
concept same_as
template<typename _Tp >
concept semiregular
template<typename _Sent , typename _Iter >
concept sentinel_for
template<typename _Tp >
concept signed_integral
template<typename _Sent , typename _Iter >
concept sized_sentinel_for
template<typename _Iter , typename _Rel = ranges::less, typename _Proj = identity>
concept sortable
template<typename _Rel , typename _Tp , typename _Up >
concept strict_weak_order
constexpr __cmp_cust::_Strong_order strong_order
template<typename _Tp >
concept swappable
template<typename _Tp , typename _Up >
concept swappable_with
template<typename _Tp , typename _Cat = partial_ordering>
concept three_way_comparable
template<typename _Tp , typename _Up , typename _Cat = partial_ordering>
concept three_way_comparable_with
template<typename _Tp >
concept totally_ordered
template<typename _Tp , typename _Up >
concept totally_ordered_with
constexpr try_to_lock_t try_to_lock
template<typename _Tp >
constexpr size_t tuple_size_v
template<typename _Tp , size_t _Nm>
constexpr size_t tuple_size_v< array< _Tp, _Nm > >
template<typename _Tp , size_t _Nm>
constexpr size_t tuple_size_v< const array< _Tp, _Nm > >
template<typename _Tp1 , typename _Tp2 >
constexpr size_t tuple_size_v< const pair< _Tp1, _Tp2 > >
template<typename... _Types>
constexpr size_t tuple_size_v< const tuple< _Types... > >
template<typename _Tp1 , typename _Tp2 >
constexpr size_t tuple_size_v< pair< _Tp1, _Tp2 > >
template<typename... _Types>
constexpr size_t tuple_size_v< tuple< _Types... > >
template<typename _Gen >
concept uniform_random_bit_generator
constexpr unreachable_sentinel_t unreachable_sentinel
template<typename _Tp >
concept unsigned_integral
constexpr size_t variant_npos
template<typename _Variant >
constexpr size_t variant_size_v
template<typename... _Types>
constexpr size_t variant_size_v< const variant< _Types... > >
template<typename... _Types>
constexpr size_t variant_size_v< variant< _Types... > >
constexpr __cmp_cust::_Weak_order weak_order
template<typename _Iter >
concept weakly_incrementable
Standard Stream Objects
The <iostream> header declares the eight standard stream objects. For other declarations, see http://gcc.gnu.org/onlinedocs/libstdc++/manual/io.html and the I/O forward declarations
They are required by default to cooperate with the global C library's FILE streams, and to be available during program startup and termination. For more information, see the section of the manual linked to above.
istream cin
ostream cout
ostream cerr
ostream clog
wistream wcin
wostream wcout
wostream wcerr
wostream wclog
template<typename... _Bn>
constexpr bool conjunction_v
template<typename... _Bn>
constexpr bool disjunction_v
template<typename _Pp >
constexpr bool negation_v
template<typename _Tp >
constexpr bool is_void_v
template<typename _Tp >
constexpr bool is_null_pointer_v
template<typename _Tp >
constexpr bool is_integral_v
template<typename _Tp >
constexpr bool is_floating_point_v
template<typename _Tp >
constexpr bool is_array_v
template<typename _Tp >
constexpr bool is_pointer_v
template<typename _Tp >
constexpr bool is_lvalue_reference_v
template<typename _Tp >
constexpr bool is_rvalue_reference_v
template<typename _Tp >
constexpr bool is_member_object_pointer_v
template<typename _Tp >
constexpr bool is_member_function_pointer_v
template<typename _Tp >
constexpr bool is_enum_v
template<typename _Tp >
constexpr bool is_union_v
template<typename _Tp >
constexpr bool is_class_v
template<typename _Tp >
constexpr bool is_function_v
template<typename _Tp >
constexpr bool is_reference_v
template<typename _Tp >
constexpr bool is_arithmetic_v
template<typename _Tp >
constexpr bool is_fundamental_v
template<typename _Tp >
constexpr bool is_object_v
template<typename _Tp >
constexpr bool is_scalar_v
template<typename _Tp >
constexpr bool is_compound_v
template<typename _Tp >
constexpr bool is_member_pointer_v
template<typename _Tp >
constexpr bool is_const_v
template<typename _Tp >
constexpr bool is_volatile_v
template<typename _Tp >
constexpr bool is_trivial_v
template<typename _Tp >
constexpr bool is_trivially_copyable_v
template<typename _Tp >
constexpr bool is_standard_layout_v
template<typename _Tp >
constexpr bool is_pod_v
template<typename _Tp >
constexpr bool is_literal_type_v
template<typename _Tp >
constexpr bool is_empty_v
template<typename _Tp >
constexpr bool is_polymorphic_v
template<typename _Tp >
constexpr bool is_abstract_v
template<typename _Tp >
constexpr bool is_final_v
template<typename _Tp >
constexpr bool is_signed_v
template<typename _Tp >
constexpr bool is_unsigned_v
template<typename _Tp , typename... _Args>
constexpr bool is_constructible_v
template<typename _Tp >
constexpr bool is_default_constructible_v
template<typename _Tp >
constexpr bool is_copy_constructible_v
template<typename _Tp >
constexpr bool is_move_constructible_v
template<typename _Tp , typename _Up >
constexpr bool is_assignable_v
template<typename _Tp >
constexpr bool is_copy_assignable_v
template<typename _Tp >
constexpr bool is_move_assignable_v
template<typename _Tp >
constexpr bool is_destructible_v
template<typename _Tp , typename... _Args>
constexpr bool is_trivially_constructible_v
template<typename _Tp >
constexpr bool is_trivially_default_constructible_v
template<typename _Tp >
constexpr bool is_trivially_copy_constructible_v
template<typename _Tp >
constexpr bool is_trivially_move_constructible_v
template<typename _Tp , typename _Up >
constexpr bool is_trivially_assignable_v
template<typename _Tp >
constexpr bool is_trivially_copy_assignable_v
template<typename _Tp >
constexpr bool is_trivially_move_assignable_v
template<typename _Tp >
constexpr bool is_trivially_destructible_v
template<typename _Tp , typename... _Args>
constexpr bool is_nothrow_constructible_v
template<typename _Tp >
constexpr bool is_nothrow_default_constructible_v
template<typename _Tp >
constexpr bool is_nothrow_copy_constructible_v
template<typename _Tp >
constexpr bool is_nothrow_move_constructible_v
template<typename _Tp , typename _Up >
constexpr bool is_nothrow_assignable_v
template<typename _Tp >
constexpr bool is_nothrow_copy_assignable_v
template<typename _Tp >
constexpr bool is_nothrow_move_assignable_v
template<typename _Tp >
constexpr bool is_nothrow_destructible_v
template<typename _Tp >
constexpr bool has_virtual_destructor_v
template<typename _Tp >
constexpr size_t alignment_of_v
template<typename _Tp >
constexpr size_t rank_v
template<typename _Tp , unsigned _Idx = 0>
constexpr size_t extent_v
template<typename _Tp , typename _Up >
constexpr bool is_same_v
template<typename _Base , typename _Derived >
constexpr bool is_base_of_v
template<typename _From , typename _To >
constexpr bool is_convertible_v
template<typename _Fn , typename... _Args>
constexpr bool is_invocable_v
template<typename _Fn , typename... _Args>
constexpr bool is_nothrow_invocable_v
template<typename _Ret , typename _Fn , typename... _Args>
constexpr bool is_invocable_r_v
template<typename _Ret , typename _Fn , typename... _Args>
constexpr bool is_nothrow_invocable_r_v
Detailed Description
ISO C++ entities toplevel namespace is std.
Typedef Documentation
__ptr_rebind
template<typename _Ptr , typename _Tp > using std::__ptr_rebind = typedef typename pointer_traits<_Ptr>::template rebind<_Tp>
Convenience alias for rebinding pointers.
Definition at line 224 of file ptr_traits.h.
__umap_traits
template<bool _Cache> using std::__umap_traits = typedef __detail::_Hashtable_traits<_Cache, false, true>
Base types for unordered_map.
Definition at line 40 of file unordered_map.h.
__ummap_traits
template<bool _Cache> using std::__ummap_traits = typedef __detail::_Hashtable_traits<_Cache, false, false>
Base types for unordered_multimap.
Definition at line 57 of file unordered_map.h.
__umset_traits
template<bool _Cache> using std::__umset_traits = typedef __detail::_Hashtable_traits<_Cache, true, false>
Base types for unordered_multiset.
Definition at line 55 of file unordered_set.h.
__uset_traits
template<bool _Cache> using std::__uset_traits = typedef __detail::_Hashtable_traits<_Cache, true, true>
Base types for unordered_set.
Definition at line 40 of file unordered_set.h.
compare_three_way_result_t
template<typename _Tp , typename _Up = _Tp> using std::compare_three_way_result_t = typedef typename __detail::__cmp3way_res_impl<_Tp, _Up>::type
[cmp.result], result of three-way comparison
Definition at line 521 of file compare.
index_sequence
template<size_t... _Idx> using std::index_sequence = typedef integer_sequence<size_t, _Idx...>
Alias template index_sequence.
Definition at line 181 of file utility.h.
index_sequence_for
template<typename... _Types> using std::index_sequence_for = typedef make_index_sequence<sizeof...(_Types)>
Alias template index_sequence_for.
Definition at line 189 of file utility.h.
make_index_sequence
template<size_t _Num> using std::make_index_sequence = typedef make_integer_sequence<size_t, _Num>
Alias template make_index_sequence.
Definition at line 185 of file utility.h.
make_integer_sequence
template<typename _Tp , _Tp _Num> using std::make_integer_sequence = typedef __make_integer_seq<integer_sequence, _Tp, _Num>
Alias template make_integer_sequence.
Definition at line 172 of file utility.h.
new_handler
typedef void(* std::new_handler) ()
If you write your own error handler to be called by new, it must be of this type.
Definition at line 103 of file new.
streamoff
typedef long long std::streamoff
Type used by fpos, char_traits<char>, and char_traits<wchar_t>.
In clauses 21.1.3.1 and 27.4.1 streamoff is described as an implementation defined type. Note: In versions of GCC up to and including GCC 3.3, streamoff was typedef long.
Definition at line 64 of file postypes.h.
streampos
typedef fpos<mbstate_t> std::streampos
File position for char streams.
Definition at line 204 of file postypes.h.
streamsize
typedef ptrdiff_t std::streamsize
Integral type for I/O operation counts and buffer sizes.
Definition at line 68 of file postypes.h.
u16streampos
typedef fpos<mbstate_t> std::u16streampos
File position for char16_t streams.
Definition at line 215 of file postypes.h.
u32streampos
typedef fpos<mbstate_t> std::u32streampos
File position for char32_t streams.
Definition at line 217 of file postypes.h.
wstreampos
typedef fpos<mbstate_t> std::wstreampos
File position for wchar_t streams.
Definition at line 206 of file postypes.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Todo:
Needs documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html This controls some aspect of the sort routines.
Definition at line 1838 of file stl_algo.h.
byte
enum std::byte : unsigned char strong
std::byte
Definition at line 69 of file cstddef.
chars_format
enum std::chars_format strong
floating-point format for primitive numerical conversion
Definition at line 618 of file charconv.
float_denorm_style
enum std::float_denorm_style
Describes the denormalization for floating-point types.
These values represent the presence or absence of a variable number of exponent bits. This type is used in the std::numeric_limits class.
Enumerator
denorm_indeterminate
Indeterminate at compile time whether denormalized values are allowed.
denorm_absent
The type does not allow denormalized values.
denorm_present
The type allows denormalized values.
Definition at line 182 of file limits.
float_round_style
enum std::float_round_style
Describes the rounding style for floating-point types.
This is used in the std::numeric_limits class.
Enumerator
round_toward_zero
Intermediate.
round_to_nearest
To zero.
round_toward_infinity
To the nearest representable value.
round_toward_neg_infinity
To infinity.
Definition at line 167 of file limits.
io_errc
enum std::io_errc strong
I/O error code.
Definition at line 204 of file ios_base.h.
Function Documentation
__final_insertion_sort()
template<typename _RandomAccessIterator , typename _Compare > constexpr void std::__final_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp) constexpr
This is a helper function for the sort routine.
Definition at line 1844 of file stl_algo.h.
References __insertion_sort(), and __unguarded_insertion_sort().
__find_if() [1/2]
template<typename _InputIterator , typename _Predicate > constexpr _InputIterator std::__find_if (_InputIterator __first, _InputIterator __last, _Predicate __pred, input_iterator_tag) inline constexpr
This is an overload used by find algos for the Input Iterator case.
Definition at line 2047 of file stl_algobase.h.
Referenced by __find_if_not(), and __search_n_aux().
__find_if() [2/2]
template<typename _RandomAccessIterator , typename _Predicate > constexpr _RandomAccessIterator std::__find_if (_RandomAccessIterator __first, _RandomAccessIterator __last, _Predicate __pred, random_access_iterator_tag) constexpr
This is an overload used by find algos for the RAI case.
Definition at line 2059 of file stl_algobase.h.
__find_if_not()
template<typename _InputIterator , typename _Predicate > constexpr _InputIterator std::__find_if_not (_InputIterator __first, _InputIterator __last, _Predicate __pred) inline constexpr
Provided for stable_partition to use.
Definition at line 106 of file stl_algo.h.
References __find_if().
__find_if_not_n()
template<typename _InputIterator , typename _Predicate , typename _Distance > constexpr _InputIterator std::__find_if_not_n (_InputIterator __first, _Distance & __len, _Predicate __pred) constexpr
Like find_if_not(), but uses and updates a count of the remaining range length instead of comparing against an end iterator.
Definition at line 120 of file stl_algo.h.
__gcd()
template<typename _EuclideanRingElement > constexpr _EuclideanRingElement std::__gcd (_EuclideanRingElement __m, _EuclideanRingElement __n) constexpr
This is a helper function for the rotate algorithm specialized on RAIs. It returns the greatest common divisor of two integer values.
Definition at line 1182 of file stl_algo.h.
__gen_two_uniform_ints()
template<typename _IntType , typename _UniformRandomBitGenerator > pair<_IntType, _IntType> std::__gen_two_uniform_ints (_IntType __b0, _IntType __b1, _UniformRandomBitGenerator && __g)
Generate two uniformly distributed integers using a single distribution invocation.
Parameters
__b0 The upper bound for the first integer.
__b1 The upper bound for the second integer.
__g A UniformRandomBitGenerator.
Returns
A pair (i, j) with i and j uniformly distributed over [0, __b0) and [0, __b1), respectively.
Requires: __b0 * __b1 <= __g.max() - __g.min().
Using uniform_int_distribution with a range that is very small relative to the range of the generator ends up wasting potentially expensively generated randomness, since uniform_int_distribution does not store leftover randomness between invocations.
If we know we want two integers in ranges that are sufficiently small, we can compose the ranges, use a single distribution invocation, and significantly reduce the waste.
Definition at line 3673 of file stl_algo.h.
Referenced by __sample().
__heap_select()
template<typename _RandomAccessIterator , typename _Compare > constexpr void std::__heap_select (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last, _Compare __comp) constexpr
This is a helper function for the sort routines.
Definition at line 1625 of file stl_algo.h.
__inplace_stable_sort()
template<typename _RandomAccessIterator , typename _Compare > void std::__inplace_stable_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
This is a helper function for the stable sorting routines.
Definition at line 2739 of file stl_algo.h.
References __insertion_sort(), and __merge_without_buffer().
__insertion_sort()
template<typename _RandomAccessIterator , typename _Compare > constexpr void std::__insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp) constexpr
This is a helper function for the sort routine.
Definition at line 1802 of file stl_algo.h.
Referenced by __final_insertion_sort(), and __inplace_stable_sort().
__introsort_loop()
template<typename _RandomAccessIterator , typename _Size , typename _Compare > constexpr void std::__introsort_loop (_RandomAccessIterator __first, _RandomAccessIterator __last, _Size __depth_limit, _Compare __comp) constexpr
This is a helper function for the sort routine.
Definition at line 1908 of file stl_algo.h.
References __unguarded_partition_pivot().
__lg()
constexpr int std::__lg (int __n) inline constexpr
This is a helper function for the sort routines and for random.tcc.
Definition at line 1505 of file stl_algobase.h.
Referenced by std::linear_congruential_engine< _UIntType, __a, __c, __m >::seed().
__merge_adaptive()
template<typename _BidirectionalIterator , typename _Distance , typename _Pointer , typename _Compare > void std::__merge_adaptive (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Distance __len1, _Distance __len2, _Pointer __buffer, _Distance __buffer_size, _Compare __comp)
This is a helper function for the merge routines.
Definition at line 2390 of file stl_algo.h.
__merge_without_buffer()
template<typename _BidirectionalIterator , typename _Distance , typename _Compare > void std::__merge_without_buffer (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, _Distance __len1, _Distance __len2, _Compare __comp)
This is a helper function for the merge routines.
Definition at line 2451 of file stl_algo.h.
References advance().
Referenced by __inplace_stable_sort().
__move_median_to_first()
template<typename _Iterator , typename _Compare > constexpr void std::__move_median_to_first (_Iterator __result, _Iterator __a, _Iterator __b, _Iterator __c, _Compare __comp) constexpr
Swaps the median value of *__a, *__b and *__c under __comp to *__result.
Definition at line 82 of file stl_algo.h.
Referenced by __unguarded_partition_pivot().
__move_merge()
template<typename _InputIterator , typename _OutputIterator , typename _Compare > _OutputIterator std::__move_merge (_InputIterator __first1, _InputIterator __last1, _InputIterator __first2, _InputIterator __last2, _OutputIterator __result, _Compare __comp)
This is a helper function for the __merge_sort_loop routines.
Definition at line 2615 of file stl_algo.h.
__move_merge_adaptive()
template<typename _InputIterator1 , typename _InputIterator2 , typename _OutputIterator , typename _Compare > void std::__move_merge_adaptive (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2, _OutputIterator __result, _Compare __comp)
This is a helper function for the __merge_adaptive routines.
Definition at line 2283 of file stl_algo.h.
__move_merge_adaptive_backward()
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 , typename _BidirectionalIterator3 , typename _Compare > void std::__move_merge_adaptive_backward (_BidirectionalIterator1 __first1, _BidirectionalIterator1 __last1, _BidirectionalIterator2 __first2, _BidirectionalIterator2 __last2, _BidirectionalIterator3 __result, _Compare __comp)
This is a helper function for the __merge_adaptive routines.
Definition at line 2309 of file stl_algo.h.
__partition() [1/2]
template<typename _BidirectionalIterator , typename _Predicate > constexpr _BidirectionalIterator std::__partition (_BidirectionalIterator __first, _BidirectionalIterator __last, _Predicate __pred, bidirectional_iterator_tag) constexpr
This is a helper function...
Definition at line 1470 of file stl_algo.h.
__partition() [2/2]
template<typename _ForwardIterator , typename _Predicate > constexpr _ForwardIterator std::__partition (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, forward_iterator_tag) constexpr
This is a helper function...
Definition at line 1444 of file stl_algo.h.
__reverse() [1/2]
template<typename _BidirectionalIterator > constexpr void std::__reverse (_BidirectionalIterator __first, _BidirectionalIterator __last, bidirectional_iterator_tag) constexpr
This is an uglified reverse(_BidirectionalIterator, _BidirectionalIterator) overloaded for bidirectional iterators.
Definition at line 1078 of file stl_algo.h.
__reverse() [2/2]
template<typename _RandomAccessIterator > constexpr void std::__reverse (_RandomAccessIterator __first, _RandomAccessIterator __last, random_access_iterator_tag) constexpr
This is an uglified reverse(_BidirectionalIterator, _BidirectionalIterator) overloaded for random access iterators.
Definition at line 1099 of file stl_algo.h.
__rotate() [1/3]
template<typename _BidirectionalIterator > constexpr _BidirectionalIterator std::_V2::__rotate (_BidirectionalIterator __first, _BidirectionalIterator __middle, _BidirectionalIterator __last, bidirectional_iterator_tag) constexpr
This is a helper function for the rotate algorithm.
Definition at line 1242 of file stl_algo.h.
References __rotate().
__rotate() [2/3]
template<typename _ForwardIterator > constexpr _ForwardIterator std::_V2::__rotate (_ForwardIterator __first, _ForwardIterator __middle, _ForwardIterator __last, forward_iterator_tag) constexpr
This is a helper function for the rotate algorithm.
Definition at line 1200 of file stl_algo.h.
References __rotate().
Referenced by __rotate().
__rotate() [3/3]
template<typename _RandomAccessIterator > constexpr _RandomAccessIterator std::_V2::__rotate (_RandomAccessIterator __first, _RandomAccessIterator __middle, _RandomAccessIterator __last, random_access_iterator_tag) constexpr
This is a helper function for the rotate algorithm.
Definition at line 1281 of file stl_algo.h.
References __rotate().
__rotate_adaptive()
template<typename _BidirectionalIterator1 , typename _BidirectionalIterator2 , typename _Distance > _BidirectionalIterator1 std::__rotate_adaptive (_BidirectionalIterator1 __first, _BidirectionalIterator1 __middle, _BidirectionalIterator1 __last, _Distance __len1, _Distance __len2, _BidirectionalIterator2 __buffer, _Distance __buffer_size)
This is a helper function for the merge routines.
Definition at line 2352 of file stl_algo.h.
__sample() [1/2]
template<typename _ForwardIterator , typename _OutputIterator , typename _Cat , typename _Size , typename _UniformRandomBitGenerator > _OutputIterator std::__sample (_ForwardIterator __first, _ForwardIterator __last, forward_iterator_tag , _OutputIterator __out, _Cat , _Size __n, _UniformRandomBitGenerator && __g)
Selection sampling algorithm.
Definition at line 5796 of file stl_algo.h.
References __gen_two_uniform_ints(), distance(), std::pair< _T1, _T2 >::first, min(), and std::pair< _T1, _T2 >::second.
Referenced by sample().
__sample() [2/2]
template<typename _InputIterator , typename _RandomAccessIterator , typename _Size , typename _UniformRandomBitGenerator > _RandomAccessIterator std::__sample (_InputIterator __first, _InputIterator __last, input_iterator_tag , _RandomAccessIterator __out, random_access_iterator_tag , _Size __n, _UniformRandomBitGenerator && __g)
Reservoir sampling algorithm.
Definition at line 5769 of file stl_algo.h.
__search_n_aux() [1/2]
template<typename _ForwardIterator , typename _Integer , typename _UnaryPredicate > constexpr _ForwardIterator std::__search_n_aux (_ForwardIterator __first, _ForwardIterator __last, _Integer __count, _UnaryPredicate __unary_pred, std::forward_iterator_tag) constexpr
This is an helper function for search_n overloaded for forward iterators.
Definition at line 197 of file stl_algo.h.
References __find_if().
__search_n_aux() [2/2]
template<typename _RandomAccessIter , typename _Integer , typename _UnaryPredicate > constexpr _RandomAccessIter std::__search_n_aux (_RandomAccessIter __first, _RandomAccessIter __last, _Integer __count, _UnaryPredicate __unary_pred, std::random_access_iterator_tag) constexpr
This is an helper function for search_n overloaded for random access iterators.
Definition at line 230 of file stl_algo.h.
__stable_partition_adaptive()
template<typename _ForwardIterator , typename _Pointer , typename _Predicate , typename _Distance > _ForwardIterator std::__stable_partition_adaptive (_ForwardIterator __first, _ForwardIterator __last, _Predicate __pred, _Distance __len, _Pointer __buffer, _Distance __buffer_size)
This is a helper function... Requires __first != __last and !__pred(__first) and __len == distance(__first, __last).
!__pred(__first) allows us to guarantee that we don't move-assign an element onto itself.
Definition at line 1506 of file stl_algo.h.
__unguarded_insertion_sort()
template<typename _RandomAccessIterator , typename _Compare > constexpr void std::__unguarded_insertion_sort (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp) inline constexpr
This is a helper function for the sort routine.
Definition at line 1826 of file stl_algo.h.
References __unguarded_linear_insert().
Referenced by __final_insertion_sort().
__unguarded_linear_insert()
template<typename _RandomAccessIterator , typename _Compare > constexpr void std::__unguarded_linear_insert (_RandomAccessIterator __last, _Compare __comp) constexpr
This is a helper function for the sort routine.
Definition at line 1782 of file stl_algo.h.
Referenced by __unguarded_insertion_sort().
__unguarded_partition()
template<typename _RandomAccessIterator , typename _Compare > constexpr _RandomAccessIterator std::__unguarded_partition (_RandomAccessIterator __first, _RandomAccessIterator __last, _RandomAccessIterator __pivot, _Compare __comp) constexpr
This is a helper function...
Definition at line 1861 of file stl_algo.h.
Referenced by __unguarded_partition_pivot().
__unguarded_partition_pivot()
template<typename _RandomAccessIterator , typename _Compare > constexpr _RandomAccessIterator std::__unguarded_partition_pivot (_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp) inline constexpr
This is a helper function...
Definition at line 1883 of file stl_algo.h.
References __move_median_to_first(), and __unguarded_partition().
Referenced by __introsort_loop().
__unique_copy() [1/3]
template<typename _ForwardIterator , typename _OutputIterator , typename _BinaryPredicate > constexpr _OutputIterator std::__unique_copy (_ForwardIterator __first, _ForwardIterator __last, _OutputIterator __result, _BinaryPredicate __binary_pred, forward_iterator_tag , output_iterator_tag) constexpr
This is an uglified unique_copy(_InputIterator, _InputIterator, _OutputIterator, _BinaryPredicate) overloaded for forward iterators and output iterator as result.
Definition at line 992 of file stl_algo.h.
__unique_copy() [2/3]
template<typename _InputIterator , typename _ForwardIterator , typename _BinaryPredicate > constexpr _ForwardIterator std::__unique_copy (_InputIterator __first, _InputIterator __last, _ForwardIterator __result, _BinaryPredicate __binary_pred, input_iterator_tag , forward_iterator_tag) constexpr
This is an uglified unique_copy(_InputIterator, _InputIterator, _OutputIterator, _BinaryPredicate) overloaded for input iterators and forward iterator as result.
Definition at line 1055 of file stl_algo.h.
__unique_copy() [3/3]
template<typename _InputIterator , typename _OutputIterator , typename _BinaryPredicate > constexpr _OutputIterator std::__unique_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, _BinaryPredicate __binary_pred, input_iterator_tag , output_iterator_tag) constexpr
This is an uglified unique_copy(_InputIterator, _InputIterator, _OutputIterator, _BinaryPredicate) overloaded for input iterators and output iterator as result.
Definition at line 1022 of file stl_algo.h.
_Construct()
template<typename _Tp , typename... _Args> constexpr void std::_Construct (_Tp * __p, _Args &&... __args) inline constexpr
Constructs an object in existing memory by invoking an allocated object's constructor with an initializer.
Definition at line 109 of file stl_construct.h.
Referenced by std::allocator_traits< allocator< void > >::construct().
_Destroy() [1/3]
template<typename _ForwardIterator > constexpr void std::_Destroy (_ForwardIterator __first, _ForwardIterator __last) inline constexpr
Destroy a range of objects. If the value_type of the object has a trivial destructor, the compiler should optimize all of this away, otherwise the objects' destructors must be invoked.
Definition at line 182 of file stl_construct.h.
_Destroy() [2/3]
template<typename _ForwardIterator , typename _Allocator > constexpr void std::_Destroy (_ForwardIterator __first, _ForwardIterator __last, _Allocator & __alloc) constexpr
Destroy a range of objects using the supplied allocator. For non-default allocators we do not optimize away invocation of destroy() even if _Tp has a trivial destructor.
Definition at line 832 of file bits/alloc_traits.h.
References __addressof(), and std::allocator_traits< _Alloc >::destroy().
Referenced by std::vector< _Tp, _Alloc >::~vector(), and std::allocator_traits< allocator< void > >::destroy().
_Destroy() [3/3]
template<typename _Tp > constexpr void std::_Destroy (_Tp * __pointer) inline constexpr
Destroy the object pointed to by a pointer type.
Definition at line 146 of file stl_construct.h.
_Destroy_n()
template<typename _ForwardIterator , typename _Size > constexpr _ForwardIterator std::_Destroy_n (_ForwardIterator __first, _Size __count) inline constexpr
Destroy a range of objects. If the value_type of the object has a trivial destructor, the compiler should optimize all of this away, otherwise the objects' destructors must be invoked.
Definition at line 231 of file stl_construct.h.
acos()
template<typename _Tp > std::complex< _Tp > std::acos (const std::complex< _Tp > & __z) inline
acos(__z) [8.1.2].
Definition at line 1609 of file complex.
acosh()
template<typename _Tp > std::complex< _Tp > std::acosh (const std::complex< _Tp > & __z) inline
acosh(__z) [8.1.5].
Definition at line 1725 of file complex.
advance()
template<typename _InputIterator , typename _Distance > constexpr void std::advance (_InputIterator & __i, _Distance __n) inline constexpr
A generalization of pointer arithmetic.
Parameters
__i An input iterator.
__n The delta by which to change __i.
Returns
Nothing.
This increments i by n. For bidirectional and random access iterators, __n may be negative, in which case __i is decremented.
For random access iterators, this uses their + and - operations and are constant time. For other iterator classes they are linear time.
Definition at line 218 of file stl_iterator_base_funcs.h.
References __iterator_category().
Referenced by __merge_without_buffer().
arg()
template<typename _Tp > __gnu_cxx::__promote<_Tp>::__type std::arg (_Tp __x) inline
Additional overloads [8.1.9].
Definition at line 1823 of file complex.
asin()
template<typename _Tp > std::complex< _Tp > std::asin (const std::complex< _Tp > & __z) inline
asin(__z) [8.1.3].
Definition at line 1645 of file complex.
asinh()
template<typename _Tp > std::complex< _Tp > std::asinh (const std::complex< _Tp > & __z) inline
asinh(__z) [8.1.6].
Definition at line 1764 of file complex.
atan()
template<typename _Tp > std::complex< _Tp > std::atan (const std::complex< _Tp > & __z) inline
atan(__z) [8.1.4].
Definition at line 1689 of file complex.
atanh()
template<typename _Tp > std::complex< _Tp > std::atanh (const std::complex< _Tp > & __z) inline
atanh(__z) [8.1.7].
Definition at line 1808 of file complex.
begin() [1/3]
template<typename _Container > constexpr auto std::begin (_Container & __cont) -> decltype(__cont.begin()) inline constexpr
Return an iterator pointing to the first element of the container.
Parameters
__cont Container.
Definition at line 52 of file range_access.h.
begin() [2/3]
template<typename _Tp , size_t _Nm> constexpr _Tp* std::begin (_Tp(&) __arr[_Nm]) inline constexpr noexcept
Return an iterator pointing to the first element of the array.
Parameters
__arr Array.
Definition at line 95 of file range_access.h.
begin() [3/3]
template<typename _Container > constexpr auto std::begin (const _Container & __cont) -> decltype(__cont.begin()) inline constexpr
Return an iterator pointing to the first element of the const container.
Parameters
__cont Container.
Definition at line 63 of file range_access.h.
bind_front()
template<typename _Fn , typename... _Args> constexpr _Bind_front_t<_Fn, _Args...> std::bind_front (_Fn && __fn, _Args &&... __args) constexpr noexcept
Create call wrapper by partial application of arguments to function.
The result of std::bind_front(f, args...) is a function object that stores f and the bound arguments, args.... When that function object is invoked with call_args... it returns the result of calling f(args..., call_args...).
Since
C++20
Definition at line 986 of file functional.
boolalpha()
ios_base& std::boolalpha (ios_base & __base) inline
Calls base.setf(ios_base::boolalpha).
Definition at line 917 of file ios_base.h.
References __gnu_debug::__base(), and std::ios_base::boolalpha.
cbegin()
template<typename _Container > constexpr auto std::cbegin (const _Container & __cont) -> decltype(std::begin(__cont)) constexpr noexcept
Return an iterator pointing to the first element of the const container.
Parameters
__cont Container.
Definition at line 126 of file range_access.h.
References begin().
cend()
template<typename _Container > constexpr auto std::cend (const _Container & __cont) -> decltype(std::end(__cont)) constexpr noexcept
Return an iterator pointing to one past the last element of the const container.
Parameters
__cont Container.
Definition at line 138 of file range_access.h.
References end().
const_pointer_cast()
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp> __shared_ptr<_Tp, _Lp> std::const_pointer_cast (const __shared_ptr< _Tp1, _Lp > & __r) inline noexcept
const_pointer_cast
Definition at line 1942 of file shared_ptr_base.h.
crbegin()
template<typename _Container > constexpr auto std::crbegin (const _Container & __cont) -> decltype(std::rbegin(__cont)) inline constexpr
Return a reverse iterator pointing to the last element of the const container.
Parameters
__cont Container.
Definition at line 238 of file range_access.h.
References rbegin().
crend()
template<typename _Container > constexpr auto std::crend (const _Container & __cont) -> decltype(std::rend(__cont)) inline constexpr
Return a reverse iterator pointing one past the first element of the const container.
Parameters
__cont Container.
Definition at line 249 of file range_access.h.
References rend().
data() [1/4]
template<typename _Container > constexpr auto std::data (_Container & __cont) -> decltype(__cont.data()) constexpr noexcept
Return the data pointer of a container.
Parameters
__cont Container.
Definition at line 311 of file range_access.h.
data() [2/4]
template<typename _Tp , size_t _Nm> constexpr _Tp* std::data (_Tp(&) __array[_Nm]) constexpr noexcept
Return the data pointer of an array.
Parameters
__array Array.
Definition at line 333 of file range_access.h.
data() [3/4]
template<typename _Container > constexpr auto std::data (const _Container & __cont) -> decltype(__cont.data()) constexpr noexcept
Return the data pointer of a const container.
Parameters
__cont Container.
Definition at line 322 of file range_access.h.
data() [4/4]
template<typename _Tp > constexpr const _Tp* std::data (initializer_list< _Tp > __il) constexpr noexcept
Return the data pointer of an initializer list.
Parameters
__il Initializer list.
Definition at line 343 of file range_access.h.
dec()
ios_base& std::dec (ios_base & __base) inline
Calls base.setf(ios_base::dec, ios_base::basefield).
Definition at line 1055 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::basefield, and std::ios_base::dec.
Referenced by operator<<(), and operator>>().
defaultfloat()
ios_base& std::defaultfloat (ios_base & __base) inline
Calls base.unsetf(ios_base::floatfield)
Definition at line 1108 of file ios_base.h.
References __gnu_debug::__base(), and std::ios_base::floatfield.
distance()
template<typename _InputIterator > constexpr iterator_traits<_InputIterator>::difference_type std::distance (_InputIterator __first, _InputIterator __last) inline constexpr
A generalization of pointer arithmetic.
Parameters
__first An input iterator.
__last An input iterator.
Returns
The distance between them.
Returns n such that __first + n == __last. This requires that __last must be reachable from __first. Note that n may be negative.
For random access iterators, this uses their + and - operations and are constant time. For other iterator classes they are linear time.
Definition at line 147 of file stl_iterator_base_funcs.h.
References __iterator_category().
Referenced by __sample(), std::deque< _Tp, _Alloc >::_M_range_initialize(), std::sub_match< _BiIter >::length(), __gnu_parallel::multiseq_partition(), __gnu_parallel::multiseq_selection(), and std::match_results< _Bi_iter, _Alloc >::position().
dynamic_pointer_cast()
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp> __shared_ptr<_Tp, _Lp> std::dynamic_pointer_cast (const __shared_ptr< _Tp1, _Lp > & __r) inline noexcept
dynamic_pointer_cast
Definition at line 1955 of file shared_ptr_base.h.
empty() [1/3]
template<typename _Container > constexpr auto std::empty (const _Container & __cont) -> decltype(__cont.empty()) constexpr noexcept
Return whether a container is empty.
Parameters
__cont Container.
Definition at line 283 of file range_access.h.
empty() [2/3]
template<typename _Tp , size_t _Nm> constexpr bool std::empty (const _Tp(&)[_Nm]) constexpr noexcept
Return whether an array is empty (always false).
Definition at line 292 of file range_access.h.
empty() [3/3]
template<typename _Tp > constexpr bool std::empty (initializer_list< _Tp > __il) constexpr noexcept
Return whether an initializer_list is empty.
Parameters
__il Initializer list.
Definition at line 301 of file range_access.h.
end() [1/3]
template<typename _Container > constexpr auto std::end (_Container & __cont) -> decltype(__cont.end()) inline constexpr
Return an iterator pointing to one past the last element of the container.
Parameters
__cont Container.
Definition at line 74 of file range_access.h.
end() [2/3]
template<typename _Tp , size_t _Nm> constexpr _Tp* std::end (_Tp(&) __arr[_Nm]) inline constexpr noexcept
Return an iterator pointing to one past the last element of the array.
Parameters
__arr Array.
Definition at line 106 of file range_access.h.
end() [3/3]
template<typename _Container > constexpr auto std::end (const _Container & __cont) -> decltype(__cont.end()) inline constexpr
Return an iterator pointing to one past the last element of the const container.
Parameters
__cont Container.
Definition at line 85 of file range_access.h.
endl()
template<typename _CharT , typename _Traits > basic_ostream<_CharT, _Traits>& std::endl (basic_ostream< _CharT, _Traits > & __os) inline
Write a newline and flush the stream.
This manipulator is often mistakenly used when a simple newline is desired, leading to poor buffering performance. See https://gcc.gnu.org/onlinedocs/libstdc++/manual/streambufs.html#io.streambuf.buffering for more on this subject.
Definition at line 688 of file ostream.
ends()
template<typename _CharT , typename _Traits > basic_ostream<_CharT, _Traits>& std::ends (basic_ostream< _CharT, _Traits > & __os) inline
Write a null character into the output sequence.
Null character is CharT() by definition. For CharT of char, this correctly writes the ASCII NUL character string terminator.
Definition at line 700 of file ostream.
exchange()
template<typename _Tp , typename _Up = _Tp> constexpr _Tp std::exchange (_Tp & __obj, _Up && __new_val) inline constexpr noexcept
Assign __new_val to __obj and return its previous value.
Definition at line 93 of file utility.
fabs()
template<typename _Tp > _Tp std::fabs (const std::complex< _Tp > & __z) inline
fabs(__z) [8.1.8].
Definition at line 1817 of file complex.
fixed()
ios_base& std::fixed (ios_base & __base) inline
Calls base.setf(ios_base::fixed, ios_base::floatfield).
Definition at line 1080 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::fixed, and std::ios_base::floatfield.
flush()
template<typename _CharT , typename _Traits > basic_ostream<_CharT, _Traits>& std::flush (basic_ostream< _CharT, _Traits > & __os) inline
Flushes the output stream.
This manipulator simply calls the stream's flush() member function.
Definition at line 710 of file ostream.
from_chars()
template<typename _Tp > __detail::__integer_from_chars_result_type<_Tp> std::from_chars (const char * __first, const char * __last, _Tp & __value, int __base = 10)
std::from_chars for integral types.
Definition at line 550 of file charconv.
gcd()
template<typename _Mn , typename _Nn > constexpr common_type_t<_Mn, _Nn> std::gcd (_Mn __m, _Nn __n) constexpr noexcept
Greatest common divisor.
Definition at line 164 of file numeric.
get() [1/12]
template<typename _Tp , typename _Up > constexpr const _Tp&& std::get (const pair< _Tp, _Up > && __p) constexpr noexcept
std::get overloads for accessing members of std::pair
Definition at line 894 of file stl_pair.h.
References move().
get() [2/12]
template<typename _Tp , typename _Up > constexpr const _Tp& std::get (const pair< _Tp, _Up > & __p) constexpr noexcept
std::get overloads for accessing members of std::pair
Definition at line 884 of file stl_pair.h.
get() [3/12]
template<size_t _Int, class _Tp1 , class _Tp2 > constexpr const tuple_element<_Int, pair<_Tp1, _Tp2> >::type&& std::get (const pair< _Tp1, _Tp2 > && __in) constexpr noexcept
std::get overloads for accessing members of std::pair
Definition at line 870 of file stl_pair.h.
References move().
get() [4/12]
template<size_t _Int, class _Tp1 , class _Tp2 > constexpr const tuple_element<_Int, pair<_Tp1, _Tp2> >::type& std::get (const pair< _Tp1, _Tp2 > & __in) constexpr noexcept
std::get overloads for accessing members of std::pair
Definition at line 865 of file stl_pair.h.
get() [5/12]
template<typename _Tp , typename _Up > constexpr const _Tp&& std::get (const pair< _Up, _Tp > && __p) constexpr noexcept
std::get overloads for accessing members of std::pair
Definition at line 914 of file stl_pair.h.
References move().
get() [6/12]
template<typename _Tp , typename _Up > constexpr const _Tp& std::get (const pair< _Up, _Tp > & __p) constexpr noexcept
std::get overloads for accessing members of std::pair
Definition at line 904 of file stl_pair.h.
get() [7/12]
template<typename _Tp , typename _Up > constexpr _Tp&& std::get (pair< _Tp, _Up > && __p) constexpr noexcept
std::get overloads for accessing members of std::pair
Definition at line 889 of file stl_pair.h.
References move().
get() [8/12]
template<typename _Tp , typename _Up > constexpr _Tp& std::get (pair< _Tp, _Up > & __p) constexpr noexcept
std::get overloads for accessing members of std::pair
Definition at line 879 of file stl_pair.h.
get() [9/12]
template<size_t _Int, class _Tp1 , class _Tp2 > constexpr tuple_element<_Int, pair<_Tp1, _Tp2> >::type&& std::get (pair< _Tp1, _Tp2 > && __in) constexpr noexcept
std::get overloads for accessing members of std::pair
Definition at line 860 of file stl_pair.h.
References move().
get() [10/12]
template<size_t _Int, class _Tp1 , class _Tp2 > constexpr tuple_element<_Int, pair<_Tp1, _Tp2> >::type& std::get (pair< _Tp1, _Tp2 > & __in) constexpr noexcept
std::get overloads for accessing members of std::pair
Definition at line 855 of file stl_pair.h.
get() [11/12]
template<typename _Tp , typename _Up > constexpr _Tp&& std::get (pair< _Up, _Tp > && __p) constexpr noexcept
std::get overloads for accessing members of std::pair
Definition at line 909 of file stl_pair.h.
References move().
get() [12/12]
template<typename _Tp , typename _Up > constexpr _Tp& std::get (pair< _Up, _Tp > & __p) constexpr noexcept
std::get overloads for accessing members of std::pair
Definition at line 899 of file stl_pair.h.
get_money()
template<typename _MoneyT > _Get_money<_MoneyT> std::get_money (_MoneyT & __mon, bool __intl = false) inline
Extended manipulator for extracting money.
Parameters
__mon Either long double or a specialization of basic_string.
__intl A bool indicating whether international format is to be used.
Sent to a stream object, this manipulator extracts __mon.
Definition at line 259 of file iomanip.
get_new_handler()
new_handler std::get_new_handler () noexcept
Return the current new handler.
get_temporary_buffer()
template<typename _Tp > pair<_Tp*, ptrdiff_t> std::get_temporary_buffer (ptrdiff_t __len) noexcept
Allocates a temporary buffer.
Parameters
__len The number of objects of type Tp.
Returns
See full description.
Reinventing the wheel, but this time with prettier spokes!
This function tries to obtain storage for __len adjacent Tp objects. The objects themselves are not constructed, of course. A pair<> is returned containing the buffer s address and capacity (in the units of sizeof(_Tp)), or a pair of 0 values if no storage can be obtained. Note that the capacity obtained may be less than that requested if the memory is unavailable; you should compare len with the .second return value.
Provides the nothrow exception guarantee.
Definition at line 101 of file stl_tempbuf.h.
get_time()
template<typename _CharT > _Get_time<_CharT> std::get_time (std::tm * __tmb, const _CharT * __fmt) inline
Extended manipulator for extracting time.
This manipulator uses time_get::get to extract time. [ext.manip]
Parameters
__tmb struct to extract the time data to.
__fmt format string.
Definition at line 413 of file iomanip.
getline() [1/6]
template<typename _CharT , typename _Traits , typename _Alloc > basic_istream<_CharT, _Traits>& std::getline (basic_istream< _CharT, _Traits > && __is, basic_string< _CharT, _Traits, _Alloc > & __str) inline
Read a line from an rvalue stream into a string.
Definition at line 3938 of file basic_string.h.
References getline().
getline() [2/6]
template<typename _CharT , typename _Traits , typename _Alloc > basic_istream<_CharT, _Traits>& std::getline (basic_istream< _CharT, _Traits > && __is, basic_string< _CharT, _Traits, _Alloc > & __str, _CharT __delim) inline
Read a line from an rvalue stream into a string.
Definition at line 3931 of file basic_string.h.
References getline().
getline() [3/6]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> basic_istream<_CharT, _Traits>& std::getline (basic_istream< _CharT, _Traits > & __is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > & __str) inline
Read a line from stream into a string.
Parameters
__is Input stream.
__str Buffer to store into.
Returns
Reference to the input stream.
Stores characters from is into __str until '
' is found, the end of the stream is encountered, or str.max_size() is reached. If is.width() is non-zero, that is the limit on the number of characters stored into __str. Any previous contents of __str are erased. If end of line was encountered, it is extracted but not stored into __str.
Definition at line 2678 of file vstring.h.
References getline(), and std::basic_ios< _CharT, _Traits >::widen().
getline() [4/6]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> basic_istream< _CharT, _Traits > & std::getline (basic_istream< _CharT, _Traits > & __is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > & __str, _CharT __delim)
Read a line from stream into a string.
Parameters
__is Input stream.
__str Buffer to store into.
__delim Character marking end of line.
Returns
Reference to the input stream.
Stores characters from __is into __str until __delim is found, the end of the stream is encountered, or str.max_size() is reached. If is.width() is non-zero, that is the limit on the number of characters stored into __str. Any previous contents of __str are erased. If delim was encountered, it is extracted but not stored into __str.
Definition at line 627 of file vstring.tcc.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::max_size().
getline() [5/6]
template<typename _CharT , typename _Traits , typename _Alloc > basic_istream<_CharT, _Traits>& std::getline (basic_istream< _CharT, _Traits > & __is, basic_string< _CharT, _Traits, _Alloc > & __str) inline
Read a line from stream into a string.
Parameters
__is Input stream.
__str Buffer to store into.
Returns
Reference to the input stream.
Stores characters from is into __str until '
' is found, the end of the stream is encountered, or str.max_size() is reached. Any previous contents of __str are erased. If end of line is encountered, it is extracted but not stored into __str.
Definition at line 3923 of file basic_string.h.
References getline(), and std::basic_ios< _CharT, _Traits >::widen().
getline() [6/6]
template<typename _CharT , typename _Traits , typename _Alloc > basic_istream< _CharT, _Traits > & std::getline (basic_istream< _CharT, _Traits > & __is, basic_string< _CharT, _Traits, _Alloc > & __str, _CharT __delim)
Read a line from stream into a string.
Parameters
__is Input stream.
__str Buffer to store into.
__delim Character marking end of line.
Returns
Reference to the input stream.
Stores characters from __is into __str until __delim is found, the end of the stream is encountered, or str.max_size() is reached. Any previous contents of __str are erased. If __delim is encountered, it is extracted but not stored into __str.
Definition at line 1012 of file basic_string.tcc.
References std::basic_string< _CharT, _Traits, _Alloc >::max_size().
Referenced by getline().
hex()
ios_base& std::hex (ios_base & __base) inline
Calls base.setf(ios_base::hex, ios_base::basefield).
Definition at line 1063 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::basefield, and std::ios_base::hex.
hexfloat()
ios_base& std::hexfloat (ios_base & __base) inline
Calls base.setf(ios_base::fixed|ios_basescientific, ios_base::floatfield)
Definition at line 1100 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::fixed, std::ios_base::floatfield, and std::ios_base::scientific.
internal()
ios_base& std::internal (ios_base & __base) inline
Calls base.setf(ios_base::internal, ios_base::adjustfield).
Definition at line 1030 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::adjustfield, and std::ios_base::internal.
invoke()
template<typename _Callable , typename... _Args> constexpr invoke_result_t<_Callable, _Args...> std::invoke (_Callable && __fn, _Args &&... __args) inline constexpr noexcept
Invoke a callable object.
std::invoke takes a callable object as its first argument and calls it with the remaining arguments. The callable object can be a pointer or reference to a function, a lambda closure, a class with operator(), or even a pointer-to-member. For a pointer-to-member the first argument must be a reference or pointer to the object that the pointer-to-member will be applied to.
Since
C++17
Definition at line 107 of file functional.
isalnum()
template<typename _CharT > bool std::isalnum (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::alnum, __c).
Definition at line 2655 of file locale_facets.h.
isalpha()
template<typename _CharT > bool std::isalpha (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::alpha, __c).
Definition at line 2631 of file locale_facets.h.
isblank()
template<typename _CharT > bool std::isblank (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::blank, __c).
Definition at line 2668 of file locale_facets.h.
iscntrl()
template<typename _CharT > bool std::iscntrl (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::cntrl, __c).
Definition at line 2613 of file locale_facets.h.
isdigit()
template<typename _CharT > bool std::isdigit (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::digit, __c).
Definition at line 2637 of file locale_facets.h.
isgraph()
template<typename _CharT > bool std::isgraph (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::graph, __c).
Definition at line 2661 of file locale_facets.h.
islower()
template<typename _CharT > bool std::islower (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::lower, __c).
Definition at line 2625 of file locale_facets.h.
isprint()
template<typename _CharT > bool std::isprint (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::print, __c).
Definition at line 2607 of file locale_facets.h.
ispunct()
template<typename _CharT > bool std::ispunct (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::punct, __c).
Definition at line 2643 of file locale_facets.h.
isspace()
template<typename _CharT > bool std::isspace (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::space, __c).
Definition at line 2601 of file locale_facets.h.
isupper()
template<typename _CharT > bool std::isupper (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::upper, __c).
Definition at line 2619 of file locale_facets.h.
isxdigit()
template<typename _CharT > bool std::isxdigit (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.is(ctype_base::xdigit, __c).
Definition at line 2649 of file locale_facets.h.
launder()
template<typename _Tp > constexpr _Tp* std::launder (_Tp * __p) constexpr noexcept
Pointer optimization barrier [ptr.launder].
Definition at line 193 of file new.
lcm()
template<typename _Mn , typename _Nn > constexpr common_type_t<_Mn, _Nn> std::lcm (_Mn __m, _Nn __n) constexpr noexcept
Least common multiple.
Definition at line 179 of file numeric.
left()
ios_base& std::left (ios_base & __base) inline
Calls base.setf(ios_base::left, ios_base::adjustfield).
Definition at line 1038 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::adjustfield, and std::ios_base::left.
noboolalpha()
ios_base& std::noboolalpha (ios_base & __base) inline
Calls base.unsetf(ios_base::boolalpha).
Definition at line 925 of file ios_base.h.
References __gnu_debug::__base(), and std::ios_base::boolalpha.
noshowbase()
ios_base& std::noshowbase (ios_base & __base) inline
Calls base.unsetf(ios_base::showbase).
Definition at line 941 of file ios_base.h.
References __gnu_debug::__base(), and std::ios_base::showbase.
noshowpoint()
ios_base& std::noshowpoint (ios_base & __base) inline
Calls base.unsetf(ios_base::showpoint).
Definition at line 957 of file ios_base.h.
References __gnu_debug::__base(), and std::ios_base::showpoint.
noshowpos()
ios_base& std::noshowpos (ios_base & __base) inline
Calls base.unsetf(ios_base::showpos).
Definition at line 973 of file ios_base.h.
References __gnu_debug::__base(), and std::ios_base::showpos.
noskipws()
ios_base& std::noskipws (ios_base & __base) inline
Calls base.unsetf(ios_base::skipws).
Definition at line 989 of file ios_base.h.
References __gnu_debug::__base(), and std::ios_base::skipws.
nounitbuf()
ios_base& std::nounitbuf (ios_base & __base) inline
Calls base.unsetf(ios_base::unitbuf).
Definition at line 1021 of file ios_base.h.
References __gnu_debug::__base(), and std::ios_base::unitbuf.
nouppercase()
ios_base& std::nouppercase (ios_base & __base) inline
Calls base.unsetf(ios_base::uppercase).
Definition at line 1005 of file ios_base.h.
References __gnu_debug::__base(), and std::ios_base::uppercase.
oct()
ios_base& std::oct (ios_base & __base) inline
Calls base.setf(ios_base::oct, ios_base::basefield).
Definition at line 1071 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::basefield, and std::ios_base::oct.
operator!=() [1/13]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator!= (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test difference of C string and string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __rhs.compare(__lhs) != 0. False otherwise.
Definition at line 3666 of file basic_string.h.
operator!=() [2/13]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator!= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) inline
Test difference of string and C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs.compare(__rhs) != 0. False otherwise.
Definition at line 3678 of file basic_string.h.
operator!=() [3/13]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator!= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline noexcept
Test difference of two strings.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs.compare(__rhs) != 0. False otherwise.
Definition at line 3653 of file basic_string.h.
operator!=() [4/13]
template<typename _Tp , typename _Alloc > bool std::operator!= (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) inline
Based on operator==.
Definition at line 2338 of file stl_deque.h.
operator!=() [5/13]
template<typename _Tp , typename _Alloc > bool std::operator!= (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly) inline
Based on operator==.
Definition at line 1503 of file forward_list.h.
operator!=() [6/13]
template<typename _Tp , typename _Alloc > bool std::operator!= (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) inline
Based on operator==.
Definition at line 2189 of file stl_list.h.
operator!=() [7/13]
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator!= (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) inline
Based on operator==.
Definition at line 1556 of file stl_map.h.
operator!=() [8/13]
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator!= (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) inline
Based on operator==.
Definition at line 1177 of file stl_multimap.h.
operator!=() [9/13]
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator!= (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) inline
Returns !(x == y).
Definition at line 1017 of file stl_multiset.h.
operator!=() [10/13]
template<typename _Tp , typename _Seq > bool std::operator!= (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) inline
Based on operator==.
Definition at line 406 of file stl_queue.h.
operator!=() [11/13]
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator!= (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) inline
Returns !(x == y).
Definition at line 1030 of file stl_set.h.
operator!=() [12/13]
template<typename _Tp , typename _Seq > bool std::operator!= (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) inline
Based on operator==.
Definition at line 382 of file stl_stack.h.
operator!=() [13/13]
template<typename _Tp , typename _Alloc > bool std::operator!= (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) inline
Based on operator==.
Definition at line 2081 of file stl_vector.h.
operator&()
template<size_t _Nb> bitset<_Nb> std::operator& (const bitset< _Nb > & __x, const bitset< _Nb > & __y) inline noexcept
Global bitwise operations on bitsets.
Parameters
__x A bitset.
__y A bitset of the same size as __x.
Returns
A new bitset.
These should be self-explanatory.
Definition at line 1435 of file bitset.
operator+() [1/5]
template<typename _CharT , typename _Traits , typename _Alloc > constexpr basic_string< _CharT, _Traits, _Alloc > std::operator+ (_CharT __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) constexpr
Concatenate character and string.
Parameters
__lhs First string.
__rhs Last string.
Returns
New string with __lhs followed by __rhs.
Definition at line 627 of file basic_string.tcc.
References std::basic_string< _CharT, _Traits, _Alloc >::get_allocator(), and std::basic_string< _CharT, _Traits, _Alloc >::size().
operator+() [2/5]
template<typename _CharT , typename _Traits , typename _Alloc > constexpr basic_string< _CharT, _Traits, _Alloc > std::operator+ (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) constexpr
Concatenate C string and string.
Parameters
__lhs First string.
__rhs Last string.
Returns
New string with value of __lhs followed by __rhs.
Definition at line 606 of file basic_string.tcc.
operator+() [3/5]
template<typename _CharT , typename _Traits , typename _Alloc > constexpr basic_string<_CharT, _Traits, _Alloc> std::operator+ (const basic_string< _CharT, _Traits, _Alloc > & __lhs, _CharT __rhs) inline constexpr
Concatenate string and character.
Parameters
__lhs First string.
__rhs Last string.
Returns
New string with __lhs followed by __rhs.
Definition at line 3489 of file basic_string.h.
operator+() [4/5]
template<typename _CharT , typename _Traits , typename _Alloc > constexpr basic_string<_CharT, _Traits, _Alloc> std::operator+ (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) inline constexpr
Concatenate string and C string.
Parameters
__lhs First string.
__rhs Last string.
Returns
New string with __lhs followed by __rhs.
Definition at line 3472 of file basic_string.h.
operator+() [5/5]
template<typename _CharT , typename _Traits , typename _Alloc > constexpr basic_string<_CharT, _Traits, _Alloc> std::operator+ (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) constexpr
Concatenate two strings.
Parameters
__lhs First string.
__rhs Last string.
Returns
New string with value of __lhs followed by __rhs.
Definition at line 3432 of file basic_string.h.
operator<() [1/13]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator< (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test if C string precedes string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __lhs precedes __rhs. False otherwise.
Definition at line 3715 of file basic_string.h.
operator<() [2/13]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator< (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) inline
Test if string precedes C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs precedes __rhs. False otherwise.
Definition at line 3703 of file basic_string.h.
operator<() [3/13]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator< (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline noexcept
Test if string precedes string.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs precedes __rhs. False otherwise.
Definition at line 3690 of file basic_string.h.
operator<() [4/13]
template<typename _Tp , typename _Alloc > bool std::operator< (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) inline
Deque ordering relation.
Parameters
__x A deque.
__y A deque of the same type as __x.
Returns
True iff x is lexicographically less than __y.
This is a total ordering relation. It is linear in the size of the deques. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 2329 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::begin(), and std::deque< _Tp, _Alloc >::end().
operator<() [5/13]
template<typename _Tp , typename _Alloc > bool std::operator< (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly) inline
Forward list ordering relation.
Parameters
__lx A forward_list.
__ly A forward_list of the same type as __lx.
Returns
True iff __lx is lexicographically less than __ly.
This is a total ordering relation. It is linear in the number of elements of the forward lists. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 1493 of file forward_list.h.
References std::forward_list< _Tp, _Alloc >::cbegin(), and std::forward_list< _Tp, _Alloc >::cend().
operator<() [6/13]
template<typename _Tp , typename _Alloc > bool std::operator< (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) inline
List ordering relation.
Parameters
__x A list.
__y A list of the same type as __x.
Returns
True iff __x is lexicographically less than __y.
This is a total ordering relation. It is linear in the size of the lists. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 2180 of file stl_list.h.
References std::list< _Tp, _Alloc >::begin(), and std::list< _Tp, _Alloc >::end().
operator<() [7/13]
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator< (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) inline
Map ordering relation.
Parameters
__x A map.
__y A map of the same type as x.
Returns
True iff x is lexicographically less than y.
This is a total ordering relation. It is linear in the size of the maps. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 1548 of file stl_map.h.
operator<() [8/13]
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator< (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) inline
Multimap ordering relation.
Parameters
__x A multimap.
__y A multimap of the same type as __x.
Returns
True iff x is lexicographically less than y.
This is a total ordering relation. It is linear in the size of the multimaps. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 1169 of file stl_multimap.h.
operator<() [9/13]
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator< (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) inline
Multiset ordering relation.
Parameters
__x A multiset.
__y A multiset of the same type as __x.
Returns
True iff __x is lexicographically less than __y.
This is a total ordering relation. It is linear in the size of the sets. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 1009 of file stl_multiset.h.
operator<() [10/13]
template<typename _Tp , typename _Seq > bool std::operator< (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) inline
Queue ordering relation.
Parameters
__x A queue.
__y A queue of the same type as x.
Returns
True iff __x is lexicographically less than __y.
This is an total ordering relation. Complexity and semantics depend on the underlying sequence type, but the expected rules are: this relation is linear in the size of the sequences, the elements must be comparable with <, and std::lexicographical_compare() is usually used to make the determination.
Definition at line 398 of file stl_queue.h.
References std::queue< _Tp, _Sequence >::c.
operator<() [11/13]
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator< (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) inline
Set ordering relation.
Parameters
__x A set.
__y A set of the same type as x.
Returns
True iff __x is lexicographically less than __y.
This is a total ordering relation. It is linear in the size of the sets. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 1022 of file stl_set.h.
operator<() [12/13]
template<typename _Tp , typename _Seq > bool std::operator< (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) inline
Stack ordering relation.
Parameters
__x A stack.
__y A stack of the same type as x.
Returns
True iff x is lexicographically less than __y.
This is an total ordering relation. Complexity and semantics depend on the underlying sequence type, but the expected rules are: this relation is linear in the size of the sequences, the elements must be comparable with <, and std::lexicographical_compare() is usually used to make the determination.
Definition at line 374 of file stl_stack.h.
operator<() [13/13]
template<typename _Tp , typename _Alloc > bool std::operator< (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) inline
Vector ordering relation.
Parameters
__x A vector.
__y A vector of the same type as __x.
Returns
True iff __x is lexicographically less than __y.
This is a total ordering relation. It is linear in the size of the vectors. The elements must be comparable with <.
See std::lexicographical_compare() for how the determination is made.
Definition at line 2073 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::begin(), and std::vector< _Tp, _Alloc >::end().
operator<<() [1/24]
template<typename _Ostream , typename _Tp > __rvalue_stream_insertion_t<_Ostream, _Tp> std::operator<< (_Ostream && __os, const _Tp & __x) inline
Generic inserter for rvalue stream.
Parameters
__os An input stream.
__x A reference to the object being inserted.
Returns
__os
This is just a forwarding function to allow insertion to rvalue streams since they won't bind to the inserter functions that take an lvalue reference.
Definition at line 727 of file ostream.
operator<<() [2/24]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> basic_ostream<_CharT, _Traits>& std::operator<< (basic_ostream< _CharT, _Traits > & __os, const __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > & __str) inline
Write string to a stream.
Parameters
__os Output stream.
__str String to write out.
Returns
Reference to the output stream.
Output characters of __str into os following the same rules as for writing a C string.
Definition at line 2616 of file vstring.h.
operator<<() [3/24]
template<typename _CharT , typename _Traits , typename _Alloc > basic_ostream<_CharT, _Traits>& std::operator<< (basic_ostream< _CharT, _Traits > & __os, const basic_string< _CharT, _Traits, _Alloc > & __str) inline
Write string to a stream.
Parameters
__os Output stream.
__str String to write out.
Returns
Reference to the output stream.
Output characters of __str into os following the same rules as for writing a C string.
Definition at line 3870 of file basic_string.h.
operator<<() [4/24]
template<typename _CharT , typename _Traits > basic_ostream<_CharT, _Traits>& std::operator<< (basic_ostream< _CharT, _Traits > & __out, _CharT __c) inline
Character inserters.
Parameters
__out An output stream.
__c A character.
Returns
out
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts a single character and any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
If __c is of type char and the character type of the stream is not char, the character is widened before insertion.
Definition at line 1 of file ostream.
operator<<() [5/24]
template<typename _CharT , typename _Traits > basic_ostream<_CharT, _Traits>& std::operator<< (basic_ostream< _CharT, _Traits > & __out, char __c) inline
Character inserters.
Parameters
__out An output stream.
__c A character.
Returns
out
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts a single character and any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
If __c is of type char and the character type of the stream is not char, the character is widened before insertion.
Definition at line 1 of file ostream.
operator<<() [6/24]
template<typename _CharT , typename _Traits > basic_ostream<_CharT, _Traits>& std::operator<< (basic_ostream< _CharT, _Traits > & __out, const _CharT * __s) inline
String inserters.
Parameters
__out An output stream.
__s A character string.
Returns
out
Precondition
__s must be a non-NULL pointer
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts traits::length(__s) characters starting at __s, widened if necessary, followed by any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
Definition at line 1 of file ostream.
operator<<() [7/24]
template<typename _CharT , typename _Traits > basic_ostream< _CharT, _Traits > & std::operator<< (basic_ostream< _CharT, _Traits > & __out, const char * __s)
String inserters.
Parameters
__out An output stream.
__s A character string.
Returns
out
Precondition
__s must be a non-NULL pointer
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts traits::length(__s) characters starting at __s, widened if necessary, followed by any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
Definition at line 282 of file ostream.tcc.
operator<<() [8/24]
template<typename _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & , char16_t) delete
Character inserters.
Parameters
__out An output stream.
__c A character.
Returns
out
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts a single character and any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
If __c is of type char and the character type of the stream is not char, the character is widened before insertion.
operator<<() [9/24]
template<typename _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & , char32_t) delete
Character inserters.
Parameters
__out An output stream.
__c A character.
Returns
out
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts a single character and any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
If __c is of type char and the character type of the stream is not char, the character is widened before insertion.
operator<<() [10/24]
template<typename _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & , const char16_t *) delete
String inserters.
Parameters
__out An output stream.
__s A character string.
Returns
out
Precondition
__s must be a non-NULL pointer
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts traits::length(__s) characters starting at __s, widened if necessary, followed by any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
operator<<() [11/24]
template<typename _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & , const char32_t *) delete
String inserters.
Parameters
__out An output stream.
__s A character string.
Returns
out
Precondition
__s must be a non-NULL pointer
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts traits::length(__s) characters starting at __s, widened if necessary, followed by any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
operator<<() [12/24]
template<typename _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & , const wchar_t *) delete
String inserters.
Parameters
__out An output stream.
__s A character string.
Returns
out
Precondition
__s must be a non-NULL pointer
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts traits::length(__s) characters starting at __s, widened if necessary, followed by any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
operator<<() [13/24]
template<typename _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & , wchar_t) delete
Character inserters.
Parameters
__out An output stream.
__c A character.
Returns
out
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts a single character and any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
If __c is of type char and the character type of the stream is not char, the character is widened before insertion.
operator<<() [14/24]
template<typename _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & __out, char __c) inline
Character inserters.
Parameters
__out An output stream.
__c A character.
Returns
out
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts a single character and any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
If __c is of type char and the character type of the stream is not char, the character is widened before insertion.
Definition at line 1 of file ostream.
operator<<() [15/24]
template<typename _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & __out, const char * __s) inline
String inserters.
Parameters
__out An output stream.
__s A character string.
Returns
out
Precondition
__s must be a non-NULL pointer
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts traits::length(__s) characters starting at __s, widened if necessary, followed by any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
Definition at line 1 of file ostream.
operator<<() [16/24]
template<typename _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & __out, const signed char * __s) inline
String inserters.
Parameters
__out An output stream.
__s A character string.
Returns
out
Precondition
__s must be a non-NULL pointer
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts traits::length(__s) characters starting at __s, widened if necessary, followed by any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
Definition at line 1 of file ostream.
operator<<() [17/24]
template<typename _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & __out, const unsigned char * __s) inline
String inserters.
Parameters
__out An output stream.
__s A character string.
Returns
out
Precondition
__s must be a non-NULL pointer
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts traits::length(__s) characters starting at __s, widened if necessary, followed by any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
Definition at line 1 of file ostream.
operator<<() [18/24]
template<typename _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & __out, signed char __c) inline
Character inserters.
Parameters
__out An output stream.
__c A character.
Returns
out
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts a single character and any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
If __c is of type char and the character type of the stream is not char, the character is widened before insertion.
Definition at line 1 of file ostream.
operator<<() [19/24]
template<typename _Traits > basic_ostream<char, _Traits>& std::operator<< (basic_ostream< char, _Traits > & __out, unsigned char __c) inline
Character inserters.
Parameters
__out An output stream.
__c A character.
Returns
out
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts a single character and any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
If __c is of type char and the character type of the stream is not char, the character is widened before insertion.
Definition at line 1 of file ostream.
operator<<() [20/24]
template<typename _Traits > basic_ostream<wchar_t, _Traits>& std::operator<< (basic_ostream< wchar_t, _Traits > & , char16_t) delete
Character inserters.
Parameters
__out An output stream.
__c A character.
Returns
out
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts a single character and any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
If __c is of type char and the character type of the stream is not char, the character is widened before insertion.
operator<<() [21/24]
template<typename _Traits > basic_ostream<wchar_t, _Traits>& std::operator<< (basic_ostream< wchar_t, _Traits > & , char32_t) delete
Character inserters.
Parameters
__out An output stream.
__c A character.
Returns
out
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts a single character and any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
If __c is of type char and the character type of the stream is not char, the character is widened before insertion.
operator<<() [22/24]
template<typename _Traits > basic_ostream<wchar_t, _Traits>& std::operator<< (basic_ostream< wchar_t, _Traits > & , const char16_t *) delete
String inserters.
Parameters
__out An output stream.
__s A character string.
Returns
out
Precondition
__s must be a non-NULL pointer
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts traits::length(__s) characters starting at __s, widened if necessary, followed by any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
operator<<() [23/24]
template<typename _Traits > basic_ostream<wchar_t, _Traits>& std::operator<< (basic_ostream< wchar_t, _Traits > & , const char32_t *) delete
String inserters.
Parameters
__out An output stream.
__s A character string.
Returns
out
Precondition
__s must be a non-NULL pointer
Behaves like one of the formatted arithmetic inserters described in std::basic_ostream. After constructing a sentry object with good status, this function inserts traits::length(__s) characters starting at __s, widened if necessary, followed by any required padding (as determined by [22.2.2.2.2]). __out.width(0) is then called.
operator<<() [24/24]
template<class _CharT , class _Traits , size_t _Nb> std::basic_ostream<_CharT, _Traits>& std::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const bitset< _Nb > & __x)
Global I/O operators for bitsets.
Direct I/O between streams and bitsets is supported. Output is straightforward. Input will skip whitespace, only accept 0 and 1 characters, and will only extract as many digits as the bitset will hold.
Definition at line 1472 of file bitset.
operator<=() [1/13]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator<= (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test if C string doesn't follow string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __lhs doesn't follow __rhs. False otherwise.
Definition at line 3791 of file basic_string.h.
operator<=() [2/13]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator<= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) inline
Test if string doesn't follow C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs doesn't follow __rhs. False otherwise.
Definition at line 3779 of file basic_string.h.
operator<=() [3/13]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator<= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline noexcept
Test if string doesn't follow string.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs doesn't follow __rhs. False otherwise.
Definition at line 3766 of file basic_string.h.
operator<=() [4/13]
template<typename _Tp , typename _Alloc > bool std::operator<= (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 2351 of file stl_deque.h.
operator<=() [5/13]
template<typename _Tp , typename _Alloc > bool std::operator<= (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly) inline
Based on operator<.
Definition at line 1526 of file forward_list.h.
operator<=() [6/13]
template<typename _Tp , typename _Alloc > bool std::operator<= (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 2202 of file stl_list.h.
operator<=() [7/13]
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator<= (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) inline
Based on operator<.
Definition at line 1569 of file stl_map.h.
operator<=() [8/13]
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator<= (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) inline
Based on operator<.
Definition at line 1190 of file stl_multimap.h.
operator<=() [9/13]
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator<= (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) inline
Returns !(y < x)
Definition at line 1030 of file stl_multiset.h.
operator<=() [10/13]
template<typename _Tp , typename _Seq > bool std::operator<= (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) inline
Based on operator<.
Definition at line 419 of file stl_queue.h.
operator<=() [11/13]
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator<= (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) inline
Returns !(y < x)
Definition at line 1043 of file stl_set.h.
operator<=() [12/13]
template<typename _Tp , typename _Seq > bool std::operator<= (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) inline
Based on operator<.
Definition at line 395 of file stl_stack.h.
operator<=() [13/13]
template<typename _Tp , typename _Alloc > bool std::operator<= (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 2092 of file stl_vector.h.
operator==() [1/15]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator== (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test equivalence of C string and string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __rhs.compare(__lhs) == 0. False otherwise.
Definition at line 3640 of file basic_string.h.
operator==() [2/15]
template<typename _CharT , typename _Traits , typename _Alloc > constexpr bool std::operator== (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) inline constexpr
Test equivalence of string and C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs.compare(__rhs) == 0. False otherwise.
Definition at line 3599 of file basic_string.h.
operator==() [3/15]
template<typename _CharT , typename _Traits , typename _Alloc > constexpr bool std::operator== (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline constexpr noexcept
Test equivalence of two strings.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs.compare(__rhs) == 0. False otherwise.
Definition at line 3575 of file basic_string.h.
operator==() [4/15]
template<typename _Tp , typename _Alloc > bool std::operator== (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) inline
Deque equality comparison.
Parameters
__x A deque.
__y A deque of the same type as __x.
Returns
True iff the size and elements of the deques are equal.
This is an equivalence relation. It is linear in the size of the deques. Deques are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 2290 of file stl_deque.h.
References std::deque< _Tp, _Alloc >::begin(), std::deque< _Tp, _Alloc >::end(), and std::deque< _Tp, _Alloc >::size().
operator==() [5/15]
template<typename _Tp , typename _Alloc > bool std::operator== (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly)
Forward list equality comparison.
Parameters
__lx A forward_list
__ly A forward_list of the same type as __lx.
Returns
True iff the elements of the forward lists are equal.
This is an equivalence relation. It is linear in the number of elements of the forward lists. Deques are considered equivalent if corresponding elements compare equal.
Definition at line 393 of file forward_list.tcc.
References std::forward_list< _Tp, _Alloc >::cbegin(), and std::forward_list< _Tp, _Alloc >::cend().
operator==() [6/15]
template<typename _StateT > bool std::operator== (const fpos< _StateT > & __lhs, const fpos< _StateT > & __rhs) inline
Test if equivalent to another position.
Definition at line 192 of file postypes.h.
operator==() [7/15]
template<typename _Res , typename... _Args> bool std::operator== (const function< _Res(_Args...)> & __f, nullptr_t) inline noexcept
Test whether a polymorphic function object wrapper is empty.
Returns
true if the wrapper has no target, false otherwise
This function will not throw exceptions.
Definition at line 718 of file std_function.h.
operator==() [8/15]
template<typename _Tp , typename _Alloc > bool std::operator== (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) inline
List equality comparison.
Parameters
__x A list.
__y A list of the same type as __x.
Returns
True iff the size and elements of the lists are equal.
This is an equivalence relation. It is linear in the size of the lists. Lists are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 2124 of file stl_list.h.
References std::list< _Tp, _Alloc >::begin(), std::list< _Tp, _Alloc >::end(), and std::list< _Tp, _Alloc >::size().
operator==() [9/15]
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator== (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) inline
Map equality comparison.
Parameters
__x A map.
__y A map of the same type as x.
Returns
True iff the size and elements of the maps are equal.
This is an equivalence relation. It is linear in the size of the maps. Maps are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 1511 of file stl_map.h.
operator==() [10/15]
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator== (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) inline
Multimap equality comparison.
Parameters
__x A multimap.
__y A multimap of the same type as __x.
Returns
True iff the size and elements of the maps are equal.
This is an equivalence relation. It is linear in the size of the multimaps. Multimaps are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 1132 of file stl_multimap.h.
operator==() [11/15]
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator== (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) inline
Multiset equality comparison.
Parameters
__x A multiset.
__y A multiset of the same type as __x.
Returns
True iff the size and elements of the multisets are equal.
This is an equivalence relation. It is linear in the size of the multisets. Multisets are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 972 of file stl_multiset.h.
operator==() [12/15]
template<typename _Tp , typename _Seq > bool std::operator== (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) inline
Queue equality comparison.
Parameters
__x A queue.
__y A queue of the same type as __x.
Returns
True iff the size and elements of the queues are equal.
This is an equivalence relation. Complexity and semantics depend on the underlying sequence type, but the expected rules are: this relation is linear in the size of the sequences, and queues are considered equivalent if their sequences compare equal.
Definition at line 380 of file stl_queue.h.
References std::queue< _Tp, _Sequence >::c.
operator==() [13/15]
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator== (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) inline
Set equality comparison.
Parameters
__x A set.
__y A set of the same type as x.
Returns
True iff the size and elements of the sets are equal.
This is an equivalence relation. It is linear in the size of the sets. Sets are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 985 of file stl_set.h.
operator==() [14/15]
template<typename _Tp , typename _Seq > bool std::operator== (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) inline
Stack equality comparison.
Parameters
__x A stack.
__y A stack of the same type as __x.
Returns
True iff the size and elements of the stacks are equal.
This is an equivalence relation. Complexity and semantics depend on the underlying sequence type, but the expected rules are: this relation is linear in the size of the sequences, and stacks are considered equivalent if their sequences compare equal.
Definition at line 356 of file stl_stack.h.
operator==() [15/15]
template<typename _Tp , typename _Alloc > constexpr bool std::operator== (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) inline constexpr
Vector equality comparison.
Parameters
__x A vector.
__y A vector of the same type as __x.
Returns
True iff the size and elements of the vectors are equal.
This is an equivalence relation. It is linear in the size of the vectors. Vectors are considered equivalent if their sizes are equal, and if corresponding elements compare equal.
Definition at line 2035 of file stl_vector.h.
References std::vector< _Tp, _Alloc >::begin(), std::vector< _Tp, _Alloc >::end(), and std::vector< _Tp, _Alloc >::size().
operator>() [1/13]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator> (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test if C string follows string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __lhs follows __rhs. False otherwise.
Definition at line 3754 of file basic_string.h.
operator>() [2/13]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator> (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) inline
Test if string follows C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs follows __rhs. False otherwise.
Definition at line 3742 of file basic_string.h.
operator>() [3/13]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator> (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline noexcept
Test if string follows string.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs follows __rhs. False otherwise.
Definition at line 3729 of file basic_string.h.
operator>() [4/13]
template<typename _Tp , typename _Alloc > bool std::operator> (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 2345 of file stl_deque.h.
operator>() [5/13]
template<typename _Tp , typename _Alloc > bool std::operator> (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly) inline
Based on operator<.
Definition at line 1511 of file forward_list.h.
operator>() [6/13]
template<typename _Tp , typename _Alloc > bool std::operator> (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 2196 of file stl_list.h.
operator>() [7/13]
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator> (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) inline
Based on operator<.
Definition at line 1563 of file stl_map.h.
operator>() [8/13]
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator> (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) inline
Based on operator<.
Definition at line 1184 of file stl_multimap.h.
operator>() [9/13]
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator> (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) inline
Returns y < x.
Definition at line 1024 of file stl_multiset.h.
operator>() [10/13]
template<typename _Tp , typename _Seq > bool std::operator> (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) inline
Based on operator<.
Definition at line 413 of file stl_queue.h.
operator>() [11/13]
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator> (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) inline
Returns y < x.
Definition at line 1037 of file stl_set.h.
operator>() [12/13]
template<typename _Tp , typename _Seq > bool std::operator> (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) inline
Based on operator<.
Definition at line 389 of file stl_stack.h.
operator>() [13/13]
template<typename _Tp , typename _Alloc > bool std::operator> (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 2087 of file stl_vector.h.
operator>=() [1/13]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator>= (const _CharT * __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline
Test if C string doesn't precede string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __lhs doesn't precede __rhs. False otherwise.
Definition at line 3830 of file basic_string.h.
operator>=() [2/13]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator>= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const _CharT * __rhs) inline
Test if string doesn't precede C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs doesn't precede __rhs. False otherwise.
Definition at line 3818 of file basic_string.h.
operator>=() [3/13]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::operator>= (const basic_string< _CharT, _Traits, _Alloc > & __lhs, const basic_string< _CharT, _Traits, _Alloc > & __rhs) inline noexcept
Test if string doesn't precede string.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs doesn't precede __rhs. False otherwise.
Definition at line 3805 of file basic_string.h.
operator>=() [4/13]
template<typename _Tp , typename _Alloc > bool std::operator>= (const deque< _Tp, _Alloc > & __x, const deque< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 2359 of file stl_deque.h.
operator>=() [5/13]
template<typename _Tp , typename _Alloc > bool std::operator>= (const forward_list< _Tp, _Alloc > & __lx, const forward_list< _Tp, _Alloc > & __ly) inline
Based on operator<.
Definition at line 1519 of file forward_list.h.
operator>=() [6/13]
template<typename _Tp , typename _Alloc > bool std::operator>= (const list< _Tp, _Alloc > & __x, const list< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 2210 of file stl_list.h.
operator>=() [7/13]
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator>= (const map< _Key, _Tp, _Compare, _Alloc > & __x, const map< _Key, _Tp, _Compare, _Alloc > & __y) inline
Based on operator<.
Definition at line 1577 of file stl_map.h.
operator>=() [8/13]
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > bool std::operator>= (const multimap< _Key, _Tp, _Compare, _Alloc > & __x, const multimap< _Key, _Tp, _Compare, _Alloc > & __y) inline
Based on operator<.
Definition at line 1198 of file stl_multimap.h.
operator>=() [9/13]
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator>= (const multiset< _Key, _Compare, _Alloc > & __x, const multiset< _Key, _Compare, _Alloc > & __y) inline
Returns !(x < y)
Definition at line 1038 of file stl_multiset.h.
operator>=() [10/13]
template<typename _Tp , typename _Seq > bool std::operator>= (const queue< _Tp, _Seq > & __x, const queue< _Tp, _Seq > & __y) inline
Based on operator<.
Definition at line 427 of file stl_queue.h.
operator>=() [11/13]
template<typename _Key , typename _Compare , typename _Alloc > bool std::operator>= (const set< _Key, _Compare, _Alloc > & __x, const set< _Key, _Compare, _Alloc > & __y) inline
Returns !(x < y)
Definition at line 1051 of file stl_set.h.
operator>=() [12/13]
template<typename _Tp , typename _Seq > bool std::operator>= (const stack< _Tp, _Seq > & __x, const stack< _Tp, _Seq > & __y) inline
Based on operator<.
Definition at line 403 of file stl_stack.h.
operator>=() [13/13]
template<typename _Tp , typename _Alloc > bool std::operator>= (const vector< _Tp, _Alloc > & __x, const vector< _Tp, _Alloc > & __y) inline
Based on operator<.
Definition at line 2099 of file stl_vector.h.
operator>>() [1/10]
template<typename _Istream , typename _Tp > __rvalue_stream_extraction_t<_Istream, _Tp> std::operator>> (_Istream && __is, _Tp && __x) inline
Generic extractor for rvalue stream.
Parameters
__is An input stream.
__x A reference to the extraction target.
Returns
__is
This is just a forwarding function to allow extraction from rvalue streams since they won't bind to the extractor functions that take an lvalue reference.
Definition at line 1006 of file istream.
operator>>() [2/10]
template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & std::operator>> (basic_istream< _CharT, _Traits > & __in, _CharT & __c)
Character extractors.
Parameters
__in An input stream.
__c A character reference.
Returns
in
Behaves like one of the formatted arithmetic extractors described in std::basic_istream. After constructing a sentry object with good status, this function extracts a character (if one is available) and stores it in __c. Otherwise, sets failbit in the input stream.
Definition at line 960 of file istream.tcc.
References std::ios_base::goodbit.
operator>>() [3/10]
template<typename _CharT , typename _Traits , size_t _Num> basic_istream<_CharT, _Traits>& std::operator>> (basic_istream< _CharT, _Traits > & __in, _CharT(&) __s[_Num]) inline
Character string extractors.
Parameters
__in An input stream.
__s A character array (or a pointer to an array before C++20).
Returns
__in
Behaves like one of the formatted arithmetic extractors described in std::basic_istream. After constructing a sentry object with good status, this function extracts up to n characters and stores them into the array __s. n is defined as:
if width() is greater than zero, n is min(width(), n)
otherwise n is the number of elements of the array
(before C++20 the pointer is assumed to point to an array of the largest possible size for an array of char_type).
Characters are extracted and stored until one of the following happens:
n - 1 characters are stored
EOF is reached
the next character is whitespace according to the current locale
width(0) is then called for the input stream.
If no characters are extracted, sets failbit.
Definition at line 859 of file istream.
operator>>() [4/10]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> basic_istream< _CharT, _Traits > & std::operator>> (basic_istream< _CharT, _Traits > & __is, __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base > & __str)
Read stream into a string.
Parameters
__is Input stream.
__str Buffer to store into.
Returns
Reference to the input stream.
Stores characters from __is into __str until whitespace is found, the end of the stream is encountered, or str.max_size() is reached. If is.width() is non-zero, that is the limit on the number of characters stored into __str. Any previous contents of __str are erased.
Definition at line 552 of file vstring.tcc.
operator>>() [5/10]
template<typename _CharT , typename _Traits , typename _Alloc > basic_istream< _CharT, _Traits > & std::operator>> (basic_istream< _CharT, _Traits > & __is, basic_string< _CharT, _Traits, _Alloc > & __str)
Read stream into a string.
Parameters
__is Input stream.
__str Buffer to store into.
Returns
Reference to the input stream.
Stores characters from __is into __str until whitespace is found, the end of the stream is encountered, or str.max_size() is reached. If is.width() is non-zero, that is the limit on the number of characters stored into __str. Any previous contents of __str are erased.
Definition at line 940 of file basic_string.tcc.
operator>>() [6/10]
template<class _Traits > basic_istream<char, _Traits>& std::operator>> (basic_istream< char, _Traits > & __in, signed char & __c) inline
Character extractors.
Parameters
__in An input stream.
__c A character reference.
Returns
in
Behaves like one of the formatted arithmetic extractors described in std::basic_istream. After constructing a sentry object with good status, this function extracts a character (if one is available) and stores it in __c. Otherwise, sets failbit in the input stream.
Definition at line 761 of file istream.
operator>>() [7/10]
template<class _Traits , size_t _Num> basic_istream<char, _Traits>& std::operator>> (basic_istream< char, _Traits > & __in, signed char(&) __s[_Num]) inline
Character string extractors.
Parameters
__in An input stream.
__s A character array (or a pointer to an array before C++20).
Returns
__in
Behaves like one of the formatted arithmetic extractors described in std::basic_istream. After constructing a sentry object with good status, this function extracts up to n characters and stores them into the array __s. n is defined as:
if width() is greater than zero, n is min(width(), n)
otherwise n is the number of elements of the array
(before C++20 the pointer is assumed to point to an array of the largest possible size for an array of char_type).
Characters are extracted and stored until one of the following happens:
n - 1 characters are stored
EOF is reached
the next character is whitespace according to the current locale
width(0) is then called for the input stream.
If no characters are extracted, sets failbit.
Definition at line 873 of file istream.
operator>>() [8/10]
template<class _Traits > basic_istream<char, _Traits>& std::operator>> (basic_istream< char, _Traits > & __in, unsigned char & __c) inline
Character extractors.
Parameters
__in An input stream.
__c A character reference.
Returns
in
Behaves like one of the formatted arithmetic extractors described in std::basic_istream. After constructing a sentry object with good status, this function extracts a character (if one is available) and stores it in __c. Otherwise, sets failbit in the input stream.
Definition at line 756 of file istream.
operator>>() [9/10]
template<class _Traits , size_t _Num> basic_istream<char, _Traits>& std::operator>> (basic_istream< char, _Traits > & __in, unsigned char(&) __s[_Num]) inline
Character string extractors.
Parameters
__in An input stream.
__s A character array (or a pointer to an array before C++20).
Returns
__in
Behaves like one of the formatted arithmetic extractors described in std::basic_istream. After constructing a sentry object with good status, this function extracts up to n characters and stores them into the array __s. n is defined as:
if width() is greater than zero, n is min(width(), n)
otherwise n is the number of elements of the array
(before C++20 the pointer is assumed to point to an array of the largest possible size for an array of char_type).
Characters are extracted and stored until one of the following happens:
n - 1 characters are stored
EOF is reached
the next character is whitespace according to the current locale
width(0) is then called for the input stream.
If no characters are extracted, sets failbit.
Definition at line 868 of file istream.
operator>>() [10/10]
template<class _CharT , class _Traits , size_t _Nb> std::basic_istream<_CharT, _Traits>& std::operator>> (std::basic_istream< _CharT, _Traits > & __is, bitset< _Nb > & __x)
Global I/O operators for bitsets.
Direct I/O between streams and bitsets is supported. Output is straightforward. Input will skip whitespace, only accept 0 and 1 characters, and will only extract as many digits as the bitset will hold.
Definition at line 1472 of file bitset.
operator^()
template<size_t _Nb> bitset<_Nb> std::operator^ (const bitset< _Nb > & __x, const bitset< _Nb > & __y) inline noexcept
Global bitwise operations on bitsets.
Parameters
__x A bitset.
__y A bitset of the same size as __x.
Returns
A new bitset.
These should be self-explanatory.
Definition at line 1453 of file bitset.
operator|()
template<size_t _Nb> bitset<_Nb> std::operator| (const bitset< _Nb > & __x, const bitset< _Nb > & __y) inline noexcept
Global bitwise operations on bitsets.
Parameters
__x A bitset.
__y A bitset of the same size as __x.
Returns
A new bitset.
These should be self-explanatory.
Definition at line 1444 of file bitset.
put_money()
template<typename _MoneyT > _Put_money<_MoneyT> std::put_money (const _MoneyT & __mon, bool __intl = false) inline
Extended manipulator for inserting money.
Parameters
__mon Either long double or a specialization of basic_string.
__intl A bool indicating whether international format is to be used.
Sent to a stream object, this manipulator inserts __mon.
Definition at line 306 of file iomanip.
put_time()
template<typename _CharT > _Put_time<_CharT> std::put_time (const std::tm * __tmb, const _CharT * __fmt) inline
Extended manipulator for formatting time.
This manipulator uses time_put::put to format time. [ext.manip]
Parameters
__tmb struct tm time data to format.
__fmt format string.
Definition at line 358 of file iomanip.
quoted()
template<typename _CharT > auto std::quoted (const _CharT * __string, _CharT __delim = _CharT('"'), _CharT __escape = _CharT('\\')) inline
Manipulator for quoted strings.
Parameters
__string String to quote.
__delim Character to quote string with.
__escape Escape character to escape itself or quote character.
Definition at line 461 of file iomanip.
rbegin() [1/4]
template<typename _Container > constexpr auto std::rbegin (_Container & __cont) -> decltype(__cont.rbegin()) inline constexpr
Return a reverse iterator pointing to the last element of the container.
Parameters
__cont Container.
Definition at line 150 of file range_access.h.
Referenced by crbegin().
rbegin() [2/4]
template<typename _Tp , size_t _Nm> constexpr reverse_iterator<_Tp*> std::rbegin (_Tp(&) __arr[_Nm]) inline constexpr noexcept
Return a reverse iterator pointing to the last element of the array.
Parameters
__arr Array.
Definition at line 194 of file range_access.h.
rbegin() [3/4]
template<typename _Container > constexpr auto std::rbegin (const _Container & __cont) -> decltype(__cont.rbegin()) inline constexpr
Return a reverse iterator pointing to the last element of the const container.
Parameters
__cont Container.
Definition at line 161 of file range_access.h.
rbegin() [4/4]
template<typename _Tp > constexpr reverse_iterator<const _Tp*> std::rbegin (initializer_list< _Tp > __il) inline constexpr noexcept
Return a reverse iterator pointing to the last element of the initializer_list.
Parameters
__il initializer_list.
Definition at line 216 of file range_access.h.
rend() [1/4]
template<typename _Container > constexpr auto std::rend (_Container & __cont) -> decltype(__cont.rend()) inline constexpr
Return a reverse iterator pointing one past the first element of the container.
Parameters
__cont Container.
Definition at line 172 of file range_access.h.
Referenced by crend().
rend() [2/4]
template<typename _Tp , size_t _Nm> constexpr reverse_iterator<_Tp*> std::rend (_Tp(&) __arr[_Nm]) inline constexpr noexcept
Return a reverse iterator pointing one past the first element of the array.
Parameters
__arr Array.
Definition at line 205 of file range_access.h.
rend() [3/4]
template<typename _Container > constexpr auto std::rend (const _Container & __cont) -> decltype(__cont.rend()) inline constexpr
Return a reverse iterator pointing one past the first element of the const container.
Parameters
__cont Container.
Definition at line 183 of file range_access.h.
rend() [4/4]
template<typename _Tp > constexpr reverse_iterator<const _Tp*> std::rend (initializer_list< _Tp > __il) inline constexpr noexcept
Return a reverse iterator pointing one past the first element of the initializer_list.
Parameters
__il initializer_list.
Definition at line 227 of file range_access.h.
replace_copy()
template<typename _InputIterator , typename _OutputIterator , typename _Tp > constexpr _OutputIterator std::replace_copy (_InputIterator __first, _InputIterator __last, _OutputIterator __result, const _Tp & __old_value, const _Tp & __new_value) inline constexpr
Copy a sequence, replacing each element of one value with another value.
Parameters
__first An input iterator.
__last An input iterator.
__result An output iterator.
__old_value The value to be replaced.
__new_value The replacement value.
Returns
The end of the output sequence, result+(last-first).
Copies each element in the input range [__first,__last) to the output range [__result,__result+(__last-__first)) replacing elements equal to __old_value with __new_value.
Definition at line 3123 of file stl_algo.h.
resetiosflags()
_Resetiosflags std::resetiosflags (ios_base::fmtflags __mask) inline
Manipulator for setf.
Parameters
__mask A format flags mask.
Sent to a stream object, this manipulator resets the specified flags, via stream.setf(0,__mask).
Definition at line 66 of file iomanip.
return_temporary_buffer()
template<typename _Tp > void std::return_temporary_buffer (_Tp * __p) inline
The companion to get_temporary_buffer().
Parameters
__p A buffer previously allocated by get_temporary_buffer.
Returns
None.
Frees the memory pointed to by __p.
Definition at line 128 of file stl_tempbuf.h.
right()
ios_base& std::right (ios_base & __base) inline
Calls base.setf(ios_base::right, ios_base::adjustfield).
Definition at line 1046 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::adjustfield, and std::ios_base::right.
sample()
template<typename _PopulationIterator , typename _SampleIterator , typename _Distance , typename _UniformRandomBitGenerator > _SampleIterator std::sample (_PopulationIterator __first, _PopulationIterator __last, _SampleIterator __out, _Distance __n, _UniformRandomBitGenerator && __g)
Take a random sample from a population.
Definition at line 5866 of file stl_algo.h.
References __sample().
scientific()
ios_base& std::scientific (ios_base & __base) inline
Calls base.setf(ios_base::scientific, ios_base::floatfield).
Definition at line 1088 of file ios_base.h.
References __gnu_debug::__base(), std::ios_base::floatfield, and std::ios_base::scientific.
search()
template<typename _ForwardIterator , typename _Searcher > constexpr _ForwardIterator std::search (_ForwardIterator __first, _ForwardIterator __last, const _Searcher & __searcher) inline constexpr
Search a sequence using a Searcher object.
Parameters
__first A forward iterator.
__last A forward iterator.
__searcher A callable object.
Returns
__searcher(__first,__last).first
Definition at line 4227 of file stl_algo.h.
set_new_handler()
new_handler std::set_new_handler (new_handler) throw ()
Takes a replacement handler as the argument, returns the previous handler.
setbase()
_Setbase std::setbase (int __base) inline
Manipulator for setf.
Parameters
__base A numeric base.
Sent to a stream object, this manipulator changes the ios_base::basefield flags to oct, dec, or hex when base is 8, 10, or 16, accordingly, and to 0 if __base is any other value.
Definition at line 127 of file iomanip.
setfill()
template<typename _CharT > _Setfill<_CharT> std::setfill (_CharT __c) inline
Manipulator for fill.
Parameters
__c The new fill character.
Sent to a stream object, this manipulator calls fill(__c) for that object.
Definition at line 165 of file iomanip.
setiosflags()
_Setiosflags std::setiosflags (ios_base::fmtflags __mask) inline
Manipulator for setf.
Parameters
__mask A format flags mask.
Sent to a stream object, this manipulator sets the format flags to __mask.
Definition at line 96 of file iomanip.
setprecision()
_Setprecision std::setprecision (int __n) inline
Manipulator for precision.
Parameters
__n The new precision.
Sent to a stream object, this manipulator calls precision(__n) for that object.
Definition at line 195 of file iomanip.
setw()
_Setw std::setw (int __n) inline
Manipulator for width.
Parameters
__n The new width.
Sent to a stream object, this manipulator calls width(__n) for that object.
Definition at line 225 of file iomanip.
showbase()
ios_base& std::showbase (ios_base & __base) inline
Calls base.setf(ios_base::showbase).
Definition at line 933 of file ios_base.h.
References __gnu_debug::__base(), and std::ios_base::showbase.
showpoint()
ios_base& std::showpoint (ios_base & __base) inline
Calls base.setf(ios_base::showpoint).
Definition at line 949 of file ios_base.h.
References __gnu_debug::__base(), and std::ios_base::showpoint.
showpos()
ios_base& std::showpos (ios_base & __base) inline
Calls base.setf(ios_base::showpos).
Definition at line 965 of file ios_base.h.
References __gnu_debug::__base(), and std::ios_base::showpos.
size() [1/2]
template<typename _Container > constexpr auto std::size (const _Container & __cont) -> decltype(__cont.size()) constexpr noexcept
Return the size of a container.
Parameters
__cont Container.
Definition at line 264 of file range_access.h.
Referenced by std::deque< _Tp, _Alloc >::_M_new_elements_at_back(), std::deque< _Tp, _Alloc >::_M_new_elements_at_front(), std::deque< _Tp, _Alloc >::_M_push_back_aux(), std::deque< _Tp, _Alloc >::_M_push_front_aux(), std::basic_string< _CharT, _Traits, _Alloc >::append(), std::basic_string< _CharT, _Traits, _Alloc >::find(), std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of(), std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of(), std::deque< _Tp, _Alloc >::operator=(), std::basic_string< _CharT, _Traits, _Alloc >::reserve(), std::basic_string< _CharT, _Traits, _Alloc >::resize(), and std::basic_string< _CharT, _Traits, _Alloc >::rfind().
size() [2/2]
template<typename _Tp , size_t _Nm> constexpr size_t std::size (const _Tp(&)[_Nm]) constexpr noexcept
Return the size of an array.
Definition at line 274 of file range_access.h.
skipws()
ios_base& std::skipws (ios_base & __base) inline
Calls base.setf(ios_base::skipws).
Definition at line 981 of file ios_base.h.
References __gnu_debug::__base(), and std::ios_base::skipws.
Referenced by operator<<(), and operator>>().
static_pointer_cast()
template<typename _Tp , typename _Tp1 , _Lock_policy _Lp> __shared_ptr<_Tp, _Lp> std::static_pointer_cast (const __shared_ptr< _Tp1, _Lp > & __r) inline noexcept
static_pointer_cast
Definition at line 1929 of file shared_ptr_base.h.
swap() [1/18]
template<class _CharT , class _Traits > void std::swap (basic_filebuf< _CharT, _Traits > & __x, basic_filebuf< _CharT, _Traits > & __y) inline
Swap specialization for filebufs.
Definition at line 1269 of file fstream.
swap() [2/18]
template<class _CharT , class _Traits > void std::swap (basic_fstream< _CharT, _Traits > & __x, basic_fstream< _CharT, _Traits > & __y) inline
Swap specialization for fstreams.
Definition at line 1290 of file fstream.
swap() [3/18]
template<class _CharT , class _Traits > void std::swap (basic_ifstream< _CharT, _Traits > & __x, basic_ifstream< _CharT, _Traits > & __y) inline
Swap specialization for ifstreams.
Definition at line 1276 of file fstream.
swap() [4/18]
template<class _CharT , class _Traits , class _Allocator > void std::swap (basic_istringstream< _CharT, _Traits, _Allocator > & __x, basic_istringstream< _CharT, _Traits, _Allocator > & __y) inline
Swap specialization for istringstreams.
Definition at line 1193 of file sstream.
swap() [5/18]
template<class _CharT , class _Traits > void std::swap (basic_ofstream< _CharT, _Traits > & __x, basic_ofstream< _CharT, _Traits > & __y) inline
Swap specialization for ofstreams.
Definition at line 1283 of file fstream.
swap() [6/18]
template<class _CharT , class _Traits , class _Allocator > void std::swap (basic_ostringstream< _CharT, _Traits, _Allocator > & __x, basic_ostringstream< _CharT, _Traits, _Allocator > & __y) inline
Swap specialization for ostringstreams.
Definition at line 1200 of file sstream.
swap() [7/18]
template<typename _CharT , typename _Traits , typename _Alloc > constexpr void std::swap (basic_string< _CharT, _Traits, _Alloc > & __lhs, basic_string< _CharT, _Traits, _Alloc > & __rhs) inline constexpr noexcept
Swap contents of two strings.
Parameters
__lhs First string.
__rhs Second string.
Exchanges the contents of __lhs and __rhs in constant time.
Definition at line 3845 of file basic_string.h.
swap() [8/18]
template<class _CharT , class _Traits , class _Allocator > void std::swap (basic_stringbuf< _CharT, _Traits, _Allocator > & __x, basic_stringbuf< _CharT, _Traits, _Allocator > & __y) inline noexcept
Swap specialization for stringbufs.
Definition at line 1185 of file sstream.
swap() [9/18]
template<class _CharT , class _Traits , class _Allocator > void std::swap (basic_stringstream< _CharT, _Traits, _Allocator > & __x, basic_stringstream< _CharT, _Traits, _Allocator > & __y) inline
Swap specialization for stringstreams.
Definition at line 1207 of file sstream.
swap() [10/18]
template<typename _Tp , typename _Alloc > void std::swap (deque< _Tp, _Alloc > & __x, deque< _Tp, _Alloc > & __y) inline noexcept
See std::deque::swap().
Definition at line 2366 of file stl_deque.h.
swap() [11/18]
template<typename _Tp , typename _Alloc > void std::swap (forward_list< _Tp, _Alloc > & __lx, forward_list< _Tp, _Alloc > & __ly) inline noexcept
See std::forward_list::swap().
Definition at line 1535 of file forward_list.h.
swap() [12/18]
template<typename _Res , typename... _Args> void std::swap (function< _Res(_Args...)> & __x, function< _Res(_Args...)> & __y) inline noexcept
Swap the targets of two polymorphic function object wrappers.
This function will not throw exceptions.
Definition at line 757 of file std_function.h.
swap() [13/18]
template<typename _Tp , typename _Alloc > void std::swap (list< _Tp, _Alloc > & __x, list< _Tp, _Alloc > & __y) inline noexcept
See std::list::swap().
Definition at line 2217 of file stl_list.h.
swap() [14/18]
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > void std::swap (map< _Key, _Tp, _Compare, _Alloc > & __x, map< _Key, _Tp, _Compare, _Alloc > & __y) inline noexcept
See std::map::swap().
Definition at line 1585 of file stl_map.h.
References std::pair< _T1, _T2 >::swap().
swap() [15/18]
template<typename _Key , typename _Tp , typename _Compare , typename _Alloc > void std::swap (multimap< _Key, _Tp, _Compare, _Alloc > & __x, multimap< _Key, _Tp, _Compare, _Alloc > & __y) inline noexcept
See std::multimap::swap().
Definition at line 1206 of file stl_multimap.h.
References std::pair< _T1, _T2 >::swap().
swap() [16/18]
template<typename _Key , typename _Compare , typename _Alloc > void std::swap (multiset< _Key, _Compare, _Alloc > & __x, multiset< _Key, _Compare, _Alloc > & __y) inline noexcept
See std::multiset::swap().
Definition at line 1046 of file stl_multiset.h.
swap() [17/18]
template<typename _Key , typename _Compare , typename _Alloc > void std::swap (set< _Key, _Compare, _Alloc > & __x, set< _Key, _Compare, _Alloc > & __y) inline noexcept
See std::set::swap().
Definition at line 1059 of file stl_set.h.
swap() [18/18]
template<typename _Tp , typename _Alloc > constexpr void std::swap (vector< _Tp, _Alloc > & __x, vector< _Tp, _Alloc > & __y) inline constexpr noexcept
See std::vector::swap().
Definition at line 2107 of file stl_vector.h.
tolower()
template<typename _CharT > _CharT std::tolower (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.tolower(__c).
Definition at line 2681 of file locale_facets.h.
toupper()
template<typename _CharT > _CharT std::toupper (_CharT __c, const locale & __loc) inline
Convenience interface to ctype.toupper(__c).
Definition at line 2675 of file locale_facets.h.
unitbuf()
ios_base& std::unitbuf (ios_base & __base) inline
Calls base.setf(ios_base::unitbuf).
Definition at line 1013 of file ios_base.h.
References __gnu_debug::__base(), and std::ios_base::unitbuf.
uppercase()
ios_base& std::uppercase (ios_base & __base) inline
Calls base.setf(ios_base::uppercase).
Definition at line 997 of file ios_base.h.
References __gnu_debug::__base(), and std::ios_base::uppercase.
ws()
template<typename _CharT , typename _Traits > basic_istream< _CharT, _Traits > & std::ws (basic_istream< _CharT, _Traits > & __is)
Quick and easy way to eat whitespace.
This manipulator extracts whitespace characters, stopping when the next character is non-whitespace, or when the input sequence is empty. If the sequence is empty, eofbit is set in the stream, but not failbit.
The current locale is used to distinguish whitespace characters.
Example:
MyClass   mc;
std::cin >> std::ws >> mc;
will skip leading whitespace before calling operator>> on cin and your object. Note that the same effect can be achieved by creating a std::basic_istream::sentry inside your definition of operator>>.
Definition at line 1055 of file istream.tcc.
References std::ios_base::goodbit.
Variable Documentation
__ioinit
ios_base::Init std::__ioinit static
Linked to standard error (buffered)
Definition at line 74 of file iostream.
assignable_from
template<typename _Lhs , typename _Rhs > concept std::assignable_from
[concept.assignable], concept assignable_from
Definition at line 123 of file concepts.
cerr
ostream std::cerr extern
Linked to standard output.
cin
istream std::cin extern
Linked to standard input.
clog
ostream std::clog extern
Linked to standard error (unbuffered)
common_reference_with
template<typename _Tp , typename _Up > concept std::common_reference_with
[concept.commonref], concept common_reference_with
Definition at line 77 of file concepts.
common_with
template<typename _Tp , typename _Up > concept std::common_with
[concept.common], concept common_with
Definition at line 84 of file concepts.
constructible_from
template<typename _Tp , typename... _Args> concept std::constructible_from
[concept.constructible], concept constructible_from
Definition at line 136 of file concepts.
convertible_to
template<typename _From , typename _To > concept std::convertible_to
[concept.convertible], concept convertible_to
Definition at line 72 of file concepts.
copy_constructible
template<typename _Tp > concept std::copy_constructible
[concept.copyconstructible], concept copy_constructible
Definition at line 155 of file concepts.
cout
ostream std::cout extern
Linked to standard input.
default_initializable
template<typename _Tp > concept std::default_initializable
[concept.defaultinitializable], concept default_initializable
Definition at line 141 of file concepts.
derived_from
template<typename _Derived , typename _Base > concept std::derived_from
[concept.derived], concept derived_from
Definition at line 67 of file concepts.
destroying_delete
constexpr destroying_delete_t std::destroying_delete inline constexpr
Tag variable of type destroying_delete_t.
Definition at line 228 of file new.
destructible
template<typename _Tp > concept std::destructible
[concept.destructible], concept destructible
Definition at line 132 of file concepts.
equivalence_relation
template<typename _Rel , typename _Tp , typename _Up > concept std::equivalence_relation
[concept.equiv], concept equivalence_relation
Definition at line 355 of file concepts.
indirectly_comparable
template<typename _I1 , typename _I2 , typename _Rel , typename _P1 = identity, typename _P2 = identity> concept std::indirectly_comparable
[alg.req.ind.cmp], concept indirectly_comparable
Definition at line 890 of file iterator_concepts.h.
indirectly_copyable
template<typename _In , typename _Out > concept std::indirectly_copyable
[alg.req.ind.copy], concept indirectly_copyable
Definition at line 784 of file iterator_concepts.h.
indirectly_movable
template<typename _In , typename _Out > concept std::indirectly_movable
[alg.req.ind.move], concept indirectly_movable
Definition at line 772 of file iterator_concepts.h.
indirectly_readable
template<typename _In > concept std::indirectly_readable
Requirements for types that are readable by applying operator*.
Definition at line 533 of file iterator_concepts.h.
indirectly_swappable
template<typename _I1 , typename _I2 = _I1> concept std::indirectly_swappable
[alg.req.ind.swap], concept indirectly_swappable
Definition at line 877 of file iterator_concepts.h.
indirectly_writable
template<typename _Out , typename _Tp > concept std::indirectly_writable
Requirements for writing a value into an iterator's referenced object.
Definition at line 542 of file iterator_concepts.h.
invocable
template<typename _Fn , typename... _Args> concept std::invocable
[concept.invocable], concept invocable
Definition at line 336 of file concepts.
mergeable
template<typename _I1 , typename _I2 , typename _Out , typename _Rel = ranges::less, typename _P1 = identity, typename _P2 = identity> concept std::mergeable
[alg.req.mergeable], concept mergeable
Definition at line 904 of file iterator_concepts.h.
move_constructible
template<typename _Tp > concept std::move_constructible
[concept.moveconstructible], concept move_constructible
Definition at line 150 of file concepts.
permutable
template<typename _Iter > concept std::permutable
[alg.req.permutable], concept permutable
Definition at line 896 of file iterator_concepts.h.
predicate
template<typename _Fn , typename... _Args> concept std::predicate
[concept.predicate], concept predicate
Definition at line 344 of file concepts.
regular_invocable
template<typename _Fn , typename... _Args> concept std::regular_invocable
[concept.regularinvocable], concept regular_invocable
Definition at line 340 of file concepts.
relation
template<typename _Rel , typename _Tp , typename _Up > concept std::relation
[concept.relation], concept relation
Definition at line 349 of file concepts.
same_as
template<typename _Tp , typename _Up > concept std::same_as
[concept.same], concept same_as
Definition at line 62 of file concepts.
sortable
template<typename _Iter , typename _Rel = ranges::less, typename _Proj = identity> concept std::sortable
[alg.req.sortable], concept sortable
Definition at line 913 of file iterator_concepts.h.
strict_weak_order
template<typename _Rel , typename _Tp , typename _Up > concept std::strict_weak_order
[concept.strictweakorder], concept strict_weak_order
Definition at line 359 of file concepts.
uniform_random_bit_generator
template<typename _Gen > concept std::uniform_random_bit_generator
Requirements for a uniform random bit generator.
Definition at line 48 of file uniform_int_dist.h.
wcerr
wostream std::wcerr extern
Linked to standard output.
wcin
wistream std::wcin extern
Linked to standard error (buffered)
wclog
wostream std::wclog extern
Linked to standard error (unbuffered)
wcout
wostream std::wcout extern
Linked to standard input.
weakly_incrementable
template<typename _Iter > concept std::weakly_incrementable
Requirements on types that can be incremented with ++.
Definition at line 600 of file iterator_concepts.h.