libstdc++: std::__debug::map< _Key, _Tp, _Compare, _Allocator > Class Template Reference
std::__debug::map< _Key, _Tp, _Compare, _Allocator > Class Template Reference
Public Types
typedef _Allocator allocator_type
typedef __gnu_debug::_Safe_iterator< _Base_const_iterator, map > const_iterator
typedef _Base::const_pointer const_pointer
typedef _Base::const_reference const_reference
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef _Base::difference_type difference_type
using insert_return_type = _Node_insert_return< iterator, node_type >
typedef __gnu_debug::_Safe_iterator< _Base_iterator, map > iterator
typedef _Compare key_compare
typedef _Key key_type
typedef _Tp mapped_type
using node_type = typename _Base::node_type
typedef _Base::pointer pointer
typedef _Base::reference reference
typedef std::reverse_iterator< iterator > reverse_iterator
typedef _Base::size_type size_type
typedef std::pair< const _Key, _Tp > value_type
Public Member Functions
map (_Base_ref __x)
template<typename _InputIterator >
map (_InputIterator __first, _InputIterator __last, const _Compare &__comp=_Compare(), const _Allocator &__a=_Allocator())
template<typename _InputIterator >
map (_InputIterator __first, _InputIterator __last, const allocator_type &__a)
map (const _Compare &__comp, const _Allocator &__a=_Allocator())
map (const allocator_type &__a)
map (const map &)=default
map (const map &__m, const __type_identity_t< allocator_type > &__a)
map (initializer_list< value_type > __l, const _Compare &__c=_Compare(), const allocator_type &__a=allocator_type())
map (initializer_list< value_type > __l, const allocator_type &__a)
map (map &&)=default
map (map &&__m, const __type_identity_t< allocator_type > &__a) noexcept(noexcept(_Base(std::move(__m), __a)))
const _Base & _M_base () const noexcept
_Base & _M_base () noexcept
template<typename _Predicate >
void _M_invalidate_if (_Predicate __pred)
template<typename _Predicate >
void _M_transfer_from_if (_Safe_sequence &__from, _Predicate __pred)
const_iterator begin () const noexcept
iterator begin () noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
void clear () noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
template<typename... _Args>
std::pair< iterator, bool > emplace (_Args &&... __args)
template<typename... _Args>
iterator emplace_hint (const_iterator __pos, _Args &&... __args)
const_iterator end () const noexcept
iterator end () noexcept
template<typename _Kt , typename _Req = typename __has_is_transparent<_Compare, _Kt>::type>
std::pair< iterator, iterator > equal_range (const _Kt &__x)
template<typename _Kt , typename _Req = typename __has_is_transparent<_Compare, _Kt>::type>
std::pair< const_iterator, const_iterator > equal_range (const _Kt &__x) const
std::pair< iterator, iterator > equal_range (const key_type &__x)
std::pair< const_iterator, const_iterator > equal_range (const key_type &__x) const
_Base_iterator erase (_Base_const_iterator __position)
size_type erase (const key_type &__x)
iterator erase (const_iterator __first, const_iterator __last)
iterator erase (const_iterator __position)
_GLIBCXX_ABI_TAG_CXX11 iterator erase (iterator __position)
node_type extract (const key_type &__key)
node_type extract (const_iterator __position)
template<typename _Kt , typename _Req = typename __has_is_transparent<_Compare, _Kt>::type>
iterator find (const _Kt &__x)
template<typename _Kt , typename _Req = typename __has_is_transparent<_Compare, _Kt>::type>
const_iterator find (const _Kt &__x) const
iterator find (const key_type &__x)
const_iterator find (const key_type &__x) const
template<typename _InputIterator >
void insert (_InputIterator __first, _InputIterator __last)
template<typename _Pair , typename = typename std::enable_if<std::is_constructible<value_type, _Pair&&>::value>::type>
std::pair< iterator, bool > insert (_Pair &&__x)
std::pair< iterator, bool > insert (const value_type &__x)
iterator insert (const_iterator __hint, node_type &&__nh)
template<typename _Pair , typename = typename std::enable_if<std::is_constructible<value_type, _Pair&&>::value>::type>
iterator insert (const_iterator __position, _Pair &&__x)
iterator insert (const_iterator __position, const value_type &__x)
iterator insert (const_iterator __position, value_type &&__x)
insert_return_type insert (node_type &&__nh)
void insert (std::initializer_list< value_type > __list)
std::pair< iterator, bool > insert (value_type &&__x)
template<typename _Obj >
std::pair< iterator, bool > insert_or_assign (const key_type &__k, _Obj &&__obj)
template<typename _Obj >
iterator insert_or_assign (const_iterator __hint, const key_type &__k, _Obj &&__obj)
template<typename _Obj >
iterator insert_or_assign (const_iterator __hint, key_type &&__k, _Obj &&__obj)
template<typename _Obj >
std::pair< iterator, bool > insert_or_assign (key_type &&__k, _Obj &&__obj)
template<typename _Kt , typename _Req = typename __has_is_transparent<_Compare, _Kt>::type>
iterator lower_bound (const _Kt &__x)
template<typename _Kt , typename _Req = typename __has_is_transparent<_Compare, _Kt>::type>
const_iterator lower_bound (const _Kt &__x) const
iterator lower_bound (const key_type &__x)
const_iterator lower_bound (const key_type &__x) const
map & operator= (const map &)=default
map & operator= (initializer_list< value_type > __l)
map & operator= (map &&)=default
const_reverse_iterator rbegin () const noexcept
reverse_iterator rbegin () noexcept
const_reverse_iterator rend () const noexcept
reverse_iterator rend () noexcept
void swap (map &__x) noexcept(/*conditional */)
template<typename... _Args>
pair< iterator, bool > try_emplace (const key_type &__k, _Args &&... __args)
template<typename... _Args>
iterator try_emplace (const_iterator __hint, const key_type &__k, _Args &&... __args)
template<typename... _Args>
iterator try_emplace (const_iterator __hint, key_type &&__k, _Args &&... __args)
template<typename... _Args>
pair< iterator, bool > try_emplace (key_type &&__k, _Args &&... __args)
template<typename _Kt , typename _Req = typename __has_is_transparent<_Compare, _Kt>::type>
iterator upper_bound (const _Kt &__x)
template<typename _Kt , typename _Req = typename __has_is_transparent<_Compare, _Kt>::type>
const_iterator upper_bound (const _Kt &__x) const
iterator upper_bound (const key_type &__x)
const_iterator upper_bound (const key_type &__x) const
Public Attributes
_Safe_iterator_base * _M_const_iterators
_Safe_iterator_base * _M_iterators
unsigned int _M_version
Protected Member Functions
void _M_detach_all ()
void _M_detach_singular ()
__gnu_cxx::__mutex & _M_get_mutex () throw ()
void _M_invalidate_all ()
void _M_invalidate_all () const
void _M_revalidate_singular ()
void _M_swap (_Safe_container &__x) noexcept
void _M_swap (_Safe_sequence_base &__x) noexcept
Friends
template<typename _ItT , typename _SeqT , typename _CatT >
class ::__gnu_debug::_Safe_iterator
Detailed Description
template<typename _Key, typename _Tp, typename _Compare = std::less<_Key>, typename _Allocator = std::allocator<std::pair<const _Key, _Tp> >>
class std::__debug::map< _Key, _Tp, _Compare, _Allocator >
Class std::map with safety/checking/debug instrumentation.
Definition at line 44 of file map.h.
Member Function Documentation
_M_detach_all()
void __gnu_debug::_Safe_sequence_base::_M_detach_all () protected inherited
Detach all iterators, leaving them singular.
Referenced by __gnu_debug::_Safe_sequence_base::~_Safe_sequence_base().
_M_detach_singular()
void __gnu_debug::_Safe_sequence_base::_M_detach_singular () protected inherited
Detach all singular iterators.
Postcondition
for all iterators i attached to this sequence, i->_M_version == _M_version.
_M_get_mutex()
__gnu_cxx::__mutex& __gnu_debug::_Safe_sequence_base::_M_get_mutex () throw () protected inherited
For use in _Safe_sequence.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
_M_invalidate_all()
void __gnu_debug::_Safe_sequence_base::_M_invalidate_all () const inline protected inherited
Invalidates all iterators.
Definition at line 256 of file safe_base.h.
References __gnu_debug::_Safe_sequence_base::_M_version.
_M_invalidate_if()
template<typename _Sequence > template<typename _Predicate > void __gnu_debug::_Safe_sequence< _Sequence >::_M_invalidate_if (_Predicate __pred) inherited
Invalidates all iterators x that reference this sequence, are not singular, and for which __pred(x) returns true. __pred will be invoked with the normal iterators nested in the safe ones.
Definition at line 37 of file safe_sequence.tcc.
_M_revalidate_singular()
void __gnu_debug::_Safe_sequence_base::_M_revalidate_singular () protected inherited
Revalidates all attached singular iterators. This method may be used to validate iterators that were invalidated before (but for some reason, such as an exception, need to become valid again).
_M_swap()
void __gnu_debug::_Safe_sequence_base::_M_swap (_Safe_sequence_base & __x) protected noexcept inherited
Swap this sequence with the given sequence. This operation also swaps ownership of the iterators, so that when the operation is complete all iterators that originally referenced one container now reference the other container.
_M_transfer_from_if()
template<typename _Sequence > template<typename _Predicate > void __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if (_Safe_sequence< _Sequence > & __from, _Predicate __pred) inherited
Transfers all iterators x that reference from sequence, are not singular, and for which __pred(x) returns true. __pred will be invoked with the normal iterators nested in the safe ones.
Definition at line 68 of file safe_sequence.tcc.
References std::__addressof(), __gnu_debug::_Safe_sequence_base::_M_const_iterators, __gnu_debug::_Safe_iterator_base::_M_detach_single(), __gnu_debug::_Safe_sequence_base::_M_get_mutex(), __gnu_debug::_Safe_sequence_base::_M_iterators, __gnu_debug::_Safe_iterator_base::_M_next, __gnu_debug::_Safe_iterator_base::_M_prior, __gnu_debug::_Safe_iterator_base::_M_sequence, and __gnu_debug::_Safe_iterator_base::_M_version.
Member Data Documentation
_M_const_iterators
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_const_iterators inherited
The list of constant iterators that reference this container.
Definition at line 197 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
_M_iterators
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_iterators inherited
The list of mutable iterators that reference this container.
Definition at line 194 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
_M_version
unsigned int __gnu_debug::_Safe_sequence_base::_M_version mutable inherited
The container version number. This number may never be 0.
Definition at line 200 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence_base::_M_invalidate_all().
The documentation for this class was generated from the following file:
map.h