libstdc++: Complex Numbers
Complex Numbers
Numerics
Classes
class std::complex< _Tp >
Functions
constexpr std::complex< float >::complex (const complex< double > &)
constexpr std::complex< float >::complex (const complex< long double > &)
constexpr std::complex< double >::complex (const complex< long double > &)
template<typename _Tp >
_Tp std::__complex_abs (const complex< _Tp > &__z)
template<typename _Tp >
_Tp std::__complex_arg (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_cos (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_cosh (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_exp (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_log (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_pow (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
complex< _Tp > std::__complex_pow_unsigned (complex< _Tp > __x, unsigned __n)
template<typename _Tp >
complex< _Tp > std::__complex_sin (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_sinh (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_sqrt (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_tan (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_tanh (const complex< _Tp > &__z)
template<typename _Tp >
_Tp std::abs (const complex< _Tp > &)
template<typename _Tp >
_Tp std::arg (const complex< _Tp > &)
template<typename _Tp >
std::complex< typename __gnu_cxx::__promote< _Tp >::__type > std::tr1::conj (_Tp __x)
template<typename _Tp >
constexpr complex< _Tp > std::conj (const complex< _Tp > &)
template<typename _Tp >
std::complex< _Tp > std::tr1::conj (const std::complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::cos (const complex< _Tp > &)
template<typename _Tp >
complex< _Tp > std::cosh (const complex< _Tp > &)
template<typename _Tp >
complex< _Tp > std::exp (const complex< _Tp > &)
template<typename _Tp >
std::complex< _Tp > std::tr1::fabs (const std::complex< _Tp > &__z)
template<typename _Tp >
constexpr _Tp std::imag (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::log (const complex< _Tp > &)
template<typename _Tp >
complex< _Tp > std::log10 (const complex< _Tp > &)
template<typename _Tp >
constexpr _Tp std::norm (const complex< _Tp > &)
constexpr complex< _Tp > & std::complex< _Tp >::operator*= (const _Tp &)
template<typename _Up >
constexpr complex< _Tp > & std::complex< _Tp >::operator*= (const complex< _Up > &)
template<typename _Tp >
constexpr complex< _Tp > std::operator+ (const complex< _Tp > &__x)
template<typename _Up >
constexpr complex< _Tp > & std::complex< _Tp >::operator+= (const complex< _Up > &)
template<typename _Tp >
constexpr complex< _Tp > std::operator- (const complex< _Tp > &__x)
template<typename _Up >
constexpr complex< _Tp > & std::complex< _Tp >::operator-= (const complex< _Up > &)
constexpr complex< _Tp > & std::complex< _Tp >::operator/= (const _Tp &)
template<typename _Up >
constexpr complex< _Tp > & std::complex< _Tp >::operator/= (const complex< _Up > &)
template<typename _Tp , typename _CharT , class _Traits >
basic_ostream< _CharT, _Traits > & std::operator<< (basic_ostream< _CharT, _Traits > &__os, const complex< _Tp > &__x)
constexpr complex< _Tp > & std::complex< _Tp >::operator= (const _Tp &)
template<typename _Up >
constexpr complex< _Tp > & std::complex< _Tp >::operator= (const complex< _Up > &)
template<typename _Tp , typename _CharT , class _Traits >
basic_istream< _CharT, _Traits > & std::operator>> (basic_istream< _CharT, _Traits > &__is, complex< _Tp > &__x)
template<typename _Tp >
complex< _Tp > std::polar (const _Tp &, const _Tp &=0)
template<typename _Tp , typename _Up >
std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > std::tr1::polar (const _Tp &__rho, const _Up &__theta)
template<typename _Tp >
complex< _Tp > std::pow (const _Tp &, const complex< _Tp > &)
template<typename _Tp >
std::complex< _Tp > std::tr1::pow (const _Tp &__x, const std::complex< _Tp > &__y)
template<typename _Tp , typename _Up >
std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > std::tr1::pow (const _Tp &__x, const std::complex< _Up > &__y)
template<typename _Tp >
complex< _Tp > std::pow (const complex< _Tp > &, const _Tp &)
template<typename _Tp >
complex< _Tp > std::pow (const complex< _Tp > &, const complex< _Tp > &)
template<typename _Tp >
complex< _Tp > std::pow (const complex< _Tp > &, int)
template<typename _Tp >
std::complex< _Tp > std::tr1::pow (const std::complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp , typename _Up >
std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > std::tr1::pow (const std::complex< _Tp > &__x, const _Up &__y)
template<typename _Tp >
std::complex< _Tp > std::tr1::pow (const std::complex< _Tp > &__x, const std::complex< _Tp > &__y)
template<typename _Tp , typename _Up >
std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > std::tr1::pow (const std::complex< _Tp > &__x, const std::complex< _Up > &__y)
template<typename _Tp >
constexpr _Tp std::real (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::sin (const complex< _Tp > &)
template<typename _Tp >
complex< _Tp > std::sinh (const complex< _Tp > &)
template<typename _Tp >
complex< _Tp > std::sqrt (const complex< _Tp > &)
template<typename _Tp >
complex< _Tp > std::tan (const complex< _Tp > &)
template<typename _Tp >
complex< _Tp > std::tanh (const complex< _Tp > &)
template<typename _Tp >
constexpr complex< _Tp > std::operator+ (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator+ (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator+ (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator- (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator- (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator- (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator* (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator* (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator* (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator/ (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator/ (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator/ (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr bool std::operator== (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr bool std::operator== (const complex< _Tp > &__x, const _Tp &__y)
Detailed Description
Classes and functions for complex numbers.
Function Documentation
abs()
template<typename _Tp > _Tp std::abs (const complex< _Tp > & __z) inline
Return magnitude of z.
Definition at line 630 of file complex.
Referenced by std::binomial_distribution< _IntType >::operator()(), and std::poisson_distribution< _IntType >::operator()().
arg()
template<typename _Tp > _Tp std::arg (const complex< _Tp > & __z) inline
Return phase angle of z.
Definition at line 657 of file complex.
conj()
template<typename _Tp > constexpr complex< _Tp > std::conj (const complex< _Tp > & __z) inline constexpr
Return complex conjugate of z.
Definition at line 709 of file complex.
cos()
template<typename _Tp > complex< _Tp > std::cos (const complex< _Tp > & __z) inline
Return complex cosine of z.
Definition at line 741 of file complex.
cosh()
template<typename _Tp > complex< _Tp > std::cosh (const complex< _Tp > & __z) inline
Return complex hyperbolic cosine of z.
Definition at line 771 of file complex.
exp()
template<typename _Tp > complex< _Tp > std::exp (const complex< _Tp > & __z) inline
Return complex base e exponential of z.
Definition at line 797 of file complex.
fabs()
template<typename _Tp > std::complex< _Tp > std::tr1::fabs (const std::complex< _Tp > & __z) inline
fabs(__z) [8.1.8].
Definition at line 309 of file tr1/complex.
log()
template<typename _Tp > complex< _Tp > std::log (const complex< _Tp > & __z) inline
Return complex natural logarithm of z.
Definition at line 824 of file complex.
Referenced by std::normal_distribution< _RealType >::operator()(), std::gamma_distribution< _RealType >::operator()(), std::binomial_distribution< _IntType >::operator()(), and std::poisson_distribution< _IntType >::operator()().
log10()
template<typename _Tp > complex< _Tp > std::log10 (const complex< _Tp > & __z) inline
Return complex base 10 logarithm of z.
Definition at line 829 of file complex.
norm()
template<typename _Tp > constexpr _Tp std::norm (const complex< _Tp > & __z) inline constexpr
Return z magnitude squared.
Definition at line 693 of file complex.
operator*() [1/3]
template<typename _Tp > constexpr complex<_Tp> std::operator* (const _Tp & __x, const complex< _Tp > & __y) inline constexpr
Return new complex value x times y.
Definition at line 410 of file complex.
operator*() [2/3]
template<typename _Tp > constexpr complex<_Tp> std::operator* (const complex< _Tp > & __x, const _Tp & __y) inline constexpr
Return new complex value x times y.
Definition at line 401 of file complex.
operator*() [3/3]
template<typename _Tp > constexpr complex<_Tp> std::operator* (const complex< _Tp > & __x, const complex< _Tp > & __y) inline constexpr
Return new complex value x times y.
Definition at line 392 of file complex.
Referenced by std::requires().
operator*=() [1/2]
template<typename _Tp > constexpr complex< _Tp > & std::complex< _Tp >::operator*= (const _Tp & __t) constexpr
Multiply this complex number by a scalar.
Definition at line 251 of file complex.
operator*=() [2/2]
template<typename _Tp > template<typename _Up > constexpr complex< _Tp > & std::complex< _Tp >::operator*= (const complex< _Up > & __z) constexpr
Multiply this complex number by another.
Definition at line 305 of file complex.
operator+() [1/4]
template<typename _Tp > constexpr complex<_Tp> std::operator+ (const _Tp & __x, const complex< _Tp > & __y) inline constexpr
Return new complex value x plus y.
Definition at line 350 of file complex.
operator+() [2/4]
template<typename _Tp > constexpr complex<_Tp> std::operator+ (const complex< _Tp > & __x) inline constexpr
Return x.
Definition at line 451 of file complex.
operator+() [3/4]
template<typename _Tp > constexpr complex<_Tp> std::operator+ (const complex< _Tp > & __x, const _Tp & __y) inline constexpr
Return new complex value x plus y.
Definition at line 341 of file complex.
operator+() [4/4]
template<typename _Tp > constexpr complex<_Tp> std::operator+ (const complex< _Tp > & __x, const complex< _Tp > & __y) inline constexpr
Return new complex value x plus y.
Definition at line 332 of file complex.
operator+=()
template<typename _Tp > template<typename _Up > constexpr complex< _Tp > & std::complex< _Tp >::operator+= (const complex< _Up > & __z) constexpr
Add another complex number to this one.
Definition at line 282 of file complex.
operator-() [1/4]
template<typename _Tp > constexpr complex<_Tp> std::operator- (const _Tp & __x, const complex< _Tp > & __y) inline constexpr
Return new complex value x minus y.
Definition at line 380 of file complex.
operator-() [2/4]
template<typename _Tp > constexpr complex<_Tp> std::operator- (const complex< _Tp > & __x) inline constexpr
Return complex negation of x.
Definition at line 457 of file complex.
operator-() [3/4]
template<typename _Tp > constexpr complex<_Tp> std::operator- (const complex< _Tp > & __x, const _Tp & __y) inline constexpr
Return new complex value x minus y.
Definition at line 371 of file complex.
operator-() [4/4]
template<typename _Tp > constexpr complex<_Tp> std::operator- (const complex< _Tp > & __x, const complex< _Tp > & __y) inline constexpr
Return new complex value x minus y.
Definition at line 362 of file complex.
operator-=()
template<typename _Tp > template<typename _Up > constexpr complex< _Tp > & std::complex< _Tp >::operator-= (const complex< _Up > & __z) constexpr
Subtract another complex number from this one.
Definition at line 293 of file complex.
operator/() [1/3]
template<typename _Tp > constexpr complex<_Tp> std::operator/ (const _Tp & __x, const complex< _Tp > & __y) inline constexpr
Return new complex value x divided by y.
Definition at line 440 of file complex.
operator/() [2/3]
template<typename _Tp > constexpr complex<_Tp> std::operator/ (const complex< _Tp > & __x, const _Tp & __y) inline constexpr
Return new complex value x divided by y.
Definition at line 431 of file complex.
operator/() [3/3]
template<typename _Tp > constexpr complex<_Tp> std::operator/ (const complex< _Tp > & __x, const complex< _Tp > & __y) inline constexpr
Return new complex value x divided by y.
Definition at line 422 of file complex.
operator/=() [1/2]
template<typename _Tp > constexpr complex< _Tp > & std::complex< _Tp >::operator/= (const _Tp & __t) constexpr
Divide this complex number by a scalar.
Definition at line 261 of file complex.
operator/=() [2/2]
template<typename _Tp > template<typename _Up > constexpr complex< _Tp > & std::complex< _Tp >::operator/= (const complex< _Up > & __z) constexpr
Divide this complex number by another.
Definition at line 318 of file complex.
operator<<()
template<typename _Tp , typename _CharT , class _Traits > basic_ostream<_CharT, _Traits>& std::operator<< (basic_ostream< _CharT, _Traits > & __os, const complex< _Tp > & __x)
Insertion operator for complex values.
Definition at line 501 of file complex.
operator=() [1/2]
template<typename _Tp > constexpr complex< _Tp > & std::complex< _Tp >::operator= (const _Tp & __t) constexpr
Assign a scalar to this complex number.
Definition at line 241 of file complex.
operator=() [2/2]
template<typename _Tp > template<typename _Up > constexpr complex< _Tp > & std::complex< _Tp >::operator= (const complex< _Up > & __z) constexpr
Assign another complex number to this one.
Definition at line 271 of file complex.
operator==() [1/2]
template<typename _Tp > constexpr bool std::operator== (const complex< _Tp > & __x, const _Tp & __y) inline constexpr
Return true if x is equal to y.
Definition at line 469 of file complex.
operator==() [2/2]
template<typename _Tp > constexpr bool std::operator== (const complex< _Tp > & __x, const complex< _Tp > & __y) inline constexpr
Return true if x is equal to y.
Definition at line 464 of file complex.
operator>>()
template<typename _Tp , typename _CharT , class _Traits > basic_istream<_CharT, _Traits>& std::operator>> (basic_istream< _CharT, _Traits > & __is, complex< _Tp > & __x)
Extraction operator for complex values.
Definition at line 501 of file complex.
polar()
template<typename _Tp > complex< _Tp > std::polar (const _Tp & __rho, const _Tp & __theta = 0) inline
Return complex with magnitude rho and angle theta.
Definition at line 701 of file complex.
pow() [1/5]
template<typename _Tp > complex< _Tp > std::pow (const _Tp & __x, const complex< _Tp > & __y) inline
Return x to the y'th power.
Definition at line 1073 of file complex.
pow() [2/5]
template<typename _Tp > complex< _Tp > std::pow (const complex< _Tp > & __x, const _Tp & __y)
Return x to the y'th power.
Definition at line 1028 of file complex.
pow() [3/5]
template<typename _Tp > complex< _Tp > std::pow (const complex< _Tp > & __x, const complex< _Tp > & __y) inline
Return x to the y'th power.
Definition at line 1067 of file complex.
pow() [4/5]
template<typename _Tp > complex< _Tp > std::pow (const complex< _Tp > & __z, int __n) inline
Return x to the y'th power.
Definition at line 1019 of file complex.
Referenced by std::gamma_distribution< _RealType >::operator()().
pow() [5/5]
template<typename _Tp , typename _Up > std::complex<typename __gnu_cxx::__promote_2<_Tp, _Up>::__type> std::tr1::pow (const std::complex< _Tp > & __x, const _Up & __y) inline
Additional overloads [8.1.9].
Definition at line 350 of file tr1/complex.
sin()
template<typename _Tp > complex< _Tp > std::sin (const complex< _Tp > & __z) inline
Return complex sine of z.
Definition at line 859 of file complex.
sinh()
template<typename _Tp > complex< _Tp > std::sinh (const complex< _Tp > & __z) inline
Return complex hyperbolic sine of z.
Definition at line 889 of file complex.
sqrt()
template<typename _Tp > complex< _Tp > std::sqrt (const complex< _Tp > & __z) inline
Return complex square root of z.
Definition at line 933 of file complex.
Referenced by std::student_t_distribution< _RealType >::operator()(), and std::normal_distribution< _RealType >::operator()().
tan()
template<typename _Tp > complex< _Tp > std::tan (const complex< _Tp > & __z) inline
Return complex tangent of z.
Definition at line 960 of file complex.
tanh()
template<typename _Tp > complex< _Tp > std::tanh (const complex< _Tp > & __z) inline
Return complex hyperbolic tangent of z.
Definition at line 988 of file complex.