libstdc++: std::unique_ptr< _Tp[], _Dp > Class Template Reference
std::unique_ptr< _Tp[], _Dp > Class Template Reference
Public Types
template<typename _Up >
using __safe_conversion_raw = __and_< __or_< __or_< is_same< _Up, pointer >, is_same< _Up, nullptr_t > >, __and_< is_pointer< _Up >, is_same< pointer, element_type * >, is_convertible< typename remove_pointer< _Up >::type(*)[], element_type(*)[]> > > >
template<typename _Up , typename _Ep , typename _UPtr = unique_ptr<_Up, _Ep>, typename _UP_pointer = typename _UPtr::pointer, typename _UP_element_type = typename _UPtr::element_type>
using __safe_conversion_up = __and_< is_array< _Up >, is_same< pointer, element_type * >, is_same< _UP_pointer, _UP_element_type * >, is_convertible< _UP_element_type(*)[], element_type(*)[]> >
using deleter_type = _Dp
using element_type = _Tp
using pointer = typename __uniq_ptr_impl< _Tp, _Dp >::pointer
Public Member Functions
template<typename _Del = _Dp, typename = _DeleterConstraint<_Del>>
constexpr unique_ptr () noexcept
template<typename _Up , typename _Vp = _Dp, typename = _DeleterConstraint<_Vp>, typename = typename enable_if< __safe_conversion_raw<_Up>::value, bool>::type>
_GLIBCXX23_CONSTEXPR unique_ptr (_Up __p) noexcept
template<typename _Up , typename _Del = deleter_type, typename = _Require<__safe_conversion_raw<_Up>, is_move_constructible<_Del>>>
_GLIBCXX23_CONSTEXPR unique_ptr (_Up __p, __enable_if_t<!is_lvalue_reference< _Del >::value, _Del && > __d) noexcept
template<typename _Up , typename _Del = deleter_type, typename = _Require<__safe_conversion_raw<_Up>, is_copy_constructible<_Del>>>
_GLIBCXX23_CONSTEXPR unique_ptr (_Up __p, const deleter_type &__d) noexcept
template<typename _Up , typename _Del = deleter_type, typename _DelUnref = typename remove_reference<_Del>::type, typename = _Require<__safe_conversion_raw<_Up>>>
unique_ptr (_Up, __enable_if_t< is_lvalue_reference< _Del >::value, _DelUnref && >)=delete
unique_ptr (const unique_ptr &)=delete
template<typename _Del = _Dp, typename = _DeleterConstraint<_Del>>
constexpr unique_ptr (nullptr_t) noexcept
unique_ptr (unique_ptr &&)=default
template<typename _Up , typename _Ep , typename = _Require< __safe_conversion_up<_Up, _Ep>, __conditional_t<is_reference<_Dp>::value, is_same<_Ep, _Dp>, is_convertible<_Ep, _Dp>>>>
_GLIBCXX23_CONSTEXPR unique_ptr (unique_ptr< _Up, _Ep > &&__u) noexcept
~unique_ptr ()
_GLIBCXX23_CONSTEXPR pointer get () const noexcept
_GLIBCXX23_CONSTEXPR const deleter_type & get_deleter () const noexcept
_GLIBCXX23_CONSTEXPR deleter_type & get_deleter () noexcept
_GLIBCXX23_CONSTEXPR operator bool () const noexcept
unique_ptr & operator= (const unique_ptr &)=delete
_GLIBCXX23_CONSTEXPR unique_ptr & operator= (nullptr_t) noexcept
unique_ptr & operator= (unique_ptr &&)=default
template<typename _Up , typename _Ep >
_GLIBCXX23_CONSTEXPR enable_if< __and_< __safe_conversion_up< _Up, _Ep >, is_assignable< deleter_type &, _Ep && > >::value, unique_ptr & >::type operator= (unique_ptr< _Up, _Ep > &&__u) noexcept
_GLIBCXX23_CONSTEXPR std::add_lvalue_reference< element_type >::type operator[] (size_t __i) const
_GLIBCXX23_CONSTEXPR pointer release () noexcept
template<typename _Up , typename = _Require< __or_<is_same<_Up, pointer>, __and_<is_same<pointer, element_type*>, is_pointer<_Up>, is_convertible< typename remove_pointer<_Up>::type(*)[], element_type(*)[] > > > >>
_GLIBCXX23_CONSTEXPR void reset (_Up __p) noexcept
_GLIBCXX23_CONSTEXPR void reset (nullptr_t=nullptr) noexcept
_GLIBCXX23_CONSTEXPR void swap (unique_ptr &__u) noexcept
Detailed Description
template<typename _Tp, typename _Dp>
class std::unique_ptr< _Tp[], _Dp >
A move-only smart pointer that manages unique ownership of an array.
Since
C++11
Definition at line 527 of file unique_ptr.h.
Constructor & Destructor Documentation
unique_ptr() [1/6]
template<typename _Tp , typename _Dp > template<typename _Del = _Dp, typename = _DeleterConstraint<_Del>> constexpr std::unique_ptr< _Tp[], _Dp >::unique_ptr () inline constexpr noexcept
Default constructor, creates a unique_ptr that owns nothing.
Definition at line 580 of file unique_ptr.h.
unique_ptr() [2/6]
template<typename _Tp , typename _Dp > template<typename _Up , typename _Vp = _Dp, typename = _DeleterConstraint<_Vp>, typename = typename enable_if< __safe_conversion_raw<_Up>::value, bool>::type> _GLIBCXX23_CONSTEXPR std::unique_ptr< _Tp[], _Dp >::unique_ptr (_Up __p) inline explicit noexcept
Takes ownership of a pointer.
Parameters
__p A pointer to an array of a type safely convertible to an array of element_type
The deleter will be value-initialized.
Definition at line 598 of file unique_ptr.h.
unique_ptr() [3/6]
template<typename _Tp , typename _Dp > template<typename _Up , typename _Del = deleter_type, typename = _Require<__safe_conversion_raw<_Up>, is_copy_constructible<_Del>>> _GLIBCXX23_CONSTEXPR std::unique_ptr< _Tp[], _Dp >::unique_ptr (_Up __p, const deleter_type & __d) inline noexcept
Takes ownership of a pointer.
Parameters
__p A pointer to an array of a type safely convertible to an array of element_type
__d A reference to a deleter.
The deleter will be initialized with __d
Definition at line 614 of file unique_ptr.h.
unique_ptr() [4/6]
template<typename _Tp , typename _Dp > template<typename _Up , typename _Del = deleter_type, typename = _Require<__safe_conversion_raw<_Up>, is_move_constructible<_Del>>> _GLIBCXX23_CONSTEXPR std::unique_ptr< _Tp[], _Dp >::unique_ptr (_Up __p, __enable_if_t<!is_lvalue_reference< _Del >::value, _Del && > __d) inline noexcept
Takes ownership of a pointer.
Parameters
__p A pointer to an array of a type safely convertible to an array of element_type
__d A reference to a deleter.
The deleter will be initialized with std::move(__d)
Definition at line 629 of file unique_ptr.h.
unique_ptr() [5/6]
template<typename _Tp , typename _Dp > std::unique_ptr< _Tp[], _Dp >::unique_ptr (unique_ptr< _Tp[], _Dp > &&) default
Move constructor.
unique_ptr() [6/6]
template<typename _Tp , typename _Dp > template<typename _Del = _Dp, typename = _DeleterConstraint<_Del>> constexpr std::unique_ptr< _Tp[], _Dp >::unique_ptr (nullptr_t) inline constexpr noexcept
Creates a unique_ptr that owns nothing.
Definition at line 647 of file unique_ptr.h.
~unique_ptr()
template<typename _Tp , typename _Dp > std::unique_ptr< _Tp[], _Dp >::~unique_ptr () inline
Destructor, invokes the deleter if the stored pointer is not null.
Definition at line 665 of file unique_ptr.h.
References std::unique_ptr< _Tp, _Dp >::get_deleter().
Member Function Documentation
get()
template<typename _Tp , typename _Dp > _GLIBCXX23_CONSTEXPR pointer std::unique_ptr< _Tp[], _Dp >::get (void) const inline noexcept
Return the stored pointer.
Definition at line 726 of file unique_ptr.h.
get_deleter() [1/2]
template<typename _Tp , typename _Dp > _GLIBCXX23_CONSTEXPR const deleter_type& std::unique_ptr< _Tp[], _Dp >::get_deleter () const inline noexcept
Return a reference to the stored deleter.
Definition at line 738 of file unique_ptr.h.
get_deleter() [2/2]
template<typename _Tp , typename _Dp > _GLIBCXX23_CONSTEXPR deleter_type& std::unique_ptr< _Tp[], _Dp >::get_deleter () inline noexcept
Return a reference to the stored deleter.
Definition at line 732 of file unique_ptr.h.
operator bool()
template<typename _Tp , typename _Dp > _GLIBCXX23_CONSTEXPR std::unique_ptr< _Tp[], _Dp >::operator bool () const inline explicit noexcept
Return true if the stored pointer is not null.
Definition at line 743 of file unique_ptr.h.
References std::unique_ptr< _Tp, _Dp >::get().
operator=() [1/3]
template<typename _Tp , typename _Dp > _GLIBCXX23_CONSTEXPR unique_ptr& std::unique_ptr< _Tp[], _Dp >::operator= (nullptr_t) inline noexcept
Reset the unique_ptr to empty, invoking the deleter if necessary.
Definition at line 706 of file unique_ptr.h.
References std::unique_ptr< _Tp, _Dp >::reset().
operator=() [2/3]
template<typename _Tp , typename _Dp > unique_ptr& std::unique_ptr< _Tp[], _Dp >::operator= (unique_ptr< _Tp[], _Dp > &&) default
Move assignment operator.
Invokes the deleter if this object owns a pointer.
operator=() [3/3]
template<typename _Tp , typename _Dp > template<typename _Up , typename _Ep > _GLIBCXX23_CONSTEXPR enable_if<__and_<__safe_conversion_up<_Up, _Ep>, is_assignable<deleter_type&, _Ep&&> >::value, unique_ptr&>::type std::unique_ptr< _Tp[], _Dp >::operator= (unique_ptr< _Up, _Ep > && __u) inline noexcept
Assignment from another type.
Parameters
__u The object to transfer ownership from, which owns a convertible pointer to an array object.
Invokes the deleter if this object owns a pointer.
Definition at line 696 of file unique_ptr.h.
References std::unique_ptr< _Tp, _Dp >::get_deleter(), and std::unique_ptr< _Tp, _Dp >::reset().
operator[]()
template<typename _Tp , typename _Dp > _GLIBCXX23_CONSTEXPR std::add_lvalue_reference<element_type>::type std::unique_ptr< _Tp[], _Dp >::operator[] (size_t __i) const inline
Access an element of owned array.
Definition at line 717 of file unique_ptr.h.
release()
template<typename _Tp , typename _Dp > _GLIBCXX23_CONSTEXPR pointer std::unique_ptr< _Tp[], _Dp >::release () inline noexcept
Release ownership of any stored pointer.
Definition at line 751 of file unique_ptr.h.
reset()
template<typename _Tp , typename _Dp > template<typename _Up , typename = _Require< __or_<is_same<_Up, pointer>, __and_<is_same<pointer, element_type*>, is_pointer<_Up>, is_convertible< typename remove_pointer<_Up>::type(*)[], element_type(*)[] > > > >> _GLIBCXX23_CONSTEXPR void std::unique_ptr< _Tp[], _Dp >::reset (_Up __p) inline noexcept
Replace the stored pointer.
Parameters
__p The new pointer to store.
The deleter will be invoked if a pointer is already owned.
Definition at line 774 of file unique_ptr.h.
References std::move().
swap()
template<typename _Tp , typename _Dp > _GLIBCXX23_CONSTEXPR void std::unique_ptr< _Tp[], _Dp >::swap (unique_ptr< _Tp[], _Dp > & __u) inline noexcept
Exchange the pointer and deleter with another object.
Definition at line 784 of file unique_ptr.h.
The documentation for this class was generated from the following file:
unique_ptr.h