libstdc++: std::__debug::list< _Tp, _Allocator > Class Template Reference
std::__debug::list< _Tp, _Allocator > Class Template Reference
Public Types
typedef _Allocator allocator_type
typedef __gnu_debug::_Safe_iterator< _Base_const_iterator, list > const_iterator
typedef _Base::const_pointer const_pointer
typedef _Base::const_reference const_reference
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef _Base::difference_type difference_type
typedef __gnu_debug::_Safe_iterator< _Base_iterator, list > iterator
typedef _Base::pointer pointer
typedef _Base::reference reference
typedef std::reverse_iterator< iterator > reverse_iterator
typedef _Base::size_type size_type
typedef _Tp value_type
Public Member Functions
list (_Base_ref __x)
template<class _InputIterator , typename = std::_RequireInputIter<_InputIterator>>
list (_InputIterator __first, _InputIterator __last, const _Allocator &__a=_Allocator())
list (const _Allocator &__a) noexcept
list (const list &)=default
list (const list &__x, const __type_identity_t< allocator_type > &__a)
list (initializer_list< value_type > __l, const allocator_type &__a=allocator_type())
list (list &&)=default
list (list &&__x, const __type_identity_t< allocator_type > &__a) noexcept(std::is_nothrow_constructible< _Base, _Base, const allocator_type & >::value)
list (size_type __n, const __type_identity_t< _Tp > &__value, const _Allocator &__a=_Allocator())
list (size_type __n, const allocator_type &__a=allocator_type())
const _Base & _M_base () const noexcept
_Base & _M_base () noexcept
template<typename _Predicate >
void _M_invalidate_if (_Predicate __pred)
template<typename _Predicate >
void _M_transfer_from_if (_Safe_sequence &__from, _Predicate __pred)
template<class _InputIterator , typename = std::_RequireInputIter<_InputIterator>>
void assign (_InputIterator __first, _InputIterator __last)
void assign (initializer_list< value_type > __l)
void assign (size_type __n, const _Tp &__t)
const_reference back () const noexcept
reference back () noexcept
const_iterator begin () const noexcept
iterator begin () noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
void clear () noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
template<typename... _Args>
iterator emplace (const_iterator __position, _Args &&... __args)
const_iterator end () const noexcept
iterator end () noexcept
iterator erase (const_iterator __first, const_iterator __last) noexcept
iterator erase (const_iterator __position) noexcept
const_reference front () const noexcept
reference front () noexcept
iterator insert (const_iterator __p, initializer_list< value_type > __l)
template<class _InputIterator , typename = std::_RequireInputIter<_InputIterator>>
iterator insert (const_iterator __position, _InputIterator __first, _InputIterator __last)
iterator insert (const_iterator __position, _Tp &&__x)
iterator insert (const_iterator __position, const _Tp &__x)
iterator insert (const_iterator __position, size_type __n, const _Tp &__x)
void merge (list &&__x)
template<class _Compare >
void merge (list &&__x, _Compare __comp)
void merge (list &__x)
template<typename _Compare >
void merge (list &__x, _Compare __comp)
list & operator= (const list &)=default
list & operator= (initializer_list< value_type > __l)
list & operator= (list &&)=default
void pop_back () noexcept
void pop_front () noexcept
const_reverse_iterator rbegin () const noexcept
reverse_iterator rbegin () noexcept
__remove_return_type remove (const _Tp &__value)
template<class _Predicate >
__remove_return_type remove_if (_Predicate __pred)
const_reverse_iterator rend () const noexcept
reverse_iterator rend () noexcept
void resize (size_type __sz)
void resize (size_type __sz, const _Tp &__c)
void sort ()
template<typename _StrictWeakOrdering >
void sort (_StrictWeakOrdering __pred)
void splice (const_iterator __position, list &&__x) noexcept
void splice (const_iterator __position, list &&__x, const_iterator __first, const_iterator __last) noexcept
void splice (const_iterator __position, list &&__x, const_iterator __i) noexcept
void splice (const_iterator __position, list &__x) noexcept
void splice (const_iterator __position, list &__x, const_iterator __first, const_iterator __last) noexcept
void splice (const_iterator __position, list &__x, const_iterator __i) noexcept
void swap (list &__x) noexcept(/*conditional */)
__remove_return_type unique ()
template<class _BinaryPredicate >
__remove_return_type unique (_BinaryPredicate __binary_pred)
Public Attributes
_Safe_iterator_base * _M_const_iterators
_Safe_iterator_base * _M_iterators
unsigned int _M_version
Protected Member Functions
void _M_detach_all ()
void _M_detach_singular ()
__gnu_cxx::__mutex & _M_get_mutex () throw ()
void _M_invalidate_all ()
void _M_invalidate_all () const
void _M_revalidate_singular ()
void _M_swap (_Safe_container &__x) noexcept
void _M_swap (_Safe_sequence_base &__x) noexcept
Friends
template<typename _ItT , typename _SeqT , typename _CatT >
class ::__gnu_debug::_Safe_iterator
Detailed Description
template<typename _Tp, typename _Allocator = std::allocator<_Tp>>
class std::__debug::list< _Tp, _Allocator >
Class std::list with safety/checking/debug instrumentation.
Definition at line 50 of file debug/list.
Member Function Documentation
_M_detach_all()
void __gnu_debug::_Safe_sequence_base::_M_detach_all () protected inherited
Detach all iterators, leaving them singular.
Referenced by __gnu_debug::_Safe_sequence_base::~_Safe_sequence_base().
_M_detach_singular()
void __gnu_debug::_Safe_sequence_base::_M_detach_singular () protected inherited
Detach all singular iterators.
Postcondition
for all iterators i attached to this sequence, i->_M_version == _M_version.
_M_get_mutex()
__gnu_cxx::__mutex& __gnu_debug::_Safe_sequence_base::_M_get_mutex () throw () protected inherited
For use in _Safe_sequence.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
_M_invalidate_all()
void __gnu_debug::_Safe_sequence_base::_M_invalidate_all () const inline protected inherited
Invalidates all iterators.
Definition at line 256 of file safe_base.h.
References __gnu_debug::_Safe_sequence_base::_M_version.
_M_invalidate_if()
template<typename _Sequence > template<typename _Predicate > void __gnu_debug::_Safe_sequence< _Sequence >::_M_invalidate_if (_Predicate __pred) inherited
Invalidates all iterators x that reference this sequence, are not singular, and for which __pred(x) returns true. __pred will be invoked with the normal iterators nested in the safe ones.
Definition at line 37 of file safe_sequence.tcc.
_M_revalidate_singular()
void __gnu_debug::_Safe_sequence_base::_M_revalidate_singular () protected inherited
Revalidates all attached singular iterators. This method may be used to validate iterators that were invalidated before (but for some reason, such as an exception, need to become valid again).
_M_swap()
void __gnu_debug::_Safe_sequence_base::_M_swap (_Safe_sequence_base & __x) protected noexcept inherited
Swap this sequence with the given sequence. This operation also swaps ownership of the iterators, so that when the operation is complete all iterators that originally referenced one container now reference the other container.
_M_transfer_from_if()
template<typename _Sequence > template<typename _Predicate > void __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if (_Safe_sequence< _Sequence > & __from, _Predicate __pred) inherited
Transfers all iterators x that reference from sequence, are not singular, and for which __pred(x) returns true. __pred will be invoked with the normal iterators nested in the safe ones.
Definition at line 68 of file safe_sequence.tcc.
References std::__addressof(), __gnu_debug::_Safe_sequence_base::_M_const_iterators, __gnu_debug::_Safe_iterator_base::_M_detach_single(), __gnu_debug::_Safe_sequence_base::_M_get_mutex(), __gnu_debug::_Safe_sequence_base::_M_iterators, __gnu_debug::_Safe_iterator_base::_M_next, __gnu_debug::_Safe_iterator_base::_M_prior, __gnu_debug::_Safe_iterator_base::_M_sequence, and __gnu_debug::_Safe_iterator_base::_M_version.
Member Data Documentation
_M_const_iterators
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_const_iterators inherited
The list of constant iterators that reference this container.
Definition at line 197 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
_M_iterators
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_iterators inherited
The list of mutable iterators that reference this container.
Definition at line 194 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
_M_version
unsigned int __gnu_debug::_Safe_sequence_base::_M_version mutable inherited
The container version number. This number may never be 0.
Definition at line 200 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence_base::_M_invalidate_all().
The documentation for this class was generated from the following file:
debug/list