libstdc++: std::__debug::vector< _Tp, _Allocator > Class Template Reference
std::__debug::vector< _Tp, _Allocator > Class Template Reference
Public Types
typedef _Allocator allocator_type
typedef __gnu_debug::_Safe_iterator< _Base_const_iterator, vector > const_iterator
typedef _Base::const_pointer const_pointer
typedef _Base::const_reference const_reference
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef _Base::difference_type difference_type
typedef __gnu_debug::_Safe_iterator< _Base_iterator, vector > iterator
typedef _Base::pointer pointer
typedef _Base::reference reference
typedef std::reverse_iterator< iterator > reverse_iterator
typedef _Base::size_type size_type
typedef _Tp value_type
Public Member Functions
vector (_Base_ref __x)
template<class _InputIterator , typename = std::_RequireInputIter<_InputIterator>>
vector (_InputIterator __first, _InputIterator __last, const _Allocator &__a=_Allocator())
vector (const _Allocator &__a) noexcept
vector (const vector &)=default
vector (const vector &__x, const __type_identity_t< allocator_type > &__a)
vector (initializer_list< value_type > __l, const allocator_type &__a=allocator_type())
vector (size_type __n, const __type_identity_t< _Tp > &__value, const _Allocator &__a=_Allocator())
vector (size_type __n, const _Allocator &__a=_Allocator())
vector (vector &&)=default
vector (vector &&__x, const __type_identity_t< allocator_type > &__a) noexcept(std::is_nothrow_constructible< _Base, _Base, const allocator_type & >::value)
const _Base & _M_base () const noexcept
_Base & _M_base () noexcept
template<typename _Predicate >
void _M_invalidate_if (_Predicate __pred)
template<typename _Predicate >
void _M_transfer_from_if (_Safe_sequence &__from, _Predicate __pred)
template<typename _InputIterator , typename = std::_RequireInputIter<_InputIterator>>
void assign (_InputIterator __first, _InputIterator __last)
void assign (initializer_list< value_type > __l)
void assign (size_type __n, const _Tp &__u)
const_reference back () const noexcept
reference back () noexcept
const_iterator begin () const noexcept
iterator begin () noexcept
size_type capacity () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
void clear () noexcept
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
template<typename... _Args>
iterator emplace (const_iterator __position, _Args &&... __args)
template<typename... _Args>
reference emplace_back (_Args &&... __args)
const_iterator end () const noexcept
iterator end () noexcept
iterator erase (const_iterator __first, const_iterator __last)
iterator erase (const_iterator __position)
const_reference front () const noexcept
reference front () noexcept
template<class _InputIterator , typename = std::_RequireInputIter<_InputIterator>>
iterator insert (const_iterator __position, _InputIterator __first, _InputIterator __last)
template<typename _Up = _Tp>
__gnu_cxx::__enable_if<!std::__are_same< _Up, bool >::__value, iterator >::__type insert (const_iterator __position, _Tp &&__x)
iterator insert (const_iterator __position, const _Tp &__x)
iterator insert (const_iterator __position, initializer_list< value_type > __l)
iterator insert (const_iterator __position, size_type __n, const _Tp &__x)
vector & operator= (const vector &)=default
vector & operator= (initializer_list< value_type > __l)
vector & operator= (vector &&)=default
const_reference operator[] (size_type __n) const noexcept
reference operator[] (size_type __n) noexcept
void pop_back () noexcept
template<typename _Up = _Tp>
__gnu_cxx::__enable_if<!std::__are_same< _Up, bool >::__value, void >::__type push_back (_Tp &&__x)
void push_back (const _Tp &__x)
const_reverse_iterator rbegin () const noexcept
reverse_iterator rbegin () noexcept
const_reverse_iterator rend () const noexcept
reverse_iterator rend () noexcept
void reserve (size_type __n)
void resize (size_type __sz)
void resize (size_type __sz, const _Tp &__c)
void shrink_to_fit ()
void swap (vector &__x) noexcept(/*conditional */)
Public Attributes
_Safe_iterator_base * _M_const_iterators
_Safe_iterator_base * _M_iterators
unsigned int _M_version
Protected Member Functions
void _M_detach_all ()
void _M_detach_singular ()
__gnu_cxx::__mutex & _M_get_mutex () throw ()
void _M_invalidate_all () const
bool _M_requires_reallocation (size_type __elements) const noexcept
void _M_revalidate_singular ()
void _M_swap (_Safe_container &__x) noexcept
void _M_swap (_Safe_sequence_base &__x) noexcept
void _M_update_guaranteed_capacity () noexcept
Protected Attributes
size_type _M_guaranteed_capacity
Friends
template<typename _ItT , typename _SeqT , typename _CatT >
class ::__gnu_debug::_Safe_iterator
Detailed Description
template<typename _Tp, typename _Allocator = std::allocator<_Tp>>
class std::__debug::vector< _Tp, _Allocator >
Class std::vector with safety/checking/debug instrumentation.
Definition at line 117 of file debug/vector.
Constructor & Destructor Documentation
vector()
template<typename _Tp , typename _Allocator = std::allocator<_Tp>> std::__debug::vector< _Tp, _Allocator >::vector (_Base_ref __x) inline
Construction from a normal-mode vector.
Definition at line 234 of file debug/vector.
Member Function Documentation
_M_detach_all()
void __gnu_debug::_Safe_sequence_base::_M_detach_all () protected inherited
Detach all iterators, leaving them singular.
Referenced by __gnu_debug::_Safe_sequence_base::~_Safe_sequence_base().
_M_detach_singular()
void __gnu_debug::_Safe_sequence_base::_M_detach_singular () protected inherited
Detach all singular iterators.
Postcondition
for all iterators i attached to this sequence, i->_M_version == _M_version.
_M_get_mutex()
__gnu_cxx::__mutex& __gnu_debug::_Safe_sequence_base::_M_get_mutex () throw () protected inherited
For use in _Safe_sequence.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
_M_invalidate_all()
void __gnu_debug::_Safe_sequence_base::_M_invalidate_all () const inline protected inherited
Invalidates all iterators.
Definition at line 256 of file safe_base.h.
References __gnu_debug::_Safe_sequence_base::_M_version.
_M_invalidate_if()
template<typename _Sequence > template<typename _Predicate > void __gnu_debug::_Safe_sequence< _Sequence >::_M_invalidate_if (_Predicate __pred) inherited
Invalidates all iterators x that reference this sequence, are not singular, and for which __pred(x) returns true. __pred will be invoked with the normal iterators nested in the safe ones.
Definition at line 37 of file safe_sequence.tcc.
_M_revalidate_singular()
void __gnu_debug::_Safe_sequence_base::_M_revalidate_singular () protected inherited
Revalidates all attached singular iterators. This method may be used to validate iterators that were invalidated before (but for some reason, such as an exception, need to become valid again).
_M_swap()
void __gnu_debug::_Safe_sequence_base::_M_swap (_Safe_sequence_base & __x) protected noexcept inherited
Swap this sequence with the given sequence. This operation also swaps ownership of the iterators, so that when the operation is complete all iterators that originally referenced one container now reference the other container.
_M_transfer_from_if()
template<typename _Sequence > template<typename _Predicate > void __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if (_Safe_sequence< _Sequence > & __from, _Predicate __pred) inherited
Transfers all iterators x that reference from sequence, are not singular, and for which __pred(x) returns true. __pred will be invoked with the normal iterators nested in the safe ones.
Definition at line 68 of file safe_sequence.tcc.
References std::__addressof(), __gnu_debug::_Safe_sequence_base::_M_const_iterators, __gnu_debug::_Safe_iterator_base::_M_detach_single(), __gnu_debug::_Safe_sequence_base::_M_get_mutex(), __gnu_debug::_Safe_sequence_base::_M_iterators, __gnu_debug::_Safe_iterator_base::_M_next, __gnu_debug::_Safe_iterator_base::_M_prior, __gnu_debug::_Safe_iterator_base::_M_sequence, and __gnu_debug::_Safe_iterator_base::_M_version.
Member Data Documentation
_M_const_iterators
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_const_iterators inherited
The list of constant iterators that reference this container.
Definition at line 197 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
_M_iterators
_Safe_iterator_base* __gnu_debug::_Safe_sequence_base::_M_iterators inherited
The list of mutable iterators that reference this container.
Definition at line 194 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence< _Sequence >::_M_transfer_from_if().
_M_version
unsigned int __gnu_debug::_Safe_sequence_base::_M_version mutable inherited
The container version number. This number may never be 0.
Definition at line 200 of file safe_base.h.
Referenced by __gnu_debug::_Safe_sequence_base::_M_invalidate_all().
The documentation for this class was generated from the following file:
debug/vector